"""Mood-reachability CI guards for the Psyche Engine (ADR-142).

Three guard families that turn the desired psyche properties into permanently
verified rules instead of hand-tuned numbers:

1. Golden characterization — the resting PAD of the 14 catalogue personalities
   under the RAW mapping (damping only, center pinned to 0.0) is frozen as
   literals. Any change to the baseline dynamics (Mehrabian coefficients,
   damping semantics, override blend) breaks this test loudly. A companion
   test pins the shipped defaults, which were promoted to the activated values
   on 2026-08-29 after the production baseline.
2. Catalogue-straddle guard — at the activation center (0.20, now the shipped
   default) the catalogue must straddle D=0 with the personality ordering
   exactly preserved. Protects the decision against future personality or
   coefficient edits.
3. Reachability oracle — a fixed ordinary-regime conversation replayed through
   the real engine: the un-recentered frame (center=0.0) keeps the mood locked
   in few labels; the recentered frame unlocks strictly more moods and breaks
   the single-mood monopoly. This is the end-to-end oracle ADR-068/ADR-104
   never had.

The personality catalogue is loaded from the seeding migration via importlib —
single source of truth, no duplicated table (Systemic Rules: registries).

Pure engine, no LLM, no DB. The appraisal stream is scripted; production
magnitudes are measured separately by ``apps/api/scripts/measure_psyche.py``.
"""

from __future__ import annotations

import importlib.util
import sys
from datetime import UTC, datetime, timedelta
from pathlib import Path

import pytest

from src.core.constants import (
    PSYCHE_BASELINE_DAMPING_DEFAULT,
    PSYCHE_DOMINANCE_CENTER_DEFAULT,
    PSYCHE_PROACTIVE_JOY_PULSE_DEFAULT,
)
from src.domains.psyche.engine import (
    PADOverride,
    PADVector,
    PersonalityTraits,
    PsycheAppraisal,
    PsycheEngine,
)

pytestmark = pytest.mark.unit

# Activation value, promoted to the shipped default on 2026-08-29.
# Derived from the catalogue mean (+0.216 at design time, +0.234 on the live
# catalogue), kept at the more conservative 0.20 for character fidelity.
RECOMMENDED_CENTER = 0.20

_MIGRATION_PATH = (
    Path(__file__).parents[4]
    / "alembic"
    / "versions"
    / "2026_04_01_0003-assign_big_five_traits_to_personalities.py"
)


def _load_catalogue() -> list[tuple[str, PersonalityTraits, PADOverride | None]]:
    """Load the 14-personality catalogue from the seeding migration.

    Importing the module executes only its top-level statements (imports and
    the ``PERSONALITY_TRAITS`` literal) — ``upgrade()`` is never called.

    Returns:
        List of (personality_id, traits, optional PAD override).
    """
    spec = importlib.util.spec_from_file_location("psyche_traits_migration", _MIGRATION_PATH)
    assert spec is not None and spec.loader is not None, f"cannot load {_MIGRATION_PATH}"
    module = importlib.util.module_from_spec(spec)
    # Canonical importlib recipe: register before exec so anything resolving
    # the module via sys.modules (e.g. dataclasses) finds it.
    sys.modules["psyche_traits_migration"] = module
    spec.loader.exec_module(module)

    catalogue: list[tuple[str, PersonalityTraits, PADOverride | None]] = []
    for pid, o, c, e, a, n, pad_p, pad_a, pad_d in module.PERSONALITY_TRAITS:
        override = (
            PADOverride(pleasure=pad_p, arousal=pad_a, dominance=pad_d)
            if any(x is not None for x in (pad_p, pad_a, pad_d))
            else None
        )
        catalogue.append((str(pid), PersonalityTraits(o, c, e, a, n), override))
    return catalogue


def _resting(
    catalogue: list[tuple[str, PersonalityTraits, PADOverride | None]],
    dominance_center: float,
) -> dict[str, PADVector]:
    """Resting PAD baseline per personality id at the shipped damping."""
    return {
        pid: PsycheEngine.compute_pad_baseline(
            traits,
            override,
            damping=PSYCHE_BASELINE_DAMPING_DEFAULT,
            dominance_center=dominance_center,
        )
        for pid, traits, override in catalogue
    }


# =============================================================================
# 1. Golden no-op characterization
# =============================================================================

# Frozen resting PAD (pleasure, arousal, dominance) of every catalogue
# personality at damping=0.75 and dominance_center=0.0 — generated by running
# compute_pad_baseline on the migration data. The center is pinned to 0.0
# DELIBERATELY, not read from the shipped default: these literals characterise
# the RAW Mehrabian+damping mapping, which the activation knob must translate
# without altering. (Before 2026-08-29 the shipped default was itself 0.0, so
# the distinction was invisible; promoting the default to 0.20 made it real.)
# If this test fails, the baseline dynamics changed: if intended, regenerate
# these literals and justify the change in an ADR; if not, you caught a
# silent regression.
_GOLDEN_RESTING: dict[str, tuple[float, float, float]] = {
    "7b769b3b-d5e5-4929-90ed-54e72941005d": (0.012375, 0.077625, 0.3011250000000001),  # Cynique
    "23266ad8-b419-4594-9b3c-28f7a580bfd9": (0.12374999999999999, 0.045, 0.18749999999999997),
    "0a25b00f-89f9-4180-bda1-fb0561f519c0": (-0.09037499999999998, 0.0495, 0.06599999999999998),
    "6274e825-d4c3-4f6c-86d7-ac5e7629c2e4": (0.29587499999999994, 0.17598749999999996, 0.16725),
    "ceaf6e6c-0ef3-4ae4-b85b-c6f834f5fd54": (0.3315, 0.016875000000000015, 0.13837499999999997),
    "6b7aeed0-37a5-4992-9fae-203b02534761": (0.15862499999999996, -0.0917625, 0.286875),
    "f30d019a-05a7-4326-adbf-64f1bb007ce9": (0.12674999999999997, -0.0135, 0.19162500000000005),
    "3ed44d2b-5898-4190-b9a7-80fc8bf9678b": (0.23362499999999997, 0.1395, 0.330375),
    "c3bb2155-984a-4414-b441-7f8a265dc535": (0.20163749999999994, -0.13874999999999998, 0.062625),
    "cdab692d-7df0-40fe-a87c-9e67c452117b": (-0.015375000000000014, -0.072, 0.1648875),
    "d8576bd9-d698-4944-bd92-bc76edf4a003": (0.171375, 0.126, 0.25649999999999995),
    "cea2a505-c932-4834-93e4-9d8f6e76b1dd": (0.16237500000000005, 0.11283750000000001, 0.3495),
    "ef2ec97b-cffc-4c3c-a4ae-1381670b701f": (0.08617499999999999, -0.030374999999999985, 0.27525),
    "8d3c8cac-8f69-443e-9dfe-15e883a7c1b8": (-0.00900000000000005, 0.019125000000000017, 0.242625),
}


class TestGoldenNoOp:
    """The raw mapping stays frozen, and the shipped defaults stay the measured ones."""

    def test_shipped_defaults_are_the_activated_values(self) -> None:
        """Both knobs were promoted on 2026-08-29 after the production baseline.

        Shipped inert in v1.25.14 (0.0 / True) so the merge could be proven a
        no-op, then promoted once production data confirmed the diagnosis:
        D<0 share 0.0% over 769 snapshots, joy dominant 31-100% of turns.
        A change here is a product-policy change and needs an ADR entry.
        """
        assert PSYCHE_DOMINANCE_CENTER_DEFAULT == 0.20
        assert PSYCHE_PROACTIVE_JOY_PULSE_DEFAULT is False

    def test_shipped_default_delivers_the_straddle(self) -> None:
        """The promoted default must actually deliver the property it was promoted for."""
        resting = _resting(_load_catalogue(), dominance_center=PSYCHE_DOMINANCE_CENTER_DEFAULT)
        below = sum(1 for pad in resting.values() if pad.dominance < 0.0)
        above = sum(1 for pad in resting.values() if pad.dominance > 0.0)
        assert below >= 5 and above >= 5, (
            f"shipped default {PSYCHE_DOMINANCE_CENTER_DEFAULT} no longer straddles "
            f"D=0 ({below} below / {above} above) — re-derive it from the catalogue"
        )

    def test_catalogue_resting_points_match_goldens(self) -> None:
        """Resting PAD of all 14 personalities is frozen (abs tol 1e-9)."""
        catalogue = _load_catalogue()
        assert len(catalogue) == 14, "catalogue size changed — regenerate goldens + ADR"
        resting = _resting(catalogue, dominance_center=0.0)
        for pid, (gp, ga, gd) in _GOLDEN_RESTING.items():
            pad = resting[pid]
            assert pad.pleasure == pytest.approx(gp, abs=1e-9), (
                f"{pid}: pleasure {pad.pleasure} != golden {gp} — psyche baseline "
                "dynamics changed; if intended, regenerate goldens and justify in an ADR"
            )
            assert pad.arousal == pytest.approx(ga, abs=1e-9), f"{pid}: arousal drifted"
            assert pad.dominance == pytest.approx(gd, abs=1e-9), f"{pid}: dominance drifted"

    def test_todays_catalogue_rests_entirely_assertive(self) -> None:
        """Documents the measured defect: at center=0.0 NO personality rests D<0.

        This is the confinement ADR-142 addresses. If this test ever fails, the
        defect no longer exists in its measured form — re-evaluate whether the
        recentering knob is still needed before touching it.
        """
        resting = _resting(_load_catalogue(), dominance_center=0.0)
        assert all(pad.dominance > 0.0 for pad in resting.values())


# =============================================================================
# 2. Catalogue-straddle guard at the recommended center
# =============================================================================


class TestCatalogueStraddle:
    """At the recommended activation value the catalogue must straddle D=0."""

    def test_straddles_zero(self) -> None:
        """>= 5 personalities rest on each side of D=0 at center 0.20."""
        resting = _resting(_load_catalogue(), dominance_center=RECOMMENDED_CENTER)
        below = sum(1 for pad in resting.values() if pad.dominance < 0.0)
        above = sum(1 for pad in resting.values() if pad.dominance > 0.0)
        assert below >= 5, f"only {below}/14 personalities rest D<0 — center too weak"
        assert above >= 5, f"only {above}/14 personalities rest D>0 — center too strong"

    def test_ordering_exactly_preserved(self) -> None:
        """The translation must not reorder personalities on the D axis."""
        catalogue = _load_catalogue()
        base = _resting(catalogue, dominance_center=0.0)
        centered = _resting(catalogue, dominance_center=RECOMMENDED_CENTER)
        ids = [pid for pid, _, _ in catalogue]
        order_base = sorted(ids, key=lambda i: base[i].dominance)
        order_centered = sorted(ids, key=lambda i: centered[i].dominance)
        assert order_base == order_centered

    def test_pleasure_and_arousal_untouched(self) -> None:
        """The translation is D-only: P and A resting points are identical."""
        catalogue = _load_catalogue()
        base = _resting(catalogue, dominance_center=0.0)
        centered = _resting(catalogue, dominance_center=RECOMMENDED_CENTER)
        for pid, _, _ in catalogue:
            assert centered[pid].pleasure == base[pid].pleasure
            assert centered[pid].arousal == base[pid].arousal


# =============================================================================
# 3. Reachability oracle — end-to-end mood dynamics on a scripted stream
# =============================================================================

# Cynique traits from the migration (the ADR-104 production power-user persona).
_CYNIC = PersonalityTraits(
    openness=0.70,
    conscientiousness=0.55,
    extraversion=0.45,
    agreeableness=0.25,
    neuroticism=0.45,
)

# Effective rates mirroring service defaults: user stability 60 -> decay x0.8,
# user sensitivity 70 -> appraisal sensitivity 0.7 * (0.15 + 1.85*0.7) ~= 1.01.
_EFFECTIVE_DECAY = 0.1 * 0.8
_EFFECTIVE_SENSITIVITY = 0.7 * (0.15 + 1.85 * 0.7)

# Ordinary-regime stream: 5 sessions x 6 messages (bursts 3 min apart, 16 h
# session gaps) — the dominant production regime per ADR-104 (81% of messages
# arrive <30 min apart). Each turn: (dt_hours, [(emotion, intensity)...],
# valence, quality). Bright-leaning palette, modest intensities (the debiased
# self-report's stated distribution).
_ORDINARY_STREAM: list[tuple[float, list[tuple[str, float]], float, float]] = [
    (0.00, [("amusement", 0.35)], 0.30, 0.80),
    (0.05, [("curiosity", 0.30)], 0.20, 0.75),
    (0.05, [("enthusiasm", 0.40)], 0.45, 0.85),
    (0.05, [("joy", 0.30), ("gratitude", 0.25)], 0.50, 0.90),
    (0.05, [("determination", 0.35)], 0.10, 0.70),
    (0.05, [("amusement", 0.30)], 0.30, 0.80),
    (16.0, [("curiosity", 0.35)], 0.10, 0.70),
    (0.05, [("pride", 0.40)], 0.40, 0.85),
    (0.05, [("enthusiasm", 0.35), ("joy", 0.25)], 0.50, 0.90),
    (0.05, [("resolve", 0.30)], 0.00, 0.70),
    (0.05, [("amusement", 0.40)], 0.35, 0.80),
    (0.05, [("wonder", 0.30)], 0.25, 0.75),
    (16.0, [("determination", 0.40)], 0.05, 0.70),
    (0.05, [("concern", 0.30)], -0.10, 0.60),
    (0.05, [("empathy", 0.35)], -0.05, 0.65),
    (0.05, [("curiosity", 0.30)], 0.15, 0.75),
    (0.05, [("joy", 0.35)], 0.45, 0.85),
    (0.05, [("playfulness", 0.35)], 0.40, 0.80),
    (16.0, [("enthusiasm", 0.40)], 0.50, 0.90),
    (0.05, [("amusement", 0.35)], 0.30, 0.80),
    (0.05, [("gratitude", 0.30)], 0.40, 0.85),
    (0.05, [("determination", 0.30)], 0.10, 0.70),
    (0.05, [("curiosity", 0.35)], 0.20, 0.75),
    (0.05, [("pride", 0.35)], 0.35, 0.80),
    (16.0, [("joy", 0.30)], 0.40, 0.85),
    (0.05, [("amusement", 0.30)], 0.30, 0.80),
    (0.05, [("resolve", 0.35)], 0.05, 0.70),
    (0.05, [("enthusiasm", 0.35)], 0.45, 0.85),
    (0.05, [("wonder", 0.25)], 0.20, 0.75),
    (0.05, [("curiosity", 0.30)], 0.15, 0.75),
]


def _replay_ordinary_regime(dominance_center: float) -> list[str]:
    """Replay the scripted stream through the real engine, service-faithfully.

    Mirrors the per-turn order of PsycheService.process_pre_response +
    process_post_response: decay -> circadian -> quadrant tracking -> proactive
    pulses -> appraisal (with relaxation) -> relationship/drives updates.

    Args:
        dominance_center: Translation under test (0.0 = today's default).

    Returns:
        Sequence of mood labels, one per turn.
    """
    baseline = PsycheEngine.compute_pad_baseline(
        _CYNIC,
        damping=PSYCHE_BASELINE_DAMPING_DEFAULT,
        dominance_center=dominance_center,
    )
    p, a, d = baseline.pleasure, baseline.arousal, baseline.dominance
    emotions: list[dict] = []
    now = datetime(2026, 7, 1, 9, 0, tzinfo=UTC)
    quadrant_since = now
    last_interaction: datetime | None = None
    last_appraisal: dict | None = None
    depth, warmth, trust, count = 0.0, 0.5, 0.3, 0
    stage = "ORIENTATION"
    curiosity, engagement = 0.5, 0.5
    tz_hour = 14.0
    labels: list[str] = []

    for dt_hours, emos, valence, quality in _ORDINARY_STREAM:
        now = now + timedelta(hours=dt_hours)
        tz_hour = (tz_hour + dt_hours) % 24.0

        pre_quadrant = PADVector(p, a, d).quadrant_key()
        p, a, d, emotions, warmth = PsycheEngine.apply_temporal_decay(
            mood_p=p,
            mood_a=a,
            mood_d=d,
            baseline=baseline,
            hours_elapsed=dt_hours,
            decay_rate=_EFFECTIVE_DECAY,
            emotions=emotions,
            emotion_decay_rate=0.4,
            warmth=warmth,
            warmth_decay_rate=0.02,
            has_interaction=True,
            traits=_CYNIC,
        )
        p = PsycheEngine.apply_circadian(p, tz_hour, 0.08)
        if PADVector(p, a, d).quadrant_key() != pre_quadrant:
            quadrant_since = now

        proactive = PsycheEngine.compute_proactive_emotions(
            drive_curiosity=curiosity,
            drive_engagement=engagement,
            interaction_count=count,
            last_appraisal=last_appraisal,
            self_efficacy=None,
            existing_emotions=emotions,
            now_iso=now.isoformat(),
        )
        if proactive:
            emotions = PsycheEngine.merge_proactive_emotions(emotions, proactive)

        inertia = PsycheEngine.compute_emotional_inertia(quadrant_since, now)
        appraisal = PsycheAppraisal(
            valence=valence, arousal=0.4, emotions=list(emos), quality=quality
        )
        p, a, d, emotions = PsycheEngine.apply_appraisal(
            mood_p=p,
            mood_a=a,
            mood_d=d,
            emotions=emotions,
            appraisal=appraisal,
            sensitivity=_EFFECTIVE_SENSITIVITY,
            inertia=inertia,
            max_active=4,
            now_iso=now.isoformat(),
            traits=_CYNIC,
            baseline=baseline,
            relaxation=0.15,
        )
        label = PsycheEngine.classify_mood(p, a, d)
        labels.append(label)
        last_appraisal = {"quality": quality, "emotion": appraisal.dominant_emotion}

        gap_hours = 0.0
        if last_interaction is not None:
            gap_hours = max(0.0, (now - last_interaction).total_seconds() / 3600.0)
        depth, warmth, trust, count, stage, reunion = PsycheEngine.update_relationship(
            depth=depth,
            warmth=warmth,
            trust=trust,
            interaction_count=count,
            stage=stage,
            quality=quality,
            gap_hours=gap_hours,
            now_iso=now.isoformat(),
        )
        if reunion:
            emotions = [*emotions, *reunion]
        curiosity, engagement = PsycheEngine.update_drives(curiosity, engagement, 0.4, quality)
        last_interaction = now

    return labels


class TestReachabilityOracle:
    """End-to-end: the recentered frame unlocks moods the un-recentered one cannot."""

    def test_uncentered_frame_stays_locked(self) -> None:
        """At center=0.0 the ordinary regime visits few moods (the measured lock).

        0.0 was the shipped default until the 2026-08-29 promotion; it stays
        pinned here as the counterfactual the recentering is measured against.
        """
        labels = _replay_ordinary_regime(dominance_center=0.0)
        assert len(set(labels)) <= 4, (
            f"unexpected variety without recentering: {sorted(set(labels))} — the "
            "confinement defect may have been fixed elsewhere; re-evaluate ADR-142"
        )

    def test_recommended_center_unlocks_variety(self) -> None:
        """At center=0.20 strictly more moods are reachable, monopoly broken."""
        locked = _replay_ordinary_regime(dominance_center=0.0)
        unlocked = _replay_ordinary_regime(dominance_center=RECOMMENDED_CENTER)
        assert len(set(unlocked)) > len(set(locked)), (
            f"recentering added no variety: {sorted(set(locked))} -> " f"{sorted(set(unlocked))}"
        )
        assert len(set(unlocked)) >= 5, f"expected >=5 moods, got {sorted(set(unlocked))}"
        top_share = max(unlocked.count(m) for m in set(unlocked)) / len(unlocked)
        assert top_share <= 0.70, f"one mood still holds {top_share:.0%} of turns"

    def test_replay_is_deterministic(self) -> None:
        """The oracle is stable: two replays produce identical label sequences."""
        assert _replay_ordinary_regime(0.0) == _replay_ordinary_regime(0.0)
