"""Compose layer selection and generated-override rendering (B04/B05/B15).

The generated ``docker-compose.install.yml`` is the ONLY writer of
install-specific Compose state: seed gating (always the digest, APPLY_SEEDS
armed only for the fresh start), LAN port republication (``!override`` list,
Compose >= 2.24.4), and — exclusively under the Caddy exposure — the
``caddy`` service with its named volumes and the generated read-only
Caddyfile. YAML is rendered as plain text: the wizard is stdlib-only.
"""

from __future__ import annotations

import string
from pathlib import Path

from scripts.install.model import (
    ComposeInvocation,
    Exposure,
    InstallMode,
    PublicAnswers,
)

BASE_COMPOSE = "docker-compose.prod.yml"
INSTALL_COMPOSE = "docker-compose.install.yml"
IMAGES_COMPOSE = "docker-compose.images.yml"
SKILL_SANDBOX_COMPOSE = "docker-compose.skill-sandbox.yml"

_CADDYFILE_TEMPLATE_RELPATH = ("infrastructure", "caddy", "Caddyfile.template")


def build_invocation(
    public: PublicAnswers, *, root: Path, project_name: str | None = None
) -> ComposeInvocation:
    """Select the exact Compose layers and profiles for these answers."""
    files = [root / BASE_COMPOSE, root / INSTALL_COMPOSE]
    if public.skill_sandbox:
        files.append(root / SKILL_SANDBOX_COMPOSE)
    if public.mode is InstallMode.PREBUILT:
        files.append(root / IMAGES_COMPOSE)
    return ComposeInvocation(
        files=tuple(files),
        profiles=("observability",) if public.observability else (),
        mode=public.mode,
        project_name=project_name,
        env={"LIA_INSTALL_CADDY": "1" if public.exposure is Exposure.CADDY else ""},
    )


#: Dependency services always started (no profile) in the base file.
BASE_DEPENDENCY_SERVICES: tuple[str, ...] = ("postgres", "postgres-backup", "redis")

#: Dependency services behind the ``observability`` profile in the base file.
OBSERVABILITY_SERVICES: tuple[str, ...] = (
    "tempo",
    "prometheus",
    "alertmanager",
    "blackbox-exporter",
    "grafana",
    "loki",
    "promtail",
    "node-exporter",
    "cadvisor",
    "postgres-exporter",
    "redis-exporter",
    "portainer",
)


def locked_services(public: PublicAnswers) -> tuple[str, ...]:
    """Exact service names the prebuilt image lock must pin for these answers.

    Passing the selected layers' own names (never a superset) keeps the lock
    from introducing Caddy into a LAN/proxy scenario.
    """
    services = ["api", "web", *BASE_DEPENDENCY_SERVICES]
    if public.observability:
        services.extend(OBSERVABILITY_SERVICES)
    if public.exposure is Exposure.CADDY:
        services.append("caddy")
    return tuple(services)


def up_suffix(invocation: ComposeInvocation) -> list[str]:
    """``up`` arguments after the prefix; prebuilt NEVER builds."""
    suffix = ["up", "-d", "--remove-orphans"]
    if invocation.mode is InstallMode.PREBUILT:
        suffix.append("--no-build")
    return suffix


def render_install_override(
    public: PublicAnswers,
    *,
    seed_intent: bool,
    seed_bundle_sha256: str,
    sandbox_api_image: str | None = None,
) -> str:
    """Render ``docker-compose.install.yml`` for these answers.

    Args:
        public: Validated public answers.
        seed_intent: True ONLY for the fresh-start candidate; the installer
            rewrites the file with False right after the first ``/ready``.
        seed_bundle_sha256: Always carried — the entrypoint refuses to seed
            under a divergent identity.
        sandbox_api_image: Locked API reference for the sandbox setting
            (required when the sandbox is enabled in prebuilt mode, where
            the base file's ``${LIA_API_IMAGE:-lia-api:local}`` fallback
            would point at a non-existent local tag).
    """
    lines = [
        "# Generated by the LIA installer (ADR-215) — do not edit by hand.",
        "services:",
        "  api:",
        "    environment:",
        f"      - APPLY_SEEDS={'true' if seed_intent else 'false'}",
        f"      - SEED_BUNDLE_SHA256={seed_bundle_sha256}",
    ]
    if sandbox_api_image is not None:
        lines.append(f"      - SKILLS_SCRIPT_SANDBOX_IMAGE={sandbox_api_image}")
    if public.exposure is Exposure.LAN:
        lines += [
            "  web:",
            "    ports: !override",
            # The base file publishes loopback-only; LAN must serve the
            # network. Only the web port opens — the API stays loopback
            # (browsers reach it same-origin through the web proxy).
            '      - "3000:3000"',
        ]
    if public.exposure is Exposure.CADDY:
        lines += [
            "  caddy:",
            "    image: ${LIA_CADDY_IMAGE:-caddy:2-alpine}",
            "    container_name: lia-caddy-prod",
            "    restart: unless-stopped",
            "    ports:",
            '      - "80:80"',
            '      - "443:443"',
            "    volumes:",
            "      - ./infrastructure/caddy/Caddyfile:/etc/caddy/Caddyfile:ro",
            "      - caddy_data:/data",
            "      - caddy_config:/config",
            "    depends_on:",
            "      - web",
            "      - api",
            "    networks:",
            "      - lia-network",
            "volumes:",
            "  caddy_data:",
            "  caddy_config:",
        ]
    return "\n".join(lines) + "\n"


def render_caddyfile(public: PublicAnswers, *, template_root: Path | None = None) -> str:
    """Render the generated Caddyfile from the repository template."""
    if public.exposure is not Exposure.CADDY:
        raise ValueError("caddyfile_requires_caddy_exposure")
    if template_root is None:
        template_root = Path(__file__).resolve().parents[2]
    template_path = template_root.joinpath(*_CADDYFILE_TEMPLATE_RELPATH)
    template = string.Template(template_path.read_text(encoding="utf-8"))
    return template.substitute(
        WEB_DOMAIN=str(public.web_domain),
        API_DOMAIN=str(public.api_domain),
        CADDY_EMAIL=str(public.caddy_email),
    )
