/** Illustrations depict a use result, never a claim about a live account. */
export type FeatureScene =
  | 'plan'
  | 'call'
  | 'voice'
  | 'document'
  | 'browser'
  | 'calculation'
  | 'image'
  | 'diagram'
  | 'home'
  | 'memory'
  | 'radio'
  | 'briefing'
  | 'automation'
  | 'board'
  | 'knowledge'
  | 'control'
  | 'people'
  | 'tools'
  | 'devices'
  | 'weather'
  | 'health';

export const FEATURE_SCENES: Readonly<Record<string, FeatureScene>> = {
  multi_agent: 'plan',
  natural_language: 'plan',
  sub_agents: 'plan',
  telephony: 'call',
  telephony_callback: 'call',
  live_voice: 'voice',
  voice_mode: 'voice',
  languages: 'voice',
  meetings: 'document',
  meeting_templates: 'document',
  document_generation: 'document',
  email_share: 'document',
  generated_files: 'document',
  browser_control: 'browser',
  devops_cli: 'browser',
  computed_answers: 'calculation',
  usage_limits: 'calculation',
  image_generation: 'image',
  excalidraw: 'diagram',
  smart_home: 'home',
  memory: 'memory',
  journals: 'memory',
  personal_crm: 'memory',
  psyche: 'memory',
  personalities: 'memory',
  mood_face: 'memory',
  personal_radio: 'radio',
  briefing: 'briefing',
  rich_responses: 'briefing',
  proactive: 'automation',
  proactive_wake: 'automation',
  proactive_moments: 'automation',
  habits: 'automation',
  habits_lifecycle: 'automation',
  conditional_routines: 'automation',
  reminders_scheduling: 'automation',
  interests: 'knowledge',
  workboard: 'board',
  workboard_delegation: 'board',
  rag_spaces: 'knowledge',
  mail_label_spaces: 'knowledge',
  bookmarks: 'knowledge',
  attachments: 'knowledge',
  web_intelligence: 'knowledge',
  self_knowledge: 'knowledge',
  control: 'control',
  privacy: 'control',
  peer_safety: 'control',
  peers: 'people',
  peer_shares: 'people',
  skills: 'tools',
  plugins: 'tools',
  mcp: 'tools',
  mcp_apps: 'tools',
  connected_services: 'tools',
  simplicity: 'tools',
  chat_sync: 'devices',
  multichannel: 'devices',
  native_apps: 'devices',
  responsive: 'devices',
  themes: 'devices',
  environment: 'weather',
  health_metrics: 'health',
};
