#!/usr/bin/env python3
"""Living architecture maps: the functional map, the technical map, the ADR history.

The three maps are published twice from ONE set of data:

* on the public site, in the six languages of the site (``/maps/*``, rendered by
  the React components of ``apps/web/src/components/maps``);
* as three self-contained French HTML documents in ``docs/maps/`` — offline
  presentation material, GENERATED by this module from the same data.

The data lives in ``apps/web/src/data/maps/`` because the web container sees
nothing else of the repository:

* ``functional.json``, ``technical.json``, ``history.json`` — the STRUCTURE,
  language-neutral (ids, icons, tones, dependencies, domains, paths, dates);
* ``text/<map>.<lang>.json`` — the WORDS, one file per map and language. French
  is the source; every other language carries, on each unit, the fingerprint
  of the French it translates (``src``);
* ``facts.json`` — GENERATED here: the counts and dates the pages show,
  computed from the tree (a document never restates a value the code owns).

Why a generator and a gate, not hand-written pages
--------------------------------------------------
A schema drawn by hand is true on the day it is drawn. This repository measured
what happens next more than once: six documents quoting six coverage floors, a
capability map describing the product of six months earlier (ADR-229), an
``AGENTS.md`` silently become a strict subset of ``CLAUDE.md``. So the facts the
maps cannot be allowed to miss are CHECKED against the tree, by the same
``task lint:docs`` that gates the rest of the documentation:

* every ADR file has exactly one history entry, and every entry either names a
  file or declares, with a reason, why it has none (ADR-008);
* every backend domain and every infrastructure module is claimed by a brick —
  a new one fails the build until somebody says where it belongs;
* every path a brick points at exists, every screen a brick names is a route;
* every reference between bricks, families, layers, themes and flows resolves,
  and every icon the documents draw is vendored;
* every unit of text exists in every language of the site, and no translation
  is STALE: when the French changes, the fingerprint no longer matches and the
  unit is named until it is translated again (then ``--restamp`` it);
* ``facts.json`` and the three documents are exactly what the data renders —
  edit the JSON, run ``task docs:maps``, commit everything.

``--write`` also stamps the fingerprint of a unit translated for the first time
(it had none). A stale fingerprint is never refreshed implicitly: re-translate,
then ``--restamp map/section/id``.

Existence is decided from the git INDEX, like ``doc_audit.py``: a fresh clone
must reach the same verdict. ``--include-unstaged`` judges tracked files plus
what ``git add -A`` would stage, for the case where the finding is a file you
just created.

Usage (from the repo root):
    python scripts/audit/doc_maps.py                   # check, exit 1 on any finding
    python scripts/audit/doc_maps.py --write           # regenerate facts + documents
    python scripts/audit/doc_maps.py --write --refresh-icons
                                                       # also re-vendor the Lucide subset
    python scripts/audit/doc_maps.py --restamp functional/bricks/f.chat
                                                       # accept re-translated units
    python scripts/audit/doc_maps.py --include-unstaged

Standard library only — no dependencies.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
import sys
import unicodedata
from dataclasses import dataclass
from pathlib import Path
from urllib.parse import quote

ROOT = Path(__file__).resolve().parents[2]

DATA_DIR = "apps/web/src/data/maps"
DOCS_DIR = "docs/maps"
LOCALES_DIR = "apps/web/locales"
SOURCE_LANG = "fr"
MAP_NAMES = ("functional", "technical", "history")

# The generated French documents of docs/maps (the site builds its own pages).
PAGES: dict[str, dict[str, str]] = {
    "functional": {
        "file": "functional-map.html",
        "label": "Carte fonctionnelle",
        "icon": "layout-grid",
        "title": "Carte fonctionnelle de LIA",
    },
    "technical": {
        "file": "technical-map.html",
        "label": "Carte technique",
        "icon": "network",
        "title": "Carte technique de LIA",
    },
    "history": {
        "file": "adr-history.html",
        "label": "Historique des décisions",
        "icon": "history",
        "title": "Historique des décisions de LIA",
    },
}

# Icons the document script draws itself (chrome), on top of those the data names.
CHROME_ICONS = frozenset(
    {
        "arrow-right",
        "arrow-up-right",
        "boxes",
        "corner-down-right",
        "file-code",
        "filter",
        "git-commit-horizontal",
        "info",
        "layers",
        "layout-grid",
        "monitor",
        "moon",
        "pause",
        "play",
        "rotate-ccw",
        "route",
        "rows-3",
        "scroll-text",
        "search",
        "share-2",
        "step-back",
        "step-forward",
        "sun",
        "tag",
        "x",
    }
)

TONES = frozenset(
    {
        "blue",
        "violet",
        "emerald",
        "amber",
        "rose",
        "cyan",
        "slate",
        "indigo",
        "orange",
        "teal",
        "fuchsia",
        "lime",
        "sky",
    }
)

# What a unit of text holds, per map and section. `intro` is one unit per map;
# every other section holds one unit per structure id. Lists are translated item
# by item and keep the source's length.
TEXT_SCHEMA: dict[str, dict[str, tuple[str, ...]]] = {
    "functional": {
        "intro": ("lede",),
        "groups": ("name", "summary"),
        "bricks": ("name", "role", "goal"),
        "flows": ("name", "summary", "steps"),
    },
    "technical": {
        "intro": ("lede",),
        "layers": ("name", "summary"),
        "bricks": ("name", "role", "stack"),
        "flows": ("name", "summary", "steps"),
    },
    "history": {
        "intro": ("lede",),
        "themes": ("name", "summary"),
        "eras": ("name", "summary"),
        "entries": ("title", "summary"),
    },
}
LIST_FIELDS = frozenset({"steps", "stack"})
FINGERPRINT = "src"
# A translated sentence identical to its French source was copied, not translated.
UNTRANSLATED_MIN_CHARS = 40

ADR_FILE_RE = re.compile(r"^docs/architecture/ADR-(\d{3})-[^/]+\.md$")
RELEASE_RE = re.compile(r"^## \[(\d+\.\d+\.\d+)\] - (\d{4}-\d{2}-\d{2})", re.M)
DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")
TEXT_FILE_RE = re.compile(r"^(functional|technical|history)\.([a-z]{2}(?:-[A-Z]{2})?)\.json$")
LOCALE_FILE_RE = re.compile(rf"^{LOCALES_DIR}/([^/]+)/translation\.json$")
LUCIDE_NODE_RE = re.compile(r'\[\s*"(\w+)"\s*,\s*\{([^}]*)\}\s*\]')
LUCIDE_ATTR_RE = re.compile(r'([A-Za-z][\w-]*)\s*:\s*"([^"]*)"')
LUCIDE_DIR = "apps/web/node_modules/lucide-react/dist/esm/icons"


@dataclass(frozen=True)
class Tree:
    """What exists in the repository, as a fresh clone would see it."""

    root: Path
    files: frozenset[str]
    dirs: frozenset[str]

    def exists(self, rel: str) -> bool:
        """Whether a repo-relative file or directory exists in the tree."""
        rel = rel.strip("/")
        return rel in self.files or rel in self.dirs


def load_tree(root: Path, include_unstaged: bool) -> Tree:
    """List tracked files (plus what ``git add -A`` would stage, on request)."""
    cmd = ["git", "ls-files", "-z"]
    names = (
        subprocess.run(cmd, cwd=root, capture_output=True, check=True)
        .stdout.decode("utf-8")
        .split("\0")
    )
    files = {n for n in names if n}
    if include_unstaged:
        extra = (
            subprocess.run(
                ["git", "ls-files", "-z", "--others", "--exclude-standard"],
                cwd=root,
                capture_output=True,
                check=True,
            )
            .stdout.decode("utf-8")
            .split("\0")
        )
        files |= {n for n in extra if n}
        files = {f for f in files if (root / f).exists()}
    dirs: set[str] = set()
    for f in files:
        parts = f.split("/")
        for i in range(1, len(parts)):
            dirs.add("/".join(parts[:i]))
    return Tree(root=root, files=frozenset(files), dirs=frozenset(dirs))


def children(tree: Tree, parent: str) -> set[str]:
    """Direct children (files and directories) of a tracked directory."""
    prefix = parent.rstrip("/") + "/"
    out: set[str] = set()
    for f in tree.files:
        if f.startswith(prefix):
            out.add(f[len(prefix) :].split("/", 1)[0])
    return out


def backend_domains(tree: Tree) -> list[str]:
    """Backend bounded contexts: the directories of ``apps/api/src/domains``."""
    base = "apps/api/src/domains"
    return sorted(
        c for c in children(tree, base) if f"{base}/{c}" in tree.dirs and not c.startswith("__")
    )


def infra_units(tree: Tree) -> list[str]:
    """Infrastructure modules: packages and top-level modules of ``src/infrastructure``."""
    base = "apps/api/src/infrastructure"
    out = set()
    for c in children(tree, base):
        if c.startswith("__"):
            continue
        if f"{base}/{c}" in tree.dirs:
            out.add(c)
        elif c.endswith(".py"):
            out.add(c[:-3])
    return sorted(out)


def adr_files(tree: Tree) -> dict[int, str]:
    """ADR number → file name, for every ADR file of ``docs/architecture``."""
    out: dict[int, str] = {}
    for f in tree.files:
        m = ADR_FILE_RE.match(f)
        if m:
            out[int(m.group(1))] = f.rsplit("/", 1)[1]
    return out


def site_languages(tree: Tree) -> list[str]:
    """The languages of the site — its locale catalogues — source language first."""
    found = {m.group(1) for f in tree.files if (m := LOCALE_FILE_RE.match(f))}
    return sorted(found, key=lambda lang: (lang != SOURCE_LANG, lang))


def repo_facts(tree: Tree) -> dict[str, object]:
    """Counts and dates the pages show, computed from the tree — never typed in the data."""
    root = tree.root
    version = json.loads((root / "package.json").read_text(encoding="utf-8"))["version"]
    releases = [
        (v, d) for v, d in RELEASE_RE.findall((root / "CHANGELOG.md").read_text(encoding="utf-8"))
    ]
    dates = dict(releases)
    milestones = sorted(
        ({"version": v, "date": d} for v, d in releases if v.endswith(".0") or v == version),
        key=lambda r: (r["date"], [int(x) for x in r["version"].split(".")]),
    )
    domains = backend_domains(tree)
    files = adr_files(tree)
    return {
        "version": version,
        "releaseDate": dates.get(version, ""),
        "releases": len(releases),
        "milestones": milestones,
        # The shared kernel is not a functional domain (the README counts the same way).
        "domains": len([d for d in domains if d != "shared"]),
        "infra": len(infra_units(tree)),
        "adrFiles": len(files),
    }


def site_facts(tree: Tree) -> dict[str, object]:
    """``facts.json``: what the site pages read from outside ``apps/web``."""
    facts = repo_facts(tree)
    names = {str(n): f for n, f in sorted(adr_files(tree).items())}
    return {**{k: v for k, v in facts.items() if k != "adrFiles"}, "adrFiles": names}


# --------------------------------------------------------------------------- JSON


def _display_width(text: str) -> int:
    """Columns a string takes, East Asian wide characters counting two (as Prettier does)."""
    return sum(2 if unicodedata.east_asian_width(ch) in ("W", "F") else 1 for ch in text)


def dump_json(value: object, width: int = 100) -> str:
    """Serialise JSON exactly as Prettier prints it, so ``pnpm format`` is a no-op on it.

    Objects are always expanded; an array of scalars stays on one line when the
    whole line — indentation, key and trailing comma included — fits ``width``.
    """

    def scalar(v: object) -> str:
        return json.dumps(v, ensure_ascii=False)

    def render(v: object, indent: int, used: int, tail: int) -> str:
        pad = "  " * indent
        if isinstance(v, dict):
            if not v:
                return "{}"
            keys = list(v)
            lines = []
            for i, k in enumerate(keys):
                head = f"{pad}  {scalar(k)}: "
                comma = "," if i < len(keys) - 1 else ""
                lines.append(
                    head + render(v[k], indent + 1, _display_width(head), len(comma)) + comma
                )
            return "{\n" + "\n".join(lines) + "\n" + pad + "}"
        if isinstance(v, list):
            if not v:
                return "[]"
            if all(not isinstance(x, (dict, list)) for x in v):
                flat = "[" + ", ".join(scalar(x) for x in v) + "]"
                if used + _display_width(flat) + tail <= width:
                    return flat
            items = []
            for i, x in enumerate(v):
                comma = "," if i < len(v) - 1 else ""
                items.append(f"{pad}  " + render(x, indent + 1, len(pad) + 2, len(comma)) + comma)
            return "[\n" + "\n".join(items) + "\n" + pad + "]"
        return scalar(v)

    return render(value, 0, 0, 0) + "\n"


def write_json(path: Path, value: object) -> None:
    """Write a data file in the one format every tool of the repository agrees on."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(dump_json(value), encoding="utf-8", newline="\n")


# --------------------------------------------------------------------------- data


@dataclass(frozen=True)
class Maps:
    """The structure of the three maps, their text in every language, the vendored icons."""

    functional: dict
    technical: dict
    history: dict
    text: dict[str, dict[str, dict]]
    icons: dict[str, list]

    def structure(self, name: str) -> dict:
        """The structure document of one map."""
        return {
            "functional": self.functional,
            "technical": self.technical,
            "history": self.history,
        }[name]


def load_maps(data_dir: Path, icons_path: Path) -> Maps:
    """Read the structure, every text file and the vendored icons."""

    def read(path: Path) -> dict:
        return json.loads(path.read_text(encoding="utf-8"))

    text: dict[str, dict[str, dict]] = {}
    for path in sorted((data_dir / "text").glob("*.json")):
        m = TEXT_FILE_RE.match(path.name)
        if m:
            text.setdefault(m.group(2), {})[m.group(1)] = read(path)
    icons = read(icons_path) if icons_path.exists() else {}
    return Maps(
        read(data_dir / "functional.json"),
        read(data_dir / "technical.json"),
        read(data_dir / "history.json"),
        text,
        icons,
    )


def unit_ids(maps: Maps, name: str, section: str) -> list[str]:
    """The ids a text section must hold, in structure order (``intro`` holds none)."""
    doc = maps.structure(name)
    if section == "entries":
        return [str(e["adr"]) for e in doc.get("entries", [])]
    return [x["id"] for x in doc.get(section, [])]


def text_units(maps: Maps, lang: str) -> dict[str, dict | None]:
    """Every unit of a language, keyed ``map/section[/id]`` — None where it is absent."""
    out: dict[str, dict | None] = {}
    for name, sections in TEXT_SCHEMA.items():
        doc = maps.text.get(lang, {}).get(name, {})
        for section in sections:
            if section == "intro":
                out[f"{name}/intro"] = doc.get("intro")
                continue
            held = doc.get(section, {})
            for uid in unit_ids(maps, name, section):
                out[f"{name}/{section}/{uid}"] = held.get(uid)
    return out


def fingerprint(unit: dict) -> str:
    """Fingerprint of a SOURCE unit — what a translation declares it translated."""
    body = {k: v for k, v in unit.items() if k != FINGERPRINT}
    canonical = json.dumps(body, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()[:12]


def referenced_icons(maps: Maps) -> set[str]:
    """Every icon name the documents will draw."""
    names = set(CHROME_ICONS) | {p["icon"] for p in PAGES.values()}
    for key in ("groups", "bricks", "flows"):
        names |= {x["icon"] for x in maps.functional.get(key, [])}
    for key in ("layers", "bricks", "flows"):
        names |= {x["icon"] for x in maps.technical.get(key, [])}
    names |= {t["icon"] for t in maps.history.get("themes", [])}
    return names


def vendor_icons(root: Path, names: set[str]) -> tuple[dict[str, list], list[str]]:
    """Extract the geometry of the named Lucide icons from the installed package."""
    out: dict[str, list] = {}
    missing: list[str] = []
    for name in sorted(names):
        src = root / LUCIDE_DIR / f"{name}.mjs"
        if not src.exists():
            missing.append(name)
            continue
        text = src.read_text(encoding="utf-8")
        start = text.find("__iconNode = [")
        body = text[start : text.find("];", start)]
        nodes = []
        for tag, attrs in LUCIDE_NODE_RE.findall(body):
            kept = {k: v for k, v in LUCIDE_ATTR_RE.findall(attrs) if k != "key"}
            nodes.append([tag, kept])
        out[name] = nodes
    return out, missing


# --------------------------------------------------------------------------- checks


def _dupes(ids: list[str]) -> set[str]:
    seen: set[str] = set()
    dup: set[str] = set()
    for i in ids:
        (dup if i in seen else seen).add(i)
    return dup


def check_map(
    name: str, doc: dict, family_key: str, brick_family: str, problems: list[str]
) -> dict[str, dict]:
    """Structural checks shared by the two maps; returns bricks by id."""
    families = doc.get(family_key, [])
    bricks = doc.get("bricks", [])
    fam_ids = {f["id"] for f in families}
    by_id = {b["id"]: b for b in bricks}
    prefix = "f." if name == "functional" else "t."
    for d in _dupes([f["id"] for f in families]) | _dupes([b["id"] for b in bricks]):
        problems.append(f"{name}: duplicate id {d}")
    for f in families:
        if f.get("tone") not in TONES:
            problems.append(f"{name}: {f['id']} has an unknown tone {f.get('tone')!r}")
    for fid in fam_ids - {b[brick_family] for b in bricks}:
        problems.append(f"{name}: {fid} holds no brick")
    for b in bricks:
        if not b["id"].startswith(prefix):
            problems.append(f"{name}: brick id {b['id']} must start with {prefix!r}")
        if b.get(brick_family) not in fam_ids:
            problems.append(
                f"{name}: {b['id']} names an unknown {brick_family} {b.get(brick_family)!r}"
            )
        deps = b.get("deps", [])
        for d in deps:
            if d == b["id"]:
                problems.append(f"{name}: {b['id']} depends on itself")
            elif d not in by_id:
                problems.append(f"{name}: {b['id']} depends on unknown brick {d}")
        for d in _dupes(deps):
            problems.append(f"{name}: {b['id']} lists {d} twice in deps")
    for d in _dupes([flow["id"] for flow in doc.get("flows", [])]):
        problems.append(f"{name}: duplicate flow id {d}")
    for flow in doc.get("flows", []):
        steps = flow.get("steps", [])
        if len(steps) < 2:
            problems.append(f"{name}: flow {flow['id']} has fewer than two steps")
        for step in steps:
            if step not in by_id:
                problems.append(f"{name}: flow {flow['id']} names unknown brick {step}")
    return by_id


def route_exists(tree: Tree, surface: str) -> bool:
    """Whether a screen path (``/dashboard/chat``) is an App Router page."""
    base = "apps/web/src/app/[lng]"
    tail = surface.rstrip("/")
    candidates = [f"{base}{tail}/page.tsx", f"{base}/(auth){tail}/page.tsx"]
    return any(c in tree.files for c in candidates)


def check_history(
    maps: Maps,
    tree: Tree,
    f_by_id: dict[str, dict],
    t_by_id: dict[str, dict],
    problems: list[str],
) -> None:
    """One entry per decision, chapters contiguous, every reference resolving."""
    hist = maps.history
    themes = {t["id"] for t in hist.get("themes", [])}
    for t in hist.get("themes", []):
        if t.get("tone") not in TONES:
            problems.append(f"history: theme {t['id']} has an unknown tone {t.get('tone')!r}")
    files = adr_files(tree)
    entries = hist.get("entries", [])
    numbers = [e["adr"] for e in entries]
    for n in _dupes([str(x) for x in numbers]):
        problems.append(f"history: ADR-{int(n):03d} has more than one entry")
    for n in sorted(set(files) - set(numbers)):
        problems.append(f"history: ADR-{n:03d} ({files[n]}) has no entry")
    eras = hist.get("eras", [])
    for d in _dupes([str(era.get("id")) for era in eras]):
        problems.append(f"history: duplicate chapter id {d}")
    for i, era in enumerate(eras):
        label = era.get("id")
        if not DATE_RE.match(era.get("from", "")) or (
            era.get("to") is not None and not DATE_RE.match(era["to"])
        ):
            problems.append(f"history: chapter {label!r} has a malformed date range")
        if era.get("to") is None and i != len(eras) - 1:
            problems.append(
                f"history: only the last chapter may be open-ended ({label!r} is not last)"
            )
        if i and eras[i - 1].get("to") and era.get("from", "") <= eras[i - 1]["to"]:
            problems.append(f"history: chapter {label!r} overlaps the previous one")
    for e in entries:
        tag = f"ADR-{e['adr']:03d}"
        if e["adr"] not in files and not str(e.get("nofile", "")).strip():
            problems.append(f"history: {tag} names no ADR file and declares no reason (`nofile`)")
        if e["adr"] in files and e.get("nofile"):
            problems.append(f"history: {tag} declares `nofile` but {files[e['adr']]} exists")
        if not DATE_RE.match(str(e.get("date", ""))):
            problems.append(f"history: {tag} has a malformed date {e.get('date')!r}")
        elif not any(
            e["date"] >= er.get("from", "") and (er.get("to") is None or e["date"] <= er["to"])
            for er in eras
        ):
            problems.append(f"history: {tag} ({e['date']}) falls in no chapter")
        if e.get("theme") not in themes:
            problems.append(f"history: {tag} has an unknown theme {e.get('theme')!r}")
        for fid in e.get("functional", []):
            if fid not in f_by_id:
                problems.append(f"history: {tag} names unknown functional brick {fid}")
        for tid in e.get("technical", []):
            if tid not in t_by_id:
                problems.append(f"history: {tag} names unknown technical brick {tid}")
        if not e.get("functional") and not e.get("technical"):
            problems.append(f"history: {tag} is linked to no brick")


def _list_lengths(maps: Maps, key: str, unit: dict) -> dict[str, int]:
    """The length each list field of a unit must have, read from the structure."""
    name, section, *rest = key.split("/")
    if section == "flows" and rest:
        flow = next((f for f in maps.structure(name).get("flows", []) if f["id"] == rest[0]), None)
        return {"steps": len(flow.get("steps", []))} if flow else {}
    return {}


def check_unit(
    maps: Maps, lang: str, key: str, unit: dict, source: dict | None, problems: list[str]
) -> None:
    """One unit of text: its fields, its lists, and — translated — its fingerprint."""
    name, section = key.split("/")[:2]
    fields = TEXT_SCHEMA[name][section]
    allowed = set(fields) | ({FINGERPRINT} if lang != SOURCE_LANG else set())
    for extra in sorted(set(unit) - allowed):
        problems.append(f"text {lang}: {key} has an unknown field {extra!r}")
    lengths = _list_lengths(maps, key, unit)
    for field in fields:
        value = unit.get(field)
        if field in LIST_FIELDS:
            if not isinstance(value, list) or not all(
                isinstance(x, str) and x.strip() for x in value
            ):
                problems.append(f"text {lang}: {key} has no well-formed {field} list")
                continue
            want = lengths.get(field)
            if want is None and source is not None and isinstance(source.get(field), list):
                want = len(source[field])
            if want is not None and len(value) != want:
                problems.append(f"text {lang}: {key} lists {len(value)} {field}, the source {want}")
        elif not isinstance(value, str) or not value.strip():
            problems.append(f"text {lang}: {key} has no {field}")
    if lang == SOURCE_LANG or source is None:
        return
    for field in fields:
        mine, theirs = unit.get(field), source.get(field)
        # A list of another length is reported above; compare what both hold.
        pairs = (
            zip(mine, theirs, strict=False)
            if isinstance(mine, list) and isinstance(theirs, list)
            else [(mine, theirs)]
        )
        if any(
            isinstance(a, str) and a == b and len(a) >= UNTRANSLATED_MIN_CHARS for a, b in pairs
        ):
            problems.append(f"text {lang}: {key} {field} is the French text, not a translation")
    stamp = unit.get(FINGERPRINT)
    if stamp is None:
        problems.append(
            f"text {lang}: {key} carries no fingerprint — run `task docs:maps` to stamp it"
        )
    elif stamp != fingerprint(source):
        problems.append(
            f"text {lang}: {key} is stale — the French changed since it was translated "
            f"(translate it again, then `--restamp {key}`)"
        )


def check_text(maps: Maps, tree: Tree, problems: list[str]) -> None:
    """Every unit in every language of the site; no translation stale or copied."""
    langs = site_languages(tree)
    for lang in sorted(set(maps.text) - set(langs)):
        problems.append(f"text: {lang} has map text but is no language of the site")
    source_units = text_units(maps, SOURCE_LANG)
    for lang in langs:
        for name in MAP_NAMES:
            if name not in maps.text.get(lang, {}):
                problems.append(f"text {lang}: {DATA_DIR}/text/{name}.{lang}.json is missing")
        if not maps.text.get(lang):
            continue
        units = text_units(maps, lang)
        for key, unit in units.items():
            if unit is None:
                problems.append(f"text {lang}: {key} is missing")
            else:
                check_unit(maps, lang, key, unit, source_units.get(key), problems)
        for name, sections in TEXT_SCHEMA.items():
            doc = maps.text.get(lang, {}).get(name, {})
            for extra in sorted(set(doc) - set(sections)):
                problems.append(f"text {lang}: {name} has an unknown section {extra!r}")
            for section in sections:
                if section == "intro":
                    continue
                known = set(unit_ids(maps, name, section))
                for orphan in sorted(set(doc.get(section, {})) - known):
                    problems.append(
                        f"text {lang}: {name}/{section}/{orphan} names nothing in the structure"
                    )


def check_all(maps: Maps, tree: Tree) -> list[str]:
    """Every finding that makes the maps untrue to the tree."""
    problems: list[str] = []
    f_by_id = check_map("functional", maps.functional, "groups", "group", problems)
    t_by_id = check_map("technical", maps.technical, "layers", "layer", problems)

    # Screens and paths the bricks point at.
    for b in f_by_id.values():
        for s in b.get("surfaces", []):
            if not route_exists(tree, s):
                problems.append(f"functional: {b['id']} names screen {s}, which is no route")
    for b in t_by_id.values():
        for p in b.get("paths", []):
            if not tree.exists(p):
                problems.append(f"technical: {b['id']} points at {p}, which does not exist")

    # Coverage: every backend domain and infrastructure module belongs somewhere.
    domains = set(backend_domains(tree))
    infra = set(infra_units(tree))
    claimed_domains = {
        d for b in [*f_by_id.values(), *t_by_id.values()] for d in b.get("domains", [])
    }
    claimed_infra = {u for b in t_by_id.values() for u in b.get("infra", [])}
    for d in sorted(domains - claimed_domains):
        problems.append(f"coverage: backend domain {d} is claimed by no brick")
    for d in sorted(claimed_domains - domains):
        problems.append(f"coverage: a brick claims backend domain {d}, which does not exist")
    for u in sorted(infra - claimed_infra):
        problems.append(f"coverage: infrastructure module {u} is claimed by no technical brick")
    for u in sorted(claimed_infra - infra):
        problems.append(f"coverage: a brick claims infrastructure module {u}, which does not exist")

    check_history(maps, tree, f_by_id, t_by_id, problems)
    check_text(maps, tree, problems)

    # Icons of the generated documents.
    for name in sorted(referenced_icons(maps) - set(maps.icons)):
        problems.append(
            f"icons: {name} is drawn but not vendored (run `task docs:maps` with --refresh-icons)"
        )
    return problems


# --------------------------------------------------------------------------- stamping


def ordered_text(maps: Maps, name: str, doc: dict) -> dict:
    """A text document in structure order, fields in schema order, fingerprint last."""
    out: dict = {}
    for section, fields in TEXT_SCHEMA[name].items():
        order = [*fields, FINGERPRINT]
        if section == "intro":
            unit = doc.get("intro")
            if unit is not None:
                out["intro"] = {k: unit[k] for k in order if k in unit}
            continue
        held = doc.get(section, {})
        out[section] = {
            uid: {k: held[uid][k] for k in order if k in held[uid]}
            for uid in unit_ids(maps, name, section)
            if uid in held
        }
    return out


def stamp_translations(maps: Maps, data_dir: Path, restamp: list[str]) -> list[str]:
    """Stamp units translated for the first time, and the re-translated ones named.

    Returns the unit keys it stamped. A stale fingerprint is refreshed ONLY when
    the unit is named in ``restamp`` — refreshing it implicitly would turn "the
    French changed" into "nothing to do" for every translation at once.
    """
    source_units = text_units(maps, SOURCE_LANG)
    stamped: list[str] = []
    for lang, docs in maps.text.items():
        if lang == SOURCE_LANG:
            continue
        for name, doc in docs.items():
            changed = False
            for key, unit in text_units(maps, lang).items():
                if not key.startswith(f"{name}/") or unit is None:
                    continue
                source = source_units.get(key)
                if source is None:
                    continue
                if FINGERPRINT not in unit or key in restamp:
                    wanted = fingerprint(source)
                    if unit.get(FINGERPRINT) != wanted:
                        unit[FINGERPRINT] = wanted
                        stamped.append(f"{lang}:{key}")
                        changed = True
            if changed:
                write_json(data_dir / "text" / f"{name}.{lang}.json", ordered_text(maps, name, doc))
    return stamped


# --------------------------------------------------------------------------- rendering


def _pick(unit: dict, fields: tuple[str, ...]) -> dict:
    return {k: unit[k] for k in fields if k in unit}


def assemble(maps: Maps, lang: str) -> dict[str, dict]:
    """Structure and one language's text merged into the shape the documents read."""
    tx = maps.text[lang]
    fx, tt, hx = tx["functional"], tx["technical"], tx["history"]

    def flows(doc: dict, text: dict) -> list[dict]:
        out = []
        for flow in doc.get("flows", []):
            unit = text["flows"][flow["id"]]
            pairs = zip(flow["steps"], unit["steps"], strict=True)
            steps = [{"brick": b, "text": t} for b, t in pairs]
            out.append(
                {
                    "id": flow["id"],
                    "icon": flow["icon"],
                    **_pick(unit, ("name", "summary")),
                    "steps": steps,
                }
            )
        return out

    functional = {
        "lede": fx["intro"]["lede"],
        "groups": [
            {**g, **_pick(fx["groups"][g["id"]], ("name", "summary"))}
            for g in maps.functional["groups"]
        ],
        "bricks": [
            {**b, **_pick(fx["bricks"][b["id"]], ("name", "role", "goal"))}
            for b in maps.functional["bricks"]
        ],
        "flows": flows(maps.functional, fx),
    }
    technical = {
        "lede": tt["intro"]["lede"],
        "repo": maps.technical["repo"],
        "layers": [
            {**la, **_pick(tt["layers"][la["id"]], ("name", "summary"))}
            for la in maps.technical["layers"]
        ],
        "bricks": [
            {**b, **_pick(tt["bricks"][b["id"]], ("name", "role", "stack"))}
            for b in maps.technical["bricks"]
        ],
        "flows": flows(maps.technical, tt),
    }
    history = {
        "lede": hx["intro"]["lede"],
        "themes": [
            {**t, **_pick(hx["themes"][t["id"]], ("name", "summary"))}
            for t in maps.history["themes"]
        ],
        "eras": [
            {**e, **_pick(hx["eras"][e["id"]], ("name", "summary"))} for e in maps.history["eras"]
        ],
        "entries": [
            {**e, **_pick(hx["entries"][str(e["adr"])], ("title", "summary"))}
            for e in maps.history["entries"]
        ],
    }
    return {"functional": functional, "technical": technical, "history": history}


def _json_for_script(payload: object) -> str:
    """JSON safe inside ``<script type="application/json">``: no ``<`` survives."""
    return json.dumps(payload, ensure_ascii=False, separators=(",", ":")).replace("<", "\\u003c")


def render(page: str, maps: Maps, tree: Tree, docs_dir: Path) -> str:
    """Render one French document from the data, the facts of the tree and the templates."""
    templates = docs_dir / "templates"
    facts = repo_facts(tree)
    files = adr_files(tree)
    docs = assemble(maps, SOURCE_LANG)
    payload = {
        "page": page,
        "pages": {
            k: {"href": v["file"], "label": v["label"], "icon": v["icon"]} for k, v in PAGES.items()
        },
        "repo": maps.technical["repo"],
        "facts": facts,
        "adrFiles": {str(n): f for n, f in sorted(files.items())},
        "icons": {k: maps.icons[k] for k in sorted(maps.icons)},
        **docs,
    }
    logo = (
        (templates / "logo.svg")
        .read_text(encoding="utf-8")
        .strip()
        .replace("grad4", "lia-mark-grad")
    )
    html = (templates / "page.html").read_text(encoding="utf-8")
    replacements = {
        "@@TITLE@@": PAGES[page]["title"],
        "@@DESCRIPTION@@": docs[page]["lede"].replace('"', "&quot;"),
        "@@PAGE@@": page,
        "@@HOME@@": PAGES["functional"]["file"],
        "@@LOGO@@": logo,
        "@@FAVICON@@": "data:image/svg+xml," + quote(logo),
        "@@CSS@@": (templates / "maps.css").read_text(encoding="utf-8").strip(),
        "@@JS@@": (templates / "maps.js").read_text(encoding="utf-8").strip(),
        "@@DATA@@": _json_for_script(payload),
    }
    for key, value in replacements.items():
        html = html.replace(key, value)
    return html


# --------------------------------------------------------------------------- entry point


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    parser.add_argument("root", nargs="?", type=Path, default=ROOT, help="repository root")
    parser.add_argument(
        "--write",
        action="store_true",
        help="regenerate facts.json and the documents, stamp first-time translations",
    )
    parser.add_argument(
        "--refresh-icons",
        action="store_true",
        help="vendor the icons the data names and drop the unused ones (reads apps/web/node_modules for a new one)",
    )
    parser.add_argument(
        "--restamp",
        nargs="+",
        default=[],
        metavar="MAP/SECTION/ID",
        help="accept re-translated units: refresh their fingerprint in every language",
    )
    parser.add_argument(
        "--include-unstaged", action="store_true", help="also count what `git add -A` would stage"
    )
    parser.add_argument(
        "--data-dir", type=Path, default=None, help=f"data directory (default: <root>/{DATA_DIR})"
    )
    parser.add_argument(
        "--docs-dir",
        type=Path,
        default=None,
        help=f"documents directory (default: <root>/{DOCS_DIR})",
    )
    args = parser.parse_args(argv)

    root = args.root.resolve()
    data_dir = (args.data_dir or root / DATA_DIR).resolve()
    docs_dir = (args.docs_dir or root / DOCS_DIR).resolve()
    icons_path = docs_dir / "templates" / "icons.json"
    tree = load_tree(root, args.include_unstaged)
    maps = load_maps(data_dir, icons_path)

    if args.refresh_icons:
        # Only a NEW icon needs the installed package: the vendored ones are kept
        # as they are, so the task also works where apps/web was never installed.
        wanted = referenced_icons(maps)
        fresh, missing = vendor_icons(root, wanted - set(maps.icons))
        if missing:
            print(
                f"doc_maps: no Lucide icon named {', '.join(missing)} in {LUCIDE_DIR}",
                file=sys.stderr,
            )
            return 1
        icons = {name: nodes for name, nodes in {**maps.icons, **fresh}.items() if name in wanted}
        icons_path.write_text(
            json.dumps(dict(sorted(icons.items())), indent=1) + "\n", encoding="utf-8", newline="\n"
        )
        maps = load_maps(data_dir, icons_path)

    if args.write or args.restamp:
        unknown = [k for k in args.restamp if k not in text_units(maps, SOURCE_LANG)]
        if unknown:
            print(f"doc_maps: no unit named {', '.join(unknown)}", file=sys.stderr)
            return 1
        for key in stamp_translations(maps, data_dir, args.restamp):
            print(f"  stamped {key}")
        maps = load_maps(data_dir, icons_path)

    problems = check_all(maps, tree)
    if problems:
        print(f"=== LIVING MAPS: {len(problems)} finding(s) ===")
        for p in problems:
            print(f"  {p}")
        return 1

    drifted: list[str] = []
    facts_path = data_dir / "facts.json"
    facts = site_facts(tree)
    if args.write:
        write_json(facts_path, facts)
    elif not facts_path.exists() or json.loads(facts_path.read_text(encoding="utf-8")) != facts:
        drifted.append(f"{DATA_DIR}/facts.json")
    for page, spec in PAGES.items():
        out = docs_dir / spec["file"]
        html = render(page, maps, tree, docs_dir)
        if args.write:
            out.write_text(html, encoding="utf-8", newline="\n")
        elif not out.exists() or out.read_text(encoding="utf-8") != html:
            drifted.append(f"{DOCS_DIR}/{spec['file']}")
    if drifted:
        print("=== LIVING MAPS: generated files out of date ===")
        for f in drifted:
            print(f"  {f} differs from what the data renders — run `task docs:maps`")
        return 1
    counts = repo_facts(tree)
    verb = "written" if args.write else "up to date"
    print(
        f"Living maps {verb}: {len(maps.functional['bricks'])} functional and "
        f"{len(maps.technical['bricks'])} technical bricks, {len(maps.history['entries'])} "
        f"decisions in {len(site_languages(tree))} languages, {counts['domains']} domains and "
        f"{counts['infra']} infrastructure modules claimed."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
