/**
 * Single source of truth for the "/more" small-attentions page: 53 cards in
 * 6 moment sections, each card carrying one lucide icon and the list of
 * translated micro-labels its animated scene needs.
 *
 * ANTI-REGRESSION CONTRACT: the guard test
 * `__tests__/more-content-coverage.test.ts` asserts the structure (53 unique
 * cards, icon/scene-label completeness), the level contract (keys disjoint
 * from the editorial landing's REQUIRED_FEATURE_KEYS — this page presents
 * craft, one level below capabilities), and the i18n content (every
 * `more.*` key present and non-empty in all 6 locales, no digits in card
 * copy). Adding, renaming, or dropping a card is therefore always a
 * deliberate edit of this file plus its locales — never a silent side
 * effect.
 */

import type { LucideIcon } from 'lucide-react';
import {
  Accessibility,
  AlertTriangle,
  AppWindow,
  ArrowDownCircle,
  BellRing,
  CalendarRange,
  ChevronsDownUp,
  ClipboardPaste,
  Clock,
  Coins,
  Contrast,
  Disc,
  Drama,
  Eclipse,
  Eye,
  FileSpreadsheet,
  FileUp,
  Gauge,
  Handshake,
  History,
  Hourglass,
  LayoutGrid,
  LibraryBig,
  LifeBuoy,
  Link2,
  ListChecks,
  ListTree,
  MailPlus,
  Menu,
  MessageSquareCheck,
  MessageSquarePlus,
  MonitorSmartphone,
  Orbit,
  Palette,
  PanelLeft,
  PanelsTopLeft,
  PanelTop,
  Paperclip,
  PencilLine,
  PenLine,
  Puzzle,
  Radio,
  RefreshCw,
  RotateCcw,
  ScrollText,
  Search,
  Share2,
  SlashSquare,
  Smartphone,
  Smile,
  Sparkles,
  Star,
  TextSearch,
  TextSelect,
  ThumbsUp,
  ToggleLeft,
  Vibrate,
  Wind,
  Zap,
} from 'lucide-react';

export interface MoreSectionConfig {
  /** Stable section identifier (scene-file suffix + anchors). */
  id: 'write' | 'respond' | 'recover' | 'find' | 'daily' | 'unseen';
  /** i18n suffix under `more.sections.`. */
  key: 's1' | 's2' | 's3' | 's4' | 's5' | 's6';
  /** Display number of the section heading eyebrow. */
  num: string;
  /** Alternating card background for visual rhythm (editorial pattern). */
  tinted: boolean;
  /** Card keys in display order. */
  cards: readonly string[];
}

export const MORE_SECTIONS: readonly MoreSectionConfig[] = [
  {
    id: 'write',
    key: 's1',
    num: '01',
    tinted: false,
    cards: ['draft_survives', 'slash_commands', 'paste_screenshot', 'drop_zone'],
  },
  {
    id: 'respond',
    key: 's2',
    num: '02',
    tinted: true,
    cards: [
      'expressive_eyes',
      'living_face',
      'followup_chips',
      'scroll_return',
      'bubble_actions',
      'provenance_why',
      'selection_actions',
      'peer_actions',
      'share_export',
      'backstage',
    ],
  },
  {
    id: 'recover',
    key: 's3',
    num: '03',
    tinted: false,
    cards: [
      'actionable_errors',
      'retry_turn',
      'honest_freshness',
      'quota_warning',
      'image_expiry',
      'attachment_limits',
      'fix_commitment',
      'meeting_banner',
      'diagnosis_evidence',
    ],
  },
  {
    id: 'find',
    key: 's4',
    num: '04',
    tinted: true,
    cards: [
      'settings_shell',
      'settings_tones',
      'settings_search',
      'deep_links',
      'history_search',
      'template_library',
      'mail_label_source',
      'mobile_logo_nav',
      'relation_star',
      'relation_sections',
    ],
  },
  {
    id: 'daily',
    key: 's5',
    num: '05',
    tinted: false,
    cards: [
      'briefing_custom',
      'card_actions',
      'alerts_hub',
      'week_grid',
      'folded_settings',
      'starter_checklist',
      'empty_starters',
      'pwa',
      'server_escape_hatch',
    ],
  },
  {
    id: 'unseen',
    key: 's6',
    num: '06',
    tinted: true,
    cards: [
      'background_response',
      'activity_timeline',
      'claim_before_effect',
      'capability_map',
      'capability_honesty',
      'finished_answer',
      'air_quality_honesty',
      'plugin_report',
      'widgets_travel',
      'cost_transparency',
      'pricing_workbook',
      'haptics',
      'readable_at_a_glance',
      'oled_black',
      'a11y_care',
      'frosted_glass',
      'narrow_screens',
    ],
  },
] as const;

/** Flat card-key inventory, derived — display order. */
export const MORE_CARD_KEYS: readonly string[] = MORE_SECTIONS.flatMap(s => [...s.cards]);

/** One lucide icon per card (guard-enforced completeness). */
export const CARD_ICONS: Record<string, LucideIcon> = {
  draft_survives: PenLine,
  slash_commands: SlashSquare,
  paste_screenshot: ClipboardPaste,
  drop_zone: FileUp,
  meeting_banner: Disc,
  diagnosis_evidence: ScrollText,
  expressive_eyes: Eye,
  living_face: Smile,
  followup_chips: MessageSquarePlus,
  scroll_return: ArrowDownCircle,
  bubble_actions: ThumbsUp,
  selection_actions: TextSelect,
  peer_actions: Handshake,
  share_export: Share2,
  backstage: Drama,
  actionable_errors: AlertTriangle,
  retry_turn: RotateCcw,
  honest_freshness: RefreshCw,
  quota_warning: Gauge,
  image_expiry: Clock,
  attachment_limits: Paperclip,
  fix_commitment: PencilLine,
  settings_shell: PanelLeft,
  settings_tones: Palette,
  settings_search: TextSearch,
  deep_links: Link2,
  history_search: History,
  template_library: LibraryBig,
  mail_label_source: MailPlus,
  mobile_logo_nav: Menu,
  relation_star: Star,
  relation_sections: PanelsTopLeft,
  briefing_custom: LayoutGrid,
  card_actions: Zap,
  starter_checklist: ListChecks,
  empty_starters: Sparkles,
  pwa: MonitorSmartphone,
  server_escape_hatch: LifeBuoy,
  background_response: Radio,
  activity_timeline: ListTree,
  claim_before_effect: Hourglass,
  widgets_travel: AppWindow,
  cost_transparency: Coins,
  pricing_workbook: FileSpreadsheet,
  readable_at_a_glance: Contrast,
  oled_black: Eclipse,
  a11y_care: Accessibility,
  haptics: Vibrate,
  folded_settings: ChevronsDownUp,
  frosted_glass: PanelTop,
  provenance_why: Search,
  alerts_hub: BellRing,
  week_grid: CalendarRange,
  capability_map: Orbit,
  capability_honesty: ToggleLeft,
  finished_answer: MessageSquareCheck,
  air_quality_honesty: Wind,
  plugin_report: Puzzle,
  narrow_screens: Smartphone,
};

/**
 * Translated micro-labels each animated scene needs, as i18n suffixes under
 * `more.scenes.<cardKey>.`. Everything else inside a stage is skeleton bars
 * and icons — scenes stay language-light by design.
 */
export const SCENE_LABEL_KEYS: Readonly<Record<string, readonly string[]>> = {
  draft_survives: ['typing'],
  slash_commands: [],
  paste_screenshot: [],
  drop_zone: [],
  meeting_banner: ['recording', 'interrupted', 'resume'],
  diagnosis_evidence: [],
  expressive_eyes: [],
  living_face: [],
  followup_chips: ['chip1', 'chip2'],
  scroll_return: [],
  bubble_actions: ['copied'],
  selection_actions: ['action'],
  peer_actions: ['reply'],
  share_export: [],
  backstage: [],
  actionable_errors: ['cause', 'action'],
  retry_turn: [],
  honest_freshness: ['fresh', 'retry'],
  quota_warning: ['warned'],
  image_expiry: [],
  attachment_limits: ['limit'],
  fix_commitment: ['before', 'after'],
  settings_shell: ['section'],
  settings_tones: ['row1', 'row2', 'row3'],
  settings_search: ['query', 'row1', 'row2'],
  deep_links: [],
  history_search: ['query'],
  template_library: ['mine', 'builtin', 'pick'],
  mail_label_source: ['label', 'space', 'indexed'],
  mobile_logo_nav: [],
  relation_star: [],
  relation_sections: ['section'],
  briefing_custom: [],
  week_grid: [],
  card_actions: ['chip1', 'chip2'],
  starter_checklist: [],
  empty_starters: ['s1', 's2', 's3'],
  pwa: [],
  server_escape_hatch: [],
  background_response: ['ready'],
  activity_timeline: ['entry1', 'entry2', 'entry3'],
  claim_before_effect: ['claimed', 'acting', 'settled'],
  widgets_travel: [],
  cost_transparency: [],
  pricing_workbook: ['preview'],
  haptics: [],
  folded_settings: [],
  readable_at_a_glance: [],
  oled_black: [],
  a11y_care: [],
  frosted_glass: [],
  provenance_why: [],
  alerts_hub: [],
  capability_map: [],
  capability_honesty: ['capability', 'reason'],
  finished_answer: ['announce', 'done'],
  air_quality_honesty: ['index', 'category'],
  plugin_report: ['skill', 'server', 'installed', 'skipped', 'reason'],
  narrow_screens: [],
};
