/**
 * Single source of truth for the "/more" small-attentions page: 90 cards in
 * 6 moment sections, each card carrying one lucide icon and the list of
 * translated micro-labels its animated scene needs.
 *
 * ANTI-REGRESSION CONTRACT: the guard test
 * `__tests__/more-content-coverage.test.ts` asserts the structure (90 unique
 * cards, icon/scene-label completeness), the level contract (keys disjoint
 * from the editorial landing's REQUIRED_FEATURE_KEYS — this page presents
 * craft, one level below capabilities), and the i18n content (every
 * `more.*` key present and non-empty in all 6 locales, no digits in card
 * copy). Adding, renaming, or dropping a card is therefore always a
 * deliberate edit of this file plus its locales — never a silent side
 * effect.
 */

import type { LucideIcon } from 'lucide-react';
import {
  Accessibility,
  ALargeSmall,
  AlertTriangle,
  AppWindow,
  ArrowDownCircle,
  AtSign,
  AudioLines,
  BellRing,
  Bookmark,
  CalendarRange,
  ChevronsDownUp,
  CirclePause,
  ClipboardPaste,
  Code2,
  Columns3,
  Clock,
  Coins,
  Contrast,
  Disc,
  Drama,
  Eclipse,
  Eye,
  FilePlus2,
  FileSpreadsheet,
  FileUp,
  FolderTree,
  Gauge,
  Globe,
  Handshake,
  History,
  Hourglass,
  KeyRound,
  LayoutGrid,
  LayoutTemplate,
  Library,
  LibraryBig,
  LifeBuoy,
  Link2,
  ListChecks,
  ListOrdered,
  ListTree,
  MailPlus,
  Menu,
  MessageSquareCheck,
  MessageSquarePlus,
  Mic,
  Metronome,
  Moon,
  MonitorSmartphone,
  PackageCheck,
  PhoneIncoming,
  NotebookPen,
  Orbit,
  Palette,
  PanelLeft,
  PanelsTopLeft,
  PanelTop,
  Paperclip,
  PencilLine,
  PenLine,
  Puzzle,
  Radio,
  RefreshCw,
  Reply,
  RotateCcw,
  ScrollText,
  Search,
  SearchX,
  Send,
  Share2,
  SlashSquare,
  Smartphone,
  Smile,
  Presentation,
  Sliders,
  Sparkles,
  Star,
  Sunrise,
  TextSearch,
  TextSelect,
  ThumbsUp,
  ToggleLeft,
  Vibrate,
  Wind,
  Zap,
  Pin,
} from 'lucide-react';

export interface MoreSectionConfig {
  /** Stable section identifier (scene-file suffix + anchors). */
  id: 'write' | 'respond' | 'recover' | 'find' | 'daily' | 'unseen';
  /** i18n suffix under `more.sections.`. */
  key: 's1' | 's2' | 's3' | 's4' | 's5' | 's6';
  /** Display number of the section heading eyebrow. */
  num: string;
  /** Alternating card background for visual rhythm (editorial pattern). */
  tinted: boolean;
  /** Card keys in display order. */
  cards: readonly string[];
}

export const MORE_SECTIONS: readonly MoreSectionConfig[] = [
  {
    id: 'write',
    key: 's1',
    num: '01',
    tinted: false,
    cards: ['draft_survives', 'slash_commands', 'paste_screenshot', 'drop_zone', 'knowledge_pick'],
  },
  {
    id: 'respond',
    key: 's2',
    num: '02',
    tinted: true,
    cards: [
      'expressive_eyes',
      'living_face',
      'composed_page',
      'card_details',
      'card_compose',
      'code_scroll',
      'followup_chips',
      'scroll_return',
      'bubble_actions',
      'provenance_why',
      'selection_actions',
      'peer_actions',
      'share_export',
      'recipient_suggest',
      'image_share',
      'keep_answer',
      'draft_sequence',
      'network_question',
      'skill_proposal',
      'backstage',
    ],
  },
  {
    id: 'recover',
    key: 's3',
    num: '03',
    tinted: false,
    cards: [
      'actionable_errors',
      'reconnect_all',
      'retry_turn',
      'honest_freshness',
      'honest_gaps',
      'quota_warning',
      'image_expiry',
      'attachment_limits',
      'fix_commitment',
      'meeting_banner',
      'diagnosis_evidence',
    ],
  },
  {
    id: 'find',
    key: 's4',
    num: '04',
    tinted: true,
    cards: [
      'settings_shell',
      'settings_tones',
      'settings_search',
      'frozen_columns',
      'deep_links',
      'history_search',
      'template_library',
      'mail_label_source',
      'sync_count',
      'mobile_logo_nav',
      'relation_star',
      'relation_sections',
      'relation_debrief',
      'pinned_dock',
      'network_grants',
      'skill_library',
    ],
  },
  {
    id: 'daily',
    key: 's5',
    num: '05',
    tinted: false,
    cards: [
      'briefing_custom',
      'card_actions',
      'alerts_hub',
      'week_grid',
      'folded_settings',
      'exchange_rhythm',
      'starter_checklist',
      'empty_starters',
      'pwa',
      'phone_channel',
      'wake_phrase',
      'live_band',
      'live_standby',
      'radio_companion',
      'server_escape_hatch',
    ],
  },
  {
    id: 'unseen',
    key: 's6',
    num: '06',
    tinted: true,
    cards: [
      'background_response',
      'activity_timeline',
      'own_initiative',
      'claim_before_effect',
      'capability_map',
      'capability_honesty',
      'demo_offer',
      'habit_status_holds',
      'finished_answer',
      'air_quality_honesty',
      'plugin_report',
      'widgets_travel',
      'cost_transparency',
      'pricing_workbook',
      'haptics',
      'readable_at_a_glance',
      'oled_black',
      'text_size',
      'a11y_care',
      'frosted_glass',
      'narrow_screens',
      'local_model_fit',
      'slide_never_overflows',
    ],
  },
] as const;

/** Flat card-key inventory, derived — display order. */
export const MORE_CARD_KEYS: readonly string[] = MORE_SECTIONS.flatMap(s => [...s.cards]);

/** One lucide icon per card (guard-enforced completeness). */
export const CARD_ICONS: Record<string, LucideIcon> = {
  draft_survives: PenLine,
  slash_commands: SlashSquare,
  paste_screenshot: ClipboardPaste,
  drop_zone: FileUp,
  knowledge_pick: FilePlus2,
  meeting_banner: Disc,
  diagnosis_evidence: ScrollText,
  expressive_eyes: Eye,
  living_face: Smile,
  composed_page: LayoutTemplate,
  code_scroll: Code2,
  followup_chips: MessageSquarePlus,
  scroll_return: ArrowDownCircle,
  bubble_actions: ThumbsUp,
  selection_actions: TextSelect,
  peer_actions: Handshake,
  share_export: Share2,
  recipient_suggest: AtSign,
  image_share: Send,
  keep_answer: Bookmark,
  card_details: ChevronsDownUp,
  card_compose: Reply,
  draft_sequence: ListOrdered,
  network_question: Globe,
  skill_proposal: PackageCheck,
  backstage: Drama,
  actionable_errors: AlertTriangle,
  reconnect_all: RefreshCw,
  retry_turn: RotateCcw,
  honest_freshness: RefreshCw,
  honest_gaps: SearchX,
  quota_warning: Gauge,
  image_expiry: Clock,
  attachment_limits: Paperclip,
  fix_commitment: PencilLine,
  settings_shell: PanelLeft,
  settings_tones: Palette,
  settings_search: TextSearch,
  frozen_columns: Columns3,
  deep_links: Link2,
  history_search: History,
  template_library: LibraryBig,
  mail_label_source: MailPlus,
  sync_count: FolderTree,
  mobile_logo_nav: Menu,
  relation_star: Star,
  relation_sections: PanelsTopLeft,
  pinned_dock: Pin,
  network_grants: KeyRound,
  skill_library: Library,
  relation_debrief: NotebookPen,
  briefing_custom: LayoutGrid,
  card_actions: Zap,
  starter_checklist: ListChecks,
  empty_starters: Sparkles,
  pwa: MonitorSmartphone,
  phone_channel: PhoneIncoming,
  wake_phrase: Mic,
  live_band: AudioLines,
  live_standby: Moon,
  radio_companion: Radio,
  server_escape_hatch: LifeBuoy,
  background_response: Radio,
  activity_timeline: ListTree,
  own_initiative: Sunrise,
  claim_before_effect: Hourglass,
  widgets_travel: AppWindow,
  cost_transparency: Coins,
  pricing_workbook: FileSpreadsheet,
  readable_at_a_glance: Contrast,
  oled_black: Eclipse,
  text_size: ALargeSmall,
  a11y_care: Accessibility,
  haptics: Vibrate,
  folded_settings: ChevronsDownUp,
  exchange_rhythm: Metronome,
  frosted_glass: PanelTop,
  provenance_why: Search,
  alerts_hub: BellRing,
  week_grid: CalendarRange,
  capability_map: Orbit,
  capability_honesty: ToggleLeft,
  demo_offer: ListChecks,
  habit_status_holds: CirclePause,
  finished_answer: MessageSquareCheck,
  air_quality_honesty: Wind,
  plugin_report: Puzzle,
  narrow_screens: Smartphone,
  local_model_fit: Sliders,
  slide_never_overflows: Presentation,
};

/**
 * Translated micro-labels each animated scene needs, as i18n suffixes under
 * `more.scenes.<cardKey>.`. Everything else inside a stage is skeleton bars
 * and icons — scenes stay language-light by design.
 */
export const SCENE_LABEL_KEYS: Readonly<Record<string, readonly string[]>> = {
  draft_survives: ['typing'],
  slash_commands: [],
  paste_screenshot: [],
  drop_zone: [],
  knowledge_pick: ['file', 'spaces', 'paused'],
  meeting_banner: ['recording', 'interrupted', 'resume'],
  diagnosis_evidence: [],
  expressive_eyes: [],
  living_face: [],
  composed_page: ['plain', 'composed'],
  code_scroll: [],
  followup_chips: ['chip1', 'chip2'],
  scroll_return: [],
  bubble_actions: ['copied'],
  selection_actions: ['action'],
  peer_actions: ['reply'],
  share_export: ['file', 'peer', 'prefill'],
  recipient_suggest: ['query', 'contact', 'address'],
  image_share: ['peer', 'comment', 'received'],
  keep_answer: ['kept', 'gone'],
  card_details: ['more', 'free'],
  card_compose: ['reply', 'context', 'draft'],
  draft_sequence: ['summary', 'first', 'second', 'report'],
  network_question: ['host', 'question', 'with_data', 'without_data', 'refuse', 'resumed'],
  skill_proposal: ['name', 'install', 'installed'],
  backstage: [],
  actionable_errors: ['cause', 'action'],
  reconnect_all: ['alert', 'all', 'done'],
  retry_turn: [],
  honest_freshness: ['fresh', 'retry'],
  honest_gaps: ['obtained', 'fallback', 'missing', 'tried'],
  quota_warning: ['warned'],
  image_expiry: [],
  attachment_limits: ['limit'],
  fix_commitment: ['before', 'after'],
  settings_shell: ['section'],
  settings_tones: ['row1', 'row2', 'row3'],
  settings_search: ['query', 'row1', 'row2'],
  frozen_columns: ['email', 'switches'],
  deep_links: [],
  history_search: ['query'],
  template_library: ['mine', 'builtin', 'pick'],
  mail_label_source: ['label', 'space', 'indexed'],
  sync_count: ['sync', 'counting', 'files', 'confirm'],
  mobile_logo_nav: [],
  relation_star: [],
  relation_sections: ['section'],
  pinned_dock: [],
  network_grants: ['reachable', 'connector', 'grant', 'scope', 'revoke', 'revoked'],
  skill_library: ['query', 'result', 'audit', 'installed'],
  relation_debrief: ['open', 'next'],
  briefing_custom: [],
  week_grid: [],
  card_actions: ['chip1', 'chip2'],
  starter_checklist: [],
  empty_starters: ['s1', 's2', 's3'],
  pwa: [],
  phone_channel: ['calling', 'spoken', 'answer'],
  wake_phrase: ['listening', 'beta', 'heard', 'stop'],
  live_band: ['status', 'you', 'working', 'lia', 'meter'],
  live_standby: ['live', 'asleep', 'wake'],
  radio_companion: ['news', 'day', 'source', 'timer'],
  server_escape_hatch: [],
  background_response: ['ready'],
  activity_timeline: ['entry1', 'entry2', 'entry3'],
  own_initiative: ['asked', 'alone'],
  claim_before_effect: ['claimed', 'acting', 'settled'],
  widgets_travel: [],
  cost_transparency: [],
  pricing_workbook: ['preview'],
  haptics: [],
  folded_settings: [],
  exchange_rhythm: ['frequent', 'occasional', 'cost'],
  readable_at_a_glance: [],
  oled_black: [],
  text_size: [],
  a11y_care: [],
  frosted_glass: [],
  provenance_why: [],
  alerts_hub: [],
  capability_map: [],
  capability_honesty: ['capability', 'reason'],
  demo_offer: ['on', 'off', 'source'],
  habit_status_holds: ['habit', 'paused'],
  finished_answer: ['announce', 'done'],
  air_quality_honesty: ['index', 'category'],
  plugin_report: ['skill', 'server', 'installed', 'skipped', 'reason'],
  narrow_screens: [],
  local_model_fit: ['thinking', 'dropped'],
  slide_never_overflows: [],
};
