"""Central i18n for the meetings feature (recording & structured minutes, ADR-258).

Strings the BACKEND renders into artifacts the user keeps — the header labels
of the Markdown/PDF/email rendering, the speaker placeholder, the proactive
notification title and the auto-created knowledge-space name. Template names
and section labels live in ``core/i18n_meeting_templates.py`` (ADR-259). Everything the
UI shows lives in the frontend locales; nothing here is a chat message.

Six supported languages, keyed by the backend-canonical code (``zh-CN``);
``normalize_language`` from ``core.i18n`` is the only entry point for raw
locale strings. Data module (like the other ``core/i18n_*``): no domain imports,
exempt from the size ratchet.
"""

from __future__ import annotations

from src.core.constants import MEETINGS_DEFAULT_BUILTIN_TEMPLATE_KEY
from src.core.i18n import normalize_language
from src.core.i18n_meeting_templates import get_section_label as _get_section_label
from src.core.i18n_meeting_templates import get_template_name as _get_template_name

_DEFAULT = "en"

_HEADER_LABELS: dict[str, dict[str, str]] = {
    "en": {
        "date": "Date",
        "time": "Time",
        "duration": "Duration",
        "location": "Location",
        "participants": "Participants",
        "minutes": "Meeting minutes",
        "generated_by": "Minutes generated by LIA from a recording",
        "gap_notice": "The recording was interrupted for a while; some content may be missing.",
        "no_speaker_names": "Speakers are numbered; names were not established from the recording.",
    },
    "fr": {
        "date": "Date",
        "time": "Heure",
        "duration": "Durée",
        "location": "Lieu",
        "participants": "Participants",
        "minutes": "Compte rendu de réunion",
        "generated_by": "Compte rendu généré par LIA à partir d'un enregistrement",
        "gap_notice": "L'enregistrement a été interrompu un moment ; une partie du contenu peut manquer.",
        "no_speaker_names": "Les interlocuteurs sont numérotés ; leurs noms n'ont pas pu être établis.",
    },
    "de": {
        "date": "Datum",
        "time": "Uhrzeit",
        "duration": "Dauer",
        "location": "Ort",
        "participants": "Teilnehmende",
        "minutes": "Besprechungsprotokoll",
        "generated_by": "Von LIA aus einer Aufnahme erstelltes Protokoll",
        "gap_notice": "Die Aufnahme wurde zeitweise unterbrochen; Inhalte können fehlen.",
        "no_speaker_names": "Die Sprechenden sind nummeriert; Namen konnten nicht ermittelt werden.",
    },
    "es": {
        "date": "Fecha",
        "time": "Hora",
        "duration": "Duración",
        "location": "Lugar",
        "participants": "Participantes",
        "minutes": "Acta de la reunión",
        "generated_by": "Acta generada por LIA a partir de una grabación",
        "gap_notice": "La grabación se interrumpió un momento; puede faltar contenido.",
        "no_speaker_names": "Los interlocutores están numerados; no se pudieron establecer sus nombres.",
    },
    "it": {
        "date": "Data",
        "time": "Ora",
        "duration": "Durata",
        "location": "Luogo",
        "participants": "Partecipanti",
        "minutes": "Verbale della riunione",
        "generated_by": "Verbale generato da LIA a partire da una registrazione",
        "gap_notice": "La registrazione è stata interrotta per un po'; parte del contenuto potrebbe mancare.",
        "no_speaker_names": "Gli interlocutori sono numerati; i nomi non sono stati individuati.",
    },
    "zh-CN": {
        "date": "日期",
        "time": "时间",
        "duration": "时长",
        "location": "地点",
        "participants": "参会者",
        "minutes": "会议纪要",
        "generated_by": "由 LIA 根据录音生成的会议纪要",
        "gap_notice": "录音曾中断一段时间，部分内容可能缺失。",
        "no_speaker_names": "发言人以编号表示，未能从录音中确定姓名。",
    },
}

_SPEAKER_LABEL: dict[str, str] = {
    "en": "Speaker {n}",
    "fr": "Interlocuteur {n}",
    "de": "Sprecher {n}",
    "es": "Interlocutor {n}",
    "it": "Interlocutore {n}",
    "zh-CN": "发言人 {n}",
}

_SPACE_NAME: dict[str, str] = {
    "en": "Meetings",
    "fr": "Réunions",
    "de": "Besprechungen",
    "es": "Reuniones",
    "it": "Riunioni",
    "zh-CN": "会议",
}

_SPACE_DESCRIPTION: dict[str, str] = {
    "en": "Minutes of the meetings you recorded with LIA, ready for questions.",
    "fr": "Les comptes rendus des réunions enregistrées avec LIA, prêts pour vos questions.",
    "de": "Protokolle der mit LIA aufgenommenen Besprechungen, bereit für Ihre Fragen.",
    "es": "Actas de las reuniones grabadas con LIA, listas para tus preguntas.",
    "it": "Verbali delle riunioni registrate con LIA, pronti per le tue domande.",
    "zh-CN": "用 LIA 录制的会议纪要，可随时提问。",
}

#: Why the built-in default template applied instead of an automatic choice
#: (ADR-259). Shown to the user next to the format of their minutes.
_SELECTION_FALLBACK: dict[str, dict[str, str]] = {
    "low_confidence": {
        "en": "LIA was not sure enough of a better template (confidence {confidence}), so the default minutes apply.",
        "fr": "LIA n'était pas assez sûre d'un meilleur modèle (confiance {confidence}) : le compte rendu par défaut s'applique.",
        "de": "LIA war sich eines besseren Modells nicht sicher genug (Konfidenz {confidence}), daher gilt das Standardprotokoll.",
        "es": "LIA no estaba lo bastante segura de un modelo mejor (confianza {confidence}); se aplica el acta por defecto.",
        "it": "LIA non era abbastanza sicura di un modello migliore (confidenza {confidence}): si applica il verbale predefinito.",
        "zh-CN": "LIA 对更合适的模板把握不足（置信度 {confidence}），因此采用默认纪要。",
    },
    "unknown_choice": {
        "en": "LIA named a template that does not exist, so the default minutes apply.",
        "fr": "LIA a désigné un modèle qui n'existe pas : le compte rendu par défaut s'applique.",
        "de": "LIA nannte ein Modell, das es nicht gibt, daher gilt das Standardprotokoll.",
        "es": "LIA indicó un modelo que no existe; se aplica el acta por defecto.",
        "it": "LIA ha indicato un modello inesistente: si applica il verbale predefinito.",
        "zh-CN": "LIA 指定了不存在的模板，因此采用默认纪要。",
    },
    "unavailable": {
        "en": "The template choice was unavailable, so the default minutes apply.",
        "fr": "Le choix du modèle n'a pas pu être fait : le compte rendu par défaut s'applique.",
        "de": "Die Modellwahl war nicht verfügbar, daher gilt das Standardprotokoll.",
        "es": "La elección del modelo no estuvo disponible; se aplica el acta por defecto.",
        "it": "La scelta del modello non era disponibile: si applica il verbale predefinito.",
        "zh-CN": "无法完成模板选择，因此采用默认纪要。",
    },
}

_NOTIFICATION_TITLE: dict[str, str] = {
    "en": "Meeting minutes ready",
    "fr": "Compte rendu de réunion prêt",
    "de": "Besprechungsprotokoll fertig",
    "es": "Acta de la reunión lista",
    "it": "Verbale della riunione pronto",
    "zh-CN": "会议纪要已就绪",
}


def _lang(language: str | None) -> str:
    """Resolve a raw locale to a table key: the single chokepoint decides the
    fallback (the configured default language), never this module."""
    code = normalize_language(language or "")
    return code if code in _SPEAKER_LABEL else _DEFAULT


def get_header_label(key: str, language: str | None) -> str:
    """Localized header label used by the Markdown/PDF/email rendering."""
    table = _HEADER_LABELS.get(_lang(language), _HEADER_LABELS[_DEFAULT])
    return table.get(key, _HEADER_LABELS[_DEFAULT][key])


def get_section_label(key: str, language: str | None) -> str:
    """Localized label of a section key (delegates to the template data module)."""
    return _get_section_label(key, language)


def get_template_name(language: str | None) -> str:
    """Name of the built-in default template (ADR-259: one catalogue entry among thirty)."""
    return _get_template_name(MEETINGS_DEFAULT_BUILTIN_TEMPLATE_KEY, language)


def get_speaker_label(index: int, language: str | None) -> str:
    """Placeholder name of an unnamed diarized speaker (1-based)."""
    return _SPEAKER_LABEL.get(_lang(language), _SPEAKER_LABEL[_DEFAULT]).format(n=index)


def get_space_name(language: str | None) -> str:
    """Default name of the auto-created « Réunions » knowledge space."""
    return _SPACE_NAME.get(_lang(language), _SPACE_NAME[_DEFAULT])


def get_space_description(language: str | None) -> str:
    """Default description of the auto-created knowledge space."""
    return _SPACE_DESCRIPTION.get(_lang(language), _SPACE_DESCRIPTION[_DEFAULT])


def get_selection_fallback_reason(kind: str, language: str | None, **values: str) -> str:
    """Why the default template applied instead of an automatic choice (ADR-259)."""
    table = _SELECTION_FALLBACK[kind]
    return table.get(_lang(language), table[_DEFAULT]).format(**values)


def get_notification_title(language: str | None) -> str:
    """Title of the « minutes ready » proactive notification."""
    return _NOTIFICATION_TITLE.get(_lang(language), _NOTIFICATION_TITLE[_DEFAULT])


def supported_languages() -> tuple[str, ...]:
    """Languages every table above covers (parity test oracle)."""
    return tuple(_SPEAKER_LABEL.keys())
