"""Golden characterization net for ``Draft.get_detailed_preview`` (extraction #2).

Pins the EXACT output string (byte-identical equality) of
``Draft.get_detailed_preview`` for a representative set of drafts covering
every ``DraftType`` value and every rendering branch, BEFORE the renderer is
extracted from ``drafts/models.py`` to a dedicated presentation module
(``drafts/preview_renderer.py``). Method: characterization-first decomposition
(Feathers), as applied by ADR-122 for the voice/TTS extraction — the net must
pass identically, unmodified, after the extraction.

The confirmation surfaces render this string verbatim, so the contract is
byte-identical output — assertions are full-string equality against the
``EXPECTED`` golden table (generated by running the implementation, never
written by hand), never substring checks. The table is regenerated ONLY on a
deliberate, reviewed behavior change, with the old/new tables diffed to prove
the change is surgical.

Two regenerations so far: the 2026-07-11 fallback fixes (localized
``no_subject``, ``None`` body, reminder ``"?"``), and ADR-276 lot 13, where
the vocabulary itself changed from HTML to Markdown — all 85 cases, each
diffed. A net that pins EVERY case is what makes such a change reviewable
rather than merely tested: the diff IS the change.

Branch coverage encoded in the case table:
- Email send/reply/forward shared branch: cc/bcc present and absent, forward
  attachments with ``filename`` key, ``name`` fallback, and ``"?"`` fallback.
- Email delete: ``from`` key vs ``from_addr`` fallback, date present/absent,
  and the localized ``no_subject`` fallback for a missing or empty subject
  (fixed 2026-07-11 — was a hardcoded French ``"(sans objet)"``).
- Reminder delete: full, partial, and fully-empty content (``"?"`` fallback
  line, consistent with the other delete types — fixed 2026-07-11).
- Event create/update/delete: timed vs all-day (``dateTime`` vs ``date``),
  modified-field ``✏️`` marks vs values preserved from ``current_event``,
  attendee ``email`` vs ``displayName`` fallback, empty content.
- Contact create/update/delete: modified marks vs ``current_contact``
  fallbacks, empty ``names`` list rendering ``"?"``.
- Task create/update/delete: due/notes present/absent, marks vs
  ``current_task`` fallbacks.
- File delete: ``mimeType`` present/absent, missing file dict.
- Label delete: ``children_only`` mode, 0 / few / more-than-5 sublabels
  (``... (+N)`` truncation), sublabel ``name`` fallback to ``"?"``.
- Forward body ``None``: shows NO message block at all (2026-07-11 it stopped
  rendering the literal string ``"None"``; lot 13 stopped heading an empty
  block, since a label above emptiness states less than silence).
- All 6 supported languages on the email branch, zh-CN datetime formatting,
  timezone conversion (Europe/Paris vs America/New_York), and the default
  argument binding (fr + DEFAULT_USER_DISPLAY_TIMEZONE).
- Unknown draft type: fallback to ``get_summary`` → ``"Draft (<value>)"``.
- MIXED cases (one field modified, the others preserved/absent) on every
  update type and on multi-optional create types: all-new/all-preserved pairs
  alone would let condition cross-wiring (e.g. the ✏️ mark of one field driven
  by another field's presence) pass undetected through the extraction.
"""

from __future__ import annotations

import json
from enum import Enum
from typing import Any, NamedTuple

import pytest

from src.core.i18n_drafts import get_draft_preview_labels
from src.domains.agents.drafts.models import Draft, DraftType


class PreviewCase(NamedTuple):
    """One golden case: draft type + content + rendering args.

    Attributes:
        case_id: Unique key into the ``EXPECTED`` golden table.
        draft_type: The ``DraftType`` under test.
        content: The draft ``content`` dict, mirroring what the matching
            ``*DraftInput.model_dump()`` produces in the real flow.
        language: User language passed to ``get_detailed_preview``.
        timezone: IANA timezone passed to ``get_detailed_preview``.
    """

    case_id: str
    draft_type: DraftType
    content: dict[str, Any]
    language: str = "fr"
    timezone: str = "Europe/Paris"


_EMAIL_FULL_CONTENT: dict[str, Any] = {
    "to": "alice@example.com",
    "cc": "bob@example.com",
    "bcc": "carol@example.com",
    "subject": "Projet LIA — point d'étape",
    "body": "Bonjour Alice,<br/>voici le point d'étape.",
    "is_html": False,
}

CASES: tuple[PreviewCase, ...] = (
    # ------------------------------------------------------------- Email send
    PreviewCase("email_full_fr", DraftType.EMAIL, _EMAIL_FULL_CONTENT),
    PreviewCase(
        "email_minimal_en",
        DraftType.EMAIL,
        {"to": "dave@example.com", "subject": "Quick sync", "body": "See you at 10."},
        language="en",
    ),
    # Label sweep: same content, remaining languages (fr covered above).
    PreviewCase("email_labels_en", DraftType.EMAIL, _EMAIL_FULL_CONTENT, language="en"),
    PreviewCase("email_labels_es", DraftType.EMAIL, _EMAIL_FULL_CONTENT, language="es"),
    PreviewCase("email_labels_de", DraftType.EMAIL, _EMAIL_FULL_CONTENT, language="de"),
    PreviewCase("email_labels_it", DraftType.EMAIL, _EMAIL_FULL_CONTENT, language="it"),
    PreviewCase("email_labels_zh", DraftType.EMAIL, _EMAIL_FULL_CONTENT, language="zh-CN"),
    # ------------------------------------------------------------ Email reply
    PreviewCase(
        "email_reply_fr",
        DraftType.EMAIL_REPLY,
        {
            "message_id": "m123",
            "to": "erin@example.com",
            "subject": "Re: Devis",
            "body": "Merci, c'est validé.",
            "reply_all": False,
            "original_subject": "Devis",
            "original_from": "erin@example.com",
        },
    ),
    PreviewCase(
        "email_reply_with_cc_fr",
        DraftType.EMAIL_REPLY,
        {
            "message_id": "m124",
            "to": "erin@example.com",
            "cc": "frank@example.com",
            "subject": "Re: Devis",
            "body": "Merci, c'est validé.",
        },
    ),
    # ---------------------------------------------------------- Email forward
    PreviewCase(
        "email_forward_attachments_fr",
        DraftType.EMAIL_FORWARD,
        {
            "message_id": "m456",
            "to": "greg@example.com",
            "cc": "clara@example.com",
            "subject": "Fwd: Contrat",
            "body": "Pour info.",
            "attachments": [
                {
                    "filename": "contrat.pdf",
                    "mime_type": "application/pdf",
                    "size": 12345,
                },
                {"name": "annexe.docx"},
                {},
            ],
        },
    ),
    PreviewCase(
        "email_forward_no_attachments_en",
        DraftType.EMAIL_FORWARD,
        {
            "message_id": "m789",
            "to": "ivan@example.com",
            "subject": "Fwd: Report",
            "body": "FYI.",
            "attachments": [],
        },
        language="en",
    ),
    # EmailForwardDraftInput.body defaults to None and model_dump() keeps the
    # key: a None body must render empty, like an empty-string body.
    PreviewCase(
        "email_forward_none_body_fr",
        DraftType.EMAIL_FORWARD,
        {
            "message_id": "m790",
            "to": "judy@example.com",
            "subject": "Fwd: Photos",
            "body": None,
        },
    ),
    # Forward with bcc and no cc: EMAIL_FORWARD gets its own renderer after the
    # extraction — bcc handling and cc-absence must be pinned on this type too.
    PreviewCase(
        "email_forward_bcc_no_cc_fr",
        DraftType.EMAIL_FORWARD,
        {
            "message_id": "m791",
            "to": "greg@example.com",
            "bcc": "mallory@example.com",
            "subject": "Fwd: Contrat",
            "body": "Pour info.",
        },
    ),
    # ----------------------------------------------------------- Email delete
    PreviewCase(
        "email_delete_full_fr",
        DraftType.EMAIL_DELETE,
        {
            "message_id": "m1",
            "from": "jane@example.com",
            "subject": "Newsletter",
            "date": "2026-05-16T14:00:00+02:00",
        },
    ),
    PreviewCase(
        "email_delete_from_addr_fallback_en",
        DraftType.EMAIL_DELETE,
        {
            "message_id": "m2",
            "from_addr": "kyle@example.com",
            "subject": "(no subject)",
        },
        language="en",
    ),
    # Missing subject key falls back to the LOCALIZED no_subject label.
    PreviewCase(
        "email_delete_no_subject_en",
        DraftType.EMAIL_DELETE,
        {"message_id": "m3", "from": "liam@example.com"},
        language="en",
    ),
    # Empty-string subject (the value the tool now stores for a subject-less
    # email) takes the same localized fallback.
    PreviewCase(
        "email_delete_empty_subject_fr",
        DraftType.EMAIL_DELETE,
        {"message_id": "m5", "from": "nina@example.com", "subject": ""},
    ),
    # Neither "from" nor "from_addr" present: pins the "?" sender default.
    PreviewCase(
        "email_delete_no_sender_fr",
        DraftType.EMAIL_DELETE,
        {"message_id": "m4", "subject": "Spam"},
    ),
    # --------------------------------------------------------- Reminder delete
    PreviewCase(
        "reminder_delete_full_fr",
        DraftType.REMINDER_DELETE,
        {"content": "Appeler le médecin", "trigger_at": "2026-05-17T19:00:00+02:00"},
    ),
    # Independent-if branches: content without trigger date.
    PreviewCase(
        "reminder_delete_content_only_fr",
        DraftType.REMINDER_DELETE,
        {"content": "Arroser les plantes"},
    ),
    # Trigger date without content: the content line falls back to "?".
    PreviewCase(
        "reminder_delete_trigger_only_fr",
        DraftType.REMINDER_DELETE,
        {"trigger_at": "2026-05-18T08:00:00+02:00"},
    ),
    # Fully empty content renders the "?" line, consistent with the other
    # delete types (was an empty string before the 2026-07-11 fix).
    PreviewCase("reminder_delete_empty_fr", DraftType.REMINDER_DELETE, {}),
    # ------------------------------------------------------------ Ticket delete
    PreviewCase(
        "ticket_delete_full_fr",
        DraftType.TICKET_DELETE,
        {"ticket_id": "t-1", "title": "Réserver la salle", "children": 2},
    ),
    # A ticket with no steps says nothing about steps: a person confirming
    # one deletion must not read a zero and wonder what it counts.
    PreviewCase(
        "ticket_delete_alone_fr",
        DraftType.TICKET_DELETE,
        {"title": "Réserver la salle", "children": 0},
    ),
    # Empty content renders the "?" line, like every other delete type.
    PreviewCase("ticket_delete_empty_fr", DraftType.TICKET_DELETE, {}),
    PreviewCase(
        "ticket_delete_full_en",
        DraftType.TICKET_DELETE,
        {"title": "Book the room", "children": 1},
        language="en",
    ),
    # ------------------------------------------------------------ Event create
    PreviewCase(
        "event_full_fr",
        DraftType.EVENT,
        {
            "summary": "Réunion projet",
            "start_datetime": "2026-06-01T09:00:00+02:00",
            "end_datetime": "2026-06-01T10:30:00+02:00",
            "location": "Salle B",
            "description": "Ordre du jour : budget.",
            "attendees": ["alice@example.com", "bob@example.com"],
        },
    ),
    PreviewCase(
        "event_minimal_en",
        DraftType.EVENT,
        {"summary": "Standup"},
        language="en",
    ),
    # Mixed optional fields: location present, attendees/description absent —
    # kills condition cross-wiring that all-present/all-absent pairs let through.
    PreviewCase(
        "event_location_only_en",
        DraftType.EVENT,
        {
            "summary": "Demo",
            "start_datetime": "2026-06-08T15:00:00+02:00",
            "end_datetime": "2026-06-08T16:00:00+02:00",
            "location": "Room A",
        },
        language="en",
    ),
    PreviewCase(
        "event_full_zh",
        DraftType.EVENT,
        {
            "summary": "项目会议",
            "start_datetime": "2026-06-01T09:00:00+02:00",
            "end_datetime": "2026-06-01T10:30:00+02:00",
            "location": "B会议室",
        },
        language="zh-CN",
    ),
    # ------------------------------------------------------------ Event update
    PreviewCase(
        "event_update_new_times_fr",
        DraftType.EVENT_UPDATE,
        {
            "event_id": "e1",
            "summary": "Réunion déplacée",
            "start_datetime": "2026-06-02T14:00:00+02:00",
            "end_datetime": "2026-06-02T15:00:00+02:00",
            "location": "Salle C",
            "current_event": {
                "summary": "Réunion projet",
                "start": {"dateTime": "2026-06-01T09:00:00+02:00"},
                "end": {"dateTime": "2026-06-01T10:30:00+02:00"},
                "location": "Salle B",
                "attendees": [{"email": "alice@example.com"}],
            },
        },
    ),
    PreviewCase(
        "event_update_preserved_fr",
        DraftType.EVENT_UPDATE,
        {
            "event_id": "e2",
            "current_event": {
                "summary": "Réunion projet",
                "start": {"dateTime": "2026-06-01T09:00:00+02:00"},
                "end": {"dateTime": "2026-06-01T10:30:00+02:00"},
                "location": "Salle B",
                "attendees": [{"email": "alice@example.com"}, {"displayName": "Bob"}],
            },
        },
    ),
    PreviewCase(
        "event_update_allday_fr",
        DraftType.EVENT_UPDATE,
        {
            "event_id": "e3",
            "current_event": {
                "summary": "Anniversaire",
                "start": {"date": "2026-06-03"},
                "end": {"date": "2026-06-04"},
            },
        },
    ),
    PreviewCase(
        "event_update_new_attendees_fr",
        DraftType.EVENT_UPDATE,
        {
            "event_id": "e4",
            "attendees": ["carol@example.com"],
            "current_event": {"summary": "Point équipe"},
        },
    ),
    # Mixed modified/preserved: ONLY the start is new — the ✏️ mark must sit on
    # start alone while end/location/attendees come from current_event unmarked.
    PreviewCase(
        "event_update_mixed_new_start_only_fr",
        DraftType.EVENT_UPDATE,
        {
            "event_id": "e6",
            "start_datetime": "2026-06-01T09:30:00+02:00",
            "current_event": {
                "summary": "Réunion projet",
                "start": {"dateTime": "2026-06-01T09:00:00+02:00"},
                "end": {"dateTime": "2026-06-01T10:30:00+02:00"},
                "location": "Salle B",
                "attendees": [{"email": "alice@example.com"}],
            },
        },
    ),
    PreviewCase("event_update_empty_fr", DraftType.EVENT_UPDATE, {"event_id": "e5"}),
    # ------------------------------------------------------------ Event delete
    PreviewCase(
        "event_delete_full_fr",
        DraftType.EVENT_DELETE,
        {
            "event_id": "e9",
            "event": {
                "summary": "Dentiste",
                "start": {"dateTime": "2026-06-05T11:00:00+02:00"},
            },
        },
    ),
    PreviewCase(
        "event_delete_allday_en",
        DraftType.EVENT_DELETE,
        {
            "event_id": "e10",
            "event": {"summary": "Holiday", "start": {"date": "2026-06-06"}},
        },
        language="en",
    ),
    PreviewCase("event_delete_empty_fr", DraftType.EVENT_DELETE, {"event_id": "e11"}),
    # ---------------------------------------------------------- Contact create
    PreviewCase(
        "contact_full_fr",
        DraftType.CONTACT,
        {
            "name": "Marie Dupont",
            "email": "marie@example.com",
            "phone": "+33612345678",
            "organization": "ACME",
            "notes": "Rencontrée au salon.",
        },
    ),
    PreviewCase("contact_minimal_en", DraftType.CONTACT, {"name": "John Smith"}, language="en"),
    # Mixed optional fields: email only, phone/organization absent.
    PreviewCase(
        "contact_email_only_fr",
        DraftType.CONTACT,
        {"name": "Luc Bernard", "email": "luc@example.com"},
    ),
    # ---------------------------------------------------------- Contact update
    PreviewCase(
        "contact_update_new_fields_fr",
        DraftType.CONTACT_UPDATE,
        {
            "resource_name": "people/c1",
            "name": "Marie Durand",
            "email": "marie.d@example.com",
            "phone": "+33699999999",
            "organization": "NewCorp",
            "current_contact": {
                "names": [{"displayName": "Marie Dupont"}],
                "emailAddresses": [{"value": "marie@example.com"}],
                "phoneNumbers": [{"value": "+33612345678"}],
                "organizations": [{"name": "ACME"}],
            },
        },
    ),
    PreviewCase(
        "contact_update_preserved_fr",
        DraftType.CONTACT_UPDATE,
        {
            "resource_name": "people/c2",
            "current_contact": {
                "names": [{"displayName": "Marie Dupont"}],
                "emailAddresses": [{"value": "marie@example.com"}],
                "phoneNumbers": [{"value": "+33612345678"}],
                "organizations": [{"name": "ACME"}],
            },
        },
    ),
    # Mixed modified/preserved: ONLY the email is new — ✏️ on email alone,
    # name/phone/organization preserved from current_contact unmarked.
    PreviewCase(
        "contact_update_mixed_new_email_only_fr",
        DraftType.CONTACT_UPDATE,
        {
            "resource_name": "people/c6",
            "email": "marie.durand@example.com",
            "current_contact": {
                "names": [{"displayName": "Marie Dupont"}],
                "emailAddresses": [{"value": "marie@example.com"}],
                "phoneNumbers": [{"value": "+33612345678"}],
                "organizations": [{"name": "ACME"}],
            },
        },
    ),
    PreviewCase(
        "contact_update_no_names_en",
        DraftType.CONTACT_UPDATE,
        {"resource_name": "people/c3", "current_contact": {}},
        language="en",
    ),
    # names present but first entry has no displayName → "?" default.
    PreviewCase(
        "contact_update_names_no_displayname_en",
        DraftType.CONTACT_UPDATE,
        {"resource_name": "people/c7", "current_contact": {"names": [{}]}},
        language="en",
    ),
    # ---------------------------------------------------------- Contact delete
    PreviewCase(
        "contact_delete_full_fr",
        DraftType.CONTACT_DELETE,
        {
            "resource_name": "people/c4",
            "contact": {
                "names": [{"displayName": "Paul Martin"}],
                "emailAddresses": [{"value": "paul@example.com"}],
            },
        },
    ),
    PreviewCase(
        "contact_delete_empty_en",
        DraftType.CONTACT_DELETE,
        {"resource_name": "people/c5"},
        language="en",
    ),
    # ------------------------------------------------------------- Task create
    PreviewCase(
        "task_full_fr",
        DraftType.TASK,
        {
            "title": "Préparer le rapport",
            "notes": "Inclure les chiffres Q2.",
            "due": "2026-06-10T00:00:00Z",
            "task_list_id": "@default",
        },
    ),
    PreviewCase("task_minimal_en", DraftType.TASK, {"title": "Buy milk"}, language="en"),
    # Timezone conversion: the same UTC-midnight due date renders as the
    # previous day in America/New_York.
    PreviewCase(
        "task_full_new_york_en",
        DraftType.TASK,
        {"title": "Prepare report", "due": "2026-06-10T00:00:00Z"},
        language="en",
        timezone="America/New_York",
    ),
    # Mixed optional fields: due only, notes absent.
    PreviewCase(
        "task_due_only_en",
        DraftType.TASK,
        {"title": "Renew passport", "due": "2026-07-01T00:00:00Z"},
        language="en",
    ),
    # ------------------------------------------------------------- Task update
    PreviewCase(
        "task_update_new_fr",
        DraftType.TASK_UPDATE,
        {
            "task_id": "t1",
            "title": "Rapport final",
            "due": "2026-06-12T00:00:00Z",
            "notes": "Version corrigée.",
            "current_task": {
                "title": "Préparer le rapport",
                "due": "2026-06-10T00:00:00Z",
                "notes": "Inclure les chiffres Q2.",
            },
        },
    ),
    PreviewCase(
        "task_update_preserved_fr",
        DraftType.TASK_UPDATE,
        {
            "task_id": "t2",
            "current_task": {
                "title": "Préparer le rapport",
                "due": "2026-06-10T00:00:00Z",
                "notes": "Inclure les chiffres Q2.",
            },
        },
    ),
    # Mixed modified/preserved: ONLY the due date is new — ✏️ on due alone,
    # title/notes preserved from current_task unmarked.
    PreviewCase(
        "task_update_mixed_new_due_only_fr",
        DraftType.TASK_UPDATE,
        {
            "task_id": "t5",
            "due": "2026-06-15T00:00:00Z",
            "current_task": {
                "title": "Préparer le rapport",
                "due": "2026-06-10T00:00:00Z",
                "notes": "Inclure les chiffres Q2.",
            },
        },
    ),
    # ------------------------------------------------------------- Task delete
    PreviewCase(
        "task_delete_fr",
        DraftType.TASK_DELETE,
        {"task_id": "t3", "title": "Ancienne tâche"},
    ),
    PreviewCase("task_delete_empty_en", DraftType.TASK_DELETE, {"task_id": "t4"}, language="en"),
    # ------------------------------------------------------------- File delete
    PreviewCase(
        "file_delete_full_fr",
        DraftType.FILE_DELETE,
        {
            "file_id": "f1",
            "file": {"name": "rapport.pdf", "mimeType": "application/pdf"},
        },
    ),
    PreviewCase("file_delete_empty_en", DraftType.FILE_DELETE, {"file_id": "f2"}, language="en"),
    # ------------------------------------------------------------ Label delete
    PreviewCase(
        "label_delete_children_only_fr",
        DraftType.LABEL_DELETE,
        {
            "label_id": "l1",
            "label_name": "pro/clients",
            "children_only": True,
            "sublabels": [{"name": "pro/clients/acme"}, {"name": "pro/clients/globex"}],
        },
    ),
    PreviewCase(
        "label_delete_many_sublabels_fr",
        DraftType.LABEL_DELETE,
        {
            "label_id": "l2",
            "label_name": "pro/archive",
            "sublabels": [{"name": f"pro/archive/{year}"} for year in range(2019, 2026)],
        },
    ),
    # Truncation boundary: exactly 5 sublabels → all listed, no "... (+N)".
    PreviewCase(
        "label_delete_five_sublabels_fr",
        DraftType.LABEL_DELETE,
        {
            "label_id": "l5",
            "label_name": "pro/projets",
            "sublabels": [{"name": f"pro/projets/p{index}"} for index in range(1, 6)],
        },
    ),
    PreviewCase(
        "label_delete_few_sublabels_en",
        DraftType.LABEL_DELETE,
        {
            "label_id": "l3",
            "label_name": "personal",
            "sublabels": [{"name": "personal/travel"}, {}],
        },
        language="en",
    ),
    PreviewCase(
        "label_delete_no_sublabels_fr",
        DraftType.LABEL_DELETE,
        {"label_id": "l4", "label_name": "perso"},
    ),
    # -------------------------------------------------------------- Phone call
    PreviewCase(
        "phone_call_full_fr",
        DraftType.PHONE_CALL,
        {
            "callee_name": "Paul Martin",
            "callee_phone": "+33612345678",
            "objective": "Vérifier sa disponibilité mardi après-midi",
        },
    ),
    # Minimal: callee only — phone and objective rows are omitted.
    PreviewCase(
        "phone_call_minimal_en",
        DraftType.PHONE_CALL,
        {"callee_name": "John Smith"},
        language="en",
    ),
    # ------------------------------------------------------------------ DevOps
    # FN-1: the task text is what the user approves, so it is never truncated.
    PreviewCase(
        "devops_task_full_fr",
        DraftType.DEVOPS_TASK,
        {
            "server": "prod-rpi5",
            "task": "Redémarre le conteneur lia-api-prod et vérifie les logs",
        },
    ),
    # With model-authored context: it reaches the CLI system prompt, so it is
    # part of what the user approves and must appear byte-for-byte.
    PreviewCase(
        "devops_task_with_context_fr",
        DraftType.DEVOPS_TASK,
        {
            "server": "prod-rpi5",
            "task": "Vérifie les logs",
            "context": "reste en lecture seule",
        },
    ),
    # Minimal: server only — the task row is omitted like every optional field.
    PreviewCase(
        "devops_task_minimal_en",
        DraftType.DEVOPS_TASK,
        {"server": "staging"},
        language="en",
    ),
    # ADR-263: a tool whose policy demands a confirmation and that builds no
    # draft of its own. The card must say WHAT will run and WITH WHAT, because
    # that is exactly what the user is being asked to allow.
    PreviewCase(
        "tool_call_full_fr",
        DraftType.TOOL_CALL,
        {
            "tool_name": "mcp_era_cancel_subscription",
            "tool_label": "era: cancel subscription",
            "tool_args": {"plan": "premium", "immediate": True},
        },
    ),
    # A card is read by a human in six languages: no Python spelling (``True``,
    # ``None``, ``{'k': 'v'}``) and no unbounded value — one argument can carry
    # an entire email body.
    PreviewCase(
        "tool_call_hostile_values_fr",
        DraftType.TOOL_CALL,
        {
            "tool_label": "era: cancel subscription",
            "tool_args": {
                "flag": False,
                "nothing": None,
                "nested": {"k": "v"},
                "body": "x" * 200,
            },
        },
    ),
    # Minimal: no arguments — the details row is omitted like every optional field.
    PreviewCase(
        "tool_call_minimal_en",
        DraftType.TOOL_CALL,
        {"tool_label": "era: cancel subscription"},
        language="en",
    ),
    # Peers (A3): the relayed message is what the sender approves — full text.
    PreviewCase(
        "peer_message_full_fr",
        DraftType.PEER_MESSAGE,
        {
            "recipient_name": "Marie Dupont",
            "message": "Demande-lui comment il va",
        },
    ),
    PreviewCase(
        "peer_message_minimal_en",
        DraftType.PEER_MESSAGE,
        {"recipient_name": "Marie Dupont"},
        language="en",
    ),
    # Gmail vacation responder (lot I): enable shows the verbatim auto-reply
    # (subject, body, date bounds as plain YYYY-MM-DD); disable is a single
    # localized sentence.
    PreviewCase(
        "vacation_enable_full_fr",
        DraftType.VACATION_RESPONDER,
        {
            "enable": True,
            "subject": "Absent jusqu'au 30/08",
            "body": "Je suis en congés, je répondrai à mon retour.",
            "start_date": "2026-08-24",
            "end_date": "2026-08-30",
        },
    ),
    PreviewCase(
        "vacation_enable_minimal_en",
        DraftType.VACATION_RESPONDER,
        {"enable": True, "body": "Away until Sept 1."},
        language="en",
    ),
    PreviewCase(
        "vacation_disable_fr",
        DraftType.VACATION_RESPONDER,
        {"enable": False},
    ),
    # Workspace writes (lot F phase write): the preview IS the write contract.
    PreviewCase(
        "spreadsheet_append_fr",
        DraftType.SPREADSHEET_WRITE,
        {
            "spreadsheet_title": "Budget 2026",
            "sheet_name": "Dépenses",
            "mode": "append",
            "values": [["Loyer", "1200"], ["EDF", "80"]],
        },
    ),
    PreviewCase(
        "spreadsheet_update_en",
        DraftType.SPREADSHEET_WRITE,
        {
            "spreadsheet_title": "Budget 2026",
            "sheet_name": "Dépenses",
            "mode": "update",
            "a1_range": "B2:B3",
            "values": [["1300"], ["90"]],
        },
        language="en",
    ),
    PreviewCase(
        "document_append_fr",
        DraftType.DOCUMENT_APPEND,
        {"document_title": "Compte-rendu", "text": "Décision: reporter la réunion."},
    ),
    # Gmail filter creation (lot I): criteria + only the requested actions.
    PreviewCase(
        "email_filter_full_fr",
        DraftType.EMAIL_FILTER,
        {
            "criteria": {"from": "news@x.com", "subject": "promo"},
            "label_name": "Newsletters",
            "archive": True,
            "mark_as_read": True,
        },
    ),
    PreviewCase(
        "email_filter_query_en",
        DraftType.EMAIL_FILTER,
        {"criteria": {"query": "has:attachment larger:5M"}, "archive": False},
        language="en",
    ),
    # Automation draft (ADR-140): title + pre-localized schedule + instruction.
    PreviewCase(
        "scheduled_action_full_fr",
        DraftType.SCHEDULED_ACTION,
        {
            "title": "Revue de presse IA",
            "schedule_human": "Lun, Mer à 08:00",
            "action_prompt": "Fais-moi une revue de presse IA",
        },
    ),
    # Minimal: title only — schedule and instruction rows are omitted.
    PreviewCase(
        "scheduled_action_minimal_en",
        DraftType.SCHEDULED_ACTION,
        {"title": "Daily digest"},
        language="en",
    ),
)


# Golden outputs generated by running the implementation over CASES.
# Regenerate ONLY on a deliberate, reviewed behavior change, and diff the
# old/new tables to prove the change touches exactly the intended cases.
#
# Last regeneration: 2026-09-09, ADR-276 lot 13 — the vocabulary became
# Markdown (85 cases, all 85 changed, each diffed). Four defects the old table
# had pinned went with it: an empty « Message » block on a forward with no
# added words, an event with no times showing « Start: » over nothing, the
# attachments row landing AFTER the body block, and the leading break every
# single preview opened with.
EXPECTED: dict[str, str] = {
    "email_full_fr": "- **Destinataire**\xa0: alice@example.com\n- **Cc**\xa0: bob@example.com\n- **Cci**\xa0: carol@example.com\n- **Objet**\xa0: Projet LIA — point d'étape\n\n**Message**\n\nBonjour Alice,<br/>voici le point d'étape.",
    "email_minimal_en": "- **To**: dave@example.com\n- **Subject**: Quick sync\n\n**Message**\n\nSee you at 10.",
    "email_labels_en": "- **To**: alice@example.com\n- **Cc**: bob@example.com\n- **Bcc**: carol@example.com\n- **Subject**: Projet LIA — point d'étape\n\n**Message**\n\nBonjour Alice,<br/>voici le point d'étape.",
    "email_labels_es": "- **Destinatario**: alice@example.com\n- **Cc**: bob@example.com\n- **Cco**: carol@example.com\n- **Asunto**: Projet LIA — point d'étape\n\n**Mensaje**\n\nBonjour Alice,<br/>voici le point d'étape.",
    "email_labels_de": "- **An**: alice@example.com\n- **Cc**: bob@example.com\n- **Bcc**: carol@example.com\n- **Betreff**: Projet LIA — point d'étape\n\n**Nachricht**\n\nBonjour Alice,<br/>voici le point d'étape.",
    "email_labels_it": "- **Destinatario**: alice@example.com\n- **Cc**: bob@example.com\n- **Ccn**: carol@example.com\n- **Oggetto**: Projet LIA — point d'étape\n\n**Messaggio**\n\nBonjour Alice,<br/>voici le point d'étape.",
    "email_labels_zh": "- **收件人**：alice@example.com\n- **抄送**：bob@example.com\n- **密送**：carol@example.com\n- **主题**：Projet LIA — point d'étape\n\n**内容**\n\nBonjour Alice,<br/>voici le point d'étape.",
    "email_reply_fr": "- **Destinataire**\xa0: erin@example.com\n- **Objet**\xa0: Re: Devis\n\n**Message**\n\nMerci, c'est validé.",
    "email_reply_with_cc_fr": "- **Destinataire**\xa0: erin@example.com\n- **Cc**\xa0: frank@example.com\n- **Objet**\xa0: Re: Devis\n\n**Message**\n\nMerci, c'est validé.",
    "email_forward_attachments_fr": "- **Destinataire**\xa0: greg@example.com\n- **Cc**\xa0: clara@example.com\n- **Objet**\xa0: Fwd: Contrat\n- **Pièces jointes**\xa0: contrat.pdf, annexe.docx, ?\n\n**Message**\n\nPour info.",
    "email_forward_no_attachments_en": "- **To**: ivan@example.com\n- **Subject**: Fwd: Report\n\n**Message**\n\nFYI.",
    "email_forward_none_body_fr": "- **Destinataire**\xa0: judy@example.com\n- **Objet**\xa0: Fwd: Photos",
    "email_forward_bcc_no_cc_fr": "- **Destinataire**\xa0: greg@example.com\n- **Cci**\xa0: mallory@example.com\n- **Objet**\xa0: Fwd: Contrat\n\n**Message**\n\nPour info.",
    "email_delete_full_fr": "- **De**\xa0: jane@example.com\n- **Objet**\xa0: Newsletter\n- **Date**\xa0: samedi 16 mai 2026 à 14:00",
    "email_delete_from_addr_fallback_en": "- **From**: kyle@example.com\n- **Subject**: (no subject)",
    "email_delete_no_subject_en": "- **From**: liam@example.com\n- **Subject**: (no subject)",
    "email_delete_empty_subject_fr": "- **De**\xa0: nina@example.com\n- **Objet**\xa0: (sans objet)",
    "email_delete_no_sender_fr": "- **De**\xa0: ?\n- **Objet**\xa0: Spam",
    "reminder_delete_full_fr": "- **Événement**\xa0: Appeler le médecin\n- **Date**\xa0: dimanche 17 mai 2026 à 19:00",
    "reminder_delete_content_only_fr": "- **Événement**\xa0: Arroser les plantes",
    "reminder_delete_trigger_only_fr": "- **Événement**\xa0: ?\n- **Date**\xa0: lundi 18 mai 2026 à 08:00",
    "reminder_delete_empty_fr": "- **Événement**\xa0: ?",
    "ticket_delete_full_fr": "- **Titre**\xa0: Réserver la salle\n- **Étapes**\xa0: 2",
    "ticket_delete_alone_fr": "- **Titre**\xa0: Réserver la salle",
    "ticket_delete_empty_fr": "- **Titre**\xa0: ?",
    "ticket_delete_full_en": "- **Title**: Book the room\n- **Steps**: 1",
    "event_full_fr": "- **Événement**\xa0: Réunion projet\n- **Début**\xa0: lundi 01 juin 2026 à 09:00\n- **Fin**\xa0: lundi 01 juin 2026 à 10:30\n- **Lieu**\xa0: Salle B\n- **Participants**\xa0: alice@example.com, bob@example.com\n\n**Message**\n\nOrdre du jour : budget.",
    "event_minimal_en": "- **Event**: Standup",
    "event_location_only_en": "- **Event**: Demo\n- **Start**: Monday 08 June 2026 at 15:00\n- **End**: Monday 08 June 2026 at 16:00\n- **Location**: Room A",
    "event_full_zh": "- **事件**：项目会议\n- **开始**：2026年6月1日 星期一 09:00\n- **结束**：2026年6月1日 星期一 10:30\n- **地点**：B会议室",
    "event_update_new_times_fr": "- **Événement**\xa0: Réunion déplacée\n- **Début**\xa0: mardi 02 juin 2026 à 14:00 ✏️\n- **Fin**\xa0: mardi 02 juin 2026 à 15:00 ✏️\n- **Lieu**\xa0: Salle C ✏️\n- **Participants**\xa0: alice@example.com",
    "event_update_preserved_fr": "- **Événement**\xa0: Réunion projet\n- **Début**\xa0: lundi 01 juin 2026 à 09:00\n- **Fin**\xa0: lundi 01 juin 2026 à 10:30\n- **Lieu**\xa0: Salle B\n- **Participants**\xa0: alice@example.com, Bob",
    "event_update_allday_fr": "- **Événement**\xa0: Anniversaire\n- **Début**\xa0: mercredi 03 juin 2026 à 02:00\n- **Fin**\xa0: jeudi 04 juin 2026 à 02:00",
    "event_update_new_attendees_fr": "- **Événement**\xa0: Point équipe\n- **Participants**\xa0: carol@example.com ✏️",
    "event_update_mixed_new_start_only_fr": "- **Événement**\xa0: Réunion projet\n- **Début**\xa0: lundi 01 juin 2026 à 09:30 ✏️\n- **Fin**\xa0: lundi 01 juin 2026 à 10:30\n- **Lieu**\xa0: Salle B\n- **Participants**\xa0: alice@example.com",
    "event_update_empty_fr": "- **Événement**\xa0: ?",
    "event_delete_full_fr": "- **Événement**\xa0: Dentiste\n- **Date**\xa0: vendredi 05 juin 2026 à 11:00",
    "event_delete_allday_en": "- **Event**: Holiday\n- **Date**: Saturday 06 June 2026 at 02:00",
    "event_delete_empty_fr": "- **Événement**\xa0: ?",
    "contact_full_fr": "- **Contact**\xa0: Marie Dupont\n- **Email**\xa0: marie@example.com\n- **Téléphone**\xa0: +33612345678\n- **Organisation**\xa0: ACME",
    "contact_minimal_en": "- **Contact**: John Smith",
    "contact_email_only_fr": "- **Contact**\xa0: Luc Bernard\n- **Email**\xa0: luc@example.com",
    "contact_update_new_fields_fr": "- **Contact**\xa0: Marie Durand ✏️\n- **Email**\xa0: marie.d@example.com ✏️\n- **Téléphone**\xa0: +33699999999 ✏️\n- **Organisation**\xa0: NewCorp ✏️",
    "contact_update_preserved_fr": "- **Contact**\xa0: Marie Dupont\n- **Email**\xa0: marie@example.com\n- **Téléphone**\xa0: +33612345678\n- **Organisation**\xa0: ACME",
    "contact_update_mixed_new_email_only_fr": "- **Contact**\xa0: Marie Dupont\n- **Email**\xa0: marie.durand@example.com ✏️\n- **Téléphone**\xa0: +33612345678\n- **Organisation**\xa0: ACME",
    "contact_update_no_names_en": "- **Contact**: ?",
    "contact_update_names_no_displayname_en": "- **Contact**: ?",
    "contact_delete_full_fr": "- **Contact**\xa0: Paul Martin\n- **Email**\xa0: paul@example.com",
    "contact_delete_empty_en": "- **Contact**: ?",
    "task_full_fr": "- **Tâche**\xa0: Préparer le rapport\n- **Échéance**\xa0: mercredi 10 juin 2026 à 02:00\n\n**Message**\n\nInclure les chiffres Q2.",
    "task_minimal_en": "- **Task**: Buy milk",
    "task_full_new_york_en": "- **Task**: Prepare report\n- **Due**: Tuesday 09 June 2026 at 20:00",
    "task_due_only_en": "- **Task**: Renew passport\n- **Due**: Wednesday 01 July 2026 at 02:00",
    "task_update_new_fr": "- **Tâche**\xa0: Rapport final ✏️\n- **Échéance**\xa0: vendredi 12 juin 2026 à 02:00 ✏️\n- **Message**\xa0: Version corrigée. ✏️",
    "task_update_preserved_fr": "- **Tâche**\xa0: Préparer le rapport\n- **Échéance**\xa0: mercredi 10 juin 2026 à 02:00\n- **Message**\xa0: Inclure les chiffres Q2.",
    "task_update_mixed_new_due_only_fr": "- **Tâche**\xa0: Préparer le rapport\n- **Échéance**\xa0: lundi 15 juin 2026 à 02:00 ✏️\n- **Message**\xa0: Inclure les chiffres Q2.",
    "task_delete_fr": "- **Tâche**\xa0: Ancienne tâche",
    "task_delete_empty_en": "- **Task**: ?",
    "file_delete_full_fr": "- **Fichier**\xa0: rapport.pdf\n- **Type**\xa0: application/pdf",
    "file_delete_empty_en": "- **File**: ?",
    "label_delete_children_only_fr": "- **Label parent**\xa0: pro/clients\n- **Sous-labels à supprimer**\xa0: 2",
    "label_delete_many_sublabels_fr": "- **Label**\xa0: pro/archive\n- **Sous-labels inclus**\xa0: 7\n- pro/archive/2019, pro/archive/2020, pro/archive/2021, pro/archive/2022, pro/archive/2023, ... (+2)",
    "label_delete_five_sublabels_fr": "- **Label**\xa0: pro/projets\n- **Sous-labels inclus**\xa0: 5\n- pro/projets/p1, pro/projets/p2, pro/projets/p3, pro/projets/p4, pro/projets/p5",
    "label_delete_few_sublabels_en": "- **Label**: personal\n- **Sub-labels included**: 2\n- personal/travel, ?",
    "label_delete_no_sublabels_fr": "- **Label**\xa0: perso",
    "phone_call_full_fr": "- **Correspondant**\xa0: Paul Martin\n- **Téléphone**\xa0: +33612345678\n- **Objectif**\xa0: Vérifier sa disponibilité mardi après-midi",
    "phone_call_minimal_en": "- **Callee**: John Smith",
    "devops_task_full_fr": "- **Serveur**\xa0: prod-rpi5\n- **Tâche**\xa0: Redémarre le conteneur lia-api-prod et vérifie les logs",
    "devops_task_with_context_fr": "- **Serveur**\xa0: prod-rpi5\n- **Tâche**\xa0: Vérifie les logs\n- **Consignes**\xa0: reste en lecture seule",
    "devops_task_minimal_en": "- **Server**: staging",
    "tool_call_full_fr": "- **Outil**\xa0: era: cancel subscription\n- **Détails**\xa0: plan: premium, immediate: true",
    "tool_call_hostile_values_fr": '- **Outil**\xa0: era: cancel subscription\n- **Détails**\xa0: flag: false, nothing: null, nested: {"k": "v"}, body: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx…',
    "tool_call_minimal_en": "- **Tool**: era: cancel subscription",
    "peer_message_full_fr": "- **Destinataire**\xa0: Marie Dupont\n\n**Message**\n\nDemande-lui comment il va",
    "peer_message_minimal_en": "- **Recipient**: Marie Dupont",
    "vacation_enable_full_fr": "- **Objet**\xa0: Absent jusqu'au 30/08\n- **Début**\xa0: 2026-08-24\n- **Fin**\xa0: 2026-08-30\n\n**Message**\n\nJe suis en congés, je répondrai à mon retour.",
    "vacation_enable_minimal_en": "**Message**\n\nAway until Sept 1.",
    "vacation_disable_fr": "- La réponse automatique sera désactivée",
    "spreadsheet_append_fr": "- **Fichier**\xa0: Budget 2026\n- **Feuille**\xa0: Dépenses\n- Loyer | 1200\n- EDF | 80",
    "spreadsheet_update_en": "- **File**: Budget 2026\n- **Sheet**: Dépenses\n- **Range**: B2:B3\n- 1300\n- 90",
    "document_append_fr": "- **Fichier**\xa0: Compte-rendu\n\n**Texte**\n\nDécision: reporter la réunion.",
    "email_filter_full_fr": "- **De**\xa0: news@x.com\n- **Objet**\xa0: promo\n- **Label**\xa0: Newsletters\n- Les messages seront archivés\n- Les messages seront marqués comme lus",
    "email_filter_query_en": "- **Query**: has:attachment larger:5M",
    "scheduled_action_full_fr": "- **Titre**\xa0: Revue de presse IA\n- **Planification**\xa0: Lun, Mer à 08:00\n- **Instruction**\xa0: Fais-moi une revue de presse IA",
    "scheduled_action_minimal_en": "- **Title**: Daily digest",
}


@pytest.mark.parametrize("case", CASES, ids=lambda case: case.case_id)
def test_detailed_preview_golden(case: PreviewCase) -> None:
    """The preview output is byte-identical to the pinned golden string."""
    draft = Draft(type=case.draft_type, content=case.content)
    assert case.case_id in EXPECTED, f"Missing golden for {case.case_id}"
    assert draft.get_detailed_preview(case.language, case.timezone) == EXPECTED[case.case_id]


def test_case_ids_are_unique() -> None:
    """Golden table keys must be unambiguous."""
    ids = [case.case_id for case in CASES]
    assert len(ids) == len(set(ids)), "Duplicate case_id in CASES"


def test_every_draft_type_is_covered() -> None:
    """The net covers every DraftType — adding a type without a case fails here."""
    covered = {case.draft_type for case in CASES}
    missing = set(DraftType) - covered
    assert (
        not missing
    ), f"DraftType(s) without characterization case: {sorted(t.value for t in missing)}"


def test_default_arguments_bind_fr_and_default_timezone() -> None:
    """Calling without args equals the explicit (fr, Europe/Paris) rendering."""
    draft = Draft(type=DraftType.EMAIL, content=_EMAIL_FULL_CONTENT)
    assert draft.get_detailed_preview() == draft.get_detailed_preview("fr", "Europe/Paris")


class TestOneVocabulary:
    """The rule the golden table encodes case by case, stated as a property.

    A table proves what it lists; a property covers the next renderer somebody
    writes. Both are wanted here — the old vocabulary leaked from 78 separate
    f-strings, and any one of them coming back would be invisible in a diff.
    """

    @staticmethod
    def _breaks_in_the_data(content: dict[str, Any]) -> int:
        """How many ``<br/>`` the CONTENT itself carries.

        A mail client writes them, and they travel in the body of a draft the
        person is confirming. What the renderer must never do is ADD one.
        """
        return json.dumps(content, ensure_ascii=False, default=str).count("<br/>")

    @pytest.mark.parametrize("case", CASES, ids=lambda case: case.case_id)
    def test_the_renderer_adds_no_html_break(self, case: PreviewCase) -> None:
        rendered = Draft(type=case.draft_type, content=case.content).get_detailed_preview(
            case.language, case.timezone
        )

        assert rendered.count("<br/>") <= self._breaks_in_the_data(case.content)

    @pytest.mark.parametrize("case", CASES, ids=lambda case: case.case_id)
    def test_nothing_opens_or_closes_on_blank_space(self, case: PreviewCase) -> None:
        # Every preview used to START with a break: the card opened on an empty
        # line, under a header that already stood on its own.
        rendered = Draft(type=case.draft_type, content=case.content).get_detailed_preview(
            case.language, case.timezone
        )

        assert rendered == rendered.strip()

    @pytest.mark.parametrize("case", CASES, ids=lambda case: case.case_id)
    def test_no_field_is_shown_with_nothing_in_it(self, case: PreviewCase) -> None:
        """« Début : » over nothing states less than saying nothing at all."""
        rendered = Draft(type=case.draft_type, content=case.content).get_detailed_preview(
            case.language, case.timezone
        )
        separator = get_draft_preview_labels(case.language)["separator"].rstrip()

        valueless = [
            line
            for line in rendered.splitlines()
            if line.rstrip() in {"-", "-" + separator} or line.rstrip().endswith(separator)
        ]
        assert not valueless, valueless


class _UnknownDraftType(str, Enum):
    """Stand-in for a future DraftType value with no preview branch."""

    SOMETHING = "something"


def test_unknown_draft_type_falls_back_to_summary() -> None:
    """Unknown types fall back to get_summary's generic 'Draft (<value>)' string."""
    draft = Draft(type=DraftType.EMAIL, content={})
    draft.type = _UnknownDraftType.SOMETHING  # type: ignore[assignment]
    assert draft.get_detailed_preview("fr", "Europe/Paris") == "Draft (something)"
