"""Golden characterization net for ``Draft.get_detailed_preview`` (extraction #2).

Pins the EXACT output string (byte-identical equality) of
``Draft.get_detailed_preview`` for a representative set of drafts covering
every ``DraftType`` value and every rendering branch, BEFORE the renderer is
extracted from ``drafts/models.py`` to a dedicated presentation module
(``drafts/preview_renderer.py``). Method: characterization-first decomposition
(Feathers), as applied by ADR-122 for the voice/TTS extraction — the net must
pass identically, unmodified, after the extraction.

The frontend confirmation cards render this string verbatim, so the contract
is byte-identical output — assertions are full-string equality against the
``EXPECTED`` golden table (generated by running the implementation, never
written by hand), never substring checks. The table is regenerated ONLY on a
deliberate, reviewed behavior change, with the old/new tables diffed to prove
the change is surgical (last: the 2026-07-11 fallback fixes — localized
``no_subject``, ``None`` body, reminder ``"?"``).

Branch coverage encoded in the case table:
- Email send/reply/forward shared branch: cc/bcc present and absent, forward
  attachments with ``filename`` key, ``name`` fallback, and ``"?"`` fallback.
- Email delete: ``from`` key vs ``from_addr`` fallback, date present/absent,
  and the localized ``no_subject`` fallback for a missing or empty subject
  (fixed 2026-07-11 — was a hardcoded French ``"(sans objet)"``).
- Reminder delete: full, partial, and fully-empty content (``"?"`` fallback
  line, consistent with the other delete types — fixed 2026-07-11).
- Event create/update/delete: timed vs all-day (``dateTime`` vs ``date``),
  modified-field ``✏️`` marks vs values preserved from ``current_event``,
  attendee ``email`` vs ``displayName`` fallback, empty content.
- Contact create/update/delete: modified marks vs ``current_contact``
  fallbacks, empty ``names`` list rendering ``"?"``.
- Task create/update/delete: due/notes present/absent, marks vs
  ``current_task`` fallbacks.
- File delete: ``mimeType`` present/absent, missing file dict.
- Label delete: ``children_only`` mode, 0 / few / more-than-5 sublabels
  (``... (+N)`` truncation), sublabel ``name`` fallback to ``"?"``.
- Forward body ``None``: renders empty, exactly like an empty-string body
  (fixed 2026-07-11 — was rendering the literal string ``"None"``).
- All 6 supported languages on the email branch, zh-CN datetime formatting,
  timezone conversion (Europe/Paris vs America/New_York), and the default
  argument binding (fr + DEFAULT_USER_DISPLAY_TIMEZONE).
- Unknown draft type: fallback to ``get_summary`` → ``"Draft (<value>)"``.
- MIXED cases (one field modified, the others preserved/absent) on every
  update type and on multi-optional create types: all-new/all-preserved pairs
  alone would let condition cross-wiring (e.g. the ✏️ mark of one field driven
  by another field's presence) pass undetected through the extraction.
"""

from __future__ import annotations

from enum import Enum
from typing import Any, NamedTuple

import pytest

from src.domains.agents.drafts.models import Draft, DraftType


class PreviewCase(NamedTuple):
    """One golden case: draft type + content + rendering args.

    Attributes:
        case_id: Unique key into the ``EXPECTED`` golden table.
        draft_type: The ``DraftType`` under test.
        content: The draft ``content`` dict, mirroring what the matching
            ``*DraftInput.model_dump()`` produces in the real flow.
        language: User language passed to ``get_detailed_preview``.
        timezone: IANA timezone passed to ``get_detailed_preview``.
    """

    case_id: str
    draft_type: DraftType
    content: dict[str, Any]
    language: str = "fr"
    timezone: str = "Europe/Paris"


_EMAIL_FULL_CONTENT: dict[str, Any] = {
    "to": "alice@example.com",
    "cc": "bob@example.com",
    "bcc": "carol@example.com",
    "subject": "Projet LIA — point d'étape",
    "body": "Bonjour Alice,<br/>voici le point d'étape.",
    "is_html": False,
}

CASES: tuple[PreviewCase, ...] = (
    # ------------------------------------------------------------- Email send
    PreviewCase("email_full_fr", DraftType.EMAIL, _EMAIL_FULL_CONTENT),
    PreviewCase(
        "email_minimal_en",
        DraftType.EMAIL,
        {"to": "dave@example.com", "subject": "Quick sync", "body": "See you at 10."},
        language="en",
    ),
    # Label sweep: same content, remaining languages (fr covered above).
    PreviewCase("email_labels_en", DraftType.EMAIL, _EMAIL_FULL_CONTENT, language="en"),
    PreviewCase("email_labels_es", DraftType.EMAIL, _EMAIL_FULL_CONTENT, language="es"),
    PreviewCase("email_labels_de", DraftType.EMAIL, _EMAIL_FULL_CONTENT, language="de"),
    PreviewCase("email_labels_it", DraftType.EMAIL, _EMAIL_FULL_CONTENT, language="it"),
    PreviewCase("email_labels_zh", DraftType.EMAIL, _EMAIL_FULL_CONTENT, language="zh-CN"),
    # ------------------------------------------------------------ Email reply
    PreviewCase(
        "email_reply_fr",
        DraftType.EMAIL_REPLY,
        {
            "message_id": "m123",
            "to": "erin@example.com",
            "subject": "Re: Devis",
            "body": "Merci, c'est validé.",
            "reply_all": False,
            "original_subject": "Devis",
            "original_from": "erin@example.com",
        },
    ),
    PreviewCase(
        "email_reply_with_cc_fr",
        DraftType.EMAIL_REPLY,
        {
            "message_id": "m124",
            "to": "erin@example.com",
            "cc": "frank@example.com",
            "subject": "Re: Devis",
            "body": "Merci, c'est validé.",
        },
    ),
    # ---------------------------------------------------------- Email forward
    PreviewCase(
        "email_forward_attachments_fr",
        DraftType.EMAIL_FORWARD,
        {
            "message_id": "m456",
            "to": "greg@example.com",
            "cc": "clara@example.com",
            "subject": "Fwd: Contrat",
            "body": "Pour info.",
            "attachments": [
                {
                    "filename": "contrat.pdf",
                    "mime_type": "application/pdf",
                    "size": 12345,
                },
                {"name": "annexe.docx"},
                {},
            ],
        },
    ),
    PreviewCase(
        "email_forward_no_attachments_en",
        DraftType.EMAIL_FORWARD,
        {
            "message_id": "m789",
            "to": "ivan@example.com",
            "subject": "Fwd: Report",
            "body": "FYI.",
            "attachments": [],
        },
        language="en",
    ),
    # EmailForwardDraftInput.body defaults to None and model_dump() keeps the
    # key: a None body must render empty, like an empty-string body.
    PreviewCase(
        "email_forward_none_body_fr",
        DraftType.EMAIL_FORWARD,
        {
            "message_id": "m790",
            "to": "judy@example.com",
            "subject": "Fwd: Photos",
            "body": None,
        },
    ),
    # Forward with bcc and no cc: EMAIL_FORWARD gets its own renderer after the
    # extraction — bcc handling and cc-absence must be pinned on this type too.
    PreviewCase(
        "email_forward_bcc_no_cc_fr",
        DraftType.EMAIL_FORWARD,
        {
            "message_id": "m791",
            "to": "greg@example.com",
            "bcc": "mallory@example.com",
            "subject": "Fwd: Contrat",
            "body": "Pour info.",
        },
    ),
    # ----------------------------------------------------------- Email delete
    PreviewCase(
        "email_delete_full_fr",
        DraftType.EMAIL_DELETE,
        {
            "message_id": "m1",
            "from": "jane@example.com",
            "subject": "Newsletter",
            "date": "2026-05-16T14:00:00+02:00",
        },
    ),
    PreviewCase(
        "email_delete_from_addr_fallback_en",
        DraftType.EMAIL_DELETE,
        {
            "message_id": "m2",
            "from_addr": "kyle@example.com",
            "subject": "(no subject)",
        },
        language="en",
    ),
    # Missing subject key falls back to the LOCALIZED no_subject label.
    PreviewCase(
        "email_delete_no_subject_en",
        DraftType.EMAIL_DELETE,
        {"message_id": "m3", "from": "liam@example.com"},
        language="en",
    ),
    # Empty-string subject (the value the tool now stores for a subject-less
    # email) takes the same localized fallback.
    PreviewCase(
        "email_delete_empty_subject_fr",
        DraftType.EMAIL_DELETE,
        {"message_id": "m5", "from": "nina@example.com", "subject": ""},
    ),
    # Neither "from" nor "from_addr" present: pins the "?" sender default.
    PreviewCase(
        "email_delete_no_sender_fr",
        DraftType.EMAIL_DELETE,
        {"message_id": "m4", "subject": "Spam"},
    ),
    # --------------------------------------------------------- Reminder delete
    PreviewCase(
        "reminder_delete_full_fr",
        DraftType.REMINDER_DELETE,
        {"content": "Appeler le médecin", "trigger_at": "2026-05-17T19:00:00+02:00"},
    ),
    # Independent-if branches: content without trigger date.
    PreviewCase(
        "reminder_delete_content_only_fr",
        DraftType.REMINDER_DELETE,
        {"content": "Arroser les plantes"},
    ),
    # Trigger date without content: the content line falls back to "?".
    PreviewCase(
        "reminder_delete_trigger_only_fr",
        DraftType.REMINDER_DELETE,
        {"trigger_at": "2026-05-18T08:00:00+02:00"},
    ),
    # Fully empty content renders the "?" line, consistent with the other
    # delete types (was an empty string before the 2026-07-11 fix).
    PreviewCase("reminder_delete_empty_fr", DraftType.REMINDER_DELETE, {}),
    # ------------------------------------------------------------ Event create
    PreviewCase(
        "event_full_fr",
        DraftType.EVENT,
        {
            "summary": "Réunion projet",
            "start_datetime": "2026-06-01T09:00:00+02:00",
            "end_datetime": "2026-06-01T10:30:00+02:00",
            "location": "Salle B",
            "description": "Ordre du jour : budget.",
            "attendees": ["alice@example.com", "bob@example.com"],
        },
    ),
    PreviewCase(
        "event_minimal_en",
        DraftType.EVENT,
        {"summary": "Standup"},
        language="en",
    ),
    # Mixed optional fields: location present, attendees/description absent —
    # kills condition cross-wiring that all-present/all-absent pairs let through.
    PreviewCase(
        "event_location_only_en",
        DraftType.EVENT,
        {
            "summary": "Demo",
            "start_datetime": "2026-06-08T15:00:00+02:00",
            "end_datetime": "2026-06-08T16:00:00+02:00",
            "location": "Room A",
        },
        language="en",
    ),
    PreviewCase(
        "event_full_zh",
        DraftType.EVENT,
        {
            "summary": "项目会议",
            "start_datetime": "2026-06-01T09:00:00+02:00",
            "end_datetime": "2026-06-01T10:30:00+02:00",
            "location": "B会议室",
        },
        language="zh-CN",
    ),
    # ------------------------------------------------------------ Event update
    PreviewCase(
        "event_update_new_times_fr",
        DraftType.EVENT_UPDATE,
        {
            "event_id": "e1",
            "summary": "Réunion déplacée",
            "start_datetime": "2026-06-02T14:00:00+02:00",
            "end_datetime": "2026-06-02T15:00:00+02:00",
            "location": "Salle C",
            "current_event": {
                "summary": "Réunion projet",
                "start": {"dateTime": "2026-06-01T09:00:00+02:00"},
                "end": {"dateTime": "2026-06-01T10:30:00+02:00"},
                "location": "Salle B",
                "attendees": [{"email": "alice@example.com"}],
            },
        },
    ),
    PreviewCase(
        "event_update_preserved_fr",
        DraftType.EVENT_UPDATE,
        {
            "event_id": "e2",
            "current_event": {
                "summary": "Réunion projet",
                "start": {"dateTime": "2026-06-01T09:00:00+02:00"},
                "end": {"dateTime": "2026-06-01T10:30:00+02:00"},
                "location": "Salle B",
                "attendees": [{"email": "alice@example.com"}, {"displayName": "Bob"}],
            },
        },
    ),
    PreviewCase(
        "event_update_allday_fr",
        DraftType.EVENT_UPDATE,
        {
            "event_id": "e3",
            "current_event": {
                "summary": "Anniversaire",
                "start": {"date": "2026-06-03"},
                "end": {"date": "2026-06-04"},
            },
        },
    ),
    PreviewCase(
        "event_update_new_attendees_fr",
        DraftType.EVENT_UPDATE,
        {
            "event_id": "e4",
            "attendees": ["carol@example.com"],
            "current_event": {"summary": "Point équipe"},
        },
    ),
    # Mixed modified/preserved: ONLY the start is new — the ✏️ mark must sit on
    # start alone while end/location/attendees come from current_event unmarked.
    PreviewCase(
        "event_update_mixed_new_start_only_fr",
        DraftType.EVENT_UPDATE,
        {
            "event_id": "e6",
            "start_datetime": "2026-06-01T09:30:00+02:00",
            "current_event": {
                "summary": "Réunion projet",
                "start": {"dateTime": "2026-06-01T09:00:00+02:00"},
                "end": {"dateTime": "2026-06-01T10:30:00+02:00"},
                "location": "Salle B",
                "attendees": [{"email": "alice@example.com"}],
            },
        },
    ),
    PreviewCase("event_update_empty_fr", DraftType.EVENT_UPDATE, {"event_id": "e5"}),
    # ------------------------------------------------------------ Event delete
    PreviewCase(
        "event_delete_full_fr",
        DraftType.EVENT_DELETE,
        {
            "event_id": "e9",
            "event": {
                "summary": "Dentiste",
                "start": {"dateTime": "2026-06-05T11:00:00+02:00"},
            },
        },
    ),
    PreviewCase(
        "event_delete_allday_en",
        DraftType.EVENT_DELETE,
        {
            "event_id": "e10",
            "event": {"summary": "Holiday", "start": {"date": "2026-06-06"}},
        },
        language="en",
    ),
    PreviewCase("event_delete_empty_fr", DraftType.EVENT_DELETE, {"event_id": "e11"}),
    # ---------------------------------------------------------- Contact create
    PreviewCase(
        "contact_full_fr",
        DraftType.CONTACT,
        {
            "name": "Marie Dupont",
            "email": "marie@example.com",
            "phone": "+33612345678",
            "organization": "ACME",
            "notes": "Rencontrée au salon.",
        },
    ),
    PreviewCase("contact_minimal_en", DraftType.CONTACT, {"name": "John Smith"}, language="en"),
    # Mixed optional fields: email only, phone/organization absent.
    PreviewCase(
        "contact_email_only_fr",
        DraftType.CONTACT,
        {"name": "Luc Bernard", "email": "luc@example.com"},
    ),
    # ---------------------------------------------------------- Contact update
    PreviewCase(
        "contact_update_new_fields_fr",
        DraftType.CONTACT_UPDATE,
        {
            "resource_name": "people/c1",
            "name": "Marie Durand",
            "email": "marie.d@example.com",
            "phone": "+33699999999",
            "organization": "NewCorp",
            "current_contact": {
                "names": [{"displayName": "Marie Dupont"}],
                "emailAddresses": [{"value": "marie@example.com"}],
                "phoneNumbers": [{"value": "+33612345678"}],
                "organizations": [{"name": "ACME"}],
            },
        },
    ),
    PreviewCase(
        "contact_update_preserved_fr",
        DraftType.CONTACT_UPDATE,
        {
            "resource_name": "people/c2",
            "current_contact": {
                "names": [{"displayName": "Marie Dupont"}],
                "emailAddresses": [{"value": "marie@example.com"}],
                "phoneNumbers": [{"value": "+33612345678"}],
                "organizations": [{"name": "ACME"}],
            },
        },
    ),
    # Mixed modified/preserved: ONLY the email is new — ✏️ on email alone,
    # name/phone/organization preserved from current_contact unmarked.
    PreviewCase(
        "contact_update_mixed_new_email_only_fr",
        DraftType.CONTACT_UPDATE,
        {
            "resource_name": "people/c6",
            "email": "marie.durand@example.com",
            "current_contact": {
                "names": [{"displayName": "Marie Dupont"}],
                "emailAddresses": [{"value": "marie@example.com"}],
                "phoneNumbers": [{"value": "+33612345678"}],
                "organizations": [{"name": "ACME"}],
            },
        },
    ),
    PreviewCase(
        "contact_update_no_names_en",
        DraftType.CONTACT_UPDATE,
        {"resource_name": "people/c3", "current_contact": {}},
        language="en",
    ),
    # names present but first entry has no displayName → "?" default.
    PreviewCase(
        "contact_update_names_no_displayname_en",
        DraftType.CONTACT_UPDATE,
        {"resource_name": "people/c7", "current_contact": {"names": [{}]}},
        language="en",
    ),
    # ---------------------------------------------------------- Contact delete
    PreviewCase(
        "contact_delete_full_fr",
        DraftType.CONTACT_DELETE,
        {
            "resource_name": "people/c4",
            "contact": {
                "names": [{"displayName": "Paul Martin"}],
                "emailAddresses": [{"value": "paul@example.com"}],
            },
        },
    ),
    PreviewCase(
        "contact_delete_empty_en",
        DraftType.CONTACT_DELETE,
        {"resource_name": "people/c5"},
        language="en",
    ),
    # ------------------------------------------------------------- Task create
    PreviewCase(
        "task_full_fr",
        DraftType.TASK,
        {
            "title": "Préparer le rapport",
            "notes": "Inclure les chiffres Q2.",
            "due": "2026-06-10T00:00:00Z",
            "task_list_id": "@default",
        },
    ),
    PreviewCase("task_minimal_en", DraftType.TASK, {"title": "Buy milk"}, language="en"),
    # Timezone conversion: the same UTC-midnight due date renders as the
    # previous day in America/New_York.
    PreviewCase(
        "task_full_new_york_en",
        DraftType.TASK,
        {"title": "Prepare report", "due": "2026-06-10T00:00:00Z"},
        language="en",
        timezone="America/New_York",
    ),
    # Mixed optional fields: due only, notes absent.
    PreviewCase(
        "task_due_only_en",
        DraftType.TASK,
        {"title": "Renew passport", "due": "2026-07-01T00:00:00Z"},
        language="en",
    ),
    # ------------------------------------------------------------- Task update
    PreviewCase(
        "task_update_new_fr",
        DraftType.TASK_UPDATE,
        {
            "task_id": "t1",
            "title": "Rapport final",
            "due": "2026-06-12T00:00:00Z",
            "notes": "Version corrigée.",
            "current_task": {
                "title": "Préparer le rapport",
                "due": "2026-06-10T00:00:00Z",
                "notes": "Inclure les chiffres Q2.",
            },
        },
    ),
    PreviewCase(
        "task_update_preserved_fr",
        DraftType.TASK_UPDATE,
        {
            "task_id": "t2",
            "current_task": {
                "title": "Préparer le rapport",
                "due": "2026-06-10T00:00:00Z",
                "notes": "Inclure les chiffres Q2.",
            },
        },
    ),
    # Mixed modified/preserved: ONLY the due date is new — ✏️ on due alone,
    # title/notes preserved from current_task unmarked.
    PreviewCase(
        "task_update_mixed_new_due_only_fr",
        DraftType.TASK_UPDATE,
        {
            "task_id": "t5",
            "due": "2026-06-15T00:00:00Z",
            "current_task": {
                "title": "Préparer le rapport",
                "due": "2026-06-10T00:00:00Z",
                "notes": "Inclure les chiffres Q2.",
            },
        },
    ),
    # ------------------------------------------------------------- Task delete
    PreviewCase(
        "task_delete_fr",
        DraftType.TASK_DELETE,
        {"task_id": "t3", "title": "Ancienne tâche"},
    ),
    PreviewCase("task_delete_empty_en", DraftType.TASK_DELETE, {"task_id": "t4"}, language="en"),
    # ------------------------------------------------------------- File delete
    PreviewCase(
        "file_delete_full_fr",
        DraftType.FILE_DELETE,
        {
            "file_id": "f1",
            "file": {"name": "rapport.pdf", "mimeType": "application/pdf"},
        },
    ),
    PreviewCase("file_delete_empty_en", DraftType.FILE_DELETE, {"file_id": "f2"}, language="en"),
    # ------------------------------------------------------------ Label delete
    PreviewCase(
        "label_delete_children_only_fr",
        DraftType.LABEL_DELETE,
        {
            "label_id": "l1",
            "label_name": "pro/clients",
            "children_only": True,
            "sublabels": [{"name": "pro/clients/acme"}, {"name": "pro/clients/globex"}],
        },
    ),
    PreviewCase(
        "label_delete_many_sublabels_fr",
        DraftType.LABEL_DELETE,
        {
            "label_id": "l2",
            "label_name": "pro/archive",
            "sublabels": [{"name": f"pro/archive/{year}"} for year in range(2019, 2026)],
        },
    ),
    # Truncation boundary: exactly 5 sublabels → all listed, no "... (+N)".
    PreviewCase(
        "label_delete_five_sublabels_fr",
        DraftType.LABEL_DELETE,
        {
            "label_id": "l5",
            "label_name": "pro/projets",
            "sublabels": [{"name": f"pro/projets/p{index}"} for index in range(1, 6)],
        },
    ),
    PreviewCase(
        "label_delete_few_sublabels_en",
        DraftType.LABEL_DELETE,
        {
            "label_id": "l3",
            "label_name": "personal",
            "sublabels": [{"name": "personal/travel"}, {}],
        },
        language="en",
    ),
    PreviewCase(
        "label_delete_no_sublabels_fr",
        DraftType.LABEL_DELETE,
        {"label_id": "l4", "label_name": "perso"},
    ),
    # -------------------------------------------------------------- Phone call
    PreviewCase(
        "phone_call_full_fr",
        DraftType.PHONE_CALL,
        {
            "callee_name": "Paul Martin",
            "callee_phone": "+33612345678",
            "objective": "Vérifier sa disponibilité mardi après-midi",
        },
    ),
    # Minimal: callee only — phone and objective rows are omitted.
    PreviewCase(
        "phone_call_minimal_en",
        DraftType.PHONE_CALL,
        {"callee_name": "John Smith"},
        language="en",
    ),
    # ------------------------------------------------------------------ DevOps
    # FN-1: the task text is what the user approves, so it is never truncated.
    PreviewCase(
        "devops_task_full_fr",
        DraftType.DEVOPS_TASK,
        {
            "server": "prod-rpi5",
            "task": "Redémarre le conteneur lia-api-prod et vérifie les logs",
        },
    ),
    # With model-authored context: it reaches the CLI system prompt, so it is
    # part of what the user approves and must appear byte-for-byte.
    PreviewCase(
        "devops_task_with_context_fr",
        DraftType.DEVOPS_TASK,
        {
            "server": "prod-rpi5",
            "task": "Vérifie les logs",
            "context": "reste en lecture seule",
        },
    ),
    # Minimal: server only — the task row is omitted like every optional field.
    PreviewCase(
        "devops_task_minimal_en",
        DraftType.DEVOPS_TASK,
        {"server": "staging"},
        language="en",
    ),
    # ADR-263: a tool whose policy demands a confirmation and that builds no
    # draft of its own. The card must say WHAT will run and WITH WHAT, because
    # that is exactly what the user is being asked to allow.
    PreviewCase(
        "tool_call_full_fr",
        DraftType.TOOL_CALL,
        {
            "tool_name": "mcp_era_cancel_subscription",
            "tool_label": "era: cancel subscription",
            "tool_args": {"plan": "premium", "immediate": True},
        },
    ),
    # A card is read by a human in six languages: no Python spelling (``True``,
    # ``None``, ``{'k': 'v'}``) and no unbounded value — one argument can carry
    # an entire email body.
    PreviewCase(
        "tool_call_hostile_values_fr",
        DraftType.TOOL_CALL,
        {
            "tool_label": "era: cancel subscription",
            "tool_args": {
                "flag": False,
                "nothing": None,
                "nested": {"k": "v"},
                "body": "x" * 200,
            },
        },
    ),
    # Minimal: no arguments — the details row is omitted like every optional field.
    PreviewCase(
        "tool_call_minimal_en",
        DraftType.TOOL_CALL,
        {"tool_label": "era: cancel subscription"},
        language="en",
    ),
    # Peers (A3): the relayed message is what the sender approves — full text.
    PreviewCase(
        "peer_message_full_fr",
        DraftType.PEER_MESSAGE,
        {
            "recipient_name": "Marie Dupont",
            "message": "Demande-lui comment il va",
        },
    ),
    PreviewCase(
        "peer_message_minimal_en",
        DraftType.PEER_MESSAGE,
        {"recipient_name": "Marie Dupont"},
        language="en",
    ),
    # Gmail vacation responder (lot I): enable shows the verbatim auto-reply
    # (subject, body, date bounds as plain YYYY-MM-DD); disable is a single
    # localized sentence.
    PreviewCase(
        "vacation_enable_full_fr",
        DraftType.VACATION_RESPONDER,
        {
            "enable": True,
            "subject": "Absent jusqu'au 30/08",
            "body": "Je suis en congés, je répondrai à mon retour.",
            "start_date": "2026-08-24",
            "end_date": "2026-08-30",
        },
    ),
    PreviewCase(
        "vacation_enable_minimal_en",
        DraftType.VACATION_RESPONDER,
        {"enable": True, "body": "Away until Sept 1."},
        language="en",
    ),
    PreviewCase(
        "vacation_disable_fr",
        DraftType.VACATION_RESPONDER,
        {"enable": False},
    ),
    # Workspace writes (lot F phase write): the preview IS the write contract.
    PreviewCase(
        "spreadsheet_append_fr",
        DraftType.SPREADSHEET_WRITE,
        {
            "spreadsheet_title": "Budget 2026",
            "sheet_name": "Dépenses",
            "mode": "append",
            "values": [["Loyer", "1200"], ["EDF", "80"]],
        },
    ),
    PreviewCase(
        "spreadsheet_update_en",
        DraftType.SPREADSHEET_WRITE,
        {
            "spreadsheet_title": "Budget 2026",
            "sheet_name": "Dépenses",
            "mode": "update",
            "a1_range": "B2:B3",
            "values": [["1300"], ["90"]],
        },
        language="en",
    ),
    PreviewCase(
        "document_append_fr",
        DraftType.DOCUMENT_APPEND,
        {"document_title": "Compte-rendu", "text": "Décision: reporter la réunion."},
    ),
    # Gmail filter creation (lot I): criteria + only the requested actions.
    PreviewCase(
        "email_filter_full_fr",
        DraftType.EMAIL_FILTER,
        {
            "criteria": {"from": "news@x.com", "subject": "promo"},
            "label_name": "Newsletters",
            "archive": True,
            "mark_as_read": True,
        },
    ),
    PreviewCase(
        "email_filter_query_en",
        DraftType.EMAIL_FILTER,
        {"criteria": {"query": "has:attachment larger:5M"}, "archive": False},
        language="en",
    ),
    # Automation draft (ADR-140): title + pre-localized schedule + instruction.
    PreviewCase(
        "scheduled_action_full_fr",
        DraftType.SCHEDULED_ACTION,
        {
            "title": "Revue de presse IA",
            "schedule_human": "Lun, Mer à 08:00",
            "action_prompt": "Fais-moi une revue de presse IA",
        },
    ),
    # Minimal: title only — schedule and instruction rows are omitted.
    PreviewCase(
        "scheduled_action_minimal_en",
        DraftType.SCHEDULED_ACTION,
        {"title": "Daily digest"},
        language="en",
    ),
)


# Golden outputs generated by running the implementation over CASES.
# Regenerate ONLY on a deliberate, reviewed behavior change, and diff the
# old/new tables to prove the change touches exactly the intended cases
# (last regeneration: 2026-07-11 fallback fixes, 3 changed + 2 added).
EXPECTED: dict[str, str] = {
    "email_full_fr": "<br/>**Destinataire**: alice@example.com<br/><br/>**Cc**: bob@example.com<br/><br/>**Cci**: carol@example.com<br/><br/>**Objet**: Projet LIA — point d'étape<br/><br/>**Message**:<br/>Bonjour Alice,<br/>voici le point d'étape.",
    "email_minimal_en": "<br/>**To**: dave@example.com<br/><br/>**Subject**: Quick sync<br/><br/>**Message**:<br/>See you at 10.",
    "email_labels_en": "<br/>**To**: alice@example.com<br/><br/>**Cc**: bob@example.com<br/><br/>**Bcc**: carol@example.com<br/><br/>**Subject**: Projet LIA — point d'étape<br/><br/>**Message**:<br/>Bonjour Alice,<br/>voici le point d'étape.",
    "email_labels_es": "<br/>**Destinatario**: alice@example.com<br/><br/>**Cc**: bob@example.com<br/><br/>**Cco**: carol@example.com<br/><br/>**Asunto**: Projet LIA — point d'étape<br/><br/>**Mensaje**:<br/>Bonjour Alice,<br/>voici le point d'étape.",
    "email_labels_de": "<br/>**An**: alice@example.com<br/><br/>**Cc**: bob@example.com<br/><br/>**Bcc**: carol@example.com<br/><br/>**Betreff**: Projet LIA — point d'étape<br/><br/>**Nachricht**:<br/>Bonjour Alice,<br/>voici le point d'étape.",
    "email_labels_it": "<br/>**Destinatario**: alice@example.com<br/><br/>**Cc**: bob@example.com<br/><br/>**Ccn**: carol@example.com<br/><br/>**Oggetto**: Projet LIA — point d'étape<br/><br/>**Messaggio**:<br/>Bonjour Alice,<br/>voici le point d'étape.",
    "email_labels_zh": "<br/>**收件人**: alice@example.com<br/><br/>**抄送**: bob@example.com<br/><br/>**密送**: carol@example.com<br/><br/>**主题**: Projet LIA — point d'étape<br/><br/>**内容**:<br/>Bonjour Alice,<br/>voici le point d'étape.",
    "email_reply_fr": "<br/>**Destinataire**: erin@example.com<br/><br/>**Objet**: Re: Devis<br/><br/>**Message**:<br/>Merci, c'est validé.",
    "email_reply_with_cc_fr": "<br/>**Destinataire**: erin@example.com<br/><br/>**Cc**: frank@example.com<br/><br/>**Objet**: Re: Devis<br/><br/>**Message**:<br/>Merci, c'est validé.",
    "email_forward_attachments_fr": "<br/>**Destinataire**: greg@example.com<br/><br/>**Cc**: clara@example.com<br/><br/>**Objet**: Fwd: Contrat<br/><br/>**Message**:<br/>Pour info.<br/><br/>**Pièces jointes**: contrat.pdf, annexe.docx, ?",
    "email_forward_no_attachments_en": "<br/>**To**: ivan@example.com<br/><br/>**Subject**: Fwd: Report<br/><br/>**Message**:<br/>FYI.",
    "email_forward_none_body_fr": "<br/>**Destinataire**: judy@example.com<br/><br/>**Objet**: Fwd: Photos<br/><br/>**Message**:<br/>",
    "email_forward_bcc_no_cc_fr": "<br/>**Destinataire**: greg@example.com<br/><br/>**Cci**: mallory@example.com<br/><br/>**Objet**: Fwd: Contrat<br/><br/>**Message**:<br/>Pour info.",
    "email_delete_full_fr": "<br/>**De**: jane@example.com<br/><br/>**Objet**: Newsletter<br/><br/>**Date**: samedi 16 mai 2026 à 14:00",
    "email_delete_from_addr_fallback_en": "<br/>**From**: kyle@example.com<br/><br/>**Subject**: (no subject)",
    "email_delete_no_subject_en": "<br/>**From**: liam@example.com<br/><br/>**Subject**: (no subject)",
    "email_delete_empty_subject_fr": "<br/>**De**: nina@example.com<br/><br/>**Objet**: (sans objet)",
    "email_delete_no_sender_fr": "<br/>**De**: ?<br/><br/>**Objet**: Spam",
    "reminder_delete_full_fr": "<br/>**Événement**: Appeler le médecin<br/><br/>**Date**: dimanche 17 mai 2026 à 19:00",
    "reminder_delete_content_only_fr": "<br/>**Événement**: Arroser les plantes",
    "reminder_delete_trigger_only_fr": "<br/>**Événement**: ?<br/><br/>**Date**: lundi 18 mai 2026 à 08:00",
    "reminder_delete_empty_fr": "<br/>**Événement**: ?",
    "event_full_fr": "<br/>**Événement**: Réunion projet<br/><br/>**Début**: lundi 01 juin 2026 à 09:00<br/><br/>**Fin**: lundi 01 juin 2026 à 10:30<br/><br/>**Lieu**: Salle B<br/><br/>**Participants**: alice@example.com, bob@example.com<br/><br/>**Message**<br/>Ordre du jour : budget.",
    "event_minimal_en": "<br/>**Event**: Standup<br/><br/>**Start**: <br/><br/>**End**: ",
    "event_location_only_en": "<br/>**Event**: Demo<br/><br/>**Start**: Monday 08 June 2026 at 15:00<br/><br/>**End**: Monday 08 June 2026 at 16:00<br/><br/>**Location**: Room A",
    "event_full_zh": "<br/>**事件**: 项目会议<br/><br/>**开始**: 2026年6月1日 星期一 09:00<br/><br/>**结束**: 2026年6月1日 星期一 10:30<br/><br/>**地点**: B会议室",
    "event_update_new_times_fr": "<br/>**Événement**: Réunion déplacée<br/><br/>**Début**: mardi 02 juin 2026 à 14:00 ✏️<br/><br/>**Fin**: mardi 02 juin 2026 à 15:00 ✏️<br/><br/>**Lieu**: Salle C ✏️<br/><br/>**Participants**: alice@example.com",
    "event_update_preserved_fr": "<br/>**Événement**: Réunion projet<br/><br/>**Début**: lundi 01 juin 2026 à 09:00<br/><br/>**Fin**: lundi 01 juin 2026 à 10:30<br/><br/>**Lieu**: Salle B<br/><br/>**Participants**: alice@example.com, Bob",
    "event_update_allday_fr": "<br/>**Événement**: Anniversaire<br/><br/>**Début**: mercredi 03 juin 2026 à 02:00<br/><br/>**Fin**: jeudi 04 juin 2026 à 02:00",
    "event_update_new_attendees_fr": "<br/>**Événement**: Point équipe<br/><br/>**Participants**: carol@example.com ✏️",
    "event_update_mixed_new_start_only_fr": "<br/>**Événement**: Réunion projet<br/><br/>**Début**: lundi 01 juin 2026 à 09:30 ✏️<br/><br/>**Fin**: lundi 01 juin 2026 à 10:30<br/><br/>**Lieu**: Salle B<br/><br/>**Participants**: alice@example.com",
    "event_update_empty_fr": "<br/>**Événement**: ?",
    "event_delete_full_fr": "<br/>**Événement**: Dentiste<br/><br/>**Date**: vendredi 05 juin 2026 à 11:00",
    "event_delete_allday_en": "<br/>**Event**: Holiday<br/><br/>**Date**: Saturday 06 June 2026 at 02:00",
    "event_delete_empty_fr": "<br/>**Événement**: ?",
    "contact_full_fr": "<br/>**Contact**: Marie Dupont<br/><br/>**Email**: marie@example.com<br/><br/>**Téléphone**: +33612345678<br/><br/>**Organisation**: ACME",
    "contact_minimal_en": "<br/>**Contact**: John Smith",
    "contact_email_only_fr": "<br/>**Contact**: Luc Bernard<br/><br/>**Email**: luc@example.com",
    "contact_update_new_fields_fr": "<br/>**Contact**: Marie Durand ✏️<br/><br/>**Email**: marie.d@example.com ✏️<br/><br/>**Téléphone**: +33699999999 ✏️<br/><br/>**Organisation**: NewCorp ✏️",
    "contact_update_preserved_fr": "<br/>**Contact**: Marie Dupont<br/><br/>**Email**: marie@example.com<br/><br/>**Téléphone**: +33612345678<br/><br/>**Organisation**: ACME",
    "contact_update_mixed_new_email_only_fr": "<br/>**Contact**: Marie Dupont<br/><br/>**Email**: marie.durand@example.com ✏️<br/><br/>**Téléphone**: +33612345678<br/><br/>**Organisation**: ACME",
    "contact_update_no_names_en": "<br/>**Contact**: ?",
    "contact_update_names_no_displayname_en": "<br/>**Contact**: ?",
    "contact_delete_full_fr": "<br/>**Contact**: Paul Martin<br/><br/>**Email**: paul@example.com",
    "contact_delete_empty_en": "<br/>**Contact**: ?",
    "task_full_fr": "<br/>**Tâche**: Préparer le rapport<br/><br/>**Échéance**: mercredi 10 juin 2026 à 02:00<br/><br/>**Message**:<br/>Inclure les chiffres Q2.",
    "task_minimal_en": "<br/>**Task**: Buy milk",
    "task_full_new_york_en": "<br/>**Task**: Prepare report<br/><br/>**Due**: Tuesday 09 June 2026 at 20:00",
    "task_due_only_en": "<br/>**Task**: Renew passport<br/><br/>**Due**: Wednesday 01 July 2026 at 02:00",
    "task_update_new_fr": "<br/>**Tâche**: Rapport final ✏️<br/><br/>**Échéance**: vendredi 12 juin 2026 à 02:00 ✏️<br/><br/>**Message**: Version corrigée. ✏️",
    "task_update_preserved_fr": "<br/>**Tâche**: Préparer le rapport<br/><br/>**Échéance**: mercredi 10 juin 2026 à 02:00<br/><br/>**Message**: Inclure les chiffres Q2.",
    "task_update_mixed_new_due_only_fr": "<br/>**Tâche**: Préparer le rapport<br/><br/>**Échéance**: lundi 15 juin 2026 à 02:00 ✏️<br/><br/>**Message**: Inclure les chiffres Q2.",
    "task_delete_fr": "<br/>**Tâche**: Ancienne tâche",
    "task_delete_empty_en": "<br/>**Task**: ?",
    "file_delete_full_fr": "<br/>**Fichier**: rapport.pdf<br/><br/>**Type**: application/pdf",
    "file_delete_empty_en": "<br/>**File**: ?",
    "label_delete_children_only_fr": "<br/>**Label parent**: pro/clients<br/><br/>**Sous-labels à supprimer**: 2",
    "label_delete_many_sublabels_fr": "<br/>**Label**: pro/archive<br/><br/>**Sous-labels inclus**: 7<br/><br/>  pro/archive/2019, pro/archive/2020, pro/archive/2021, pro/archive/2022, pro/archive/2023, ... (+2)",
    "label_delete_five_sublabels_fr": "<br/>**Label**: pro/projets<br/><br/>**Sous-labels inclus**: 5<br/><br/>  pro/projets/p1, pro/projets/p2, pro/projets/p3, pro/projets/p4, pro/projets/p5",
    "label_delete_few_sublabels_en": "<br/>**Label**: personal<br/><br/>**Sub-labels included**: 2<br/><br/>  personal/travel, ?",
    "label_delete_no_sublabels_fr": "<br/>**Label**: perso",
    "phone_call_full_fr": "<br/>**Correspondant**: Paul Martin<br/><br/>**Téléphone**: +33612345678<br/><br/>**Objectif**: Vérifier sa disponibilité mardi après-midi",
    "scheduled_action_full_fr": "<br/>**Titre**: Revue de presse IA<br/><br/>**Planification**: Lun, Mer à 08:00<br/><br/>**Instruction**: Fais-moi une revue de presse IA",
    "phone_call_minimal_en": "<br/>**Callee**: John Smith",
    "scheduled_action_minimal_en": "<br/>**Title**: Daily digest",
    "peer_message_full_fr": "<br/>**Destinataire**: Marie Dupont<br/><br/>**Message**: Demande-lui comment il va",
    "peer_message_minimal_en": "<br/>**Recipient**: Marie Dupont",
    "tool_call_full_fr": "<br/>**Outil**: era: cancel subscription<br/><br/>**Détails**: plan: premium, immediate: true",
    "tool_call_hostile_values_fr": '<br/>**Outil**: era: cancel subscription<br/><br/>**Détails**: flag: false, nothing: null, nested: {"k": "v"}, body: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx…',
    "tool_call_minimal_en": "<br/>**Tool**: era: cancel subscription",
    "devops_task_full_fr": "<br/>**Serveur**: prod-rpi5<br/><br/>**Tâche**: Redémarre le conteneur lia-api-prod et vérifie les logs",
    "devops_task_minimal_en": "<br/>**Server**: staging",
    "devops_task_with_context_fr": "<br/>**Serveur**: prod-rpi5<br/><br/>**Tâche**: Vérifie les logs<br/><br/>**Consignes**: reste en lecture seule",
    "vacation_enable_full_fr": "<br/>**Objet**: Absent jusqu'au 30/08<br/><br/>**Message**: Je suis en congés, je répondrai à mon retour.<br/><br/>**Début**: 2026-08-24<br/><br/>**Fin**: 2026-08-30",
    "vacation_enable_minimal_en": "<br/>**Message**: Away until Sept 1.",
    "vacation_disable_fr": "<br/>La réponse automatique sera désactivée",
    "spreadsheet_append_fr": "<br/>**Fichier**: Budget 2026<br/><br/>**Feuille**: Dépenses<br/><br/>Loyer | 1200<br/><br/>EDF | 80",
    "spreadsheet_update_en": "<br/>**File**: Budget 2026<br/><br/>**Sheet**: Dépenses<br/><br/>**Range**: B2:B3<br/><br/>1300<br/><br/>90",
    "document_append_fr": "<br/>**Fichier**: Compte-rendu<br/><br/>**Texte**: Décision: reporter la réunion.",
    "email_filter_full_fr": "<br/>**De**: news@x.com<br/><br/>**Objet**: promo<br/><br/>**Label**: Newsletters<br/><br/>Les messages seront archivés<br/><br/>Les messages seront marqués comme lus",
    "email_filter_query_en": "<br/>**Query**: has:attachment larger:5M",
}


@pytest.mark.parametrize("case", CASES, ids=lambda case: case.case_id)
def test_detailed_preview_golden(case: PreviewCase) -> None:
    """The preview output is byte-identical to the pinned golden string."""
    draft = Draft(type=case.draft_type, content=case.content)
    assert case.case_id in EXPECTED, f"Missing golden for {case.case_id}"
    assert draft.get_detailed_preview(case.language, case.timezone) == EXPECTED[case.case_id]


def test_case_ids_are_unique() -> None:
    """Golden table keys must be unambiguous."""
    ids = [case.case_id for case in CASES]
    assert len(ids) == len(set(ids)), "Duplicate case_id in CASES"


def test_every_draft_type_is_covered() -> None:
    """The net covers every DraftType — adding a type without a case fails here."""
    covered = {case.draft_type for case in CASES}
    missing = set(DraftType) - covered
    assert (
        not missing
    ), f"DraftType(s) without characterization case: {sorted(t.value for t in missing)}"


def test_default_arguments_bind_fr_and_default_timezone() -> None:
    """Calling without args equals the explicit (fr, Europe/Paris) rendering."""
    draft = Draft(type=DraftType.EMAIL, content=_EMAIL_FULL_CONTENT)
    assert draft.get_detailed_preview() == draft.get_detailed_preview("fr", "Europe/Paris")


class _UnknownDraftType(str, Enum):
    """Stand-in for a future DraftType value with no preview branch."""

    SOMETHING = "something"


def test_unknown_draft_type_falls_back_to_summary() -> None:
    """Unknown types fall back to get_summary's generic 'Draft (<value>)' string."""
    draft = Draft(type=DraftType.EMAIL, content={})
    draft.type = _UnknownDraftType.SOMETHING  # type: ignore[assignment]
    assert draft.get_detailed_preview("fr", "Europe/Paris") == "Draft (something)"
