"""Render a scannable QR code as a base64-encoded PNG image.

Reads ``content`` (the string to encode) from stdin parameters. The content
may be a plain URL, a plain text, a WiFi payload
(``WIFI:T:WPA;S:ssid;P:password;;``) or a vCard. The script does not
interpret the payload — it encodes whatever string is provided.

Emits a ``SkillScriptOutput`` JSON on stdout with:
- ``text``: one-line human-readable caption.
- ``image.url``: ``data:image/png;base64,...`` data URI.
- ``image.alt``: accessibility description.

The QR code is generated by ``segno`` (pure Python, no compiled deps, tiny).
Error correction level is set to 'M' (~15% recovery) — the default that
balances size and robustness for general-purpose QR codes.
"""

from __future__ import annotations

import base64
import io
import json
import sys


_LABELS: dict[str, dict[str, str]] = {
    "fr": {"wifi": "Réseau WiFi '{ssid}'", "wifi_generic": "Réseau WiFi",
           "vcard": "Contact (vCard)", "link": "Lien : {d}", "text": "Texte : {d}",
           "caption": "QR code généré : {s}.", "alt": "QR code encodant {s}"},
    "en": {"wifi": "WiFi network '{ssid}'", "wifi_generic": "WiFi network",
           "vcard": "Contact (vCard)", "link": "Link: {d}", "text": "Text: {d}",
           "caption": "QR code generated: {s}.", "alt": "QR code encoding {s}"},
    "es": {"wifi": "Red WiFi '{ssid}'", "wifi_generic": "Red WiFi",
           "vcard": "Contacto (vCard)", "link": "Enlace: {d}", "text": "Texto: {d}",
           "caption": "Código QR generado: {s}.", "alt": "Código QR que codifica {s}"},
    "de": {"wifi": "WLAN-Netzwerk '{ssid}'", "wifi_generic": "WLAN-Netzwerk",
           "vcard": "Kontakt (vCard)", "link": "Link: {d}", "text": "Text: {d}",
           "caption": "QR-Code erzeugt: {s}.", "alt": "QR-Code, der {s} codiert"},
    "it": {"wifi": "Rete WiFi '{ssid}'", "wifi_generic": "Rete WiFi",
           "vcard": "Contatto (vCard)", "link": "Link: {d}", "text": "Testo: {d}",
           "caption": "Codice QR generato: {s}.", "alt": "Codice QR che codifica {s}"},
    "zh": {"wifi": "WiFi 网络 '{ssid}'", "wifi_generic": "WiFi 网络",
           "vcard": "联系人 (vCard)", "link": "链接:{d}", "text": "文本:{d}",
           "caption": "已生成 QR 码:{s}。", "alt": "编码 {s} 的 QR 码"},
}


def _lang_code(lang: str) -> str:
    base = (lang or "en").lower().split("-")[0]
    return base if base in _LABELS else "en"


def _summarize(content: str, lang: str, max_len: int = 80) -> str:
    """Return a human-readable one-line summary of the encoded content."""
    labels = _LABELS[lang]
    c = content.strip()
    if c.startswith("WIFI:"):
        ssid = ""
        for part in c.split(";"):
            if part.startswith("S:"):
                ssid = part[2:]
                break
        return labels["wifi"].format(ssid=ssid) if ssid else labels["wifi_generic"]
    if c.upper().startswith("BEGIN:VCARD"):
        return labels["vcard"]
    if c.startswith(("http://", "https://")):
        display = c if len(c) <= max_len else c[: max_len - 1] + "…"
        return labels["link"].format(d=display)
    display = c if len(c) <= max_len else c[: max_len - 1] + "…"
    return labels["text"].format(d=display)


def main() -> None:
    raw = sys.stdin.read() or "{}"
    try:
        payload = json.loads(raw)
    except json.JSONDecodeError:
        print(
            json.dumps(
                {"text": "Invalid payload.", "error": "stdin is not valid JSON"}
            )
        )
        return

    params = payload.get("parameters") or {}
    content = params.get("content")
    if not isinstance(content, str) or not content.strip():
        print(
            json.dumps(
                {
                    "text": "No content provided to encode.",
                    "error": "Missing 'content' parameter",
                }
            )
        )
        return

    try:
        import segno  # type: ignore[import-untyped]
    except ImportError:
        print(
            json.dumps(
                {
                    "text": "QR generator unavailable (segno not installed).",
                    "error": "segno import failed — check backend requirements.txt",
                }
            )
        )
        return

    # Encode with error correction 'M' (~15% recovery) and a decent scale so
    # the resulting PNG stays sharp once rendered at any size.
    qr = segno.make(content, error="m")
    buf = io.BytesIO()
    qr.save(
        buf,
        kind="png",
        scale=10,
        border=2,
        dark="black",
        light="white",
    )
    png_bytes = buf.getvalue()
    b64 = base64.b64encode(png_bytes).decode("ascii")
    data_uri = f"data:image/png;base64,{b64}"

    lang = _lang_code(params.get("_lang", "en"))
    summary = _summarize(content, lang)
    labels = _LABELS[lang]

    print(
        json.dumps(
            {
                "text": labels["caption"].format(s=summary),
                "image": {
                    "url": data_uri,
                    "alt": labels["alt"].format(s=summary),
                },
            }
        )
    )


if __name__ == "__main__":
    main()
