/**
 * AnimatedEmoji — animated Noto emoji with graceful static fallback.
 *
 * Renders a self-hosted animated WebP (public/animated-emoji/) for the given
 * glyph, falling back to the plain Unicode glyph when the animation is not
 * requested, the asset is missing (per-codepoint error memory), or the user
 * prefers reduced motion (the WebP is then not even fetched).
 * Assets are regenerated by scripts/assets/fetch_noto_animated_emoji.py.
 */

'use client';

import { useState } from 'react';

import { cn } from '@/lib/utils';

/** Derive the asset codepoint from a glyph (e.g. '⚖️' -> '2696-fe0f'). */
export function emojiToCodepoint(glyph: string): string {
  return [...glyph].map(ch => (ch.codePointAt(0) as number).toString(16)).join('-');
}

export interface AnimatedEmojiProps {
  /** Unicode emoji glyph — also the static fallback rendering. */
  glyph: string;
  /** Asset codepoint override (registry-provided); derived from glyph when omitted. */
  codepoint?: string;
  /** Render the animated WebP; false renders the static glyph. */
  animate?: boolean;
  /** Classes for the animated <img> (size it per call site). */
  imgClassName?: string;
  /** Classes for the static <span> fallback. */
  spanClassName?: string;
}

export function AnimatedEmoji({
  glyph,
  codepoint,
  animate,
  imgClassName,
  spanClassName,
}: AnimatedEmojiProps) {
  // Per-codepoint load-failure memory: a broken/missing asset falls back to
  // the static glyph without retry loops; a different glyph retries its own.
  const [failedCodepoint, setFailedCodepoint] = useState<string | null>(null);
  const assetCodepoint = codepoint ?? emojiToCodepoint(glyph);

  // Never animate under reduced motion — checked here so the WebP is not even fetched.
  const prefersReducedMotion =
    typeof window !== 'undefined' && window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  const showAnimated =
    Boolean(animate) && !prefersReducedMotion && failedCodepoint !== assetCodepoint;

  if (!showAnimated) {
    return <span className={spanClassName}>{glyph}</span>;
  }
  return (
    // eslint-disable-next-line @next/next/no-img-element -- self-hosted animated WebP; next/image would not preserve the animation pipeline
    <img
      src={`/animated-emoji/${assetCodepoint}.webp`}
      alt=""
      aria-hidden="true"
      loading="lazy"
      draggable={false}
      className={cn('pointer-events-none select-none', imgClassName)}
      onError={() => setFailedCodepoint(assetCodepoint)}
    />
  );
}
