'use client';

/**
 * FollowupChips — tappable follow-up suggestions under the latest assistant
 * answer (UXR Lot 4, A2; content generated by the Initiative node, ADR-062).
 *
 * A chip click PREFILLS the input (replacing its content — an explicit user
 * action) and never sends. Text is generated in the user's language and
 * rendered strictly as React children (XSS boundary — never markdown/HTML).
 * The page owns the visibility gate: latest assistant message only, never
 * during streaming, history view, or while the input is disabled.
 */

import { CornerDownRight, Sparkles } from 'lucide-react';
import { useTranslation } from 'react-i18next';

import type { Message } from '@/types/chat';

/**
 * Visibility rule (pure, exported for tests): chips belong to the LATEST
 * message only when it is an assistant answer carrying suggestions, and
 * never while the surface is TRANSIENTLY busy (streaming, history view — the
 * page folds those into `blocked`). Disappearing on the next user turn is a
 * consequence of the latest-only rule.
 *
 * Competition with the other conditional surfaces — the usage wall, a pending
 * approval — is NOT decided here: `lib/chat-surfaces` arbitrates that in one
 * place (S1), and the page only mounts the chips when they hold the slot.
 */
export function visibleFollowups(messages: Message[], blocked: boolean): string[] {
  if (blocked) return [];
  const last = messages[messages.length - 1];
  if (!last || last.role !== 'assistant') return [];
  const raw = last.metadata?.followup_suggestions;
  return Array.isArray(raw) ? raw.filter((x): x is string => typeof x === 'string') : [];
}

/** Provenance line of the latest answer's chips (Lot 1-A3): the initiative's
 * own stated trigger ("Parce que tu suis la F1"). Same latest-only gate as
 * the chips — a motivation without chips is never shown. */
export function visibleMotivation(messages: Message[], blocked: boolean): string | null {
  if (visibleFollowups(messages, blocked).length === 0) return null;
  const last = messages[messages.length - 1];
  const raw = last?.metadata?.initiative_motivation;
  return typeof raw === 'string' && raw.trim() ? raw : null;
}

export interface FollowupChipsProps {
  /** Sanitized suggestions (0-3, server-bounded). */
  suggestions: string[];
  /** Provenance line naming the memory/interest that motivated the chips. */
  motivation?: string | null;
  /** Prefill handler — receives the chip's text verbatim. */
  onPick: (text: string) => void;
}

export function FollowupChips({ suggestions, motivation, onPick }: FollowupChipsProps) {
  const { t } = useTranslation();
  if (suggestions.length === 0) return null;
  return (
    <div
      role="group"
      aria-label={t('chat.followups.aria')}
      className="flex flex-wrap items-center gap-2 px-2 pb-2 mobile:px-6"
    >
      {motivation && (
        <span className="flex w-full items-center gap-1.5 text-xs italic text-muted-foreground">
          <Sparkles className="h-3 w-3 shrink-0 text-primary/70" aria-hidden />
          {motivation}
        </span>
      )}
      {suggestions.map(text => (
        <button
          key={text}
          type="button"
          onClick={() => onPick(text)}
          title={text}
          className="inline-flex max-w-full items-center gap-1.5 rounded-full border border-primary/30 bg-primary/5 px-3 py-1.5 text-xs font-medium text-foreground/90 hover:bg-primary/10 hover:border-primary/50 transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
        >
          <CornerDownRight className="h-3 w-3 shrink-0 text-primary/70" aria-hidden />
          <span className="truncate">{text}</span>
        </button>
      ))}
    </div>
  );
}
