import React, { useState, useMemo, memo, useEffect, lazy, Suspense } from 'react';
import { createPortal } from 'react-dom';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import remarkMath from 'remark-math';
import rehypeRaw from 'rehype-raw';
import rehypeKatex from 'rehype-katex';
import { useTranslation } from 'react-i18next';
import { cn, GOOGLE_IMAGE_DOMAINS, proxyGoogleImageUrl } from '@/lib/utils';
import { ImageLightbox } from '@/components/ui/image-lightbox';
import { InlinePlaceCarousel } from '@/components/ui/inline-place-carousel';
import { formatPhonesInText } from '@/lib/format';
import { isImageLoaded, markImageLoaded } from '@/lib/image-cache';

// MCP Apps widget — lazy loaded (only needed when MCP App sentinel divs are present)
const McpAppWidget = lazy(() =>
  import('@/components/chat/McpAppWidget').then(m => ({ default: m.McpAppWidget }))
);

// Skill Apps widget — lazy loaded (only needed when Skill App sentinel divs are present)
const SkillAppWidget = lazy(() =>
  import('@/components/chat/SkillAppWidget').then(m => ({ default: m.SkillAppWidget }))
);

// Code block with syntax highlighting — lazy loaded to keep Prism out of main bundle
const CodeBlock = lazy(() =>
  import('@/components/chat/CodeBlock').then(m => ({ default: m.CodeBlock }))
);

/**
 * MarkdownContent Component
 *
 * Renders Markdown content with custom styling adapted to the application's design system.
 * Follows Tailwind CSS 4.0 best practices and supports dark mode.
 *
 * Features:
 * - GitHub Flavored Markdown (GFM) support
 * - Custom component styling for headings, lists, links, code blocks
 * - Responsive typography
 * - Dark mode support via Tailwind's dark: variant
 * - Professional appearance aligned with the app's OKLCH color system
 */

/**
 * StableGalleryImage - Image component with global load state
 *
 * Issue #64: Images were scintillating during streaming because React re-rendered
 * them on every token. This component uses a global cache to remember which images
 * have already loaded, so they appear instantly on subsequent renders.
 *
 * IMPORTANT: Uses custom memo comparison that ignores onClick to prevent re-renders
 * when parent passes new function references.
 */
const StableGalleryImage = memo(
  ({ src, alt, onClick }: { src: string; alt: string; onClick: () => void }) => {
    // Check if already loaded from cache (instant display)
    const alreadyLoaded = isImageLoaded(src);
    const [loaded, setLoaded] = useState(alreadyLoaded);

    const handleLoad = () => {
      markImageLoaded(src);
      setLoaded(true);
    };

    return (
      // eslint-disable-next-line @next/next/no-img-element -- External dynamic URL (Google Contacts photos), needs onLoad callback for cache
      <img
        src={proxyGoogleImageUrl(src) || src}
        alt={alt}
        className="contact-photo"
        style={{
          // Only keep opacity for loading animation - all other styles handled by CSS class
          opacity: loaded ? 1 : 0,
        }}
        onLoad={handleLoad}
        onClick={onClick}
      />
    );
  },
  (prevProps, nextProps) => {
    // Only re-render if src or alt changes - ignore onClick function reference changes
    return prevProps.src === nextProps.src && prevProps.alt === nextProps.alt;
  }
);
StableGalleryImage.displayName = 'StableGalleryImage';

/**
 * Global cache for extracted gallery images.
 * Key: stringified image sources, Value: array of image data
 * This prevents re-extraction during streaming when the same images are present.
 */
const galleryImagesCache = new Map<string, Array<{ src: string; alt: string }>>();

/**
 * ContactPhotoGallery - Renders horizontal photo gallery with lightbox
 *
 * This component intercepts the HTML photo gallery generated by response_node.py
 * and adds interactive lightbox functionality to each photo.
 *
 * The backend generates:
 *   <div class="contact-photos-gallery">
 *     <img src="..." alt="Photo de {name}" class="contact-photo" />
 *     <img src="..." alt="Photo de {name}" class="contact-photo" />
 *   </div>
 *
 * This component enhances it with:
 * - Click to open lightbox
 * - Keyboard navigation (TODO: arrows for gallery)
 * - Proper responsive sizing
 * - Cached image extraction to prevent flicker during streaming
 */
const ContactPhotoGallery = ({ children }: { children?: React.ReactNode }) => {
  const [lightboxSrc, setLightboxSrc] = useState<string | null>(null);
  const [lightboxAlt, setLightboxAlt] = useState<string>('');

  // Extract images from children
  const extractImages = (node: React.ReactNode): Array<{ src: string; alt: string }> => {
    const images: Array<{ src: string; alt: string }> = [];

    const extract = (n: React.ReactNode) => {
      React.Children.forEach(n, child => {
        if (React.isValidElement(child)) {
          const childProps = child.props as {
            src?: string;
            alt?: string;
            children?: React.ReactNode;
          };
          if (child.type === 'img') {
            if (childProps.src) {
              images.push({ src: childProps.src, alt: childProps.alt || '' });
            }
          } else if (childProps.children) {
            extract(childProps.children);
          } else if (childProps.src && typeof childProps.src === 'string') {
            images.push({ src: childProps.src, alt: childProps.alt || '' });
          }
        }
      });
    };

    extract(node);
    return images;
  };

  // Extract current images
  const currentImages = extractImages(children);

  // Create cache key from image sources
  const cacheKey = currentImages
    .map(img => img.src)
    .sort()
    .join('|');

  // Use cached images if available (prevents flicker during streaming)
  // Only update cache if we have new images
  if (cacheKey && !galleryImagesCache.has(cacheKey)) {
    galleryImagesCache.set(cacheKey, currentImages);
  }

  const imagesToRender = galleryImagesCache.get(cacheKey) || currentImages;

  return (
    <>
      <div className="contact-photos-gallery">
        {imagesToRender.map(img => (
          <StableGalleryImage
            key={img.src}
            src={img.src}
            alt={img.alt}
            onClick={() => {
              setLightboxSrc(img.src);
              setLightboxAlt(img.alt);
            }}
          />
        ))}
      </div>
      {lightboxSrc && (
        <ImageLightbox
          src={lightboxSrc}
          alt={lightboxAlt}
          isOpen={!!lightboxSrc}
          onClose={() => setLightboxSrc(null)}
          minWidth={192}
        />
      )}
    </>
  );
};

/**
 * PlacePhotoWrapper - Wrapper for place photos with inline carousel
 *
 * When multiple photos are available (data-photo-urls attribute), displays
 * an inline carousel directly within the place card photo area.
 * The carousel has the same dimensions as the original photo.
 *
 * Fallback: If no data-photo-urls attribute is present (e.g., cached messages),
 * renders the original photo as-is.
 */
const PlacePhotoWrapper = ({
  children,
  ...props
}: {
  children?: React.ReactNode;
  [key: string]: unknown;
}) => {
  const { t } = useTranslation();

  // Parse data-photo-urls (JSON array of URLs)
  const photoUrlsJson = props['data-photo-urls'] as string | undefined;
  const photoUrls = useMemo(() => {
    if (!photoUrlsJson) return [];
    try {
      return JSON.parse(photoUrlsJson) as string[];
    } catch (error) {
      console.warn('[PlacePhotoWrapper] Failed to parse photo URLs:', error);
      return [];
    }
  }, [photoUrlsJson]);

  const hasMultiplePhotos = photoUrls.length > 1;

  // If multiple photos available, show inline carousel
  if (hasMultiplePhotos) {
    return (
      <div className="lia-place__photo">
        <InlinePlaceCarousel images={photoUrls} alt={t('gallery.place_photo')} />
      </div>
    );
  }

  // Single photo or no gallery data - render original content
  return <div className="lia-place__photo">{children}</div>;
};

/**
 * MarkdownImage - Renders images in markdown with smart detection
 *
 * Detects profile photos (Google Contacts) and uses Avatar component
 * for enhanced styling (rounded, glassmorphism, hover effects).
 * Falls back to standard image rendering for non-profile images.
 * Click to open in lightbox at 3x size.
 *
 * NOTE: This is for standalone markdown images (![](url)).
 * For HTML photo galleries, see ContactPhotoGallery component.
 *
 * LIA Component System: Images with 'lia-*' classes are part of the
 * LIA design system and must be rendered as-is to preserve flexbox
 * layouts and component styling. This is critical for contact cards,
 * file items, and other structured components.
 *
 * Issue #64: Uses global image cache to prevent scintillation during streaming.
 */
const MarkdownImage = memo(
  ({ src: srcProp, alt, className }: React.ImgHTMLAttributes<HTMLImageElement>) => {
    const [isLightboxOpen, setIsLightboxOpen] = useState(false);
    // Normalize src to string (React 19 types allow Blob)
    const src = typeof srcProp === 'string' ? srcProp : undefined;
    // Use global cache to check if image already loaded
    const alreadyLoaded = src ? isImageLoaded(src) : false;
    const [loaded, setLoaded] = useState(alreadyLoaded);

    // For Avatar component (no onLoad prop), preload image in background
    useEffect(() => {
      if (src && !alreadyLoaded) {
        const img = new Image();
        img.onload = () => {
          markImageLoaded(src);
          setLoaded(true);
        };
        img.src = src;
      }
    }, [src, alreadyLoaded]);

    const handleLoad = () => {
      if (src) {
        markImageLoaded(src);
      }
      setLoaded(true);
    };

    if (!src) return null;

    // =========================================================================
    // LIA COMPONENT SYSTEM - Preserve structured component images
    // =========================================================================
    // Images with 'lia-*' classes are part of the LIA design system (avatars,
    // thumbnails, etc.). They must be rendered as-is to preserve:
    // - Flexbox layouts in card headers (.lia-contact__header, etc.)
    // - Component-specific sizing (.lia-avatar--sm, .lia-avatar--md)
    // - Design system consistency
    //
    // Without this check, transformations below would wrap LIA images in
    // full-width blocks, breaking flexbox layouts and changing CSS classes.
    // =========================================================================
    const isLiaComponent = className?.startsWith('lia-');
    if (isLiaComponent) {
      return (
        // eslint-disable-next-line @next/next/no-img-element
        <img
          src={src}
          alt={alt || ''}
          className={className}
          style={{
            opacity: loaded ? 1 : 0,
            transition: 'opacity 0.15s ease-in',
          }}
          onLoad={handleLoad}
        />
      );
    }

    // Detect if this is a profile photo (from Google Contacts API or explicit alt text)
    // Exclude place photos (/api/v1/connectors/google-places/photo path) - they use proxy endpoint
    const isPlacePhoto = src.includes('/connectors/google-places/photo');
    const isProfilePhoto =
      !isPlacePhoto &&
      (() => {
        try {
          const parsed = new URL(src);
          return GOOGLE_IMAGE_DOMAINS.includes(parsed.hostname);
        } catch {
          return alt?.toLowerCase().includes('photo') ?? false;
        }
      })();

    // Place photo - clickable with lightbox (2x zoom: 200px -> 400px)
    if (isPlacePhoto) {
      return (
        <>
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            src={src}
            alt={alt || 'Photo du lieu'}
            className="place-photo"
            style={{
              opacity: loaded ? 1 : 0,
              transition: loaded
                ? 'transform 0.2s ease, box-shadow 0.2s ease'
                : 'opacity 0.15s ease-in',
            }}
            onLoad={handleLoad}
            onClick={() => setIsLightboxOpen(true)}
          />
          {typeof document !== 'undefined' &&
            createPortal(
              <ImageLightbox
                src={src}
                alt={alt || 'Photo du lieu'}
                isOpen={isLightboxOpen}
                onClose={() => setIsLightboxOpen(false)}
                minWidth={400}
              />,
              document.body
            )}
        </>
      );
    }

    // Profile photo (Google Contacts) - Single contact detail view
    // Uses contact-photo CSS class for consistent styling with vignette effect
    if (isProfilePhoto) {
      const proxiedSrc = proxyGoogleImageUrl(src) || src;
      return (
        <>
          <span
            style={{
              display: 'block',
            }}
            className="flex justify-center my-4 w-full"
          >
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              src={proxiedSrc}
              alt={alt || 'Photo de profil'}
              className="contact-photo"
              style={{
                opacity: loaded ? 1 : 0,
              }}
              onLoad={handleLoad}
              onClick={() => setIsLightboxOpen(true)}
            />
          </span>
          {typeof document !== 'undefined' &&
            createPortal(
              <ImageLightbox
                src={proxiedSrc}
                alt={alt || 'Photo de profil'}
                isOpen={isLightboxOpen}
                onClose={() => setIsLightboxOpen(false)}
                minWidth={250}
              />,
              document.body
            )}
        </>
      );
    }

    // Default image rendering for non-profile images (screenshots, diagrams, etc.)
    return (
      <span className="block relative w-full max-w-[150px] my-3 mx-auto">
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img
          src={src}
          alt={alt || 'Image'}
          className="w-full h-full object-cover rounded-lg shadow-md"
          style={{
            opacity: loaded ? 1 : 0,
            transition: 'opacity 0.15s ease-in',
          }}
          loading="lazy"
          onLoad={handleLoad}
        />
      </span>
    );
  }
);
MarkdownImage.displayName = 'MarkdownImage';

interface MarkdownContentProps {
  content: string;
  isUser?: boolean;
  className?: string;
}

/**
 * MarkdownContent component - Memoized to prevent unnecessary re-renders during streaming.
 * Issue #64: Without memo, images would flash on every token because React recreates the DOM.
 * The memo comparison uses default shallow equality which is sufficient since content changes
 * trigger the necessary re-render anyway.
 */
/**
 * Sanitize malformed HTML tags that contain emojis.
 * LLMs sometimes generate tags like `<li📧>` instead of `<li>📧`.
 * This regex fixes common patterns to prevent createElement errors.
 */
function sanitizeMalformedTags(text: string): string {
  // Fix tags with emojis attached: <li📧 -> <li>📧, </li📧> -> </li>
  // Matches: < followed by valid tag name, then emoji(s), then optional attributes/closing
  // Unicode emoji ranges: \u{1F300}-\u{1F9FF} covers most emojis
  return text.replace(
    /<(\/?)([a-zA-Z][a-zA-Z0-9]*)([\u{1F300}-\u{1F9FF}\u{2600}-\u{26FF}\u{2700}-\u{27BF}]+)([^>]*)>/gu,
    (_, slash, tag, emoji, rest) => `<${slash}${tag}${rest}>${emoji}`
  );
}

export const MarkdownContent: React.FC<MarkdownContentProps> = memo(
  ({ content, isUser = false, className }) => {
    const { t } = useTranslation();

    // Sanitize malformed HTML tags (e.g., <li📧> -> <li>📧)
    const sanitizedContent = useMemo(() => sanitizeMalformedTags(content), [content]);

    // Format phone numbers in content (French: 06.12.34.56.78, others: national format)
    const formattedContent = useMemo(
      () => formatPhonesInText(sanitizedContent),
      [sanitizedContent]
    );

    return (
      <div className={cn('markdown-content text-[13px] mobile:text-sm leading-relaxed', className)}>
        <ReactMarkdown
          remarkPlugins={[remarkGfm, remarkMath]}
          remarkRehypeOptions={{ allowDangerousHtml: true }}
          rehypePlugins={[rehypeRaw, rehypeKatex]}
          // Custom URL transform to allow tel: and mailto: protocols
          // Default only allows: http, https, irc, ircs, mailto, xmpp
          urlTransform={(url: string) => {
            // Allow tel: protocol for click-to-call
            if (url.startsWith('tel:')) return url;
            // Allow mailto: protocol for email links
            if (url.startsWith('mailto:')) return url;
            // Allow safe protocols
            if (url.startsWith('http://') || url.startsWith('https://')) return url;
            // Allow relative URLs
            if (url.startsWith('/') || url.startsWith('#') || url.startsWith('?')) return url;
            // Block other protocols (javascript:, data:, etc.)
            if (url.includes(':')) return '';
            // Allow protocol-relative URLs
            return url;
          }}
          components={{
            // Headings
            h1: ({ children }) => (
              <h1 className="text-2xl font-bold mt-6 mb-4 first:mt-0 border-b border-border pb-2">
                {children}
              </h1>
            ),
            h2: ({ children }) => (
              <h2 className="text-xl font-semibold mt-5 mb-3 first:mt-0 border-b border-border/50 pb-1.5">
                {children}
              </h2>
            ),
            h3: ({ children }) => (
              <h3 className="text-lg font-semibold mt-4 mb-2 first:mt-0">{children}</h3>
            ),
            h4: ({ children }) => (
              <h4 className="text-base font-semibold mt-3 mb-2 first:mt-0">{children}</h4>
            ),
            h5: ({ children }) => (
              <h5 className="text-sm font-semibold mt-3 mb-1.5 first:mt-0">{children}</h5>
            ),
            h6: ({ children }) => (
              <h6 className="text-sm font-semibold mt-3 mb-1.5 first:mt-0 text-muted-foreground">
                {children}
              </h6>
            ),

            // Paragraphs - preserve LIA component classes
            p: ({ className, children, ...props }) => {
              // LIA components (e.g., lia-email__snippet) need their original class preserved
              const isLiaComponent = className?.startsWith('lia-');
              return (
                <p
                  className={
                    isLiaComponent
                      ? className
                      : cn('mb-3 last:mb-0 whitespace-pre-wrap break-words', className)
                  }
                  {...props}
                >
                  {children}
                </p>
              );
            },

            // Strong (bold)
            strong: ({ children }) => (
              <strong className="font-semibold text-foreground">{children}</strong>
            ),

            // Emphasis (italic)
            em: ({ children }) => <em className="italic text-foreground">{children}</em>,

            // Links
            a: ({ href, className, children, ...props }) => {
              // LIA components (e.g., lia-event__title) need their original class preserved
              const isLiaComponent = className?.startsWith('lia-');

              // tel: and mailto: links should NOT open in new tab (breaks native handlers)
              const isProtocolLink = href?.startsWith('tel:') || href?.startsWith('mailto:');

              return (
                <a
                  href={href}
                  // Only external links open in new tab - tel:/mailto: use native handlers
                  {...(!isProtocolLink && { target: '_blank', rel: 'noopener noreferrer' })}
                  className={
                    isLiaComponent
                      ? className
                      : cn(
                          'underline decoration-primary/40 hover:decoration-primary transition-colors',
                          isUser
                            ? 'text-primary-foreground hover:text-primary-foreground/90'
                            : 'text-primary hover:text-primary/80'
                        )
                  }
                  {...props}
                >
                  {children}
                </a>
              );
            },

            // Unordered lists - balanced spacing between items
            ul: ({ children }) => (
              <ul className="list-disc list-outside pl-5 mb-2 space-y-1.5 last:mb-0">{children}</ul>
            ),

            // Ordered lists - generous spacing (numbered items often contain rich content)
            ol: ({ children }) => (
              <ol className="list-decimal list-outside pl-5 mb-2 space-y-3 last:mb-0">
                {children}
              </ol>
            ),

            // List items - normal leading for readability
            li: ({ children }) => <li className="pl-1 leading-normal">{children}</li>,

            // Blockquotes
            blockquote: ({ children }) => (
              <blockquote
                className={cn(
                  'border-l-4 pl-4 py-2 my-3 italic',
                  isUser
                    ? 'border-primary-foreground/30 bg-primary-foreground/5'
                    : 'border-primary/40 bg-muted/30'
                )}
              >
                {children}
              </blockquote>
            ),

            // Inline code and code blocks
            code: ({ className: codeClassName, children, ...props }) => {
              // Check if it's a code block (has className with language-*)
              const isCodeBlock = codeClassName?.startsWith('language-');

              if (isCodeBlock) {
                const language = codeClassName?.replace('language-', '') || 'text';
                const codeText = String(children).replace(/\n$/, '');

                // Suspense fallback matches the old plain <pre> look so the
                // visual transition on lazy-load is imperceptible.
                const fallback = (
                  <div className="my-3 rounded-lg overflow-hidden border border-border/50 shadow-sm">
                    <div className="px-3 py-1 text-xs font-mono bg-muted/50 text-muted-foreground border-b border-border/50">
                      {language}
                    </div>
                    <pre className="p-3 overflow-x-auto bg-muted/20">
                      <code className="text-sm font-mono text-foreground block">{codeText}</code>
                    </pre>
                  </div>
                );

                return (
                  <Suspense fallback={fallback}>
                    <CodeBlock language={language}>{codeText}</CodeBlock>
                  </Suspense>
                );
              }

              // Inline code
              return (
                <code
                  className={cn(
                    'px-1.5 py-0.5 rounded text-xs font-mono',
                    isUser
                      ? 'bg-primary-foreground/20 text-primary-foreground'
                      : 'bg-muted text-foreground'
                  )}
                  {...props}
                >
                  {children}
                </code>
              );
            },

            // Horizontal rule
            hr: () => <hr className="my-4 border-t border-border/50" />,

            // Tables - responsive with scroll indicator on mobile
            table: ({ children }) => (
              <div className="table-wrapper my-3 overflow-x-auto rounded-lg border border-border/50 shadow-sm">
                <table className="divide-y divide-border/50">{children}</table>
              </div>
            ),
            thead: ({ children }) => <thead className="bg-muted/30">{children}</thead>,
            tbody: ({ children }) => (
              <tbody className="divide-y divide-border/30 bg-card/30">{children}</tbody>
            ),
            tr: ({ children }) => (
              <tr className="hover:bg-muted/20 transition-colors">{children}</tr>
            ),
            th: ({ children }) => (
              <th className="px-4 py-2 text-left font-semibold uppercase tracking-wider text-foreground">
                {children}
              </th>
            ),
            td: ({ children }) => <td className="px-3 py-2 text-foreground sm:px-4">{children}</td>,

            // Task lists (GFM extension)
            input: ({ checked, ...props }) => (
              <input
                type="checkbox"
                checked={checked}
                disabled
                className="mr-2 align-middle accent-primary cursor-default"
                {...props}
              />
            ),

            // Images - using separate component to comply with React hooks rules
            img: MarkdownImage,

            // Divs - intercept photo galleries and MCP Apps for enhanced interactivity
            div: ({ className, children, ...props }) => {
              // MCP App widget (generated by mcp_app_sentinel.py)
              // Replaces sentinel div with interactive sandboxed iframe + JSON-RPC bridge
              if (className?.includes('lia-mcp-app')) {
                const registryId = (props as Record<string, unknown>)['data-registry-id'] as
                  | string
                  | undefined;
                if (registryId) {
                  return (
                    <Suspense
                      fallback={
                        <div className="lia-mcp-app__placeholder">
                          <div className="lia-mcp-app__loading">{t('mcp_apps.loading')}</div>
                        </div>
                      }
                    >
                      <McpAppWidget registryId={registryId} />
                    </Suspense>
                  );
                }
              }

              // Skill App widget (generated by skill_app_sentinel.py)
              // Replaces sentinel div with iframe (frame.html/url) and/or image card
              if (className?.includes('lia-skill-app')) {
                const registryId = (props as Record<string, unknown>)['data-registry-id'] as
                  | string
                  | undefined;
                if (registryId) {
                  return (
                    <Suspense
                      fallback={
                        <div className="lia-skill-app__placeholder">
                          <div className="lia-skill-app__loading">
                            {t('skill_apps.loading', { defaultValue: 'Loading skill…' })}
                          </div>
                        </div>
                      }
                    >
                      <SkillAppWidget registryId={registryId} />
                    </Suspense>
                  );
                }
              }

              // Place photo gallery (generated by place_card.py)
              // Uses PlacePhotoWrapper for multi-image gallery lightbox
              if (className?.includes('lia-place__photo')) {
                return <PlacePhotoWrapper {...props}>{children}</PlacePhotoWrapper>;
              }

              // Contact photo gallery (generated by response_node.py)
              // Also handle corrupted class names (LLM sometimes adds spaces: "contact - photos - gallery")
              const isContactPhotoGallery =
                className?.includes('contact-photos-gallery') ||
                className?.replace(/\s+/g, '').includes('contact-photos-gallery');

              if (isContactPhotoGallery) {
                return <ContactPhotoGallery>{children}</ContactPhotoGallery>;
              }

              // Default div rendering
              return (
                <div className={className} {...props}>
                  {children}
                </div>
              );
            },
          }}
        >
          {formattedContent}
        </ReactMarkdown>
      </div>
    );
  }
);
MarkdownContent.displayName = 'MarkdownContent';
