import React, { useState, useMemo, memo, useEffect, lazy, Suspense } from 'react';
import { createPortal } from 'react-dom';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import remarkMath from 'remark-math';
import rehypeRaw from 'rehype-raw';
import rehypeSanitize from 'rehype-sanitize';
import rehypeKatex from 'rehype-katex';
import { markdownSanitizeSchema } from '@/lib/markdown-sanitize-schema';
import rehypeMathInText from '@/lib/rehype-math-in-text';
import rehypeSearchHighlight from '@/lib/rehype-search-highlight';
import { useTranslation } from 'react-i18next';
import { cn, GOOGLE_IMAGE_DOMAINS, proxyGoogleImageUrl } from '@/lib/utils';
import { ImageLightbox } from '@/components/ui/image-lightbox';
import { InlinePlaceCarousel } from '@/components/ui/inline-place-carousel';
import { ReasoningScroll } from '@/components/chat/ReasoningScroll';
import { formatPhonesInText } from '@/lib/format';
import { isImageLoaded, markImageLoaded } from '@/lib/image-cache';
import { logger } from '@/lib/logger';

// MCP Apps widget — lazy loaded (only needed when MCP App sentinel divs are present)
const McpAppWidget = lazy(() =>
  import('@/components/chat/McpAppWidget').then(m => ({ default: m.McpAppWidget }))
);

// Skill Apps widget — lazy loaded (only needed when Skill App sentinel divs are present)
const SkillAppWidget = lazy(() =>
  import('@/components/chat/SkillAppWidget').then(m => ({ default: m.SkillAppWidget }))
);

// Code block with syntax highlighting — lazy loaded to keep Prism out of main bundle
const CodeBlock = lazy(() =>
  import('@/components/chat/CodeBlock').then(m => ({ default: m.CodeBlock }))
);

/**
 * MarkdownContent Component
 *
 * Renders Markdown content with custom styling adapted to the application's design system.
 * Follows Tailwind CSS 4.0 best practices and supports dark mode.
 *
 * Features:
 * - GitHub Flavored Markdown (GFM) support
 * - Custom component styling for headings, lists, links, code blocks
 * - Responsive typography
 * - Dark mode support via Tailwind's dark: variant
 * - Professional appearance aligned with the app's OKLCH color system
 */

/**
 * StableGalleryImage - Image component with global load state
 *
 * Issue #64: Images were scintillating during streaming because React re-rendered
 * them on every token. This component uses a global cache to remember which images
 * have already loaded, so they appear instantly on subsequent renders.
 *
 * IMPORTANT: Uses custom memo comparison that ignores onClick to prevent re-renders
 * when parent passes new function references.
 */
const StableGalleryImage = memo(
  ({ src, alt, onClick }: { src: string; alt: string; onClick: () => void }) => {
    // Check if already loaded from cache (instant display)
    const alreadyLoaded = isImageLoaded(src);
    const [loaded, setLoaded] = useState(alreadyLoaded);
    // Context subscription bypasses the custom comparator below, so the
    // accessible name still refreshes on a language switch.
    const { t } = useTranslation();

    const handleLoad = () => {
      markImageLoaded(src);
      setLoaded(true);
    };

    return (
      // Opening the lightbox is a real action: native <button> around the
      // image — Enter/Space and focus come from the platform (audit F013).
      <button
        type="button"
        onClick={onClick}
        aria-label={t('common.expand_image')}
        className="inline-block align-top p-0 border-0 bg-transparent cursor-pointer rounded focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
      >
        {/* eslint-disable-next-line @next/next/no-img-element -- External dynamic URL (Google Contacts photos), needs onLoad callback for cache */}
        <img
          src={proxyGoogleImageUrl(src) || src}
          alt={alt}
          className="contact-photo"
          referrerPolicy="no-referrer"
          style={{
            // Only keep opacity for loading animation - all other styles handled by CSS class
            opacity: loaded ? 1 : 0,
          }}
          onLoad={handleLoad}
        />
      </button>
    );
  },
  (prevProps, nextProps) => {
    // Only re-render if src or alt changes - ignore onClick function reference changes
    return prevProps.src === nextProps.src && prevProps.alt === nextProps.alt;
  }
);
StableGalleryImage.displayName = 'StableGalleryImage';

/**
 * Global cache for extracted gallery images.
 * Key: stringified image sources, Value: array of image data
 * This prevents re-extraction during streaming when the same images are present.
 */
const galleryImagesCache = new Map<string, Array<{ src: string; alt: string }>>();

/**
 * ContactPhotoGallery - Renders horizontal photo gallery with lightbox
 *
 * This component intercepts the HTML photo gallery generated by response_node.py
 * and adds interactive lightbox functionality to each photo.
 *
 * The backend generates:
 *   <div class="contact-photos-gallery">
 *     <img src="..." alt="Photo de {name}" class="contact-photo" />
 *     <img src="..." alt="Photo de {name}" class="contact-photo" />
 *   </div>
 *
 * This component enhances it with:
 * - Click to open lightbox
 * - Keyboard navigation (TODO: arrows for gallery)
 * - Proper responsive sizing
 * - Cached image extraction to prevent flicker during streaming
 */
const ContactPhotoGallery = ({ children }: { children?: React.ReactNode }) => {
  const [lightboxSrc, setLightboxSrc] = useState<string | null>(null);
  const [lightboxAlt, setLightboxAlt] = useState<string>('');

  // Extract images from children
  const extractImages = (node: React.ReactNode): Array<{ src: string; alt: string }> => {
    const images: Array<{ src: string; alt: string }> = [];

    const extract = (n: React.ReactNode) => {
      React.Children.forEach(n, child => {
        if (React.isValidElement(child)) {
          const childProps = child.props as {
            src?: string;
            alt?: string;
            children?: React.ReactNode;
          };
          if (child.type === 'img') {
            if (childProps.src) {
              images.push({ src: childProps.src, alt: childProps.alt || '' });
            }
          } else if (childProps.children) {
            extract(childProps.children);
          } else if (childProps.src && typeof childProps.src === 'string') {
            images.push({ src: childProps.src, alt: childProps.alt || '' });
          }
        }
      });
    };

    extract(node);
    return images;
  };

  // Extract current images
  const currentImages = extractImages(children);

  // Create cache key from image sources
  const cacheKey = currentImages
    .map(img => img.src)
    .sort()
    .join('|');

  // Use cached images if available (prevents flicker during streaming)
  // Only update cache if we have new images
  if (cacheKey && !galleryImagesCache.has(cacheKey)) {
    galleryImagesCache.set(cacheKey, currentImages);
  }

  const imagesToRender = galleryImagesCache.get(cacheKey) || currentImages;

  return (
    <>
      <div className="contact-photos-gallery">
        {imagesToRender.map(img => (
          <StableGalleryImage
            key={img.src}
            src={img.src}
            alt={img.alt}
            onClick={() => {
              setLightboxSrc(img.src);
              setLightboxAlt(img.alt);
            }}
          />
        ))}
      </div>
      {lightboxSrc && (
        <ImageLightbox
          src={lightboxSrc}
          alt={lightboxAlt}
          isOpen={!!lightboxSrc}
          onClose={() => setLightboxSrc(null)}
          minWidth={192}
        />
      )}
    </>
  );
};

/**
 * PlacePhotoWrapper - Wrapper for place photos with inline carousel
 *
 * When multiple photos are available (data-photo-urls attribute), displays
 * an inline carousel directly within the place card photo area.
 * The carousel has the same dimensions as the original photo.
 *
 * Fallback: If no data-photo-urls attribute is present (e.g., cached messages),
 * renders the original photo as-is.
 */
const PlacePhotoWrapper = ({
  children,
  ...props
}: {
  children?: React.ReactNode;
  [key: string]: unknown;
}) => {
  const { t } = useTranslation();

  // Parse data-photo-urls (JSON array of URLs)
  const photoUrlsJson = props['data-photo-urls'] as string | undefined;
  const photoUrls = useMemo(() => {
    if (!photoUrlsJson) return [];
    try {
      return JSON.parse(photoUrlsJson) as string[];
    } catch (error) {
      logger.warn('place_photo_urls_parse_failed', {
        component: 'PlacePhotoWrapper',
        error: error instanceof Error ? error.message : String(error),
      });
      return [];
    }
  }, [photoUrlsJson]);

  const hasMultiplePhotos = photoUrls.length > 1;

  // If multiple photos available, show inline carousel
  if (hasMultiplePhotos) {
    return (
      <div className="lia-place__photo">
        <InlinePlaceCarousel images={photoUrls} alt={t('gallery.place_photo')} />
      </div>
    );
  }

  // Single photo or no gallery data - render original content
  return <div className="lia-place__photo">{children}</div>;
};

/**
 * MarkdownImage - Renders images in markdown with smart detection
 *
 * Detects profile photos (Google Contacts) and uses Avatar component
 * for enhanced styling (rounded, glassmorphism, hover effects).
 * Falls back to standard image rendering for non-profile images.
 * Click to open in lightbox at 3x size.
 *
 * NOTE: This is for standalone markdown images (![](url)).
 * For HTML photo galleries, see ContactPhotoGallery component.
 *
 * LIA Component System: Images with 'lia-*' classes are part of the
 * LIA design system and must be rendered as-is to preserve flexbox
 * layouts and component styling. This is critical for contact cards,
 * file items, and other structured components.
 *
 * Issue #64: Uses global image cache to prevent scintillation during streaming.
 */
const MarkdownImage = memo(
  ({ src: srcProp, alt, className }: React.ImgHTMLAttributes<HTMLImageElement>) => {
    const [isLightboxOpen, setIsLightboxOpen] = useState(false);
    const { t } = useTranslation();
    // Normalize src to string (React 19 types allow Blob)
    const src = typeof srcProp === 'string' ? srcProp : undefined;
    // Use global cache to check if image already loaded
    const alreadyLoaded = src ? isImageLoaded(src) : false;
    const [loaded, setLoaded] = useState(alreadyLoaded);

    // For Avatar component (no onLoad prop), preload image in background
    useEffect(() => {
      if (src && !alreadyLoaded) {
        const img = new Image();
        img.onload = () => {
          markImageLoaded(src);
          setLoaded(true);
        };
        // SEC-027: this preload is a real network request and leaks the same
        // Referer as the rendered <img>. Set BEFORE `src` — assigning the
        // source is what starts the fetch.
        img.referrerPolicy = 'no-referrer';
        img.src = src;
      }
    }, [src, alreadyLoaded]);

    const handleLoad = () => {
      if (src) {
        markImageLoaded(src);
      }
      setLoaded(true);
    };

    if (!src) return null;

    // =========================================================================
    // LIA COMPONENT SYSTEM - Preserve structured component images
    // =========================================================================
    // Images with 'lia-*' classes are part of the LIA design system (avatars,
    // thumbnails, etc.). They must be rendered as-is to preserve:
    // - Flexbox layouts in card headers (.lia-contact__header, etc.)
    // - Component-specific sizing (.lia-avatar--sm, .lia-avatar--md)
    // - Design system consistency
    //
    // Without this check, transformations below would wrap LIA images in
    // full-width blocks, breaking flexbox layouts and changing CSS classes.
    // =========================================================================
    const isLiaComponent = className?.startsWith('lia-');
    if (isLiaComponent) {
      return (
        // eslint-disable-next-line @next/next/no-img-element
        <img
          src={src}
          alt={alt || ''}
          className={className}
          referrerPolicy="no-referrer"
          style={{
            opacity: loaded ? 1 : 0,
            transition: 'opacity 0.15s ease-in',
          }}
          onLoad={handleLoad}
        />
      );
    }

    // Detect if this is a profile photo (from Google Contacts API or explicit alt text)
    // Exclude place photos (/api/v1/connectors/google-places/photo path) - they use proxy endpoint
    const isPlacePhoto = src.includes('/connectors/google-places/photo');
    const isProfilePhoto =
      !isPlacePhoto &&
      (() => {
        try {
          const parsed = new URL(src);
          return GOOGLE_IMAGE_DOMAINS.includes(parsed.hostname);
        } catch {
          return alt?.toLowerCase().includes('photo') ?? false;
        }
      })();

    // Place photo - clickable with lightbox (2x zoom: 200px -> 400px)
    if (isPlacePhoto) {
      return (
        <>
          {/* Real action -> native button around the image (audit F013). */}
          <button
            type="button"
            onClick={() => setIsLightboxOpen(true)}
            aria-label={t('common.expand_image')}
            className="inline-block align-top p-0 border-0 bg-transparent cursor-pointer rounded focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
          >
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img
              src={src}
              alt={alt || 'Photo du lieu'}
              className="place-photo"
              referrerPolicy="no-referrer"
              style={{
                opacity: loaded ? 1 : 0,
                transition: loaded
                  ? 'transform 0.2s ease, box-shadow 0.2s ease'
                  : 'opacity 0.15s ease-in',
              }}
              onLoad={handleLoad}
            />
          </button>
          {typeof document !== 'undefined' &&
            createPortal(
              <ImageLightbox
                src={src}
                alt={alt || 'Photo du lieu'}
                isOpen={isLightboxOpen}
                onClose={() => setIsLightboxOpen(false)}
                minWidth={400}
              />,
              document.body
            )}
        </>
      );
    }

    // Profile photo (Google Contacts) - Single contact detail view
    // Uses contact-photo CSS class for consistent styling with vignette effect
    if (isProfilePhoto) {
      const proxiedSrc = proxyGoogleImageUrl(src) || src;
      return (
        <>
          <span
            style={{
              display: 'block',
            }}
            className="flex justify-center my-4 w-full"
          >
            {/* Real action -> native button around the image (audit F013). */}
            <button
              type="button"
              onClick={() => setIsLightboxOpen(true)}
              aria-label={t('common.expand_image')}
              className="inline-block align-top p-0 border-0 bg-transparent cursor-pointer rounded focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"
            >
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src={proxiedSrc}
                alt={alt || 'Photo de profil'}
                className="contact-photo"
                referrerPolicy="no-referrer"
                style={{
                  opacity: loaded ? 1 : 0,
                }}
                onLoad={handleLoad}
              />
            </button>
          </span>
          {typeof document !== 'undefined' &&
            createPortal(
              <ImageLightbox
                src={proxiedSrc}
                alt={alt || 'Photo de profil'}
                isOpen={isLightboxOpen}
                onClose={() => setIsLightboxOpen(false)}
                minWidth={250}
              />,
              document.body
            )}
        </>
      );
    }

    // Default image rendering for non-profile images (screenshots, diagrams, etc.)
    return (
      <span className="block relative w-full max-w-[150px] my-3 mx-auto">
        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img
          src={src}
          alt={alt || 'Image'}
          className="w-full h-full object-cover rounded-lg shadow-md"
          referrerPolicy="no-referrer"
          style={{
            opacity: loaded ? 1 : 0,
            transition: 'opacity 0.15s ease-in',
          }}
          loading="lazy"
          onLoad={handleLoad}
        />
      </span>
    );
  }
);
MarkdownImage.displayName = 'MarkdownImage';

interface MarkdownContentProps {
  content: string;
  isUser?: boolean;
  className?: string;
  /**
   * History-search term to highlight in the rendered output (QW-2). Matches
   * are accent/case-insensitive and wrapped in fixed-class `<mark>` elements
   * by the post-sanitize `rehype-search-highlight` plugin.
   */
  searchHighlight?: string;
}

/**
 * MarkdownContent component - Memoized to prevent unnecessary re-renders during streaming.
 * Issue #64: Without memo, images would flash on every token because React recreates the DOM.
 * The memo comparison uses default shallow equality which is sufficient since content changes
 * trigger the necessary re-render anyway.
 */
/**
 * Sanitize malformed HTML tags that contain emojis.
 * LLMs sometimes generate tags like `<li📧>` instead of `<li>📧`.
 * This regex fixes common patterns to prevent createElement errors.
 */
function sanitizeMalformedTags(text: string): string {
  // Fix tags with emojis attached: <li📧 -> <li>📧, </li📧> -> </li>
  // Matches: < followed by valid tag name, then emoji(s), then optional attributes/closing
  // Unicode emoji ranges: \u{1F300}-\u{1F9FF} covers most emojis
  return text.replace(
    /<(\/?)([a-zA-Z][a-zA-Z0-9]*)([\u{1F300}-\u{1F9FF}\u{2600}-\u{26FF}\u{2700}-\u{27BF}]+)([^>]*)>/gu,
    (_, slash, tag, emoji, rest) => `<${slash}${tag}${rest}>${emoji}`
  );
}

/** Block-level HTML open tag at the very start — marks an HTML response. */
const HTML_BLOCK_START_RE =
  /^<(?:div|section|article|header|main|aside|nav|figure|details|h[1-6]|p|ul|ol|table|blockquote)\b/i;

/**
 * De-indent the structural lines of an HTML response so CommonMark never
 * mistakes a pretty-printed tag for an indented code block.
 *
 * Measured on prod (2026-07-29): the model intermittently pretty-prints its
 * `<div class="lia-response">` card with 4-space-indented tag lines AND blank
 * lines between blocks. A CommonMark HTML block (type 6) ends at the first
 * blank line; the next 4-space-indented `<h2>` is then read as an INDENTED
 * CODE block, so the rest of the card renders as raw `<h2>…` TEXT. Two
 * consecutive replies proved the asymmetry: identical wrapper, column-0 tags
 * rendered, 4-space-indented tags did not.
 *
 * Stripping the leading indentation of every structural line puts each block
 * tag back at column 0, where it (re)starts an HTML block. Whitespace between
 * block-level tags is insignificant, so this changes PARSING only, never the
 * rendered card. Lines inside <pre>/<code> keep their indentation (there,
 * leading whitespace is meaningful). Scoped to content that STARTS with a
 * block-level HTML tag, so a Markdown answer's legitimate indented code block
 * is never touched.
 */
function stripHtmlBlockIndent(text: string): string {
  if (!HTML_BLOCK_START_RE.test(text.replace(/^[\s﻿]+/, ''))) return text;
  let protectedDepth = 0;
  return text
    .split('\n')
    .map(line => {
      const out = protectedDepth === 0 ? line.replace(/^[ \t]+/, '') : line;
      const opens = (line.match(/<(?:pre|code)\b/gi) ?? []).length;
      const closes = (line.match(/<\/(?:pre|code)>/gi) ?? []).length;
      protectedDepth = Math.max(0, protectedDepth + opens - closes);
      return out;
    })
    .join('\n');
}

// Regions where `$` must be left untouched: fenced code blocks, inline code
// (single/double backtick), and `$$…$$` display math. Escaping `$` inside a
// code span would surface a literal backslash (markdown does not unescape
// inside code), and display math is already handled by remark-math.
const PROTECTED_SPAN_RE =
  /(```[\s\S]*?```|~~~[\s\S]*?~~~|``[\s\S]*?``|`[^`\n]*`|\$\$[\s\S]*?\$\$)/g;

/**
 * Normalize every math notation an LLM emits into remark-math delimiters, so
 * a formula renders regardless of the style the model picked:
 *   - ```` ```math ```` / ```` ```latex ```` fenced block → `$$…$$` (display)
 *   - `\[ … \]` → `$$…$$` (display)
 *   - `\( … \)` → `$…$`  (inline)
 * Without this, a formula the model wrapped in a ```` ```latex ```` block
 * rendered as a literal code block instead of math. `\[`/`\(` conversion
 * skips code spans/blocks (so a regex `\(` in a code sample is preserved);
 * the fenced-block conversion only targets the `math`/`latex` languages, so
 * ```` ```python ```` etc. stay code.
 */
function normalizeMathDelimiters(text: string): string {
  // 1) Fenced ```math / ```latex → $$…$$ (run first: otherwise these blocks
  //    would be treated as protected code spans below).
  let out = text.replace(
    /```(?:math|latex)\b[^\n]*\n([\s\S]*?)```[ \t]*(?=\n|$)/gi,
    (_match, body: string) => `\n$$\n${body.trim()}\n$$\n`
  );

  if (!out.includes('\\[') && !out.includes('\\(')) return out;

  // 2) \[…\] and \(…\) outside code / display-math regions.
  out = out
    .split(PROTECTED_SPAN_RE)
    .map((part, i) => {
      if (i % 2 === 1) return part; // protected span (code or $$…$$)
      return part
        .replace(/\\\[\s*([\s\S]*?)\s*\\\]/g, (_m, b: string) => `$$${b}$$`)
        .replace(/\\\(\s*([\s\S]*?)\s*\\\)/g, (_m, b: string) => `$${b}$`);
    })
    .join('');
  return out;
}

export const MarkdownContent: React.FC<MarkdownContentProps> = memo(
  ({ content, isUser = false, className, searchHighlight }) => {
    const { t } = useTranslation();

    // Search highlight (QW-2): appended LAST so KaTeX output is already in
    // place (the plugin skips it). Memoized on the term — an empty term keeps
    // the exact base pipeline (no per-render plugin churn while streaming).
    const searchTerm = searchHighlight?.trim() ?? '';
    const rehypePlugins = useMemo(() => {
      const base: import('unified').PluggableList = [
        rehypeRaw,
        [rehypeSanitize, markdownSanitizeSchema],
        rehypeMathInText,
        rehypeKatex,
      ];
      if (searchTerm) base.push([rehypeSearchHighlight, { query: searchTerm }]);
      return base;
    }, [searchTerm]);

    // Prod 2026-07-29: de-indent a pretty-printed HTML card BEFORE parsing, so
    // a 4-space-indented block after a blank line is never read as a code block
    // (which rendered the rest of the card as raw <h2>… text). No-op for
    // Markdown answers (they don't start with a block-level HTML tag).
    const dedentedContent = useMemo(() => stripHtmlBlockIndent(content), [content]);

    // Sanitize malformed HTML tags (e.g., <li📧> -> <li>📧)
    const sanitizedContent = useMemo(
      () => sanitizeMalformedTags(dedentedContent),
      [dedentedContent]
    );

    // Canonicalize alternative math notations (```math/```latex fences, \[…\],
    // \(…\)) to `$`/`$$` at the string level. Dollar delimiters are then turned
    // into KaTeX markers at the hast level by rehypeMathInText (below), which
    // — unlike remark-math — also sees math inside the raw HTML the assistant
    // emits. Currency `$` needs no escaping anymore: rehypeMathInText applies
    // MathJax rules and simply leaves non-math `$` as literal text.
    const mathNormalizedContent = useMemo(
      () => normalizeMathDelimiters(sanitizedContent),
      [sanitizedContent]
    );

    // Format phone numbers in content (French: 06.12.34.56.78, others: national format)
    const formattedContent = useMemo(
      () => formatPhonesInText(mathNormalizedContent),
      [mathNormalizedContent]
    );

    return (
      <div className={cn('markdown-content text-[13px] mobile:text-sm leading-relaxed', className)}>
        <ReactMarkdown
          // singleDollarTextMath: false — remark-math never touches single `$`
          // (so currency is never swallowed); all `$…$`/`$$…$$` rendering is
          // owned by rehypeMathInText at the hast level, which — unlike
          // remark-math — also sees math inside the raw HTML the assistant
          // emits. remark-math still handles ```math fences and markdown `$$`.
          remarkPlugins={[remarkGfm, [remarkMath, { singleDollarTextMath: false }]]}
          remarkRehypeOptions={{ allowDangerousHtml: true }}
          // Order matters: rehypeRaw parses embedded HTML, rehypeSanitize is
          // the XSS boundary (schema audited against all legitimate card /
          // rich-HTML markup). rehypeMathInText then converts `$…$`/`$$…$$`
          // found in the (now expanded) HTML text into math markers, and
          // rehypeKatex runs LAST so its generated markup is not stripped while
          // the math nodes it consumes survive sanitization (className allowed
          // globally). Both math steps are sanitize-exempt by design: they only
          // read already-sanitized text and emit fixed-class spans.
          rehypePlugins={rehypePlugins}
          // Custom URL transform to allow tel: and mailto: protocols
          // Default only allows: http, https, irc, ircs, mailto, xmpp
          urlTransform={(url: string) => {
            // Allow tel: protocol for click-to-call
            if (url.startsWith('tel:')) return url;
            // Allow mailto: protocol for email links
            if (url.startsWith('mailto:')) return url;
            // Allow safe protocols
            if (url.startsWith('http://') || url.startsWith('https://')) return url;
            // Allow relative URLs
            if (url.startsWith('/') || url.startsWith('#') || url.startsWith('?')) return url;
            // Block other protocols (javascript:, data:, etc.)
            if (url.includes(':')) return '';
            // Allow protocol-relative URLs
            return url;
          }}
          components={{
            // Headings
            h1: ({ children }) => (
              <h1 className="text-2xl font-bold mt-6 mb-4 first:mt-0 border-b border-border pb-2">
                {children}
              </h1>
            ),
            h2: ({ children }) => (
              <h2 className="text-xl font-semibold mt-5 mb-3 first:mt-0 border-b border-border/50 pb-1.5">
                {children}
              </h2>
            ),
            h3: ({ children }) => (
              <h3 className="text-lg font-semibold mt-4 mb-2 first:mt-0">{children}</h3>
            ),
            h4: ({ children }) => (
              <h4 className="text-base font-semibold mt-3 mb-2 first:mt-0">{children}</h4>
            ),
            h5: ({ children }) => (
              <h5 className="text-sm font-semibold mt-3 mb-1.5 first:mt-0">{children}</h5>
            ),
            h6: ({ children }) => (
              <h6 className="text-sm font-semibold mt-3 mb-1.5 first:mt-0 text-muted-foreground">
                {children}
              </h6>
            ),

            // Paragraphs - preserve LIA component classes
            p: ({ className, children, ...props }) => {
              // LIA components (e.g., lia-email__snippet) need their original class preserved
              const isLiaComponent = className?.startsWith('lia-');
              return (
                <p
                  className={
                    isLiaComponent
                      ? className
                      : cn('mb-3 last:mb-0 whitespace-pre-wrap break-words', className)
                  }
                  {...props}
                >
                  {children}
                </p>
              );
            },

            // Strong (bold)
            strong: ({ children }) => (
              <strong className="font-semibold text-foreground">{children}</strong>
            ),

            // Emphasis (italic)
            em: ({ children }) => <em className="italic text-foreground">{children}</em>,

            // Links
            a: ({ href, className, children, ...props }) => {
              // LIA components (e.g., lia-event__title) need their original class preserved
              const isLiaComponent = className?.startsWith('lia-');

              // tel: and mailto: links should NOT open in new tab (breaks native handlers)
              const isProtocolLink = href?.startsWith('tel:') || href?.startsWith('mailto:');

              return (
                <a
                  href={href}
                  // Only external links open in new tab - tel:/mailto: use native handlers
                  {...(!isProtocolLink && { target: '_blank', rel: 'noopener noreferrer' })}
                  className={
                    isLiaComponent
                      ? className
                      : cn(
                          'underline decoration-primary/40 hover:decoration-primary transition-colors',
                          isUser
                            ? 'text-primary-foreground hover:text-primary-foreground/90'
                            : 'text-primary hover:text-primary/90'
                        )
                  }
                  {...props}
                >
                  {children}
                </a>
              );
            },

            // Unordered lists - balanced spacing between items
            ul: ({ children }) => (
              <ul className="list-disc list-outside pl-5 mb-2 space-y-1.5 last:mb-0">{children}</ul>
            ),

            // Ordered lists - generous spacing (numbered items often contain rich content)
            ol: ({ children }) => (
              <ol className="list-decimal list-outside pl-5 mb-2 space-y-3 last:mb-0">
                {children}
              </ol>
            ),

            // List items - normal leading for readability
            li: ({ children }) => <li className="pl-1 leading-normal">{children}</li>,

            // Blockquotes
            blockquote: ({ children }) => (
              <blockquote
                className={cn(
                  'border-l-4 pl-4 py-2 my-3 italic',
                  isUser
                    ? 'border-primary-foreground/30 bg-primary-foreground/5'
                    : 'border-primary/40 bg-muted/30'
                )}
              >
                {children}
              </blockquote>
            ),

            // Inline code and code blocks
            code: ({ className: codeClassName, children, ...props }) => {
              // Check if it's a code block (has className with language-*)
              const isCodeBlock = codeClassName?.startsWith('language-');

              if (isCodeBlock) {
                const language = codeClassName?.replace('language-', '') || 'text';
                const codeText = String(children).replace(/\n$/, '');

                // Suspense fallback matches the old plain <pre> look so the
                // visual transition on lazy-load is imperceptible.
                const fallback = (
                  <div className="my-3 rounded-lg overflow-hidden border border-border/50 shadow-sm">
                    <div className="px-3 py-1 text-xs font-mono bg-muted/50 text-muted-foreground border-b border-border/50">
                      {language}
                    </div>
                    <pre className="p-3 overflow-x-auto bg-muted/20">
                      <code className="text-sm font-mono text-foreground block">{codeText}</code>
                    </pre>
                  </div>
                );

                return (
                  <Suspense fallback={fallback}>
                    <CodeBlock language={language}>{codeText}</CodeBlock>
                  </Suspense>
                );
              }

              // Inline code
              return (
                <code
                  className={cn(
                    'px-1.5 py-0.5 rounded text-xs font-mono',
                    isUser
                      ? 'bg-primary-foreground/20 text-primary-foreground'
                      : 'bg-muted text-foreground'
                  )}
                  {...props}
                >
                  {children}
                </code>
              );
            },

            // Horizontal rule
            hr: () => <hr className="my-4 border-t border-border/50" />,

            // Tables - responsive with scroll indicator on mobile
            table: ({ children }) => (
              <div className="table-wrapper my-3 overflow-x-auto rounded-lg border border-border/50 shadow-sm">
                <table className="divide-y divide-border/50">{children}</table>
              </div>
            ),
            thead: ({ children }) => <thead className="bg-muted/30">{children}</thead>,
            tbody: ({ children }) => (
              <tbody className="divide-y divide-border/30 bg-card/30">{children}</tbody>
            ),
            tr: ({ children }) => (
              <tr className="hover:bg-muted/20 transition-colors">{children}</tr>
            ),
            th: ({ children }) => (
              <th className="px-4 py-2 text-left font-semibold uppercase tracking-wider text-foreground">
                {children}
              </th>
            ),
            td: ({ children }) => <td className="px-3 py-2 text-foreground sm:px-4">{children}</td>,

            // Task lists (GFM extension)
            input: ({ checked, ...props }) => (
              <input
                type="checkbox"
                checked={checked}
                disabled
                className="mr-2 align-middle accent-primary cursor-default"
                {...props}
              />
            ),

            // Images - using separate component to comply with React hooks rules
            img: MarkdownImage,

            // Divs - intercept photo galleries and MCP Apps for enhanced interactivity
            div: ({ className, children, ...props }) => {
              // Live reasoning block (💭) — emitted by the SSE reasoning handler
              // as <div class="lia-reasoning">. Wrap in a fixed-height, auto-
              // scrolling container so the streamed thoughts scroll smoothly
              // (no jump) instead of pushing the page.
              if (className?.includes('lia-reasoning')) {
                return <ReasoningScroll>{children}</ReasoningScroll>;
              }

              // MCP App widget (generated by mcp_app_sentinel.py)
              // Replaces sentinel div with interactive sandboxed iframe + JSON-RPC bridge
              if (className?.includes('lia-mcp-app')) {
                const registryId = (props as Record<string, unknown>)['data-registry-id'] as
                  | string
                  | undefined;
                if (registryId) {
                  return (
                    <Suspense
                      fallback={
                        <div className="lia-mcp-app__placeholder">
                          <div className="lia-mcp-app__loading">{t('mcp_apps.loading')}</div>
                        </div>
                      }
                    >
                      <McpAppWidget registryId={registryId} />
                    </Suspense>
                  );
                }
              }

              // Skill App widget (generated by skill_app_sentinel.py)
              // Replaces sentinel div with iframe (frame.html/url) and/or image card
              if (className?.includes('lia-skill-app')) {
                const registryId = (props as Record<string, unknown>)['data-registry-id'] as
                  | string
                  | undefined;
                if (registryId) {
                  return (
                    <Suspense
                      fallback={
                        <div className="lia-skill-app__placeholder">
                          <div className="lia-skill-app__loading">
                            {t('skill_apps.loading', { defaultValue: 'Loading skill…' })}
                          </div>
                        </div>
                      }
                    >
                      <SkillAppWidget registryId={registryId} />
                    </Suspense>
                  );
                }
              }

              // Place photo gallery (generated by place_card.py)
              // Uses PlacePhotoWrapper for multi-image gallery lightbox
              if (className?.includes('lia-place__photo')) {
                return <PlacePhotoWrapper {...props}>{children}</PlacePhotoWrapper>;
              }

              // Contact photo gallery (generated by response_node.py)
              // Also handle corrupted class names (LLM sometimes adds spaces: "contact - photos - gallery")
              const isContactPhotoGallery =
                className?.includes('contact-photos-gallery') ||
                className?.replace(/\s+/g, '').includes('contact-photos-gallery');

              if (isContactPhotoGallery) {
                return <ContactPhotoGallery>{children}</ContactPhotoGallery>;
              }

              // Default div rendering
              return (
                <div className={className} {...props}>
                  {children}
                </div>
              );
            },
          }}
        >
          {formattedContent}
        </ReactMarkdown>
      </div>
    );
  }
);
MarkdownContent.displayName = 'MarkdownContent';
