"""
Base types for Proactive Task Infrastructure.

Defines the core Protocol and data structures used by all proactive tasks.

Types:
    - ProactiveTask: Protocol that all proactive tasks must implement
    - ProactiveTaskResult: Result of content generation with token tracking
    - ContentSource: Enum of available content sources
"""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any, Protocol
from uuid import UUID


class ContentSource(str, Enum):
    """Available content sources for proactive notifications."""

    WIKIPEDIA = "wikipedia"
    PERPLEXITY = "perplexity"
    LLM_REFLECTION = "llm_reflection"
    CALENDAR = "calendar"
    MEMORY = "memory"
    HEARTBEAT = "heartbeat"
    CUSTOM = "custom"


@dataclass
class ProactiveTaskResult:
    """
    Result of a proactive task content generation.

    Contains the generated content, source information, and token usage
    for cost tracking.

    Attributes:
        success: Whether content generation succeeded
        content: Generated message content (None if failed)
        source: Content source used (wikipedia, perplexity, llm, etc.)
        tokens_in: Input tokens consumed by LLM calls
        tokens_out: Output tokens generated by LLM calls
        tokens_cache: Cached tokens used (for cost calculation)
        model_name: LLM model used for generation
        metadata: Additional metadata (citations, article_url, etc.)
        error: Error message if generation failed
        target_id: ID of the target (interest_id, event_id, etc.) for tracking

    Example:
        >>> result = ProactiveTaskResult(
        ...     success=True,
        ...     content="Did you know that...",
        ...     source=ContentSource.WIKIPEDIA,
        ...     tokens_in=500,
        ...     tokens_out=150,
        ...     model_name="gpt-4.1-mini",
        ...     metadata={"article_url": "https://..."},
        ... )
    """

    success: bool
    content: str | None = None
    source: ContentSource | str | None = None
    tokens_in: int = 0
    tokens_out: int = 0
    tokens_cache: int = 0
    model_name: str | None = None
    metadata: dict[str, Any] = field(default_factory=dict)
    error: str | None = None
    target_id: str | None = None

    @property
    def total_tokens(self) -> int:
        """Total tokens consumed (input + output)."""
        return self.tokens_in + self.tokens_out

    @property
    def source_name(self) -> str:
        """Get source name as string."""
        if isinstance(self.source, ContentSource):
            return self.source.value
        return str(self.source) if self.source else "unknown"

    def add_tokens(self, tokens_in: int, tokens_out: int, tokens_cache: int = 0) -> None:
        """
        Add token usage from an additional LLM call.

        Useful when multiple LLM calls are made during content generation
        (e.g., fetch from source + presentation formatting).

        Args:
            tokens_in: Input tokens from this call
            tokens_out: Output tokens from this call
            tokens_cache: Cached tokens from this call
        """
        self.tokens_in += tokens_in
        self.tokens_out += tokens_out
        self.tokens_cache += tokens_cache

    @classmethod
    def failure(
        cls, error: str, source: ContentSource | str | None = None
    ) -> "ProactiveTaskResult":
        """
        Create a failure result.

        Args:
            error: Error message describing the failure
            source: Source that failed (optional)

        Returns:
            ProactiveTaskResult with success=False
        """
        return cls(success=False, error=error, source=source)


class ProactiveTask(Protocol):
    """
    Protocol for all proactive tasks.

    Implement this protocol to create a new proactive task type.
    The ProactiveTaskRunner will orchestrate execution using these methods.

    Attributes:
        task_type: Unique identifier for this task type (e.g., "interest", "birthday")

    Methods:
        check_eligibility: Check if user is eligible for this task now
        select_target: Select the target for notification (interest, event, etc.)
        generate_content: Generate the notification content
        on_feedback: Handle user feedback on the notification

    Example:
        >>> class InterestProactiveTask:
        ...     task_type = "interest"
        ...
        ...     async def check_eligibility(self, user_id, settings, now):
        ...         return settings.get("interests_enabled", False)
        ...
        ...     async def select_target(self, user_id):
        ...         # Return top interest or None
        ...         return await get_top_interest(user_id)
        ...
        ...     async def generate_content(self, user_id, target, language):
        ...         # Generate interesting content about the interest
        ...         return ProactiveTaskResult(success=True, content="...")
        ...
        ...     async def on_feedback(self, user_id, target, feedback):
        ...         # Update interest weight based on feedback
        ...         await update_interest_weight(target.id, feedback)
    """

    task_type: str

    async def check_eligibility(
        self,
        user_id: UUID,
        user_settings: dict[str, Any],
        now: datetime,
    ) -> bool:
        """
        Check if user is eligible for this proactive task.

        Called before select_target to perform task-specific eligibility checks.
        Common checks (timezone, quota, cooldown) are handled by EligibilityChecker.

        Args:
            user_id: User UUID
            user_settings: User settings dict (from User model)
            now: Current datetime in user's timezone

        Returns:
            True if user is eligible for this task, False otherwise

        Note:
            This is for TASK-SPECIFIC checks only. Common checks like:
            - Feature enabled
            - Time window
            - Daily quota
            - Global cooldown
            - Activity cooldown
            Are handled by EligibilityChecker before this method is called.
        """
        ...

    async def select_target(
        self,
        user_id: UUID,
    ) -> Any | None:
        """
        Select the target for notification.

        The target is the specific item to notify about (interest, event, etc.).
        Return None if no suitable target is available.

        Args:
            user_id: User UUID

        Returns:
            The selected target (e.g., UserInterest, CalendarEvent) or None

        Example targets:
            - InterestTask: UserInterest with highest weight not in cooldown
            - BirthdayTask: Contact with birthday today
            - EventTask: Upcoming calendar event
        """
        ...

    async def generate_content(
        self,
        user_id: UUID,
        target: Any,
        user_language: str,
    ) -> ProactiveTaskResult:
        """
        Generate notification content for the target.

        This is where the actual content generation happens:
        - Fetch data from sources (Wikipedia, Perplexity, etc.)
        - Format content for presentation
        - Track token usage

        Args:
            user_id: User UUID
            target: The target selected by select_target()
            user_language: User's preferred language (e.g., "fr", "en")

        Returns:
            ProactiveTaskResult with generated content and token usage

        Note:
            - Include ALL token usage in the result (source fetch + formatting)
            - Set target_id in result for tracking
            - Return failure result if generation fails
        """
        ...

    async def on_feedback(
        self,
        user_id: UUID,
        target: Any,
        feedback: str,
    ) -> None:
        """
        Handle user feedback on the notification.

        Called when user provides feedback (thumbs up/down, block).
        Update the target accordingly.

        Args:
            user_id: User UUID
            target: The target that received feedback
            feedback: Feedback type ("thumbs_up", "thumbs_down", "block")

        Feedback meanings:
            - thumbs_up: User found this useful, increase weight/priority
            - thumbs_down: User didn't find this useful, decrease weight
            - block: User never wants notifications about this target
        """
        ...

    async def on_notification_sent(
        self,
        user_id: UUID,
        target: Any,
        result: ProactiveTaskResult,
    ) -> None:
        """
        Called after notification is successfully sent.

        Optional hook for post-notification tasks like:
        - Update last_notified_at on target
        - Record notification in history
        - Update statistics

        Args:
            user_id: User UUID
            target: The target that was notified
            result: The result of content generation

        Note:
            Default implementation does nothing. Override if needed.
        """
        ...
