/**
 * The icons the living maps' DATA names, resolved to Lucide components.
 *
 * `src/data/maps/*.json` names icons in Lucide's own kebab-case vocabulary (the
 * French documents of `docs/maps` vendor the same geometry). The registry is
 * explicit rather than a dynamic import, so the pages render their icons on the
 * server and ship exactly the ones they draw. `__tests__/map-icons.test.ts`
 * fails when the data names an icon the registry lacks — an unknown name would
 * otherwise render nothing, in silence.
 */

import {
  Activity,
  AlarmClock,
  AppWindow,
  AudioLines,
  BadgeCheck,
  Bell,
  BellRing,
  Blocks,
  BookOpen,
  BookUser,
  Bookmark,
  Bot,
  Boxes,
  Braces,
  Brain,
  Cable,
  Calendar,
  CalendarClock,
  CalendarSync,
  ChartLine,
  ChartNoAxesCombined,
  CircleDashed,
  Clock,
  Cog,
  Coins,
  Compass,
  Contact,
  Container,
  Cpu,
  Database,
  FileLock,
  FileText,
  FlaskConical,
  FolderTree,
  Gauge,
  GitBranch,
  Globe,
  Handshake,
  HardDrive,
  HeartPulse,
  History as HistoryIcon,
  Image as ImageIcon,
  Kanban,
  KeyRound,
  Languages,
  Layers,
  Library,
  Link2,
  ListChecks,
  ListRestart,
  ListTodo,
  LockKeyhole,
  Logs,
  Mail,
  MapPin,
  MessageSquare,
  MessagesSquare,
  Mic,
  MicVocal,
  Monitor,
  MonitorSmartphone,
  NotebookPen,
  Package,
  Palette,
  Phone,
  Plug,
  PlugZap,
  Power,
  Puzzle,
  Radio,
  Repeat,
  Rocket,
  ScanSearch,
  Scroll,
  ScrollText,
  Send,
  Server,
  Shield,
  ShieldCheck,
  Siren,
  SlidersHorizontal,
  Smartphone,
  Smile,
  Sparkles,
  SquareTerminal,
  Stethoscope,
  Sunrise,
  Telescope,
  Timer,
  UserCheck,
  VenetianMask,
  Waypoints,
  Workflow,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react';

import { cn } from '@/lib/utils';

export const MAP_ICONS: Readonly<Record<string, LucideIcon>> = {
  activity: Activity,
  'alarm-clock': AlarmClock,
  'app-window': AppWindow,
  'audio-lines': AudioLines,
  'badge-check': BadgeCheck,
  bell: Bell,
  'bell-ring': BellRing,
  blocks: Blocks,
  'book-open': BookOpen,
  'book-user': BookUser,
  bookmark: Bookmark,
  bot: Bot,
  boxes: Boxes,
  braces: Braces,
  brain: Brain,
  cable: Cable,
  calendar: Calendar,
  'calendar-clock': CalendarClock,
  'calendar-sync': CalendarSync,
  'chart-line': ChartLine,
  'chart-no-axes-combined': ChartNoAxesCombined,
  'circle-dashed': CircleDashed,
  clock: Clock,
  cog: Cog,
  coins: Coins,
  compass: Compass,
  contact: Contact,
  container: Container,
  cpu: Cpu,
  database: Database,
  'file-lock': FileLock,
  'file-text': FileText,
  'flask-conical': FlaskConical,
  'folder-tree': FolderTree,
  gauge: Gauge,
  'git-branch': GitBranch,
  globe: Globe,
  handshake: Handshake,
  'hard-drive': HardDrive,
  'heart-pulse': HeartPulse,
  history: HistoryIcon,
  image: ImageIcon,
  kanban: Kanban,
  'key-round': KeyRound,
  languages: Languages,
  layers: Layers,
  library: Library,
  'link-2': Link2,
  'list-checks': ListChecks,
  'list-restart': ListRestart,
  'list-todo': ListTodo,
  'lock-keyhole': LockKeyhole,
  logs: Logs,
  mail: Mail,
  'map-pin': MapPin,
  'message-square': MessageSquare,
  'messages-square': MessagesSquare,
  mic: Mic,
  'mic-vocal': MicVocal,
  monitor: Monitor,
  'monitor-smartphone': MonitorSmartphone,
  'notebook-pen': NotebookPen,
  package: Package,
  palette: Palette,
  phone: Phone,
  plug: Plug,
  'plug-zap': PlugZap,
  power: Power,
  puzzle: Puzzle,
  radio: Radio,
  repeat: Repeat,
  rocket: Rocket,
  'scan-search': ScanSearch,
  scroll: Scroll,
  'scroll-text': ScrollText,
  send: Send,
  server: Server,
  shield: Shield,
  'shield-check': ShieldCheck,
  siren: Siren,
  'sliders-horizontal': SlidersHorizontal,
  smartphone: Smartphone,
  smile: Smile,
  sparkles: Sparkles,
  'square-terminal': SquareTerminal,
  stethoscope: Stethoscope,
  sunrise: Sunrise,
  telescope: Telescope,
  timer: Timer,
  'user-check': UserCheck,
  'venetian-mask': VenetianMask,
  waypoints: Waypoints,
  workflow: Workflow,
  wrench: Wrench,
  zap: Zap,
};

/** An icon the map data names — decorative: the text beside it carries the meaning. */
export function MapIcon({
  name,
  size = 18,
  className,
}: {
  name: string;
  size?: number;
  className?: string;
}) {
  const Icon = MAP_ICONS[name];
  if (!Icon) return null;
  return <Icon aria-hidden="true" width={size} height={size} className={cn('lm-ic', className)} />;
}
