"""Content-provenance trust classification for registry item types.

Registry payloads reach the LLM through two distinct surfaces:

- **pipeline** — ``formatters/text_summary.generate_data_for_filtering`` feeds
  the ``{data_for_filtering}`` block of the response prompt;
- **ReAct** — ``tools/react_tool_wrapper.ReactToolWrapper._process_result``
  feeds the ``Data:`` section of every ``ToolMessage``.

Some of those payloads carry free text **written by a third party**: an email
body, the description of a calendar invitation authored by its organiser, a
fetched web page, a Google Places editorial summary, an MCP server result.
That text must reach the model tagged as *data to analyse*, never as
*instructions to follow*.

Why classify the DATA and not the producing tool
------------------------------------------------
A tool-name allowlist rots: every new tool that surfaces third-party text has
to remember to opt in, and four already had not (``brave``, ``perplexity``,
``emails``, MCP). The registry type travels **with** the payload, so a new tool
emitting an ``EMAIL`` item is protected without touching this module — and a
new :class:`RegistryItemType` without a classification refuses to boot
(ADR-085 completeness doctrine, same pattern as
``drafts/display.assert_registry_completeness``).

Classification rule
-------------------
A type is :data:`ContentTrust.EXTERNAL` when its payload **can** contain free
text authored by someone other than the user or LIA. Ambiguity resolves to
EXTERNAL: the cost of a wrong EXTERNAL is a few tokens, the cost of a wrong
INTERNAL is an unmarked injection vector.
"""

from __future__ import annotations

from enum import StrEnum

from src.domains.agents.data_registry.models import RegistryItemType


class ContentTrust(StrEnum):
    """Provenance of the free text a registry payload can carry.

    This is an **integrity** axis (who wrote the text), orthogonal to the
    ``data_classification`` of :class:`~src.domains.agents.registry.catalogue.PermissionProfile`,
    which is a **confidentiality** axis (who may read it). A payload can be
    INTERNAL yet SENSITIVE (a user reminder), or EXTERNAL yet PUBLIC (a
    Wikipedia article).
    """

    INTERNAL = "internal"
    """Authored by the user, by LIA, or machine-generated by a trusted API."""

    EXTERNAL = "external"
    """Can contain free text authored by an untrusted third party."""


# One entry per RegistryItemType. assert_trust_registry_completeness() enforces
# exhaustivity at boot AND in CI. Each EXTERNAL entry names the attacker-writable
# field(s) so the classification can be re-argued rather than trusted blindly.
TRUST_BY_REGISTRY_TYPE: dict[RegistryItemType, ContentTrust] = {
    # --- Google Workspace / connectors ------------------------------------
    # body + subject + sender display name are authored by whoever wrote to
    # the user. Highest-volume injection vector: anybody can email anybody.
    RegistryItemType.EMAIL: ContentTrust.EXTERNAL,
    # summary / description / location of an invitation are authored by the
    # ORGANISER, not by the user. Second-highest vector: an attacker only
    # needs the user's address to place text in their calendar.
    RegistryItemType.EVENT: ContentTrust.EXTERNAL,
    # notes / organisation / custom fields arrive from directory sync.
    RegistryItemType.CONTACT: ContentTrust.EXTERNAL,
    # a subscribed or shared calendar carries its owner's name/description.
    RegistryItemType.CALENDAR: ContentTrust.EXTERNAL,
    # shared task lists (Microsoft To Do) carry other people's titles/notes.
    RegistryItemType.TASK: ContentTrust.EXTERNAL,
    # a Drive file shared with the user carries the sharer's name and snippet.
    RegistryItemType.FILE: ContentTrust.EXTERNAL,
    # --- External APIs -----------------------------------------------------
    # Google Places returns editorial summaries and user reviews.
    RegistryItemType.PLACE: ContentTrust.EXTERNAL,
    RegistryItemType.WIKIPEDIA_ARTICLE: ContentTrust.EXTERNAL,
    RegistryItemType.SEARCH_RESULT: ContentTrust.EXTERNAL,
    RegistryItemType.WEB_SEARCH: ContentTrust.EXTERNAL,
    RegistryItemType.WEB_PAGE: ContentTrust.EXTERNAL,
    # accessibility tree of an arbitrary page the agent navigated to.
    RegistryItemType.BROWSER_PAGE: ContentTrust.EXTERNAL,
    # third-party MCP servers: LIA does not control what they return.
    RegistryItemType.MCP_RESULT: ContentTrust.EXTERNAL,
    RegistryItemType.MCP_APP: ContentTrust.EXTERNAL,
    # skills are importable from an arbitrary URL, so their rich output is
    # third-party authored even though the execution is local.
    RegistryItemType.SKILL_APP: ContentTrust.EXTERNAL,
    # --- Machine-generated or user/LIA-authored ---------------------------
    # reverse geocoding, forecast, computed itinerary: no free-text author.
    RegistryItemType.LOCATION: ContentTrust.INTERNAL,
    RegistryItemType.WEATHER: ContentTrust.INTERNAL,
    RegistryItemType.ROUTE: ContentTrust.INTERNAL,
    # device names come from the user's own Hue bridge.
    RegistryItemType.HUE_LIGHT: ContentTrust.INTERNAL,
    # produced by LIA itself and confirmed by the user before execution.
    RegistryItemType.DRAFT: ContentTrust.INTERNAL,
    RegistryItemType.CHART: ContentTrust.INTERNAL,
    # authored by the user.
    RegistryItemType.REMINDER: ContentTrust.INTERNAL,
    RegistryItemType.NOTE: ContentTrust.INTERNAL,
    # computed free/busy slot, no text.
    RegistryItemType.CALENDAR_SLOT: ContentTrust.INTERNAL,
}


def is_external(item_type: RegistryItemType | str | None) -> bool:
    """Return True when a registry type can carry third-party free text.

    Unknown or missing types are treated as EXTERNAL (fail-closed): a payload
    whose provenance cannot be established must not reach the model unmarked.
    The boot-time assert makes that path unreachable for declared types, so
    fail-closed here only ever covers malformed checkpoint data.

    Args:
        item_type: A :class:`RegistryItemType`, its raw string value, or None.

    Returns:
        True if the payload must be marked as untrusted for the LLM.
    """
    if item_type is None:
        return True
    if isinstance(item_type, RegistryItemType):
        return TRUST_BY_REGISTRY_TYPE.get(item_type, ContentTrust.EXTERNAL) is ContentTrust.EXTERNAL
    try:
        resolved = RegistryItemType(str(item_type))
    except ValueError:
        return True
    return TRUST_BY_REGISTRY_TYPE.get(resolved, ContentTrust.EXTERNAL) is ContentTrust.EXTERNAL


def assert_trust_registry_completeness() -> None:
    """Assert every ``RegistryItemType`` value has a trust classification.

    Called from ``run_failfast_validations`` (startup) so a missing entry
    refuses to boot the application, and from a unit test so CI catches it
    before merge.

    Raises:
        AssertionError: If any ``RegistryItemType`` value is missing from
            :data:`TRUST_BY_REGISTRY_TYPE`, listing the missing types.
    """
    missing = {t for t in RegistryItemType if t not in TRUST_BY_REGISTRY_TYPE}
    if missing:
        names = ", ".join(sorted(t.value for t in missing))
        raise AssertionError(
            f"TRUST_BY_REGISTRY_TYPE is missing {len(missing)} RegistryItemType(s): "
            f"{names}. Every registry type must declare whether its payload can "
            "carry third-party free text — see "
            "src/domains/agents/data_registry/trust.py."
        )


__all__ = [
    "ContentTrust",
    "TRUST_BY_REGISTRY_TYPE",
    "assert_trust_registry_completeness",
    "is_external",
]
