"""
Repository for Interests domain database operations.

Provides optimized queries for:
- Interest CRUD operations
- Weight calculations
- Notification tracking
- Deduplication checks
"""

from datetime import UTC, datetime, timedelta, timezone
from uuid import UUID
from zoneinfo import ZoneInfo

from sqlalchemy import and_, delete, func, select, update
from sqlalchemy.ext.asyncio import AsyncSession

from src.core.config import settings
from src.core.constants import (
    INTEREST_ACTIVE_LIST_LIMIT,
    INTEREST_CONTENT_LOOKBACK_DAYS,
    INTEREST_USER_LIST_LIMIT,
)
from src.domains.interests.models import (
    InterestNotification,
    InterestStatus,
    UserInterest,
)
from src.infrastructure.observability.logging import get_logger

logger = get_logger(__name__)


class InterestRepository:
    """
    Repository for UserInterest database operations.

    Provides CRUD operations and specialized queries for:
    - Interest retrieval with computed weights
    - Deduplication via embedding similarity
    - Status transitions and updates
    """

    def __init__(self, db: AsyncSession):
        """Initialize repository with database session."""
        self.db = db

    # =========================================================================
    # CRUD Operations
    # =========================================================================

    async def create(
        self,
        user_id: UUID,
        topic: str,
        category: str,
        embedding: list[float] | None = None,
    ) -> UserInterest:
        """
        Create a new interest for a user.

        Args:
            user_id: User UUID
            topic: Interest topic
            category: Interest category
            embedding: Optional embedding for deduplication

        Returns:
            Created UserInterest instance
        """
        interest = UserInterest(
            user_id=user_id,
            topic=topic,
            category=category,
            positive_signals=1,
            negative_signals=0,
            status=InterestStatus.ACTIVE.value,
            last_mentioned_at=datetime.now(UTC),
            embedding=embedding,
        )
        self.db.add(interest)
        await self.db.flush()

        logger.info(
            "interest_created",
            user_id=str(user_id),
            interest_id=str(interest.id),
            topic=topic[:50],
            category=category,
        )

        return interest

    async def get_by_id(self, interest_id: UUID) -> UserInterest | None:
        """Get interest by ID."""
        result = await self.db.execute(select(UserInterest).where(UserInterest.id == interest_id))
        return result.scalar_one_or_none()

    async def get_by_user_and_topic(self, user_id: UUID, topic: str) -> UserInterest | None:
        """Get interest by user and exact topic match."""
        result = await self.db.execute(
            select(UserInterest).where(
                and_(
                    UserInterest.user_id == user_id,
                    UserInterest.topic == topic,
                )
            )
        )
        return result.scalar_one_or_none()

    async def get_by_user_topic_category(
        self, user_id: UUID, topic: str, category: str
    ) -> UserInterest | None:
        """
        Get interest by user, topic, and category.

        Used for uniqueness check when updating interests.
        Same topic can exist in different categories.

        Args:
            user_id: User UUID
            topic: Interest topic
            category: Interest category

        Returns:
            UserInterest if found, None otherwise
        """
        result = await self.db.execute(
            select(UserInterest).where(
                and_(
                    UserInterest.user_id == user_id,
                    UserInterest.topic == topic,
                    UserInterest.category == category,
                )
            )
        )
        return result.scalar_one_or_none()

    async def update(
        self,
        interest: UserInterest,
        topic: str | None = None,
        category: str | None = None,
        positive_signals: int | None = None,
        negative_signals: int | None = None,
        embedding: list[float] | None = None,
    ) -> UserInterest:
        """
        Update an existing interest.

        Only updates fields that are not None.
        Embedding should be regenerated by caller if topic changes.

        Args:
            interest: UserInterest to update
            topic: New topic (triggers embedding regeneration)
            category: New category
            positive_signals: New positive signals count
            negative_signals: New negative signals count
            embedding: New embedding (if topic changed)

        Returns:
            Updated UserInterest instance
        """
        if topic is not None:
            interest.topic = topic
        if category is not None:
            interest.category = category
        if positive_signals is not None:
            interest.positive_signals = positive_signals
        if negative_signals is not None:
            interest.negative_signals = negative_signals
        if embedding is not None:
            interest.embedding = embedding

        await self.db.flush()

        logger.info(
            "interest_updated",
            interest_id=str(interest.id),
            user_id=str(interest.user_id),
        )

        return interest

    async def get_all_for_user(
        self,
        user_id: UUID,
        status: str | None = None,
        limit: int = INTEREST_USER_LIST_LIMIT,
    ) -> list[UserInterest]:
        """
        Get all interests for a user.

        Args:
            user_id: User UUID
            status: Optional filter by status
            limit: Maximum results

        Returns:
            List of UserInterest ordered by weight (computed)
        """
        query = select(UserInterest).where(UserInterest.user_id == user_id)

        if status:
            query = query.where(UserInterest.status == status)

        query = query.limit(limit)
        result = await self.db.execute(query)
        return list(result.scalars().all())

    async def get_active_for_user(
        self,
        user_id: UUID,
        limit: int = INTEREST_ACTIVE_LIST_LIMIT,
    ) -> list[UserInterest]:
        """Get active interests for a user."""
        return await self.get_all_for_user(
            user_id=user_id,
            status=InterestStatus.ACTIVE.value,
            limit=limit,
        )

    async def delete(self, interest: UserInterest) -> None:
        """Delete an interest."""
        await self.db.delete(interest)

        logger.info(
            "interest_deleted",
            interest_id=str(interest.id),
            user_id=str(interest.user_id),
            topic=interest.topic[:50],
        )

    # =========================================================================
    # Weight Calculations
    # =========================================================================

    def calculate_weight(self, interest: UserInterest) -> float:
        """
        Calculate Bayesian confidence weight.

        Uses Beta distribution with configurable prior (default 2, 1) for optimistic start.
        Prior values are configurable via INTEREST_PRIOR_ALPHA and INTEREST_PRIOR_BETA
        environment variables.

        Args:
            interest: UserInterest instance

        Returns:
            Weight between 0.0 and 1.0
        """
        alpha = settings.interest_prior_alpha + interest.positive_signals
        beta = settings.interest_prior_beta + interest.negative_signals
        return alpha / (alpha + beta)

    def calculate_effective_weight(
        self,
        interest: UserInterest,
        decay_rate_per_day: float = 0.01,
        now: datetime | None = None,
    ) -> float:
        """
        Calculate effective weight with temporal decay.

        Args:
            interest: UserInterest instance
            decay_rate_per_day: Decay rate per day (default 1%)
            now: Current datetime (defaults to UTC now)

        Returns:
            Effective weight with decay applied
        """
        now = now or datetime.now(UTC)
        base_weight = self.calculate_weight(interest)

        # Calculate days since last mention
        days_since = (now - interest.last_mentioned_at).days
        decay = max(0.1, 1.0 - (days_since * decay_rate_per_day))

        return base_weight * decay

    async def get_top_weighted_interests(
        self,
        user_id: UUID,
        top_percent: float = 0.2,
        min_count: int = 1,
        exclude_in_cooldown: bool = True,
        cooldown_hours: int = 24,
        now: datetime | None = None,
    ) -> list[tuple[UserInterest, float]]:
        """
        Get top N% weighted interests for notification selection.

        Args:
            user_id: User UUID
            top_percent: Top percentage to select (default 20%)
            min_count: Minimum interests to return
            exclude_in_cooldown: Exclude recently notified
            cooldown_hours: Cooldown period in hours
            now: Current datetime

        Returns:
            List of (interest, effective_weight) tuples sorted by weight
        """
        now = now or datetime.now(UTC)

        # Get all active interests
        interests = await self.get_active_for_user(user_id)

        if not interests:
            return []

        # Calculate effective weights
        weighted = []
        cooldown_threshold = now - timedelta(hours=cooldown_hours)

        for interest in interests:
            # Skip if in cooldown
            if exclude_in_cooldown and interest.last_notified_at:
                if interest.last_notified_at > cooldown_threshold:
                    continue

            weight = self.calculate_effective_weight(interest, now=now)
            weighted.append((interest, weight))

        # Sort by weight descending
        weighted.sort(key=lambda x: x[1], reverse=True)

        # Select top N%
        count = max(min_count, int(len(weighted) * top_percent))
        return weighted[:count]

    # =========================================================================
    # Signal Updates
    # =========================================================================

    async def consolidate_on_mention(
        self,
        interest: UserInterest,
        now: datetime | None = None,
    ) -> None:
        """
        Consolidate interest on user mention.

        Increments positive_signals and updates last_mentioned_at.
        """
        now = now or datetime.now(UTC)
        interest.positive_signals += 1
        interest.last_mentioned_at = now

        # Reset dormant status if was dormant
        if interest.status == InterestStatus.DORMANT.value:
            interest.status = InterestStatus.ACTIVE.value
            interest.dormant_since = None

        logger.debug(
            "interest_consolidated",
            interest_id=str(interest.id),
            positive_signals=interest.positive_signals,
        )

    async def apply_feedback(
        self,
        interest: UserInterest,
        feedback: str,
    ) -> None:
        """
        Apply user feedback to interest.

        Args:
            interest: UserInterest instance
            feedback: "thumbs_up", "thumbs_down", or "block"
        """
        if feedback == "thumbs_up":
            interest.positive_signals += 2
        elif feedback == "thumbs_down":
            interest.negative_signals += 2
        elif feedback == "block":
            interest.status = InterestStatus.BLOCKED.value

        logger.info(
            "interest_feedback_applied",
            interest_id=str(interest.id),
            feedback=feedback,
            new_status=interest.status,
        )

    async def mark_notified(
        self,
        interest: UserInterest,
        now: datetime | None = None,
    ) -> None:
        """Mark interest as notified (update cooldown)."""
        now = now or datetime.now(UTC)
        interest.last_notified_at = now

    async def mark_dormant(
        self,
        interest: UserInterest,
        now: datetime | None = None,
    ) -> None:
        """Mark interest as dormant."""
        now = now or datetime.now(UTC)
        interest.status = InterestStatus.DORMANT.value
        interest.dormant_since = now

        logger.info(
            "interest_marked_dormant",
            interest_id=str(interest.id),
            user_id=str(interest.user_id),
        )

    # =========================================================================
    # Bulk Operations
    # =========================================================================

    async def delete_all_for_user(self, user_id: UUID) -> int:
        """
        Delete all interests for a user (GDPR erasure).

        Args:
            user_id: User UUID

        Returns:
            Number of deleted interests
        """
        result = await self.db.execute(delete(UserInterest).where(UserInterest.user_id == user_id))

        deleted: int = result.rowcount  # type: ignore[attr-defined]
        if deleted > 0:
            logger.info(
                "interests_delete_all_for_user",
                user_id=str(user_id),
                count=deleted,
            )

        return deleted

    async def delete_dormant_older_than(
        self,
        days: int,
        now: datetime | None = None,
    ) -> int:
        """
        Delete interests dormant for more than N days.

        Args:
            days: Days threshold for deletion
            now: Current datetime

        Returns:
            Number of deleted interests
        """
        now = now or datetime.now(UTC)
        threshold = now - timedelta(days=days)

        result = await self.db.execute(
            delete(UserInterest).where(
                and_(
                    UserInterest.status == InterestStatus.DORMANT.value,
                    UserInterest.dormant_since <= threshold,
                )
            )
        )

        deleted: int = result.rowcount  # type: ignore[attr-defined]
        if deleted > 0:
            logger.info(
                "dormant_interests_deleted",
                count=deleted,
                threshold_days=days,
            )

        return deleted

    async def get_interests_for_embedding_update(
        self,
        limit: int = INTEREST_USER_LIST_LIMIT,
    ) -> list[UserInterest]:
        """Get interests without embeddings for batch embedding update."""
        result = await self.db.execute(
            select(UserInterest).where(UserInterest.embedding.is_(None)).limit(limit)
        )
        return list(result.scalars().all())

    async def count_by_user_ids(self, user_ids: list[UUID]) -> dict[UUID, int]:
        """
        Count interests per user for multiple users (batch operation).

        Args:
            user_ids: List of user UUIDs

        Returns:
            Dict mapping user_id to interest count
        """
        if not user_ids:
            return {}

        from sqlalchemy import func

        result = await self.db.execute(
            select(UserInterest.user_id, func.count(UserInterest.id))
            .where(UserInterest.user_id.in_(user_ids))
            .group_by(UserInterest.user_id)
        )

        counts = {row[0]: row[1] for row in result.all()}

        # Fill in zeros for users with no interests
        for user_id in user_ids:
            if user_id not in counts:
                counts[user_id] = 0

        return counts


class InterestNotificationRepository:
    """
    Repository for InterestNotification database operations.

    Provides queries for:
    - Notification tracking
    - Quota checking
    - Deduplication
    """

    def __init__(self, db: AsyncSession):
        """Initialize repository with database session."""
        self.db = db

    async def create(
        self,
        user_id: UUID,
        interest_id: UUID | None,
        run_id: str,
        content_hash: str,
        source: str,
        content_embedding: list[float] | None = None,
    ) -> InterestNotification:
        """
        Create a notification record.

        Args:
            user_id: User UUID
            interest_id: Interest UUID (nullable)
            run_id: Unique run ID for token tracking
            content_hash: SHA256 hash of content
            source: Content source
            content_embedding: Optional embedding

        Returns:
            Created InterestNotification instance
        """
        notification = InterestNotification(
            user_id=user_id,
            interest_id=interest_id,
            run_id=run_id,
            content_hash=content_hash,
            source=source,
            content_embedding=content_embedding,
        )
        self.db.add(notification)
        await self.db.flush()

        logger.info(
            "interest_notification_created",
            user_id=str(user_id),
            notification_id=str(notification.id),
            source=source,
            run_id=run_id,
        )

        return notification

    async def get_by_id(self, notification_id: UUID) -> InterestNotification | None:
        """Get notification by ID."""
        result = await self.db.execute(
            select(InterestNotification).where(InterestNotification.id == notification_id)
        )
        return result.scalar_one_or_none()

    async def count_today_for_user(
        self,
        user_id: UUID,
        user_timezone: str = "UTC",
        now: datetime | None = None,
    ) -> int:
        """
        Count notifications sent today for a user.

        Args:
            user_id: User UUID
            user_timezone: User's timezone
            now: Current datetime

        Returns:
            Count of notifications today
        """
        now = now or datetime.now(UTC)

        # Calculate start of today in user's timezone
        try:
            user_tz: ZoneInfo | timezone = ZoneInfo(user_timezone)
        except (KeyError, ValueError):
            user_tz = UTC

        user_now = now.astimezone(user_tz)
        today_start = datetime(
            user_now.year, user_now.month, user_now.day, tzinfo=user_tz
        ).astimezone(UTC)

        result = await self.db.execute(
            select(func.count()).where(
                and_(
                    InterestNotification.user_id == user_id,
                    InterestNotification.created_at >= today_start,
                )
            )
        )
        return result.scalar() or 0

    async def get_last_for_user(
        self,
        user_id: UUID,
    ) -> InterestNotification | None:
        """Get the most recent notification for a user."""
        result = await self.db.execute(
            select(InterestNotification)
            .where(InterestNotification.user_id == user_id)
            .order_by(InterestNotification.created_at.desc())
            .limit(1)
        )
        return result.scalar_one_or_none()

    async def get_recent_for_interest(
        self,
        interest_id: UUID,
        days: int = INTEREST_CONTENT_LOOKBACK_DAYS,
        now: datetime | None = None,
    ) -> list[InterestNotification]:
        """
        Get recent notifications for an interest.

        Used for content deduplication.
        """
        now = now or datetime.now(UTC)
        threshold = now - timedelta(days=days)

        result = await self.db.execute(
            select(InterestNotification)
            .where(
                and_(
                    InterestNotification.interest_id == interest_id,
                    InterestNotification.created_at >= threshold,
                )
            )
            .order_by(InterestNotification.created_at.desc())
        )
        return list(result.scalars().all())

    async def check_content_hash_exists(
        self,
        user_id: UUID,
        content_hash: str,
        days: int = INTEREST_CONTENT_LOOKBACK_DAYS,
        now: datetime | None = None,
    ) -> bool:
        """
        Check if content hash already exists (exact deduplication).

        Args:
            user_id: User UUID
            content_hash: SHA256 hash to check
            days: Lookback period
            now: Current datetime

        Returns:
            True if duplicate exists
        """
        now = now or datetime.now(UTC)
        threshold = now - timedelta(days=days)

        result = await self.db.execute(
            select(func.count()).where(
                and_(
                    InterestNotification.user_id == user_id,
                    InterestNotification.content_hash == content_hash,
                    InterestNotification.created_at >= threshold,
                )
            )
        )
        return (result.scalar() or 0) > 0

    async def update_feedback(
        self,
        notification_id: UUID,
        feedback: str,
    ) -> bool:
        """
        Update user feedback on a notification.

        Args:
            notification_id: Notification UUID
            feedback: Feedback value

        Returns:
            True if updated
        """
        result = await self.db.execute(
            update(InterestNotification)
            .where(InterestNotification.id == notification_id)
            .values(user_feedback=feedback)
        )
        return result.rowcount > 0  # type: ignore[attr-defined, no-any-return]
