"""Increase picture_url length to 2048 chars for OAuth URLs

Revision ID: 090adf8517f4
Revises: initial_001
Create Date: 2025-10-19 13:37:06.696903

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '090adf8517f4'
down_revision: str | None = 'initial_001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('connectors', 'connector_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('GMAIL', 'GOOGLE_DRIVE', 'GOOGLE_CALENDAR', 'SLACK', 'NOTION', 'GITHUB', name='connectortype', native_enum=False),
               existing_nullable=False)
    op.alter_column('connectors', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               type_=sa.Enum('ACTIVE', 'INACTIVE', 'REVOKED', 'ERROR', name='connectorstatus', native_enum=False),
               existing_nullable=False)
    op.alter_column('connectors', 'scopes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('connectors', 'credentials_encrypted',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_index('ix_connectors_status', table_name='connectors')
    op.add_column('embeddings', sa.Column('embedding_metadata', sa.Text(), nullable=True))
    op.drop_column('embeddings', 'metadata')
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'picture_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=2048),
               existing_nullable=True)
    op.drop_index('ix_users_oauth_provider', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_oauth_provider', 'users', ['oauth_provider'], unique=False)
    op.alter_column('users', 'picture_url',
               existing_type=sa.String(length=2048),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('users', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.add_column('embeddings', sa.Column('metadata', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('embeddings', 'embedding_metadata')
    op.create_index('ix_connectors_status', 'connectors', ['status'], unique=False)
    op.alter_column('connectors', 'credentials_encrypted',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('connectors', 'scopes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('connectors', 'status',
               existing_type=sa.Enum('ACTIVE', 'INACTIVE', 'REVOKED', 'ERROR', name='connectorstatus', native_enum=False),
               server_default=sa.text("'active'::character varying"),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('connectors', 'connector_type',
               existing_type=sa.Enum('GMAIL', 'GOOGLE_DRIVE', 'GOOGLE_CALENDAR', 'SLACK', 'NOTION', 'GITHUB', name='connectortype', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
