"""T1 durable return notification outbox

Revision ID: c75adcbc2f90
Revises: 58ac1d6c32e0
Create Date: 2026-07-14 00:01:14.511571

"""

from typing import Union
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c75adcbc2f90"
down_revision: str | None = "58ac1d6c32e0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "phone_calls",
        sa.Column(
            "notification_status",
            sa.Enum(
                "PENDING",
                "DELIVERED",
                "FAILED",
                name="notificationstatus",
                native_enum=False,
                length=20,
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "phone_calls",
        sa.Column("notification_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "phone_calls",
        sa.Column(
            "notification_attempts", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
    )
    op.create_index(
        "ix_phone_calls_notification_pending",
        "phone_calls",
        ["completed_at"],
        unique=False,
        postgresql_where=sa.text("notification_status = 'PENDING'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_phone_calls_notification_pending",
        table_name="phone_calls",
        postgresql_where=sa.text("notification_status = 'PENDING'"),
    )
    op.drop_column("phone_calls", "notification_attempts")
    op.drop_column("phone_calls", "notification_payload")
    op.drop_column("phone_calls", "notification_status")
    # ### end Alembic commands ###
