"""The turn, and what was decided in it (ADR-263, lot 6).

The spine the other two registers hang off. ``agent_effects`` says what was
DONE and ``agent_treatments`` what was READ; both carry a ``run_id`` that until
now pointed at nothing. This table is what that identifier means.

Three shapes carry the decisions:

1. ``UNIQUE (run_id)`` — one row per TURN, and a HITL resumption is the SAME
   turn: it reuses the identifier, so the write is an upsert and ``segments``
   counts how many times the turn ran. A plain insert would either fail on
   every resumption or, with the constraint dropped, quietly file one turn as
   two.

2. Both message references are ``ON DELETE SET NULL``. The register POINTS at
   the request and the answer instead of copying them — ``conversation_messages``
   is already the user's own data, purged with the account, and a copy here
   would be a second place to leak the very words the register exists to make
   accountable. Deleting a conversation therefore leaves a dated TOMBSTONE (the
   turn happened, its text is gone), never a resurrection and never a lie.
   Same doctrine as ``provenance_references`` (ADR-201).

3. Both enums are CHECK-backed VARCHARs, like the two registers before it —
   never native PostgreSQL types. Adding a value then stays an ordinary
   migration instead of an ``ALTER TYPE`` that cannot run in a transaction.

Written by hand rather than autogenerated, like its three predecessors:
autogenerate would sweep in whatever unrelated model drift the working tree
carries.

Revision ID: e2b3c4d5f6a7
Revises: d1a2b3c4e5f6
Create Date: 2026-09-04 21:00:00.000000
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "e2b3c4d5f6a7"
down_revision: str | None = "d1a2b3c4e5f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


#: Same convention as the two registers before it: a CHECK-backed VARCHAR, not
#: a native PostgreSQL type. Adding a value then stays an ordinary migration
#: rather than an ``ALTER TYPE`` that cannot run inside a transaction.
_SOURCE = sa.Enum(
    "user", "scheduled", "subagent", name="effectsource", native_enum=False, length=20
)
_OUTCOME = sa.Enum(
    "answered",
    "failed",
    "interrupted",
    name="decisionoutcome",
    native_enum=False,
    length=12,
)


def upgrade() -> None:
    """Create the decision register."""
    op.create_table(
        "agent_decisions",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
            comment="Account the turn belongs to. Dies with it.",
        ),
        sa.Column(
            "thread_id",
            sa.String(length=100),
            nullable=False,
            comment="Conversation the turn belongs to.",
        ),
        sa.Column(
            "run_id",
            sa.String(length=100),
            nullable=False,
            comment="The turn. Unique: a HITL resumption reuses it and updates this row.",
        ),
        sa.Column(
            "source",
            _SOURCE,
            nullable=False,
            comment="Under whose authority the turn ran (user | scheduled | subagent).",
        ),
        sa.Column(
            "execution_mode",
            sa.String(length=20),
            nullable=False,
            comment="pipeline | react | subagent",
        ),
        sa.Column(
            "route",
            sa.String(length=40),
            nullable=True,
            comment="What the router decided (conversation | actionable | react); "
            "NULL when the turn ended before routing.",
        ),
        sa.Column(
            "plan_step_count",
            sa.Integer(),
            nullable=True,
            comment="Steps the planner produced; NULL when no plan was built.",
        ),
        sa.Column(
            "request_message_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("conversation_messages.id", ondelete="SET NULL"),
            nullable=True,
            comment="POINTER to what was asked — never a copy. SET NULL leaves a tombstone.",
        ),
        sa.Column(
            "response_message_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("conversation_messages.id", ondelete="SET NULL"),
            nullable=True,
            comment="POINTER to what was answered — never a copy. SET NULL leaves a tombstone.",
        ),
        sa.Column(
            "outcome",
            _OUTCOME,
            nullable=False,
            comment="answered | failed | interrupted — a turn that never answered is a fact.",
        ),
        sa.Column(
            "segments",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("1"),
            comment="How many times this turn ran. Above 1 = it was interrupted and resumed.",
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="When the turn began (UTC) — the EARLIEST across its segments.",
        ),
        sa.Column(
            "ended_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="When it last ended (UTC) — the LATEST across its segments.",
        ),
        sa.Column(
            "duration_ms",
            sa.Integer(),
            nullable=False,
            comment="Cumulative time the turn actually ran.",
        ),
        sa.Column(
            "schema_version",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("1"),
            comment="Shape of the row, so a reader never guesses which columns "
            "it was written with.",
        ),
        sa.UniqueConstraint("run_id", name="uq_agent_decisions_run"),
        comment="One row per turn: the spine the two registers hang off (ADR-263).",
    )
    op.create_index("ix_agent_decisions_user_started", "agent_decisions", ["user_id", "started_at"])
    op.create_index("ix_agent_decisions_thread", "agent_decisions", ["thread_id"])


def downgrade() -> None:
    """Drop the register. Both enums are CHECK constraints carried by the
    table itself, so nothing outlives it."""
    op.drop_index("ix_agent_decisions_thread", table_name="agent_decisions")
    op.drop_index("ix_agent_decisions_user_started", table_name="agent_decisions")
    op.drop_table("agent_decisions")
