"""Agent effects ledger: one durable row per external effect (ADR-263).

The table is INERT until lot 2 wires the effect gate — nothing reads or writes
it yet, so this migration is safe on every deployment, flag or no flag.

Three properties are enforced by the schema rather than by code:

- ``uq_agent_effects_thread_idempotency`` makes "the same approval spent twice"
  impossible: the claim is an ``INSERT ... ON CONFLICT DO NOTHING``, so a
  second claim on the same key loses by construction rather than by a check.
- ``claim_token`` is NOT NULL, so every row has an owner and no close can be
  written by a worker that no longer holds it.
- ``user_id`` cascades: the ledger is retained until the account is deleted,
  and not one second longer (owner decision, 2026-09-03).

Written by hand rather than autogenerated: autogenerate would have swept in
whatever unrelated model drift the working tree carries, and this table is
small enough to state exactly.

Revision ID: b8d4fa2e5c39
Revises: f1a2b3c4d5e6
Create Date: 2026-09-04 01:00:00.000000
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "b8d4fa2e5c39"
down_revision: str | None = "f1a2b3c4d5e6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_STATUS = sa.Enum(
    "claimed",
    "succeeded",
    "failed",
    "abandoned",
    "refused",
    name="effectstatus",
    native_enum=False,
    length=20,
)
_SOURCE = sa.Enum(
    "user",
    "scheduled",
    "subagent",
    name="effectsource",
    native_enum=False,
    length=20,
)


def upgrade() -> None:
    """Create the ledger table, its unique claim key and its two read indexes."""
    op.create_table(
        "agent_effects",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
            comment="Acting user; the ledger is deleted with the account.",
        ),
        sa.Column(
            "thread_id",
            sa.String(length=100),
            nullable=False,
            comment="LangGraph thread the effect belongs to.",
        ),
        sa.Column(
            "run_id",
            sa.String(length=100),
            nullable=False,
            comment="Billing/correlation id of the run.",
        ),
        sa.Column(
            "source",
            _SOURCE,
            nullable=False,
            comment="Who asked for the turn: user, scheduled action, sub-agent.",
        ),
        sa.Column(
            "execution_mode",
            sa.String(length=20),
            nullable=False,
            comment="pipeline | react | subagent.",
        ),
        sa.Column("tool_name", sa.String(length=100), nullable=False),
        sa.Column(
            "mutation_policy",
            sa.String(length=20),
            nullable=False,
            comment="The policy that applied when the effect was claimed (ADR-263).",
        ),
        sa.Column(
            "idempotency_key",
            sa.String(length=200),
            nullable=False,
            comment="tool_call_id (react) | draft_id (draft) | run_id:step_id (pipeline).",
        ),
        sa.Column(
            "args_digest",
            sa.String(length=64),
            nullable=False,
            comment="Keyed digest of tool name + arguments.",
        ),
        sa.Column(
            "approval_kind",
            sa.String(length=30),
            nullable=True,
            comment="draft_critique | tool_confirmation | for_each | policy.",
        ),
        sa.Column(
            "approval_ref",
            sa.String(length=200),
            nullable=True,
            comment="message_id of the card, or draft_id.",
        ),
        sa.Column(
            "draft_digest",
            sa.String(length=64),
            nullable=True,
            comment="Digest of the draft_content the user was shown (ADR-092 binding).",
        ),
        sa.Column("status", _STATUS, nullable=False),
        sa.Column(
            "claim_token",
            postgresql.UUID(as_uuid=True),
            nullable=False,
            comment="Owner token: every close is conditioned on it (fencing).",
        ),
        sa.Column(
            "retry_of",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("agent_effects.id", ondelete="SET NULL"),
            nullable=True,
            comment="The FAILED/ABANDONED row this claim retries.",
        ),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "provider_ref",
            sa.String(length=500),
            nullable=True,
            comment="Provider-side identifier (message id, event id) when the tool returns one.",
        ),
        sa.Column(
            "result_digest",
            sa.String(length=64),
            nullable=True,
            comment="Digest of the result, to verify the payload.",
        ),
        sa.Column(
            "result_payload",
            sa.Text(),
            nullable=True,
            comment="Encrypted (encrypt_data) tool result, kept so a resume can be served from the ledger instead of re-executing the effect.",
        ),
        sa.Column(
            "result_truncated",
            sa.Boolean(),
            nullable=False,
            server_default=sa.text("false"),
            comment="True when result_payload was cut at the configured cap.",
        ),
        sa.Column(
            "error_code",
            sa.String(length=50),
            nullable=True,
            comment="Stable code of a FAILED or REFUSED effect.",
        ),
        sa.Column(
            "label",
            sa.Text(),
            nullable=True,
            comment="Encrypted (encrypt_data) JSON {i18n_key, values} built at claim time; rendered in the reader's language at export, never a frozen sentence.",
        ),
        sa.Column(
            "catalogue_fingerprint",
            sa.String(length=64),
            nullable=True,
            comment="Digest of the catalogue that offered the tool.",
        ),
        sa.Column(
            "schema_version",
            sa.Integer(),
            nullable=False,
            server_default=sa.text("1"),
            comment="Row shape, bumped on every additive column (ADR-263).",
        ),
        sa.UniqueConstraint(
            "thread_id", "idempotency_key", name="uq_agent_effects_thread_idempotency"
        ),
    )
    op.create_index("ix_agent_effects_tool_name", "agent_effects", ["tool_name"])
    op.create_index("ix_agent_effects_status", "agent_effects", ["status"])
    op.create_index("ix_agent_effects_user_claimed", "agent_effects", ["user_id", "claimed_at"])
    op.create_index("ix_agent_effects_run", "agent_effects", ["run_id"])


def downgrade() -> None:
    """Drop the ledger. Nothing else reads it, so nothing else has to be undone."""
    op.drop_index("ix_agent_effects_run", table_name="agent_effects")
    op.drop_index("ix_agent_effects_user_claimed", table_name="agent_effects")
    op.drop_index("ix_agent_effects_status", table_name="agent_effects")
    op.drop_index("ix_agent_effects_tool_name", table_name="agent_effects")
    op.drop_table("agent_effects")
