"""Tamper-evident chain over the two registers (ADR-263, lot 5).

Three things land together because they are one mechanism:

1. ``ledger_chain`` — one chain per ACCOUNT. Per account, not global, and that
   is the decision the whole design turns on: deleting an account removes a
   COMPLETE chain (FK CASCADE) instead of punching a permanent hole in a shared
   one. It is what lets inalterability and the right to erasure coexist without
   either giving way.

2. The notary's bookkeeping columns on both registers. They are the ONLY
   columns the chain does not digest — digesting them would make the act of
   notarising invalidate the digest it just took.

3. **Partial** indexes on those columns. Measured on 50 000 rows: finding the
   pending set through a join against the chain costs 9,93 ms per tick and
   grows with the register; through ``WHERE notarised_at IS NULL`` it costs
   0,64 ms and grows with the PENDING set alone. And unlike a timestamp
   watermark, a NULL marker has no late-commit blind spot — simulated: a row
   whose transaction committed after the notary passed was picked up on the
   next tick, with nothing left behind.

``UNIQUE (user_id, seq)`` is not decoration: it makes a forked chain impossible
even when two notaries run at once. Simulated with two concurrent passes — one
was refused by this very constraint, the sequence stayed contiguous, no subject
was notarised twice, and nothing was left pending.

Written by hand rather than autogenerated, for the same reason as the two
register migrations: autogenerate would sweep in whatever unrelated model drift
the working tree carries.

Revision ID: d1a2b3c4e5f6
Revises: c9e5fb3a6d47
Create Date: 2026-09-04 19:00:00.000000
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "d1a2b3c4e5f6"
down_revision: str | None = "c9e5fb3a6d47"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create the chain, and open the pending sets the notary reads."""
    op.create_table(
        "ledger_chain",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "user_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
            comment="Whose chain. The chain is deleted with the account, entire.",
        ),
        sa.Column(
            "seq",
            sa.Integer(),
            nullable=False,
            comment="Position in THIS account's chain, from 1, contiguous.",
        ),
        sa.Column(
            "kind",
            sa.String(length=40),
            nullable=False,
            comment="Stage covered: chain.genesis | effect.claimed | effect.settled "
            "| treatment.recorded. Written into the hash, so never renamed.",
        ),
        sa.Column(
            "subject_id",
            postgresql.UUID(as_uuid=True),
            nullable=True,
            comment="Register row covered; NULL for the genesis entry, which covers none.",
        ),
        sa.Column(
            "payload_digest",
            sa.String(length=64),
            nullable=False,
            comment="Digest of the covered row's business columns (chain_digest).",
        ),
        sa.Column(
            "prev_hash",
            sa.String(length=64),
            nullable=True,
            comment="Hash of the previous entry; NULL only for the first of a chain.",
        ),
        sa.Column(
            "entry_hash",
            sa.String(length=64),
            nullable=False,
            comment="sha256 over the canonical encoding of this entry, predecessor included.",
        ),
        sa.Column(
            "digest_version",
            sa.Integer(),
            nullable=False,
            comment="Encoding rule that produced the digests — read back at verification.",
        ),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="When this entry was appended (UTC) — notarisation order, not "
            "necessarily the covered row's chronology.",
        ),
        sa.UniqueConstraint("user_id", "seq", name="uq_ledger_chain_user_seq"),
        comment="Tamper-evident chain notarising the two registers (ADR-263).",
    )
    op.create_index("ix_ledger_chain_user_seq", "ledger_chain", ["user_id", "seq"])
    op.create_index("ix_ledger_chain_subject", "ledger_chain", ["subject_id", "kind"])

    op.add_column(
        "agent_effects",
        sa.Column(
            "notarised_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When the CLAIM stage entered the chain. NULL = pending.",
        ),
    )
    op.add_column(
        "agent_effects",
        sa.Column(
            "settled_notarised_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When the OUTCOME stage entered the chain. NULL = pending.",
        ),
    )
    op.add_column(
        "agent_treatments",
        sa.Column(
            "notarised_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="When this consultation entered the chain. NULL = pending.",
        ),
    )

    # The partial indexes: O(pending), never O(register) — and led by
    # ``user_id``, because the notary walks account by account (the chain is
    # per account), so one index scan answers both « which accounts have
    # pending work » and « that account's pending rows, in order ».
    op.create_index(
        "ix_agent_effects_pending_claim",
        "agent_effects",
        ["user_id", "claimed_at", "id"],
        postgresql_where=sa.text("notarised_at IS NULL"),
    )
    op.create_index(
        "ix_agent_effects_pending_settled",
        "agent_effects",
        ["user_id", "closed_at", "id"],
        postgresql_where=sa.text("settled_notarised_at IS NULL AND status <> 'claimed'"),
    )
    op.create_index(
        "ix_agent_treatments_pending",
        "agent_treatments",
        ["user_id", "occurred_at", "id"],
        postgresql_where=sa.text("notarised_at IS NULL"),
    )


def downgrade() -> None:
    """Drop the chain and the bookkeeping. The registers themselves are untouched."""
    op.drop_index("ix_agent_treatments_pending", table_name="agent_treatments")
    op.drop_index("ix_agent_effects_pending_settled", table_name="agent_effects")
    op.drop_index("ix_agent_effects_pending_claim", table_name="agent_effects")
    op.drop_column("agent_treatments", "notarised_at")
    op.drop_column("agent_effects", "settled_notarised_at")
    op.drop_column("agent_effects", "notarised_at")
    op.drop_index("ix_ledger_chain_subject", table_name="ledger_chain")
    op.drop_index("ix_ledger_chain_user_seq", table_name="ledger_chain")
    op.drop_table("ledger_chain")
