"""
Validator for agent execution plans.

This module validates plans generated by the planner before their execution by the orchestrator.
It relies on catalogue manifests (Phase 1) to ensure:
- Parameters conform to ParameterSchema
- Sufficient permissions (OAuth scopes, roles)
- Acceptable total cost (budget, limits)
- HITL (Human-In-The-Loop) when required

Architecture:
- PlanValidator: Main validation class
- ValidationResult: Validation result (success, errors, warnings)
- ValidationError: Validation error with context

Usage:
    from .validator import PlanValidator, ValidationContext

    validator = PlanValidator(registry)
    context = ValidationContext(
        user_id="user123",
        session_id="sess456",
        available_scopes=["google_contacts.read"],
        budget_usd=1.0
    )

    result = validator.validate_plan(plan, context)
    if not result.is_valid:
        raise ValidationError(result.errors)

Compliance: LangGraph v1.0 + declarative catalogue Phase 1
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import UTC, datetime
from typing import Any

from src.core.field_names import FIELD_STEP_ID
from src.domains.agents.registry.agent_registry import AgentRegistry
from src.domains.agents.registry.catalogue import (
    ParameterConstraint,
    ToolManifest,
    ToolManifestNotFound,
)
from src.domains.agents.tools.common import ToolErrorCode
from src.infrastructure.observability.logging import get_logger

# Import ExecutionPlan DSL (Phase 5)
try:
    from .plan_schemas import ExecutionPlan, ExecutionStep, StepType  # PlanValidationError

    HAS_EXECUTION_PLAN = True
except ImportError:
    HAS_EXECUTION_PLAN = False

logger = get_logger(__name__)


# ============================================================================
# Validation Context
# ============================================================================


@dataclass
class ValidationContext:
    """
    Validation context for a plan.

    Contains the information needed to validate:
    - Permissions (available OAuth scopes, user roles)
    - Budget (max allowed cost)
    - Session (user_id, session_id for audit)

    Attributes:
        user_id: User identifier
        session_id: Session identifier
        available_scopes: List of available OAuth scopes
        user_roles: List of user roles
        budget_usd: Max budget in USD (None = no limit)
        allow_hitl: If False, rejects tools requiring HITL
        max_steps: Max number of allowed steps (None = no limit)

    Examples:
        >>> context = ValidationContext(
        ...     user_id="user123",
        ...     session_id="sess456",
        ...     available_scopes=["google_contacts.read"],
        ...     budget_usd=1.0
        ... )
    """

    user_id: str
    session_id: str
    available_scopes: list[str] = field(default_factory=list)
    user_roles: list[str] = field(default_factory=list)
    budget_usd: float | None = None
    allow_hitl: bool = True
    max_steps: int | None = None


# ============================================================================
# Validation Results
# ============================================================================


@dataclass
class ValidationIssue:
    """
    Validation issue (error or warning).

    Attributes:
        severity: "error" or "warning"
        code: Standardized error code
        message: Descriptive message
        step_index: Index of the affected step (None if global)
        tool_name: Name of the affected tool (None if not applicable)
        context: Additional context for debugging

    Examples:
        >>> issue = ValidationIssue(
        ...     severity="error",
        ...     code=ToolErrorCode.MISSING_REQUIRED_PARAM,
        ...     message="Parameter 'query' is required",
        ...     step_index=2,
        ...     tool_name="search_contacts_tool",
        ...     context={"param": "query"}
        ... )
    """

    severity: str  # "error" | "warning"
    code: ToolErrorCode
    message: str
    step_index: int | None = None
    tool_name: str | None = None
    context: dict[str, Any] = field(default_factory=dict)


@dataclass
class ValidationResult:
    """
    Validation result for a plan.

    Attributes:
        is_valid: True if the plan is valid (no errors)
        errors: List of blocking errors
        warnings: List of non-blocking warnings
        total_cost_usd: Estimated total cost of the plan
        total_steps: Total number of steps
        requires_hitl: If True, at least one step requires HITL
        validated_at: Validation timestamp

    Examples:
        >>> result = ValidationResult(
        ...     is_valid=True,
        ...     errors=[],
        ...     warnings=[],
        ...     total_cost_usd=0.05,
        ...     total_steps=3,
        ...     requires_hitl=False
        ... )
    """

    is_valid: bool
    errors: list[ValidationIssue] = field(default_factory=list)
    warnings: list[ValidationIssue] = field(default_factory=list)
    total_cost_usd: float = 0.0
    total_steps: int = 0
    requires_hitl: bool = False
    validated_at: datetime = field(default_factory=lambda: datetime.now(UTC))

    def add_error(
        self,
        code: ToolErrorCode,
        message: str,
        step_index: int | None = None,
        tool_name: str | None = None,
        context: dict[str, Any] | None = None,
    ) -> None:
        """Add an error and mark the result as invalid."""
        self.errors.append(
            ValidationIssue(
                severity="error",
                code=code,
                message=message,
                step_index=step_index,
                tool_name=tool_name,
                context=context or {},
            )
        )
        self.is_valid = False

    def add_warning(
        self,
        code: ToolErrorCode,
        message: str,
        step_index: int | None = None,
        tool_name: str | None = None,
        context: dict[str, Any] | None = None,
    ) -> None:
        """Add a warning without invalidating the result."""
        self.warnings.append(
            ValidationIssue(
                severity="warning",
                code=code,
                message=message,
                step_index=step_index,
                tool_name=tool_name,
                context=context or {},
            )
        )


# ============================================================================
# Plan Validator
# ============================================================================


class PlanValidator:
    """
    Validator for agent execution plans.

    Validates a plan generated by the planner before execution by the orchestrator.
    Relies on catalogue manifests for exhaustive validation.

    Validations performed:
    1. Parameters: conformity with ParameterSchema (types, constraints, required)
    2. Permissions: required OAuth scopes, allowed roles
    3. Costs: total budget, cost per step
    4. HITL: detection of tools requiring human approval
    5. Structure: valid steps, existing tools, dependencies

    Attributes:
        registry: AgentRegistry containing manifests

    Examples:
        >>> validator = PlanValidator(registry)
        >>> context = ValidationContext(user_id="user123", session_id="sess456")
        >>> result = validator.validate_plan(plan, context)
        >>> if result.is_valid:
        ...     orchestrator.execute(plan)
        ... else:
        ...     logger.error("plan_invalid", errors=result.errors)
    """

    def __init__(self, registry: AgentRegistry) -> None:
        """
        Initialize the validator.

        Args:
            registry: AgentRegistry with catalogue manifests
        """
        self.registry = registry

    def validate_plan(self, plan: dict[str, Any], context: ValidationContext) -> ValidationResult:
        """
        Validate a complete plan.

        Args:
            plan: Plan generated by planner (format: {"steps": [...]})
            context: Validation context (user, scopes, budget)

        Returns:
            ValidationResult with is_valid, errors, warnings

        Examples:
            >>> plan = {
            ...     "steps": [
            ...         {"tool": "search_contacts_tool", "args": {"query": "John"}},
            ...         {"tool": "get_contact_details_tool", "args": {"resource_name": "$steps.0.contacts[0].resource_name"}}
            ...     ]
            ... }
            >>> result = validator.validate_plan(plan, context)
            >>> assert result.is_valid
        """
        result = ValidationResult(is_valid=True)

        # Validate plan structure
        if not isinstance(plan, dict) or "steps" not in plan:
            result.add_error(
                code=ToolErrorCode.INVALID_INPUT,
                message="Plan must be a dict with 'steps' key",
                context={"plan": str(plan)[:100]},
            )
            return result

        steps = plan["steps"]
        if not isinstance(steps, list):
            result.add_error(
                code=ToolErrorCode.INVALID_INPUT,
                message="Plan 'steps' must be a list",
                context={"steps_type": type(steps).__name__},
            )
            return result

        # Validate max number of steps
        result.total_steps = len(steps)
        if context.max_steps and result.total_steps > context.max_steps:
            result.add_error(
                code=ToolErrorCode.CONSTRAINT_VIOLATION,
                message=f"Plan exceeds max steps limit: {result.total_steps} > {context.max_steps}",
                context={"total_steps": result.total_steps, "max_steps": context.max_steps},
            )

        # Validate each step
        for idx, step in enumerate(steps):
            self._validate_step(step, idx, context, result)

        # Validate total budget
        if context.budget_usd is not None and result.total_cost_usd > context.budget_usd:
            result.add_error(
                code=ToolErrorCode.CONSTRAINT_VIOLATION,
                message=f"Plan exceeds budget: ${result.total_cost_usd:.4f} > ${context.budget_usd:.4f}",
                context={"total_cost": result.total_cost_usd, "budget": context.budget_usd},
            )

        # Validate HITL
        if result.requires_hitl and not context.allow_hitl:
            result.add_error(
                code=ToolErrorCode.FORBIDDEN,
                message="Plan requires HITL approval but HITL is not allowed in this context",
                context={"allow_hitl": context.allow_hitl},
            )

        logger.info(
            "plan_validated",
            user_id=context.user_id,
            session_id=context.session_id,
            is_valid=result.is_valid,
            errors_count=len(result.errors),
            warnings_count=len(result.warnings),
            total_cost_usd=result.total_cost_usd,
            total_steps=result.total_steps,
            requires_hitl=result.requires_hitl,
        )

        return result

    def _validate_step(
        self,
        step: dict[str, Any],
        step_index: int,
        context: ValidationContext,
        result: ValidationResult,
    ) -> None:
        """
        Validate an individual step.

        Args:
            step: Step to validate (format: {"tool": "...", "args": {...}})
            step_index: Step index in the plan
            context: Validation context
            result: ValidationResult to enrich
        """
        # Validate step structure
        if not isinstance(step, dict):
            result.add_error(
                code=ToolErrorCode.INVALID_INPUT,
                message=f"Step {step_index} must be a dict",
                step_index=step_index,
                context={"step_type": type(step).__name__},
            )
            return

        if "tool" not in step:
            result.add_error(
                code=ToolErrorCode.MISSING_REQUIRED_PARAM,
                message=f"Step {step_index} missing required 'tool' field",
                step_index=step_index,
            )
            return

        tool_name = step["tool"]
        args = step.get("args", {})

        # Retrieve tool manifest
        try:
            manifest = self.registry.get_tool_manifest(tool_name)
        except ToolManifestNotFound:
            # Fallback: MCP tools with hallucinated suffix (evolution F2.1/F2.5)
            from src.core.context import (
                strip_hallucinated_mcp_suffix,
                user_mcp_tools_ctx,
            )

            manifest = None

            # 1. Admin MCP: strip suffix and retry central registry
            stripped = strip_hallucinated_mcp_suffix(tool_name)
            if stripped:
                try:
                    manifest = self.registry.get_tool_manifest(stripped)
                    step["tool"] = stripped
                except ToolManifestNotFound:
                    pass

            # 2. User MCP: ContextVar with fuzzy resolve
            if manifest is None:
                user_ctx = user_mcp_tools_ctx.get()
                if user_ctx:
                    manifest = user_ctx.resolve_tool_manifest(tool_name)
                    if manifest and manifest.name != tool_name:
                        step["tool"] = manifest.name

            if manifest is None:
                result.add_error(
                    code=ToolErrorCode.NOT_FOUND,
                    message=f"Tool '{tool_name}' not found in catalogue",
                    step_index=step_index,
                    tool_name=tool_name,
                )
                return

        # Validate parameters
        self._validate_parameters(args, manifest, step_index, result)

        # Validate permissions
        self._validate_permissions(manifest, context, step_index, result)

        # Accumulate cost
        step_cost = manifest.cost.est_cost_usd
        result.total_cost_usd += step_cost

        # Detect HITL
        if manifest.permissions.hitl_required:
            result.requires_hitl = True

    def _validate_parameters(
        self,
        args: dict[str, Any],
        manifest: ToolManifest,
        step_index: int,
        result: ValidationResult,
    ) -> None:
        """
        Validate step parameters against the manifest's ParameterSchema.

        Args:
            args: Arguments provided to the tool
            manifest: Tool's ToolManifest
            step_index: Step index
            result: ValidationResult to enrich
        """
        # Build parameter map by name
        params_by_name = {p.name: p for p in manifest.parameters}
        provided_params = set(args.keys())
        schema_params = set(params_by_name.keys())

        # Check required params
        for param_schema in manifest.parameters:
            if param_schema.required and param_schema.name not in provided_params:
                result.add_error(
                    code=ToolErrorCode.MISSING_REQUIRED_PARAM,
                    message=f"Missing required parameter '{param_schema.name}'",
                    step_index=step_index,
                    tool_name=manifest.name,
                    context={"param": param_schema.name},
                )

        # Check unknown params
        unknown_params = provided_params - schema_params
        for unknown in unknown_params:
            result.add_warning(
                code=ToolErrorCode.INVALID_PARAM_VALUE,
                message=f"Unknown parameter '{unknown}' not in tool schema",
                step_index=step_index,
                tool_name=manifest.name,
                context={"param": unknown},
            )

        # Validate each provided param
        for param_name, param_value in args.items():
            if param_name not in params_by_name:
                continue  # Already reported as unknown

            param_schema = params_by_name[param_name]
            self._validate_parameter_value(
                param_name, param_value, param_schema, step_index, manifest.name, result
            )

    def _validate_parameter_value(
        self,
        param_name: str,
        param_value: Any,
        param_schema: Any,
        step_index: int,
        tool_name: str,
        result: ValidationResult,
    ) -> None:
        """
        Validate a parameter value against its schema.

        Args:
            param_name: Parameter name
            param_value: Provided value
            param_schema: Catalogue ParameterSchema
            step_index: Step index
            tool_name: Tool name
            result: ValidationResult to enrich
        """
        # Skip validation for references ($steps.X.field, $context.X.field)
        if isinstance(param_value, str) and param_value.startswith("$"):
            # Note: reference validation will be done by the orchestrator
            # Accept both $steps.X and $context.X patterns
            return

        # Skip validation for Jinja templates ({% ... %} or {{ ... }})
        # These templates will be evaluated at runtime by parallel_executor and their
        # final type cannot be determined statically.
        # Issue: The planner generates Jinja templates that produce strings
        # but the schema expects an array - coercion will happen at runtime.
        if isinstance(param_value, str) and ("{%" in param_value or "{{" in param_value):
            return

        # Validate basic type
        expected_type = param_schema.type
        actual_type = type(param_value).__name__

        type_mapping = {
            "string": str,
            "integer": int,
            "boolean": bool,
            "array": list,
            "object": dict,
        }

        if expected_type in type_mapping:
            expected_python_type = type_mapping[expected_type]
            if not isinstance(param_value, expected_python_type):
                result.add_error(
                    code=ToolErrorCode.INVALID_PARAM_VALUE,
                    message=f"Parameter '{param_name}' has wrong type: expected {expected_type}, got {actual_type}",
                    step_index=step_index,
                    tool_name=tool_name,
                    context={
                        "param": param_name,
                        "expected_type": expected_type,
                        "actual_type": actual_type,
                    },
                )
                return

        # Validate constraints
        for constraint in param_schema.constraints:
            self._validate_constraint(
                param_name, param_value, constraint, step_index, tool_name, result
            )

    def _validate_constraint(
        self,
        param_name: str,
        param_value: Any,
        constraint: ParameterConstraint,
        step_index: int,
        tool_name: str,
        result: ValidationResult,
    ) -> None:
        """
        Validate a Pydantic constraint.

        Args:
            param_name: Parameter name
            param_value: Provided value
            constraint: ParameterConstraint to validate
            step_index: Step index
            tool_name: Tool name
            result: ValidationResult to enrich
        """
        kind = constraint.kind
        expected = constraint.value

        try:
            if kind == "min_length" and isinstance(param_value, str):
                if len(param_value) < expected:
                    result.add_error(
                        code=ToolErrorCode.CONSTRAINT_VIOLATION,
                        message=f"Parameter '{param_name}' length {len(param_value)} < min {expected}",
                        step_index=step_index,
                        tool_name=tool_name,
                        context={"param": param_name, "length": len(param_value), "min": expected},
                    )

            elif kind == "max_length" and isinstance(param_value, str):
                if len(param_value) > expected:
                    result.add_error(
                        code=ToolErrorCode.CONSTRAINT_VIOLATION,
                        message=f"Parameter '{param_name}' length {len(param_value)} > max {expected}",
                        step_index=step_index,
                        tool_name=tool_name,
                        context={"param": param_name, "length": len(param_value), "max": expected},
                    )

            elif kind == "minimum" and isinstance(param_value, int | float):
                if param_value < expected:
                    result.add_error(
                        code=ToolErrorCode.CONSTRAINT_VIOLATION,
                        message=f"Parameter '{param_name}' value {param_value} < min {expected}",
                        step_index=step_index,
                        tool_name=tool_name,
                        context={"param": param_name, "value": param_value, "min": expected},
                    )

            elif kind == "maximum" and isinstance(param_value, int | float):
                if param_value > expected:
                    result.add_error(
                        code=ToolErrorCode.CONSTRAINT_VIOLATION,
                        message=f"Parameter '{param_name}' value {param_value} > max {expected}",
                        step_index=step_index,
                        tool_name=tool_name,
                        context={"param": param_name, "value": param_value, "max": expected},
                    )

            elif kind == "pattern" and isinstance(param_value, str):
                import re

                if not re.match(expected, param_value):
                    result.add_error(
                        code=ToolErrorCode.CONSTRAINT_VIOLATION,
                        message=f"Parameter '{param_name}' does not match pattern {expected}",
                        step_index=step_index,
                        tool_name=tool_name,
                        context={"param": param_name, "value": param_value, "pattern": expected},
                    )

            elif kind == "enum":
                if param_value not in expected:
                    result.add_error(
                        code=ToolErrorCode.CONSTRAINT_VIOLATION,
                        message=f"Parameter '{param_name}' not in allowed values {expected}",
                        step_index=step_index,
                        tool_name=tool_name,
                        context={"param": param_name, "value": param_value, "allowed": expected},
                    )

        except Exception as e:
            logger.warning(
                "constraint_validation_error",
                param=param_name,
                constraint_kind=kind,
                error=str(e),
            )

    def _validate_permissions(
        self,
        manifest: ToolManifest,
        context: ValidationContext,
        step_index: int,
        result: ValidationResult,
    ) -> None:
        """
        Validate required permissions for a tool.

        Args:
            manifest: Tool's ToolManifest
            context: Validation context
            step_index: Step index
            result: ValidationResult to enrich
        """
        # Validate required scopes
        required_scopes = manifest.permissions.required_scopes
        missing_scopes = set(required_scopes) - set(context.available_scopes)

        if missing_scopes:
            result.add_error(
                code=ToolErrorCode.UNAUTHORIZED,
                message=f"Missing required scopes: {', '.join(missing_scopes)}",
                step_index=step_index,
                tool_name=manifest.name,
                context={
                    "missing_scopes": list(missing_scopes),
                    "required_scopes": required_scopes,
                },
            )

        # Validate allowed roles
        allowed_roles = manifest.permissions.allowed_roles
        if allowed_roles:  # If empty, all roles OK
            user_has_role = any(role in allowed_roles for role in context.user_roles)
            if not user_has_role:
                result.add_error(
                    code=ToolErrorCode.FORBIDDEN,
                    message=f"User role not authorized. Required roles: {', '.join(allowed_roles)}",
                    step_index=step_index,
                    tool_name=manifest.name,
                    context={"user_roles": context.user_roles, "allowed_roles": allowed_roles},
                )

    # ============================================================================
    # ExecutionPlan Validation (Phase 5)
    # ============================================================================

    def validate_execution_plan(
        self, plan: ExecutionPlan, context: ValidationContext
    ) -> ValidationResult:
        """
        Validate an ExecutionPlan (DSL Phase 5 format).

        This method supports the new ExecutionPlan format with:
        - Typed ExecutionSteps (TOOL, CONDITIONAL, REPLAN, HUMAN)
        - Explicit dependencies (depends_on)
        - Safe Python conditions
        - Enriched metadata

        Args:
            plan: ExecutionPlan to validate (Pydantic model)
            context: Validation context (user, scopes, budget)

        Returns:
            ValidationResult with is_valid, errors, warnings

        Examples:
            >>> from .plan_schemas import ExecutionPlan, ExecutionStep, StepType
            >>> plan = ExecutionPlan(
            ...     user_id="user123",
            ...     steps=[
            ...         ExecutionStep(
            ...             step_id="step_1",
            ...             step_type=StepType.TOOL,
            ...             agent_name="contacts_agent",
            ...             tool_name="search_contacts_tool",
            ...             parameters={"query": "John"}
            ...         )
            ...     ]
            ... )
            >>> result = validator.validate_execution_plan(plan, context)
            >>> assert result.is_valid
        """
        if not HAS_EXECUTION_PLAN:
            raise ImportError("ExecutionPlan not available. Install plan_schemas module.")

        result = ValidationResult(is_valid=True)

        # Validate max number of steps
        result.total_steps = len(plan.steps)
        if context.max_steps and result.total_steps > context.max_steps:
            result.add_error(
                code=ToolErrorCode.CONSTRAINT_VIOLATION,
                message=f"Plan exceeds max steps limit: {result.total_steps} > {context.max_steps}",
                context={"total_steps": result.total_steps, "max_steps": context.max_steps},
            )

        # Validate each step
        for idx, step in enumerate(plan.steps):
            self._validate_execution_step(step, idx, context, result)

        # Validate dependencies (no cycles)
        self._validate_dependencies(plan.steps, result)

        # Validate references in conditions and parameters
        self._validate_step_references(plan.steps, result)

        # Validate total budget
        if context.budget_usd is not None and result.total_cost_usd > context.budget_usd:
            result.add_error(
                code=ToolErrorCode.CONSTRAINT_VIOLATION,
                message=f"Plan exceeds budget: ${result.total_cost_usd:.4f} > ${context.budget_usd:.4f}",
                context={"total_cost": result.total_cost_usd, "budget": context.budget_usd},
            )

        # Validate HITL
        if result.requires_hitl and not context.allow_hitl:
            result.add_error(
                code=ToolErrorCode.FORBIDDEN,
                message="Plan requires HITL approval but HITL is not allowed in this context",
                context={"allow_hitl": context.allow_hitl},
            )

        logger.info(
            "execution_plan_validated",
            plan_id=plan.plan_id,
            user_id=context.user_id,
            session_id=context.session_id,
            is_valid=result.is_valid,
            errors_count=len(result.errors),
            warnings_count=len(result.warnings),
            total_cost_usd=result.total_cost_usd,
            total_steps=result.total_steps,
            requires_hitl=result.requires_hitl,
        )

        return result

    def _validate_execution_step(
        self,
        step: ExecutionStep,
        step_index: int,
        context: ValidationContext,
        result: ValidationResult,
    ) -> None:
        """
        Validate an ExecutionStep.

        Args:
            step: ExecutionStep to validate
            step_index: Step index in the plan
            context: Validation context
            result: ValidationResult to enrich
        """
        # TOOL steps: validate tool exists and params
        if step.step_type == StepType.TOOL:
            if not step.agent_name:
                result.add_error(
                    code=ToolErrorCode.INVALID_INPUT,
                    message=f"Step {step.step_id}: agent_name required for TOOL steps",
                    step_index=step_index,
                )
                return

            if not step.tool_name:
                result.add_error(
                    code=ToolErrorCode.INVALID_INPUT,
                    message=f"Step {step.step_id}: tool_name required for TOOL steps",
                    step_index=step_index,
                )
                return

            # Retrieve tool manifest
            try:
                manifest = self.registry.get_tool_manifest(step.tool_name)
            except ToolManifestNotFound:
                # Fallback: MCP tools with hallucinated suffix (evolution F2.1/F2.5)
                from src.core.context import (
                    strip_hallucinated_mcp_suffix,
                    user_mcp_tools_ctx,
                )

                manifest = None

                # 1. Admin MCP: strip suffix and retry central registry
                stripped = strip_hallucinated_mcp_suffix(step.tool_name)
                if stripped:
                    try:
                        manifest = self.registry.get_tool_manifest(stripped)
                        step.tool_name = stripped
                    except ToolManifestNotFound:
                        pass

                # 2. User MCP: ContextVar with fuzzy resolve
                if manifest is None:
                    user_ctx = user_mcp_tools_ctx.get()
                    if user_ctx:
                        manifest = user_ctx.resolve_tool_manifest(step.tool_name)
                        if manifest and manifest.name != step.tool_name:
                            step.tool_name = manifest.name

                if manifest is None:
                    result.add_error(
                        code=ToolErrorCode.NOT_FOUND,
                        message=f"Tool '{step.tool_name}' not found in catalogue",
                        step_index=step_index,
                        tool_name=step.tool_name,
                    )
                    return

            # Validate parameters (skip $steps.X references)
            self._validate_step_parameters(step.parameters, manifest, step_index, result)

            # Validate permissions
            self._validate_permissions(manifest, context, step_index, result)

            # Accumulate cost
            step_cost = manifest.cost.est_cost_usd
            result.total_cost_usd += step_cost

            # Detect HITL
            # FIX 2026-01-30: Skip plan_approval for FOR_EACH steps
            # They get confirmation via for_each_confirmation which provides better UX
            # with real item data from pre-execution (count + previews)
            if manifest.permissions.hitl_required or step.approvals_required:
                if not step.is_for_each_step:
                    result.requires_hitl = True

        # CONDITIONAL steps: validate condition is safe
        elif step.step_type == StepType.CONDITIONAL:
            if not step.condition:
                result.add_error(
                    code=ToolErrorCode.INVALID_INPUT,
                    message=f"Step {step.step_id}: condition required for CONDITIONAL steps",
                    step_index=step_index,
                )
                return

            # Validate that the condition is safe (AST whitelist)
            self._validate_condition_safe(step.condition, step.step_id, step_index, result)

        # HUMAN steps: require HITL approval (supported for confirmation workflows)
        elif step.step_type == StepType.HUMAN:
            result.requires_hitl = True

        # REPLAN: not supported in MVP
        elif step.step_type == StepType.REPLAN:
            result.add_error(
                code=ToolErrorCode.NOT_IMPLEMENTED,
                message=f"Step {step.step_id}: {step.step_type} not supported in MVP (Phase 2)",
                step_index=step_index,
                context={"step_type": step.step_type.value},
            )

    def _validate_step_parameters(
        self,
        args: dict[str, Any],
        manifest: ToolManifest,
        step_index: int,
        result: ValidationResult,
    ) -> None:
        """
        Validate TOOL step parameters (excluding $steps references).

        Args:
            args: Arguments provided to the tool
            manifest: Tool's ToolManifest
            step_index: Step index
            result: ValidationResult to enrich
        """
        # Build parameter map by name
        params_by_name = {p.name: p for p in manifest.parameters}
        provided_params = set(args.keys())
        schema_params = set(params_by_name.keys())

        # Check required params (skip if it's a $steps.X or $context.X reference)
        for param_schema in manifest.parameters:
            if param_schema.required:
                param_value = args.get(param_schema.name)
                # Skip validation if reference
                if param_value is None:
                    result.add_error(
                        code=ToolErrorCode.MISSING_REQUIRED_PARAM,
                        message=f"Missing required parameter '{param_schema.name}'",
                        step_index=step_index,
                        tool_name=manifest.name,
                        context={"param": param_schema.name},
                    )
                elif isinstance(param_value, str) and param_value.startswith("$"):
                    # Reference ($steps.X or $context.X): will be validated at execution time
                    continue

        # Check unknown params
        unknown_params = provided_params - schema_params
        for unknown in unknown_params:
            result.add_warning(
                code=ToolErrorCode.INVALID_PARAM_VALUE,
                message=f"Unknown parameter '{unknown}' not in tool schema",
                step_index=step_index,
                tool_name=manifest.name,
                context={"param": unknown},
            )

        # Validate constraints for each provided param (type, min_length, etc.)
        # Critical: without this validation, empty strings pass for required params
        for param_name, param_value in args.items():
            if param_name not in params_by_name:
                continue  # Already reported as unknown

            # Skip validation for references (validated at execution time)
            if isinstance(param_value, str) and param_value.startswith("$"):
                continue

            param_schema = params_by_name[param_name]
            self._validate_parameter_value(
                param_name, param_value, param_schema, step_index, manifest.name, result
            )

    def _validate_condition_safe(
        self, condition: str, step_id: str, step_index: int, result: ValidationResult
    ) -> None:
        """
        Validate that a condition is safe (AST whitelist).

        Verifies that the condition only contains safe operations:
        - Comparisons: ==, !=, <, >, <=, >=
        - Booleans: and, or, not
        - Lengths: len()
        - Field access: $steps.X.field

        Args:
            condition: Python expression to validate
            step_id: Step ID
            step_index: Step index
            result: ValidationResult to enrich
        """
        import ast
        import re

        # Replace $steps.X with safe variable for AST parsing
        # Support both numeric indices ($steps.0) and named step IDs ($steps.search_contacts)
        safe_condition = re.sub(
            r"\$steps\.[a-zA-Z_][a-zA-Z0-9_]*(\.[a-zA-Z_][a-zA-Z0-9_]*)*", "var", condition
        )

        try:
            tree = ast.parse(safe_condition, mode="eval")
        except SyntaxError as e:
            result.add_error(
                code=ToolErrorCode.INVALID_INPUT,
                message=f"Invalid condition syntax: {e}",
                step_index=step_index,
                context={"condition": condition, FIELD_STEP_ID: step_id},
            )
            return

        # Whitelist of allowed AST nodes
        allowed_nodes = {
            ast.Expression,  # Wrapper node from ast.parse(mode="eval")
            ast.Compare,
            ast.BoolOp,
            ast.UnaryOp,
            ast.Call,  # For len()
            ast.Name,
            ast.Constant,
            ast.Attribute,
            ast.Subscript,
            ast.Load,
            ast.Eq,
            ast.NotEq,
            ast.Lt,
            ast.LtE,
            ast.Gt,
            ast.GtE,
            ast.And,
            ast.Or,
            ast.Not,
            ast.In,
            ast.NotIn,
        }

        for node in ast.walk(tree):
            if type(node) not in allowed_nodes:
                result.add_error(
                    code=ToolErrorCode.FORBIDDEN,
                    message=f"Unsafe node in condition: {node.__class__.__name__}",
                    step_index=step_index,
                    context={"condition": condition, "unsafe_node": node.__class__.__name__},
                )
                return

            # Verify that Call is only len()
            if isinstance(node, ast.Call):
                if isinstance(node.func, ast.Name) and node.func.id != "len":
                    result.add_error(
                        code=ToolErrorCode.FORBIDDEN,
                        message=f"Only len() function allowed in conditions, got: {node.func.id}",
                        step_index=step_index,
                        context={"condition": condition, "function": node.func.id},
                    )
                    return

    def _validate_dependencies(self, steps: list[ExecutionStep], result: ValidationResult) -> None:
        """
        Validate that there are no cyclic dependencies.

        Args:
            steps: List of steps
            result: ValidationResult to enrich
        """
        # Create dependency graph
        step_ids = {step.step_id for step in steps}
        graph: dict[str, list[str]] = {step.step_id: step.depends_on for step in steps}

        # Verify that all dependencies exist
        for step in steps:
            for dep in step.depends_on:
                if dep not in step_ids:
                    result.add_error(
                        code=ToolErrorCode.INVALID_INPUT,
                        message=f"Step {step.step_id} depends on non-existent step: {dep}",
                        context={FIELD_STEP_ID: step.step_id, "missing_dependency": dep},
                    )

        # Detect cycles (DFS)
        visited = set()
        rec_stack = set()

        def has_cycle(node: str) -> bool:
            visited.add(node)
            rec_stack.add(node)

            for neighbor in graph.get(node, []):
                if neighbor not in visited:
                    if has_cycle(neighbor):
                        return True
                elif neighbor in rec_stack:
                    return True

            rec_stack.remove(node)
            return False

        for step_id in step_ids:
            if step_id not in visited:
                if has_cycle(step_id):
                    result.add_error(
                        code=ToolErrorCode.INVALID_INPUT,
                        message="Cyclic dependency detected in plan steps",
                        context={"graph": graph},
                    )
                    break

    def _validate_step_references(
        self, steps: list[ExecutionStep], result: ValidationResult
    ) -> None:
        """
        Validate that all $steps.X references in conditions and parameters
        point to steps that exist and will be executed BEFORE.

        Detects issues such as:
        - References to non-existent steps
        - Circular references (step referencing itself)
        - Forward references (step referencing a future step not yet executed)

        Args:
            steps: List of steps to validate
            result: ValidationResult to enrich
        """
        import re

        # Create a step_id -> index mapping for order validation
        step_indices = {step.step_id: idx for idx, step in enumerate(steps)}
        step_ids = set(step_indices.keys())

        # Pattern to extract $steps.X references
        # Captures the step_id after "$steps."
        steps_reference_pattern = re.compile(r"\$steps\.([a-zA-Z_][a-zA-Z0-9_]*)")

        # Pattern to extract $context.X references
        # Captures: $context.contacts.0.resource_name, $context.emails[0].id
        # Valid domains: contacts, emails, calendar, tasks, drive
        context_reference_pattern = re.compile(r"\$context\.([a-zA-Z_][a-zA-Z0-9_]*)")
        valid_context_domains = {"contacts", "emails", "events", "tasks", "drive"}

        for idx, step in enumerate(steps):
            # Collect all strings to analyze for this step
            strings_to_check = []

            # 1. Condition for CONDITIONAL steps
            if step.step_type == StepType.CONDITIONAL and step.condition:
                strings_to_check.append(("condition", step.condition))

            # 2. Parameters for TOOL steps
            if step.step_type == StepType.TOOL and step.parameters:
                for param_name, param_value in step.parameters.items():
                    if isinstance(param_value, str):
                        strings_to_check.append((f"parameter '{param_name}'", param_value))

            # 3. on_success and on_fail for CONDITIONAL steps
            # Phase 5.2A: Strict validation with forbidden values
            if step.step_type == StepType.CONDITIONAL:
                # List of forbidden values (generic placeholders)
                forbidden_step_ids = {
                    "done",
                    "error",
                    "end",
                    "success",
                    "fail",
                    "complete",
                    "finished",
                    "abort",
                    "stop",
                }

                if step.on_success:
                    # Check forbidden values (ONLY if step doesn't exist)
                    # Allow forbidden placeholders if they match an actual step_id
                    # Example: step_id="error" is allowed, "error" as generic placeholder is not
                    if step.on_success in forbidden_step_ids and step.on_success not in step_ids:
                        result.add_error(
                            code=ToolErrorCode.INVALID_INPUT,
                            message=(
                                f"Step {step.step_id}: on_success uses forbidden placeholder '{step.on_success}'. "
                                f"Must reference an actual step_id that exists in steps array. "
                                f"Forbidden values: {', '.join(sorted(forbidden_step_ids))}"
                            ),
                            context={
                                FIELD_STEP_ID: step.step_id,
                                "step_index": idx,
                                "forbidden_value": step.on_success,
                                "available_steps": list(step_ids),
                            },
                        )
                    # Verify that the referenced step exists
                    elif step.on_success not in step_ids:
                        result.add_error(
                            code=ToolErrorCode.INVALID_INPUT,
                            message=(
                                f"Step {step.step_id}: on_success references "
                                f"non-existent step '{step.on_success}'. "
                                f"Available steps: {', '.join(sorted(step_ids))}"
                            ),
                            context={
                                FIELD_STEP_ID: step.step_id,
                                "step_index": idx,
                                "missing_target": step.on_success,
                                "available_steps": list(step_ids),
                            },
                        )

                if step.on_fail:
                    # Check forbidden values (ONLY if step doesn't exist)
                    # Allow forbidden placeholders if they match an actual step_id
                    # Example: step_id="error" is allowed, "error" as generic placeholder is not
                    if step.on_fail in forbidden_step_ids and step.on_fail not in step_ids:
                        result.add_error(
                            code=ToolErrorCode.INVALID_INPUT,
                            message=(
                                f"Step {step.step_id}: on_fail uses forbidden placeholder '{step.on_fail}'. "
                                f"Must reference an actual step_id that exists in steps array. "
                                f"Forbidden values: {', '.join(sorted(forbidden_step_ids))}"
                            ),
                            context={
                                FIELD_STEP_ID: step.step_id,
                                "step_index": idx,
                                "forbidden_value": step.on_fail,
                                "available_steps": list(step_ids),
                            },
                        )
                    # Verify that the referenced step exists
                    elif step.on_fail not in step_ids:
                        result.add_error(
                            code=ToolErrorCode.INVALID_INPUT,
                            message=(
                                f"Step {step.step_id}: on_fail references "
                                f"non-existent step '{step.on_fail}'. "
                                f"Available steps: {', '.join(sorted(step_ids))}"
                            ),
                            context={
                                FIELD_STEP_ID: step.step_id,
                                "step_index": idx,
                                "missing_target": step.on_fail,
                                "available_steps": list(step_ids),
                            },
                        )

            # Analyze all collected strings
            for source, string_value in strings_to_check:
                # Extract all $steps.X references
                steps_matches = steps_reference_pattern.findall(string_value)

                for referenced_step_id in steps_matches:
                    # Verify that the referenced step exists
                    if referenced_step_id not in step_ids:
                        result.add_error(
                            code=ToolErrorCode.INVALID_INPUT,
                            message=(
                                f"Step {step.step_id}: {source} references "
                                f"non-existent step: {referenced_step_id}"
                            ),
                            context={
                                FIELD_STEP_ID: step.step_id,
                                "step_index": idx,
                                "source": source,
                                "missing_reference": referenced_step_id,
                            },
                        )
                        continue

                    # Check for circular reference
                    if referenced_step_id == step.step_id:
                        result.add_error(
                            code=ToolErrorCode.INVALID_INPUT,
                            message=(
                                f"Step {step.step_id}: {source} has circular reference to itself"
                            ),
                            context={
                                FIELD_STEP_ID: step.step_id,
                                "step_index": idx,
                                "source": source,
                            },
                        )
                        continue

                    # Check execution order (no forward reference)
                    referenced_idx = step_indices[referenced_step_id]
                    if referenced_idx >= idx:
                        result.add_error(
                            code=ToolErrorCode.INVALID_INPUT,
                            message=(
                                f"Step {step.step_id}: {source} references "
                                f"step {referenced_step_id} that will be executed "
                                f"later (index {referenced_idx} >= {idx})"
                            ),
                            context={
                                FIELD_STEP_ID: step.step_id,
                                "step_index": idx,
                                "referenced_step_id": referenced_step_id,
                                "referenced_step_index": referenced_idx,
                                "source": source,
                            },
                        )

                # Extract all $context.X references
                context_matches = context_reference_pattern.findall(string_value)

                for referenced_domain in context_matches:
                    # Verify that the context domain is valid
                    if referenced_domain not in valid_context_domains:
                        result.add_error(
                            code=ToolErrorCode.INVALID_INPUT,
                            message=(
                                f"Step {step.step_id}: {source} references "
                                f"invalid context domain: {referenced_domain}. "
                                f"Valid domains: {', '.join(sorted(valid_context_domains))}"
                            ),
                            context={
                                FIELD_STEP_ID: step.step_id,
                                "step_index": idx,
                                "source": source,
                                "invalid_domain": referenced_domain,
                                "valid_domains": list(valid_context_domains),
                            },
                        )

        # Phase 2.3 - Issue #32: Validate field paths against tool schemas
        self._validate_reference_field_paths(steps, result)

    def _validate_reference_field_paths(
        self, steps: list[ExecutionStep], result: ValidationResult
    ) -> None:
        """
        Validate field paths in $steps.X.field.path references against tool schemas.

        Phase 2.3 - Issue #32: Pre-Execution Validation

        This validation catches schema mismatches BEFORE tool execution, preventing
        costly API calls for invalid references.

        Common errors detected:
        - ❌ $steps.search.emails[0].value → Field is 'emailAddresses' not 'emails'
        - ❌ $steps.details.phones[0] → Field is 'phoneNumbers' not 'phones'
        - ❌ $steps.search.results[0] → No 'results' field (use 'contacts')

        Args:
            steps: List of ExecutionSteps to validate
            result: ValidationResult to populate with errors

        Algorithm:
            1. Build mapping step_id -> tool_name
            2. For each step:
               a. Collect parameters and condition
               b. Extract $steps references
               c. Validate field paths against tool schemas
            3. Add errors to result

        Examples:
            >>> # Valid reference
            >>> steps = [
            ...     ExecutionStep(
            ...         step_id="search",
            ...         step_type=StepType.TOOL,
            ...         tool_name="search_contacts_tool",
            ...         parameters={"query": "John"}
            ...     ),
            ...     ExecutionStep(
            ...         step_id="send",
            ...         step_type=StepType.TOOL,
            ...         tool_name="send_email_tool",
            ...         parameters={
            ...             "to": "$steps.search.contacts[0].emailAddresses[0].value"
            ...         }
            ...     )
            ... ]
            >>> validator._validate_reference_field_paths(steps, result)
            >>> assert result.is_valid  # Valid path
            >>>
            >>> # Invalid reference (wrong field name)
            >>> steps[1].parameters["to"] = "$steps.search.contacts[0].emails[0].value"
            >>> validator._validate_reference_field_paths(steps, result)
            >>> assert not result.is_valid  # Invalid - 'emails' doesn't exist
        """
        from src.domains.agents.orchestration.reference_validator import ReferenceValidator

        # Build mapping step_id -> tool_name for schema lookup
        step_tools: dict[str, str] = {}
        for step in steps:
            if step.step_type == StepType.TOOL and step.tool_name:
                step_tools[step.step_id] = step.tool_name

        # Create validator instance
        validator = ReferenceValidator()

        # Track all reference errors
        all_ref_errors: list = []

        # Validate each step
        for idx, step in enumerate(steps):
            # Only validate TOOL and CONDITIONAL steps
            if step.step_type not in [StepType.TOOL, StepType.CONDITIONAL]:
                continue

            # Collect parameters and condition
            parameters = step.parameters if step.step_type == StepType.TOOL else {}
            condition = step.condition if step.step_type == StepType.CONDITIONAL else None

            # Validate references in this step
            ref_errors = validator.validate_references_in_step(
                step_id=step.step_id,
                step_index=idx,
                parameters=parameters,
                step_tools=step_tools,
                condition=condition,
            )

            # Add errors to result and tracking list
            for ref_error in ref_errors:
                all_ref_errors.append(ref_error)
                result.add_error(
                    code=ref_error.code,
                    message=ref_error.message,
                    step_index=ref_error.step_index,
                    tool_name=ref_error.tool_name,
                    context={
                        FIELD_STEP_ID: ref_error.step_id,
                        "parameter_name": ref_error.parameter_name,
                        "reference": ref_error.reference,
                        "invalid_path": ref_error.invalid_path,
                        **(ref_error.context or {}),
                    },
                )

        # Log validation completion
        if all_ref_errors:
            logger.info(
                "reference_field_path_validation_complete",
                errors_count=len(all_ref_errors),
                steps_count=len(steps),
                message=f"Found {len(all_ref_errors)} field path validation errors",
            )


__all__ = [
    "PlanValidator",
    "ValidationContext",
    "ValidationIssue",
    "ValidationResult",
]
