"""Golden characterization net for the health baseline / variations pipeline.

Pins the EXACT output of ``HealthMetricsService.compute_kind_baseline_delta``
and ``HealthMetricsService.detect_all_variations`` for 15 datasets crossed with
every ``window_days`` an LLM-facing tool can request (1..14 — the clamp of
``HEALTH_METRICS_BASELINE_WINDOW_MAX_DAYS``), BEFORE the per-sample fetch is
replaced by a server-side per-day rollup (``fetch_daily_stats``). Method:
characterization-first decomposition (Feathers), as applied by ADR-122 for the
voice/TTS extraction and by extraction #2 for the draft preview renderer — this
net must pass identically, UNMODIFIED, after the conversion.

Why this exact shape:

- **The oracle cannot be the sample-based function.** After the conversion the
  sample-based entry points become thin wrappers over the stats-based ones, so
  comparing the two would be tautological. The table below is therefore
  generated by RUNNING the pre-conversion implementation and pinned as
  literals — never written by hand, regenerated ONLY on a deliberate, reviewed
  behavior change with the old/new tables diffed.
- **One dataset, both read paths.** ``_FakeSampleRepo`` serves BOTH repository
  interfaces (``fetch_samples_kind`` today, ``fetch_daily_stats`` after) from a
  single in-memory source of truth, so the very same net exercises the old and
  the new read path without a single edit. What the unit net proves is that the
  service contract is invariant across the two paths; that the SQL rollup
  equals the in-Python grouping is pinned separately by the integration test
  ``test_daily_stats_rollup.py`` (real PostgreSQL).
- **The clock is pinned per module.** ``detect_notable_events`` branches on
  ``datetime.now(UTC)``; without a frozen clock the table would be a calendar
  time bomb (the failure mode documented in ``test_context_aggregator.py``).
  Patching is scoped to the modules under test — no global freeze.

Branch coverage encoded in the case table (counted at generation time):

- Baseline modes: ``empty`` (72 entries), ``bootstrap`` (14), ``rolling`` (124).
- Notable variations: 36, both directions (``rising`` 12, ``falling`` 24).
- Notable events: 24 ``inactivity_streak`` occurrences.
- Both registered kinds: ``heart_rate`` (``DAILY_AVG``) and ``steps``
  (``DAILY_SUM``) — i.e. every ``BaselineKind`` reachable from the registry.
- Window boundaries: 1 (degenerate — window is the whole series), 6/7/8 (the
  bootstrap↔rolling switch at ``health_metrics_baseline_min_days``), 14 (the
  tool clamp).
- Data shapes: empty, missing days (gaps), monotonic rise, monotonic fall,
  all-zero values (null baseline → early return), steps inactivity streak,
  constant series (no variation).
- Fixture clock semantics — read this before adding a case: samples are placed
  at 12:00 UTC of their day while the frozen clock reads 11:00, so a
  ``days_ago=0`` entry falls *after* ``now`` and is excluded by the
  ``date_start < to_ts`` bound. The cases named ``*_after_now`` /
  ``*_last_in_future`` therefore pin that exclusion, and are NOT same-day
  coverage. Genuine same-day behaviour (``summary_today``,
  ``last_update_minutes_ago``) is covered by the heartbeat builder net, and a
  single-visible-day series by ``test_single_visible_day_*`` below — written as
  explicit assertions rather than golden entries, because the table must stay
  the one generated before the conversion.
- Non-terminating daily averages (3 and 7 samples/day whose sum is not
  divisible by the count). Without them the net is numerically blind: every
  other dataset yields a daily average of ``.0`` or ``.5``, so a rounding
  drift stays invisible.

Sensitivity verified by mutation testing (the net is worthless if it only
passes): ``DAILY_AVG`` → ``min`` fails 56 entries; the window split boundary
``<`` → ``<=`` fails 136; rounding the daily average to 1 decimal fails 14 —
that last one is caught ONLY by ``EXPECTED_DAILY`` plus the two
repeating-decimal cases, since the service payload rounds everything to one
decimal and hides sub-0.05 drift.
"""

from __future__ import annotations

from datetime import UTC, datetime, timedelta
from unittest.mock import MagicMock
from uuid import UUID

import pytest

from src.domains.health_metrics.baseline import (
    DailyStat,
    _daily_aggregate,
    _group_samples_by_day,
    _stat_value,
    compute_baseline,
    daily_stats_from_samples,
)
from src.domains.health_metrics.kinds import HEALTH_KINDS, BaselineKind
from src.domains.health_metrics.models import HealthSample
from src.domains.health_metrics.service import HealthMetricsService

pytestmark = pytest.mark.unit

USER_ID = UUID("00000000-0000-0000-0000-0000000000aa")

# Mid-June, mid-morning UTC: far from any month/DST edge, and every dataset
# below is built relative to it so day bucketing is fully deterministic.
FROZEN_NOW = datetime(2026, 6, 15, 11, 0, tzinfo=UTC)


class _FrozenDatetime(datetime):
    """datetime subclass with a pinned now(); everything else inherited."""

    @classmethod
    def now(cls, tz=None):  # type: ignore[override]
        if tz is None:
            return FROZEN_NOW.replace(tzinfo=None)
        return FROZEN_NOW.astimezone(tz)


@pytest.fixture(autouse=True)
def _frozen_clock(monkeypatch: pytest.MonkeyPatch) -> None:
    """Pin the module clock of every module that branches on ``now()``."""
    monkeypatch.setattr("src.domains.health_metrics.service.datetime", _FrozenDatetime)
    monkeypatch.setattr("src.domains.health_metrics.signals.datetime", _FrozenDatetime)


class _FakeSampleRepo:
    """In-memory stand-in for ``HealthSampleRepository``.

    Serves the raw-sample and the per-day-rollup interfaces from ONE dataset,
    so the golden net is blind to which one the service calls.
    """

    def __init__(self, samples: list[HealthSample]) -> None:
        self._samples = samples

    def _window(self, kind: str, from_ts: datetime, to_ts: datetime) -> list[HealthSample]:
        return [s for s in self._samples if s.kind == kind and from_ts <= s.date_start < to_ts]

    async def fetch_samples_kind(
        self, user_id: UUID, *, kind: str, from_ts: datetime, to_ts: datetime
    ) -> list[HealthSample]:
        return self._window(kind, from_ts, to_ts)

    async def fetch_daily_stats(
        self, user_id: UUID, *, kind: str, from_ts: datetime, to_ts: datetime
    ) -> list[DailyStat]:
        return daily_stats_from_samples(self._window(kind, from_ts, to_ts))


def _make_samples(kind: str, day_values: list[tuple[int, list[int]]]) -> list[HealthSample]:
    """Build samples at ``FROZEN_NOW - days_ago``, noon UTC, one per minute."""
    out: list[HealthSample] = []
    for days_ago, values in day_values:
        base = (FROZEN_NOW - timedelta(days=days_ago)).replace(
            hour=12, minute=0, second=0, microsecond=0
        )
        for index, value in enumerate(values):
            ts = base + timedelta(minutes=index)
            out.append(
                HealthSample(
                    user_id=USER_ID,
                    kind=kind,
                    date_start=ts,
                    date_end=ts + timedelta(minutes=1),
                    value=value,
                    source="test",
                )
            )
    out.sort(key=lambda s: s.date_start)
    return out


# (name, kind, [(days_ago, [values])]) — mirrored EXACTLY by the generator that
# produced EXPECTED; changing a case without regenerating breaks the net.
CASES: list[tuple[str, str, list[tuple[int, list[int]]]]] = [
    ("empty", "heart_rate", []),
    ("single_sample_after_now", "heart_rate", [(0, [70])]),
    ("many_samples_after_now", "heart_rate", [(0, [70, 71, 72, 73])]),
    ("three_days_last_in_future", "heart_rate", [(2, [60, 62]), (1, [70]), (0, [80, 82, 84])]),
    (
        "six_days_bootstrap_edge",
        "heart_rate",
        [(i, [60 + i * 3, 61 + i * 3]) for i in range(6, 0, -1)],
    ),
    (
        "seven_days_rolling_edge",
        "heart_rate",
        [(i, [60 + i * 3, 61 + i * 3]) for i in range(7, 0, -1)],
    ),
    (
        "forty_days_with_gaps",
        "heart_rate",
        [(i, [70 + (i % 5), 72 + (i % 3)]) for i in range(40, 0, -1) if i % 4 != 0],
    ),
    ("forty_days_rising", "heart_rate", [(i, [50 + (40 - i) * 2]) for i in range(40, 0, -1)]),
    ("forty_days_falling", "heart_rate", [(i, [50 + i * 2]) for i in range(40, 0, -1)]),
    (
        "steps_then_five_zero_days",
        "steps",
        [(i, [4000, 5000]) for i in range(30, 5, -1)] + [(i, [0]) for i in range(5, 0, -1)],
    ),
    ("steps_all_zero", "steps", [(i, [0]) for i in range(20, 0, -1)]),
    ("steps_constant", "steps", [(i, [8000]) for i in range(30, 0, -1)]),
    ("zero_values_null_baseline", "heart_rate", [(i, [0]) for i in range(20, 0, -1)]),
    (
        "avg_repeating_decimals",
        "heart_rate",
        [(i, [70 + (i % 7), 71 + (i % 5), 73 + (i % 3)]) for i in range(30, 0, -1)],
    ),
    (
        "avg_seven_samples_per_day",
        "heart_rate",
        [(i, [60 + ((i * 3 + j) % 11) for j in range(7)]) for i in range(30, 0, -1)],
    ),
]

WINDOW_DAYS = list(range(1, 15))


# =============================================================================
# Golden table — GENERATED, never hand-written
# =============================================================================

EXPECTED: dict[str, str] = {
    "avg_repeating_decimals|1": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 73.7, 'window_value': 72.3, 'delta_pct': -1.8, 'window_days': 1, 'days_available': 28}, [])",
    "avg_repeating_decimals|10": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 73.7, 'window_value': 73.2, 'delta_pct': -0.6, 'window_days': 10, 'days_available': 20}, [])",
    "avg_repeating_decimals|11": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 73.7, 'window_value': 73.3, 'delta_pct': -0.5, 'window_days': 11, 'days_available': 19}, [])",
    "avg_repeating_decimals|12": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 73.7, 'window_value': 73.3, 'delta_pct': -0.5, 'window_days': 12, 'days_available': 18}, [])",
    "avg_repeating_decimals|13": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 73.7, 'window_value': 73.4, 'delta_pct': -0.3, 'window_days': 13, 'days_available': 17}, [])",
    "avg_repeating_decimals|14": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 73.7, 'window_value': 73.4, 'delta_pct': -0.4, 'window_days': 14, 'days_available': 16}, [])",
    "avg_repeating_decimals|2": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 73.7, 'window_value': 72.8, 'delta_pct': -1.1, 'window_days': 2, 'days_available': 28}, [])",
    "avg_repeating_decimals|3": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 73.7, 'window_value': 73.0, 'delta_pct': -0.9, 'window_days': 3, 'days_available': 27}, [])",
    "avg_repeating_decimals|4": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 73.7, 'window_value': 73.3, 'delta_pct': -0.5, 'window_days': 4, 'days_available': 26}, [])",
    "avg_repeating_decimals|5": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 73.7, 'window_value': 73.4, 'delta_pct': -0.4, 'window_days': 5, 'days_available': 25}, [])",
    "avg_repeating_decimals|6": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 73.5, 'window_value': 73.4, 'delta_pct': -0.1, 'window_days': 6, 'days_available': 24}, [])",
    "avg_repeating_decimals|7": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 73.7, 'window_value': 73.3, 'delta_pct': -0.5, 'window_days': 7, 'days_available': 23}, [])",
    "avg_repeating_decimals|8": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 73.7, 'window_value': 73.3, 'delta_pct': -0.5, 'window_days': 8, 'days_available': 22}, [])",
    "avg_repeating_decimals|9": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 73.7, 'window_value': 73.3, 'delta_pct': -0.5, 'window_days': 9, 'days_available': 21}, [])",
    "avg_seven_samples_per_day|1": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 65.0, 'window_value': 66.0, 'delta_pct': 1.5, 'window_days': 1, 'days_available': 28}, [])",
    "avg_seven_samples_per_day|10": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 65.0, 'window_value': 65.2, 'delta_pct': 0.3, 'window_days': 10, 'days_available': 20}, [])",
    "avg_seven_samples_per_day|11": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 65.0, 'window_value': 65.0, 'delta_pct': 0.0, 'window_days': 11, 'days_available': 19}, [])",
    "avg_seven_samples_per_day|12": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 65.0, 'window_value': 65.1, 'delta_pct': 0.1, 'window_days': 12, 'days_available': 18}, [])",
    "avg_seven_samples_per_day|13": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 65.0, 'window_value': 65.1, 'delta_pct': 0.2, 'window_days': 13, 'days_available': 17}, [])",
    "avg_seven_samples_per_day|14": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 65.0, 'window_value': 65.1, 'delta_pct': 0.1, 'window_days': 14, 'days_available': 16}, [])",
    "avg_seven_samples_per_day|2": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 65.0, 'window_value': 65.9, 'delta_pct': 1.4, 'window_days': 2, 'days_available': 28}, [])",
    "avg_seven_samples_per_day|3": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 65.0, 'window_value': 65.3, 'delta_pct': 0.5, 'window_days': 3, 'days_available': 27}, [])",
    "avg_seven_samples_per_day|4": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 65.0, 'window_value': 65.0, 'delta_pct': 0.0, 'window_days': 4, 'days_available': 26}, [])",
    "avg_seven_samples_per_day|5": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 65.0, 'window_value': 65.4, 'delta_pct': 0.6, 'window_days': 5, 'days_available': 25}, [])",
    "avg_seven_samples_per_day|6": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 65.0, 'window_value': 65.4, 'delta_pct': 0.6, 'window_days': 6, 'days_available': 24}, [])",
    "avg_seven_samples_per_day|7": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 65.0, 'window_value': 65.1, 'delta_pct': 0.2, 'window_days': 7, 'days_available': 23}, [])",
    "avg_seven_samples_per_day|8": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 65.0, 'window_value': 65.1, 'delta_pct': 0.2, 'window_days': 8, 'days_available': 22}, [])",
    "avg_seven_samples_per_day|9": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 65.0, 'window_value': 65.3, 'delta_pct': 0.4, 'window_days': 9, 'days_available': 21}, [])",
    "empty|1": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'empty', 'baseline_value': None, 'window_value': None, 'delta_pct': None, 'window_days': 1}, [])",
    "empty|10": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'empty', 'baseline_value': None, 'window_value': None, 'delta_pct': None, 'window_days': 10}, [])",
    "empty|11": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'empty', 'baseline_value': None, 'window_value': None, 'delta_pct': None, 'window_days': 11}, [])",
    "empty|12": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'empty', 'baseline_value': None, 'window_value': None, 'delta_pct': None, 'window_days': 12}, [])",
    "empty|13": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'empty', 'baseline_value': None, 'window_value': None, 'delta_pct': None, 'window_days': 13}, [])",
    "empty|14": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'empty', 'baseline_value': None, 'window_value': None, 'delta_pct': None, 'window_days': 14}, [])",
    "empty|2": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'empty', 'baseline_value': None, 'window_value': None, 'delta_pct': None, 'window_days': 2}, [])",
    "empty|3": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'empty', 'baseline_value': None, 'window_value': None, 'delta_pct': None, 'window_days': 3}, [])",
    "empty|4": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'empty', 'baseline_value': None, 'window_value': None, 'delta_pct': None, 'window_days': 4}, [])",
    "empty|5": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'empty', 'baseline_value': None, 'window_value': None, 'delta_pct': None, 'window_days': 5}, [])",
    "empty|6": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'empty', 'baseline_value': None, 'window_value': None, 'delta_pct': None, 'window_days': 6}, [])",
    "empty|7": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'empty', 'baseline_value': None, 'window_value': None, 'delta_pct': None, 'window_days': 7}, [])",
    "empty|8": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'empty', 'baseline_value': None, 'window_value': None, 'delta_pct': None, 'window_days': 8}, [])",
    "empty|9": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'empty', 'baseline_value': None, 'window_value': None, 'delta_pct': None, 'window_days': 9}, [])",
    "forty_days_falling|1": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 81.0, 'window_value': 52.0, 'delta_pct': -35.8, 'window_days': 1, 'days_available': 28}, [])",
    "forty_days_falling|10": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 99.0, 'window_value': 61.0, 'delta_pct': -38.4, 'window_days': 10, 'days_available': 28}, [{'kind': 'heart_rate', 'trend': 'falling', 'days': 10, 'delta_pct': -38.4, 'notable': True, 'baseline_mode': 'rolling', 'baseline_value': 99.0}])",
    "forty_days_falling|11": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 101.0, 'window_value': 62.0, 'delta_pct': -38.6, 'window_days': 11, 'days_available': 28}, [{'kind': 'heart_rate', 'trend': 'falling', 'days': 11, 'delta_pct': -38.6, 'notable': True, 'baseline_mode': 'rolling', 'baseline_value': 101.0}])",
    "forty_days_falling|12": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 103.0, 'window_value': 63.0, 'delta_pct': -38.8, 'window_days': 12, 'days_available': 28}, [{'kind': 'heart_rate', 'trend': 'falling', 'days': 12, 'delta_pct': -38.8, 'notable': True, 'baseline_mode': 'rolling', 'baseline_value': 103.0}])",
    "forty_days_falling|13": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 104.0, 'window_value': 64.0, 'delta_pct': -38.5, 'window_days': 13, 'days_available': 27}, [{'kind': 'heart_rate', 'trend': 'falling', 'days': 13, 'delta_pct': -38.5, 'notable': True, 'baseline_mode': 'rolling', 'baseline_value': 104.0}])",
    "forty_days_falling|14": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 105.0, 'window_value': 65.0, 'delta_pct': -38.1, 'window_days': 14, 'days_available': 26}, [{'kind': 'heart_rate', 'trend': 'falling', 'days': 14, 'delta_pct': -38.1, 'notable': True, 'baseline_mode': 'rolling', 'baseline_value': 105.0}])",
    "forty_days_falling|2": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 83.0, 'window_value': 53.0, 'delta_pct': -36.1, 'window_days': 2, 'days_available': 28}, [])",
    "forty_days_falling|3": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 85.0, 'window_value': 54.0, 'delta_pct': -36.5, 'window_days': 3, 'days_available': 28}, [{'kind': 'heart_rate', 'trend': 'falling', 'days': 3, 'delta_pct': -36.5, 'notable': True, 'baseline_mode': 'rolling', 'baseline_value': 85.0}])",
    "forty_days_falling|4": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 87.0, 'window_value': 55.0, 'delta_pct': -36.8, 'window_days': 4, 'days_available': 28}, [{'kind': 'heart_rate', 'trend': 'falling', 'days': 4, 'delta_pct': -36.8, 'notable': True, 'baseline_mode': 'rolling', 'baseline_value': 87.0}])",
    "forty_days_falling|5": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 89.0, 'window_value': 56.0, 'delta_pct': -37.1, 'window_days': 5, 'days_available': 28}, [{'kind': 'heart_rate', 'trend': 'falling', 'days': 5, 'delta_pct': -37.1, 'notable': True, 'baseline_mode': 'rolling', 'baseline_value': 89.0}])",
    "forty_days_falling|6": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 91.0, 'window_value': 57.0, 'delta_pct': -37.4, 'window_days': 6, 'days_available': 28}, [{'kind': 'heart_rate', 'trend': 'falling', 'days': 6, 'delta_pct': -37.4, 'notable': True, 'baseline_mode': 'rolling', 'baseline_value': 91.0}])",
    "forty_days_falling|7": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 93.0, 'window_value': 58.0, 'delta_pct': -37.6, 'window_days': 7, 'days_available': 28}, [{'kind': 'heart_rate', 'trend': 'falling', 'days': 7, 'delta_pct': -37.6, 'notable': True, 'baseline_mode': 'rolling', 'baseline_value': 93.0}])",
    "forty_days_falling|8": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 95.0, 'window_value': 59.0, 'delta_pct': -37.9, 'window_days': 8, 'days_available': 28}, [{'kind': 'heart_rate', 'trend': 'falling', 'days': 8, 'delta_pct': -37.9, 'notable': True, 'baseline_mode': 'rolling', 'baseline_value': 95.0}])",
    "forty_days_falling|9": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 97.0, 'window_value': 60.0, 'delta_pct': -38.1, 'window_days': 9, 'days_available': 28}, [{'kind': 'heart_rate', 'trend': 'falling', 'days': 9, 'delta_pct': -38.1, 'notable': True, 'baseline_mode': 'rolling', 'baseline_value': 97.0}])",
    "forty_days_rising|1": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 99.0, 'window_value': 128.0, 'delta_pct': 29.3, 'window_days': 1, 'days_available': 28}, [])",
    "forty_days_rising|10": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 81.0, 'window_value': 119.0, 'delta_pct': 46.9, 'window_days': 10, 'days_available': 28}, [{'kind': 'heart_rate', 'trend': 'rising', 'days': 10, 'delta_pct': 46.9, 'notable': True, 'baseline_mode': 'rolling', 'baseline_value': 81.0}])",
    "forty_days_rising|11": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 79.0, 'window_value': 118.0, 'delta_pct': 49.4, 'window_days': 11, 'days_available': 28}, [{'kind': 'heart_rate', 'trend': 'rising', 'days': 11, 'delta_pct': 49.4, 'notable': True, 'baseline_mode': 'rolling', 'baseline_value': 79.0}])",
    "forty_days_rising|12": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 77.0, 'window_value': 117.0, 'delta_pct': 51.9, 'window_days': 12, 'days_available': 28}, [{'kind': 'heart_rate', 'trend': 'rising', 'days': 12, 'delta_pct': 51.9, 'notable': True, 'baseline_mode': 'rolling', 'baseline_value': 77.0}])",
    "forty_days_rising|13": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 76.0, 'window_value': 116.0, 'delta_pct': 52.6, 'window_days': 13, 'days_available': 27}, [{'kind': 'heart_rate', 'trend': 'rising', 'days': 13, 'delta_pct': 52.6, 'notable': True, 'baseline_mode': 'rolling', 'baseline_value': 76.0}])",
    "forty_days_rising|14": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 75.0, 'window_value': 115.0, 'delta_pct': 53.3, 'window_days': 14, 'days_available': 26}, [{'kind': 'heart_rate', 'trend': 'rising', 'days': 14, 'delta_pct': 53.3, 'notable': True, 'baseline_mode': 'rolling', 'baseline_value': 75.0}])",
    "forty_days_rising|2": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 97.0, 'window_value': 127.0, 'delta_pct': 30.9, 'window_days': 2, 'days_available': 28}, [])",
    "forty_days_rising|3": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 95.0, 'window_value': 126.0, 'delta_pct': 32.6, 'window_days': 3, 'days_available': 28}, [{'kind': 'heart_rate', 'trend': 'rising', 'days': 3, 'delta_pct': 32.6, 'notable': True, 'baseline_mode': 'rolling', 'baseline_value': 95.0}])",
    "forty_days_rising|4": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 93.0, 'window_value': 125.0, 'delta_pct': 34.4, 'window_days': 4, 'days_available': 28}, [{'kind': 'heart_rate', 'trend': 'rising', 'days': 4, 'delta_pct': 34.4, 'notable': True, 'baseline_mode': 'rolling', 'baseline_value': 93.0}])",
    "forty_days_rising|5": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 91.0, 'window_value': 124.0, 'delta_pct': 36.3, 'window_days': 5, 'days_available': 28}, [{'kind': 'heart_rate', 'trend': 'rising', 'days': 5, 'delta_pct': 36.3, 'notable': True, 'baseline_mode': 'rolling', 'baseline_value': 91.0}])",
    "forty_days_rising|6": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 89.0, 'window_value': 123.0, 'delta_pct': 38.2, 'window_days': 6, 'days_available': 28}, [{'kind': 'heart_rate', 'trend': 'rising', 'days': 6, 'delta_pct': 38.2, 'notable': True, 'baseline_mode': 'rolling', 'baseline_value': 89.0}])",
    "forty_days_rising|7": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 87.0, 'window_value': 122.0, 'delta_pct': 40.2, 'window_days': 7, 'days_available': 28}, [{'kind': 'heart_rate', 'trend': 'rising', 'days': 7, 'delta_pct': 40.2, 'notable': True, 'baseline_mode': 'rolling', 'baseline_value': 87.0}])",
    "forty_days_rising|8": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 85.0, 'window_value': 121.0, 'delta_pct': 42.4, 'window_days': 8, 'days_available': 28}, [{'kind': 'heart_rate', 'trend': 'rising', 'days': 8, 'delta_pct': 42.4, 'notable': True, 'baseline_mode': 'rolling', 'baseline_value': 85.0}])",
    "forty_days_rising|9": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 83.0, 'window_value': 120.0, 'delta_pct': 44.6, 'window_days': 9, 'days_available': 28}, [{'kind': 'heart_rate', 'trend': 'rising', 'days': 9, 'delta_pct': 44.6, 'notable': True, 'baseline_mode': 'rolling', 'baseline_value': 83.0}])",
    "forty_days_with_gaps|1": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 72.5, 'window_value': 72.0, 'delta_pct': -0.7, 'window_days': 1, 'days_available': 22}, [])",
    "forty_days_with_gaps|10": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 72.5, 'window_value': 72.3, 'delta_pct': -0.2, 'window_days': 10, 'days_available': 20}, [])",
    "forty_days_with_gaps|11": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 72.5, 'window_value': 72.5, 'delta_pct': 0.0, 'window_days': 11, 'days_available': 19}, [])",
    "forty_days_with_gaps|12": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 72.5, 'window_value': 72.4, 'delta_pct': -0.2, 'window_days': 12, 'days_available': 18}, [])",
    "forty_days_with_gaps|13": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 72.5, 'window_value': 72.4, 'delta_pct': -0.1, 'window_days': 13, 'days_available': 17}, [])",
    "forty_days_with_gaps|14": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 72.5, 'window_value': 72.4, 'delta_pct': -0.1, 'window_days': 14, 'days_available': 16}, [])",
    "forty_days_with_gaps|2": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 72.5, 'window_value': 72.5, 'delta_pct': 0.0, 'window_days': 2, 'days_available': 22}, [])",
    "forty_days_with_gaps|3": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 72.5, 'window_value': 72.5, 'delta_pct': 0.0, 'window_days': 3, 'days_available': 21}, [])",
    "forty_days_with_gaps|4": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 72.5, 'window_value': 72.4, 'delta_pct': -0.2, 'window_days': 4, 'days_available': 21}, [])",
    "forty_days_with_gaps|5": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 72.5, 'window_value': 72.2, 'delta_pct': -0.4, 'window_days': 5, 'days_available': 21}, [])",
    "forty_days_with_gaps|6": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 72.5, 'window_value': 72.2, 'delta_pct': -0.3, 'window_days': 6, 'days_available': 21}, [])",
    "forty_days_with_gaps|7": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 72.5, 'window_value': 72.4, 'delta_pct': -0.2, 'window_days': 7, 'days_available': 20}, [])",
    "forty_days_with_gaps|8": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 72.5, 'window_value': 72.2, 'delta_pct': -0.3, 'window_days': 8, 'days_available': 20}, [])",
    "forty_days_with_gaps|9": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 72.5, 'window_value': 72.3, 'delta_pct': -0.3, 'window_days': 9, 'days_available': 20}, [])",
    "many_samples_after_now|1": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'empty', 'baseline_value': None, 'window_value': None, 'delta_pct': None, 'window_days': 1}, [])",
    "many_samples_after_now|10": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'empty', 'baseline_value': None, 'window_value': None, 'delta_pct': None, 'window_days': 10}, [])",
    "many_samples_after_now|11": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'empty', 'baseline_value': None, 'window_value': None, 'delta_pct': None, 'window_days': 11}, [])",
    "many_samples_after_now|12": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'empty', 'baseline_value': None, 'window_value': None, 'delta_pct': None, 'window_days': 12}, [])",
    "many_samples_after_now|13": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'empty', 'baseline_value': None, 'window_value': None, 'delta_pct': None, 'window_days': 13}, [])",
    "many_samples_after_now|14": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'empty', 'baseline_value': None, 'window_value': None, 'delta_pct': None, 'window_days': 14}, [])",
    "many_samples_after_now|2": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'empty', 'baseline_value': None, 'window_value': None, 'delta_pct': None, 'window_days': 2}, [])",
    "many_samples_after_now|3": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'empty', 'baseline_value': None, 'window_value': None, 'delta_pct': None, 'window_days': 3}, [])",
    "many_samples_after_now|4": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'empty', 'baseline_value': None, 'window_value': None, 'delta_pct': None, 'window_days': 4}, [])",
    "many_samples_after_now|5": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'empty', 'baseline_value': None, 'window_value': None, 'delta_pct': None, 'window_days': 5}, [])",
    "many_samples_after_now|6": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'empty', 'baseline_value': None, 'window_value': None, 'delta_pct': None, 'window_days': 6}, [])",
    "many_samples_after_now|7": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'empty', 'baseline_value': None, 'window_value': None, 'delta_pct': None, 'window_days': 7}, [])",
    "many_samples_after_now|8": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'empty', 'baseline_value': None, 'window_value': None, 'delta_pct': None, 'window_days': 8}, [])",
    "many_samples_after_now|9": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'empty', 'baseline_value': None, 'window_value': None, 'delta_pct': None, 'window_days': 9}, [])",
    "single_sample_after_now|1": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'empty', 'baseline_value': None, 'window_value': None, 'delta_pct': None, 'window_days': 1}, [])",
    "single_sample_after_now|10": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'empty', 'baseline_value': None, 'window_value': None, 'delta_pct': None, 'window_days': 10}, [])",
    "single_sample_after_now|11": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'empty', 'baseline_value': None, 'window_value': None, 'delta_pct': None, 'window_days': 11}, [])",
    "single_sample_after_now|12": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'empty', 'baseline_value': None, 'window_value': None, 'delta_pct': None, 'window_days': 12}, [])",
    "single_sample_after_now|13": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'empty', 'baseline_value': None, 'window_value': None, 'delta_pct': None, 'window_days': 13}, [])",
    "single_sample_after_now|14": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'empty', 'baseline_value': None, 'window_value': None, 'delta_pct': None, 'window_days': 14}, [])",
    "single_sample_after_now|2": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'empty', 'baseline_value': None, 'window_value': None, 'delta_pct': None, 'window_days': 2}, [])",
    "single_sample_after_now|3": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'empty', 'baseline_value': None, 'window_value': None, 'delta_pct': None, 'window_days': 3}, [])",
    "single_sample_after_now|4": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'empty', 'baseline_value': None, 'window_value': None, 'delta_pct': None, 'window_days': 4}, [])",
    "single_sample_after_now|5": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'empty', 'baseline_value': None, 'window_value': None, 'delta_pct': None, 'window_days': 5}, [])",
    "single_sample_after_now|6": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'empty', 'baseline_value': None, 'window_value': None, 'delta_pct': None, 'window_days': 6}, [])",
    "single_sample_after_now|7": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'empty', 'baseline_value': None, 'window_value': None, 'delta_pct': None, 'window_days': 7}, [])",
    "single_sample_after_now|8": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'empty', 'baseline_value': None, 'window_value': None, 'delta_pct': None, 'window_days': 8}, [])",
    "single_sample_after_now|9": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'empty', 'baseline_value': None, 'window_value': None, 'delta_pct': None, 'window_days': 9}, [])",
    "seven_days_rolling_edge|1": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'bootstrap', 'baseline_value': 74.0, 'window_value': 63.5, 'delta_pct': -14.2, 'window_days': 1, 'days_available': 6}, [])",
    "seven_days_rolling_edge|10": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'empty', 'baseline_value': None, 'window_value': 72.5, 'delta_pct': None, 'window_days': 10, 'days_available': 0}, [])",
    "seven_days_rolling_edge|11": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'empty', 'baseline_value': None, 'window_value': 72.5, 'delta_pct': None, 'window_days': 11, 'days_available': 0}, [])",
    "seven_days_rolling_edge|12": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'empty', 'baseline_value': None, 'window_value': 72.5, 'delta_pct': None, 'window_days': 12, 'days_available': 0}, [])",
    "seven_days_rolling_edge|13": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'empty', 'baseline_value': None, 'window_value': 72.5, 'delta_pct': None, 'window_days': 13, 'days_available': 0}, [])",
    "seven_days_rolling_edge|14": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'empty', 'baseline_value': None, 'window_value': 72.5, 'delta_pct': None, 'window_days': 14, 'days_available': 0}, [])",
    "seven_days_rolling_edge|2": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'bootstrap', 'baseline_value': 75.5, 'window_value': 65.0, 'delta_pct': -13.9, 'window_days': 2, 'days_available': 5}, [])",
    "seven_days_rolling_edge|3": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'bootstrap', 'baseline_value': 77.0, 'window_value': 66.5, 'delta_pct': -13.6, 'window_days': 3, 'days_available': 4}, [])",
    "seven_days_rolling_edge|4": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'bootstrap', 'baseline_value': 78.5, 'window_value': 68.0, 'delta_pct': -13.4, 'window_days': 4, 'days_available': 3}, [])",
    "seven_days_rolling_edge|5": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'bootstrap', 'baseline_value': 80.0, 'window_value': 69.5, 'delta_pct': -13.1, 'window_days': 5, 'days_available': 2}, [])",
    "seven_days_rolling_edge|6": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'bootstrap', 'baseline_value': 81.5, 'window_value': 71.0, 'delta_pct': -12.9, 'window_days': 6, 'days_available': 1}, [])",
    "seven_days_rolling_edge|7": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'empty', 'baseline_value': None, 'window_value': 72.5, 'delta_pct': None, 'window_days': 7, 'days_available': 0}, [])",
    "seven_days_rolling_edge|8": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'empty', 'baseline_value': None, 'window_value': 72.5, 'delta_pct': None, 'window_days': 8, 'days_available': 0}, [])",
    "seven_days_rolling_edge|9": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'empty', 'baseline_value': None, 'window_value': 72.5, 'delta_pct': None, 'window_days': 9, 'days_available': 0}, [])",
    "six_days_bootstrap_edge|1": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'bootstrap', 'baseline_value': 72.5, 'window_value': 63.5, 'delta_pct': -12.4, 'window_days': 1, 'days_available': 5}, [])",
    "six_days_bootstrap_edge|10": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'empty', 'baseline_value': None, 'window_value': 71.0, 'delta_pct': None, 'window_days': 10, 'days_available': 0}, [])",
    "six_days_bootstrap_edge|11": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'empty', 'baseline_value': None, 'window_value': 71.0, 'delta_pct': None, 'window_days': 11, 'days_available': 0}, [])",
    "six_days_bootstrap_edge|12": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'empty', 'baseline_value': None, 'window_value': 71.0, 'delta_pct': None, 'window_days': 12, 'days_available': 0}, [])",
    "six_days_bootstrap_edge|13": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'empty', 'baseline_value': None, 'window_value': 71.0, 'delta_pct': None, 'window_days': 13, 'days_available': 0}, [])",
    "six_days_bootstrap_edge|14": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'empty', 'baseline_value': None, 'window_value': 71.0, 'delta_pct': None, 'window_days': 14, 'days_available': 0}, [])",
    "six_days_bootstrap_edge|2": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'bootstrap', 'baseline_value': 74.0, 'window_value': 65.0, 'delta_pct': -12.2, 'window_days': 2, 'days_available': 4}, [])",
    "six_days_bootstrap_edge|3": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'bootstrap', 'baseline_value': 75.5, 'window_value': 66.5, 'delta_pct': -11.9, 'window_days': 3, 'days_available': 3}, [])",
    "six_days_bootstrap_edge|4": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'bootstrap', 'baseline_value': 77.0, 'window_value': 68.0, 'delta_pct': -11.7, 'window_days': 4, 'days_available': 2}, [])",
    "six_days_bootstrap_edge|5": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'bootstrap', 'baseline_value': 78.5, 'window_value': 69.5, 'delta_pct': -11.5, 'window_days': 5, 'days_available': 1}, [])",
    "six_days_bootstrap_edge|6": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'empty', 'baseline_value': None, 'window_value': 71.0, 'delta_pct': None, 'window_days': 6, 'days_available': 0}, [])",
    "six_days_bootstrap_edge|7": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'empty', 'baseline_value': None, 'window_value': 71.0, 'delta_pct': None, 'window_days': 7, 'days_available': 0}, [])",
    "six_days_bootstrap_edge|8": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'empty', 'baseline_value': None, 'window_value': 71.0, 'delta_pct': None, 'window_days': 8, 'days_available': 0}, [])",
    "six_days_bootstrap_edge|9": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'empty', 'baseline_value': None, 'window_value': 71.0, 'delta_pct': None, 'window_days': 9, 'days_available': 0}, [])",
    "steps_all_zero|1": "({'kind': 'steps', 'unit': 'steps', 'mode': 'rolling', 'baseline_value': 0.0, 'window_value': 0.0, 'delta_pct': None, 'window_days': 1, 'days_available': 19}, [])",
    "steps_all_zero|10": "({'kind': 'steps', 'unit': 'steps', 'mode': 'rolling', 'baseline_value': 0.0, 'window_value': 0.0, 'delta_pct': None, 'window_days': 10, 'days_available': 10}, [{'event': 'inactivity_streak', 'kind': 'steps', 'days': 10}])",
    "steps_all_zero|11": "({'kind': 'steps', 'unit': 'steps', 'mode': 'rolling', 'baseline_value': 0.0, 'window_value': 0.0, 'delta_pct': None, 'window_days': 11, 'days_available': 9}, [{'event': 'inactivity_streak', 'kind': 'steps', 'days': 11}])",
    "steps_all_zero|12": "({'kind': 'steps', 'unit': 'steps', 'mode': 'rolling', 'baseline_value': 0.0, 'window_value': 0.0, 'delta_pct': None, 'window_days': 12, 'days_available': 8}, [{'event': 'inactivity_streak', 'kind': 'steps', 'days': 12}])",
    "steps_all_zero|13": "({'kind': 'steps', 'unit': 'steps', 'mode': 'rolling', 'baseline_value': 0.0, 'window_value': 0.0, 'delta_pct': None, 'window_days': 13, 'days_available': 7}, [{'event': 'inactivity_streak', 'kind': 'steps', 'days': 13}])",
    "steps_all_zero|14": "({'kind': 'steps', 'unit': 'steps', 'mode': 'bootstrap', 'baseline_value': 0.0, 'window_value': 0.0, 'delta_pct': None, 'window_days': 14, 'days_available': 6}, [{'event': 'inactivity_streak', 'kind': 'steps', 'days': 14}])",
    "steps_all_zero|2": "({'kind': 'steps', 'unit': 'steps', 'mode': 'rolling', 'baseline_value': 0.0, 'window_value': 0.0, 'delta_pct': None, 'window_days': 2, 'days_available': 18}, [])",
    "steps_all_zero|3": "({'kind': 'steps', 'unit': 'steps', 'mode': 'rolling', 'baseline_value': 0.0, 'window_value': 0.0, 'delta_pct': None, 'window_days': 3, 'days_available': 17}, [{'event': 'inactivity_streak', 'kind': 'steps', 'days': 3}])",
    "steps_all_zero|4": "({'kind': 'steps', 'unit': 'steps', 'mode': 'rolling', 'baseline_value': 0.0, 'window_value': 0.0, 'delta_pct': None, 'window_days': 4, 'days_available': 16}, [{'event': 'inactivity_streak', 'kind': 'steps', 'days': 4}])",
    "steps_all_zero|5": "({'kind': 'steps', 'unit': 'steps', 'mode': 'rolling', 'baseline_value': 0.0, 'window_value': 0.0, 'delta_pct': None, 'window_days': 5, 'days_available': 15}, [{'event': 'inactivity_streak', 'kind': 'steps', 'days': 5}])",
    "steps_all_zero|6": "({'kind': 'steps', 'unit': 'steps', 'mode': 'rolling', 'baseline_value': 0.0, 'window_value': 0.0, 'delta_pct': None, 'window_days': 6, 'days_available': 14}, [{'event': 'inactivity_streak', 'kind': 'steps', 'days': 6}])",
    "steps_all_zero|7": "({'kind': 'steps', 'unit': 'steps', 'mode': 'rolling', 'baseline_value': 0.0, 'window_value': 0.0, 'delta_pct': None, 'window_days': 7, 'days_available': 13}, [{'event': 'inactivity_streak', 'kind': 'steps', 'days': 7}])",
    "steps_all_zero|8": "({'kind': 'steps', 'unit': 'steps', 'mode': 'rolling', 'baseline_value': 0.0, 'window_value': 0.0, 'delta_pct': None, 'window_days': 8, 'days_available': 12}, [{'event': 'inactivity_streak', 'kind': 'steps', 'days': 8}])",
    "steps_all_zero|9": "({'kind': 'steps', 'unit': 'steps', 'mode': 'rolling', 'baseline_value': 0.0, 'window_value': 0.0, 'delta_pct': None, 'window_days': 9, 'days_available': 11}, [{'event': 'inactivity_streak', 'kind': 'steps', 'days': 9}])",
    "steps_constant|1": "({'kind': 'steps', 'unit': 'steps', 'mode': 'rolling', 'baseline_value': 8000.0, 'window_value': 8000.0, 'delta_pct': 0.0, 'window_days': 1, 'days_available': 28}, [])",
    "steps_constant|10": "({'kind': 'steps', 'unit': 'steps', 'mode': 'rolling', 'baseline_value': 8000.0, 'window_value': 8000.0, 'delta_pct': 0.0, 'window_days': 10, 'days_available': 20}, [])",
    "steps_constant|11": "({'kind': 'steps', 'unit': 'steps', 'mode': 'rolling', 'baseline_value': 8000.0, 'window_value': 8000.0, 'delta_pct': 0.0, 'window_days': 11, 'days_available': 19}, [])",
    "steps_constant|12": "({'kind': 'steps', 'unit': 'steps', 'mode': 'rolling', 'baseline_value': 8000.0, 'window_value': 8000.0, 'delta_pct': 0.0, 'window_days': 12, 'days_available': 18}, [])",
    "steps_constant|13": "({'kind': 'steps', 'unit': 'steps', 'mode': 'rolling', 'baseline_value': 8000.0, 'window_value': 8000.0, 'delta_pct': 0.0, 'window_days': 13, 'days_available': 17}, [])",
    "steps_constant|14": "({'kind': 'steps', 'unit': 'steps', 'mode': 'rolling', 'baseline_value': 8000.0, 'window_value': 8000.0, 'delta_pct': 0.0, 'window_days': 14, 'days_available': 16}, [])",
    "steps_constant|2": "({'kind': 'steps', 'unit': 'steps', 'mode': 'rolling', 'baseline_value': 8000.0, 'window_value': 8000.0, 'delta_pct': 0.0, 'window_days': 2, 'days_available': 28}, [])",
    "steps_constant|3": "({'kind': 'steps', 'unit': 'steps', 'mode': 'rolling', 'baseline_value': 8000.0, 'window_value': 8000.0, 'delta_pct': 0.0, 'window_days': 3, 'days_available': 27}, [])",
    "steps_constant|4": "({'kind': 'steps', 'unit': 'steps', 'mode': 'rolling', 'baseline_value': 8000.0, 'window_value': 8000.0, 'delta_pct': 0.0, 'window_days': 4, 'days_available': 26}, [])",
    "steps_constant|5": "({'kind': 'steps', 'unit': 'steps', 'mode': 'rolling', 'baseline_value': 8000.0, 'window_value': 8000.0, 'delta_pct': 0.0, 'window_days': 5, 'days_available': 25}, [])",
    "steps_constant|6": "({'kind': 'steps', 'unit': 'steps', 'mode': 'rolling', 'baseline_value': 8000.0, 'window_value': 8000.0, 'delta_pct': 0.0, 'window_days': 6, 'days_available': 24}, [])",
    "steps_constant|7": "({'kind': 'steps', 'unit': 'steps', 'mode': 'rolling', 'baseline_value': 8000.0, 'window_value': 8000.0, 'delta_pct': 0.0, 'window_days': 7, 'days_available': 23}, [])",
    "steps_constant|8": "({'kind': 'steps', 'unit': 'steps', 'mode': 'rolling', 'baseline_value': 8000.0, 'window_value': 8000.0, 'delta_pct': 0.0, 'window_days': 8, 'days_available': 22}, [])",
    "steps_constant|9": "({'kind': 'steps', 'unit': 'steps', 'mode': 'rolling', 'baseline_value': 8000.0, 'window_value': 8000.0, 'delta_pct': 0.0, 'window_days': 9, 'days_available': 21}, [])",
    "steps_then_five_zero_days|1": "({'kind': 'steps', 'unit': 'steps', 'mode': 'rolling', 'baseline_value': 9000.0, 'window_value': 0.0, 'delta_pct': -100.0, 'window_days': 1, 'days_available': 28}, [])",
    "steps_then_five_zero_days|10": "({'kind': 'steps', 'unit': 'steps', 'mode': 'rolling', 'baseline_value': 9000.0, 'window_value': 4500.0, 'delta_pct': -50.0, 'window_days': 10, 'days_available': 20}, [{'kind': 'steps', 'trend': 'falling', 'days': 5, 'delta_pct': -100.0, 'notable': True, 'baseline_mode': 'rolling', 'baseline_value': 9000.0}, {'event': 'inactivity_streak', 'kind': 'steps', 'days': 5}])",
    "steps_then_five_zero_days|11": "({'kind': 'steps', 'unit': 'steps', 'mode': 'rolling', 'baseline_value': 9000.0, 'window_value': 4909.1, 'delta_pct': -45.5, 'window_days': 11, 'days_available': 19}, [{'kind': 'steps', 'trend': 'falling', 'days': 5, 'delta_pct': -100.0, 'notable': True, 'baseline_mode': 'rolling', 'baseline_value': 9000.0}, {'event': 'inactivity_streak', 'kind': 'steps', 'days': 5}])",
    "steps_then_five_zero_days|12": "({'kind': 'steps', 'unit': 'steps', 'mode': 'rolling', 'baseline_value': 9000.0, 'window_value': 5250.0, 'delta_pct': -41.7, 'window_days': 12, 'days_available': 18}, [{'kind': 'steps', 'trend': 'falling', 'days': 5, 'delta_pct': -100.0, 'notable': True, 'baseline_mode': 'rolling', 'baseline_value': 9000.0}, {'event': 'inactivity_streak', 'kind': 'steps', 'days': 5}])",
    "steps_then_five_zero_days|13": "({'kind': 'steps', 'unit': 'steps', 'mode': 'rolling', 'baseline_value': 9000.0, 'window_value': 5538.5, 'delta_pct': -38.5, 'window_days': 13, 'days_available': 17}, [{'kind': 'steps', 'trend': 'falling', 'days': 5, 'delta_pct': -100.0, 'notable': True, 'baseline_mode': 'rolling', 'baseline_value': 9000.0}, {'event': 'inactivity_streak', 'kind': 'steps', 'days': 5}])",
    "steps_then_five_zero_days|14": "({'kind': 'steps', 'unit': 'steps', 'mode': 'rolling', 'baseline_value': 9000.0, 'window_value': 5785.7, 'delta_pct': -35.7, 'window_days': 14, 'days_available': 16}, [{'kind': 'steps', 'trend': 'falling', 'days': 5, 'delta_pct': -100.0, 'notable': True, 'baseline_mode': 'rolling', 'baseline_value': 9000.0}, {'event': 'inactivity_streak', 'kind': 'steps', 'days': 5}])",
    "steps_then_five_zero_days|2": "({'kind': 'steps', 'unit': 'steps', 'mode': 'rolling', 'baseline_value': 9000.0, 'window_value': 0.0, 'delta_pct': -100.0, 'window_days': 2, 'days_available': 28}, [])",
    "steps_then_five_zero_days|3": "({'kind': 'steps', 'unit': 'steps', 'mode': 'rolling', 'baseline_value': 9000.0, 'window_value': 0.0, 'delta_pct': -100.0, 'window_days': 3, 'days_available': 27}, [{'kind': 'steps', 'trend': 'falling', 'days': 3, 'delta_pct': -100.0, 'notable': True, 'baseline_mode': 'rolling', 'baseline_value': 9000.0}, {'event': 'inactivity_streak', 'kind': 'steps', 'days': 3}])",
    "steps_then_five_zero_days|4": "({'kind': 'steps', 'unit': 'steps', 'mode': 'rolling', 'baseline_value': 9000.0, 'window_value': 0.0, 'delta_pct': -100.0, 'window_days': 4, 'days_available': 26}, [{'kind': 'steps', 'trend': 'falling', 'days': 4, 'delta_pct': -100.0, 'notable': True, 'baseline_mode': 'rolling', 'baseline_value': 9000.0}, {'event': 'inactivity_streak', 'kind': 'steps', 'days': 4}])",
    "steps_then_five_zero_days|5": "({'kind': 'steps', 'unit': 'steps', 'mode': 'rolling', 'baseline_value': 9000.0, 'window_value': 0.0, 'delta_pct': -100.0, 'window_days': 5, 'days_available': 25}, [{'kind': 'steps', 'trend': 'falling', 'days': 5, 'delta_pct': -100.0, 'notable': True, 'baseline_mode': 'rolling', 'baseline_value': 9000.0}, {'event': 'inactivity_streak', 'kind': 'steps', 'days': 5}])",
    "steps_then_five_zero_days|6": "({'kind': 'steps', 'unit': 'steps', 'mode': 'rolling', 'baseline_value': 9000.0, 'window_value': 1500.0, 'delta_pct': -83.3, 'window_days': 6, 'days_available': 24}, [{'kind': 'steps', 'trend': 'falling', 'days': 5, 'delta_pct': -100.0, 'notable': True, 'baseline_mode': 'rolling', 'baseline_value': 9000.0}, {'event': 'inactivity_streak', 'kind': 'steps', 'days': 5}])",
    "steps_then_five_zero_days|7": "({'kind': 'steps', 'unit': 'steps', 'mode': 'rolling', 'baseline_value': 9000.0, 'window_value': 2571.4, 'delta_pct': -71.4, 'window_days': 7, 'days_available': 23}, [{'kind': 'steps', 'trend': 'falling', 'days': 5, 'delta_pct': -100.0, 'notable': True, 'baseline_mode': 'rolling', 'baseline_value': 9000.0}, {'event': 'inactivity_streak', 'kind': 'steps', 'days': 5}])",
    "steps_then_five_zero_days|8": "({'kind': 'steps', 'unit': 'steps', 'mode': 'rolling', 'baseline_value': 9000.0, 'window_value': 3375.0, 'delta_pct': -62.5, 'window_days': 8, 'days_available': 22}, [{'kind': 'steps', 'trend': 'falling', 'days': 5, 'delta_pct': -100.0, 'notable': True, 'baseline_mode': 'rolling', 'baseline_value': 9000.0}, {'event': 'inactivity_streak', 'kind': 'steps', 'days': 5}])",
    "steps_then_five_zero_days|9": "({'kind': 'steps', 'unit': 'steps', 'mode': 'rolling', 'baseline_value': 9000.0, 'window_value': 4000.0, 'delta_pct': -55.6, 'window_days': 9, 'days_available': 21}, [{'kind': 'steps', 'trend': 'falling', 'days': 5, 'delta_pct': -100.0, 'notable': True, 'baseline_mode': 'rolling', 'baseline_value': 9000.0}, {'event': 'inactivity_streak', 'kind': 'steps', 'days': 5}])",
    "three_days_last_in_future|1": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'bootstrap', 'baseline_value': 61.0, 'window_value': 70.0, 'delta_pct': 14.8, 'window_days': 1, 'days_available': 1}, [])",
    "three_days_last_in_future|10": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'empty', 'baseline_value': None, 'window_value': 65.5, 'delta_pct': None, 'window_days': 10, 'days_available': 0}, [])",
    "three_days_last_in_future|11": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'empty', 'baseline_value': None, 'window_value': 65.5, 'delta_pct': None, 'window_days': 11, 'days_available': 0}, [])",
    "three_days_last_in_future|12": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'empty', 'baseline_value': None, 'window_value': 65.5, 'delta_pct': None, 'window_days': 12, 'days_available': 0}, [])",
    "three_days_last_in_future|13": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'empty', 'baseline_value': None, 'window_value': 65.5, 'delta_pct': None, 'window_days': 13, 'days_available': 0}, [])",
    "three_days_last_in_future|14": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'empty', 'baseline_value': None, 'window_value': 65.5, 'delta_pct': None, 'window_days': 14, 'days_available': 0}, [])",
    "three_days_last_in_future|2": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'empty', 'baseline_value': None, 'window_value': 65.5, 'delta_pct': None, 'window_days': 2, 'days_available': 0}, [])",
    "three_days_last_in_future|3": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'empty', 'baseline_value': None, 'window_value': 65.5, 'delta_pct': None, 'window_days': 3, 'days_available': 0}, [])",
    "three_days_last_in_future|4": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'empty', 'baseline_value': None, 'window_value': 65.5, 'delta_pct': None, 'window_days': 4, 'days_available': 0}, [])",
    "three_days_last_in_future|5": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'empty', 'baseline_value': None, 'window_value': 65.5, 'delta_pct': None, 'window_days': 5, 'days_available': 0}, [])",
    "three_days_last_in_future|6": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'empty', 'baseline_value': None, 'window_value': 65.5, 'delta_pct': None, 'window_days': 6, 'days_available': 0}, [])",
    "three_days_last_in_future|7": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'empty', 'baseline_value': None, 'window_value': 65.5, 'delta_pct': None, 'window_days': 7, 'days_available': 0}, [])",
    "three_days_last_in_future|8": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'empty', 'baseline_value': None, 'window_value': 65.5, 'delta_pct': None, 'window_days': 8, 'days_available': 0}, [])",
    "three_days_last_in_future|9": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'empty', 'baseline_value': None, 'window_value': 65.5, 'delta_pct': None, 'window_days': 9, 'days_available': 0}, [])",
    "zero_values_null_baseline|1": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 0.0, 'window_value': 0.0, 'delta_pct': None, 'window_days': 1, 'days_available': 19}, [])",
    "zero_values_null_baseline|10": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 0.0, 'window_value': 0.0, 'delta_pct': None, 'window_days': 10, 'days_available': 10}, [])",
    "zero_values_null_baseline|11": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 0.0, 'window_value': 0.0, 'delta_pct': None, 'window_days': 11, 'days_available': 9}, [])",
    "zero_values_null_baseline|12": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 0.0, 'window_value': 0.0, 'delta_pct': None, 'window_days': 12, 'days_available': 8}, [])",
    "zero_values_null_baseline|13": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 0.0, 'window_value': 0.0, 'delta_pct': None, 'window_days': 13, 'days_available': 7}, [])",
    "zero_values_null_baseline|14": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'bootstrap', 'baseline_value': 0.0, 'window_value': 0.0, 'delta_pct': None, 'window_days': 14, 'days_available': 6}, [])",
    "zero_values_null_baseline|2": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 0.0, 'window_value': 0.0, 'delta_pct': None, 'window_days': 2, 'days_available': 18}, [])",
    "zero_values_null_baseline|3": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 0.0, 'window_value': 0.0, 'delta_pct': None, 'window_days': 3, 'days_available': 17}, [])",
    "zero_values_null_baseline|4": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 0.0, 'window_value': 0.0, 'delta_pct': None, 'window_days': 4, 'days_available': 16}, [])",
    "zero_values_null_baseline|5": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 0.0, 'window_value': 0.0, 'delta_pct': None, 'window_days': 5, 'days_available': 15}, [])",
    "zero_values_null_baseline|6": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 0.0, 'window_value': 0.0, 'delta_pct': None, 'window_days': 6, 'days_available': 14}, [])",
    "zero_values_null_baseline|7": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 0.0, 'window_value': 0.0, 'delta_pct': None, 'window_days': 7, 'days_available': 13}, [])",
    "zero_values_null_baseline|8": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 0.0, 'window_value': 0.0, 'delta_pct': None, 'window_days': 8, 'days_available': 12}, [])",
    "zero_values_null_baseline|9": "({'kind': 'heart_rate', 'unit': 'bpm', 'mode': 'rolling', 'baseline_value': 0.0, 'window_value': 0.0, 'delta_pct': None, 'window_days': 9, 'days_available': 11}, [])",
}

# Unrounded per-day aggregates + raw baseline, per case. Catches drift
# below the 1-decimal rounding of the service payload (bit-exactness).
EXPECTED_DAILY: dict[str, str] = {
    "avg_repeating_decimals": "([72.0, 73.66666666666667, 72.66666666666667, 74.0, 74.0, 73.0, 73.66666666666667, 73.66666666666667, 72.66666666666667, 71.66666666666667, 74.0, 74.66666666666667, 73.66666666666667, 73.66666666666667, 72.66666666666667, 71.66666666666667, 73.33333333333333, 74.66666666666667, 73.66666666666667, 73.66666666666667, 72.66666666666667, 73.33333333333333, 73.33333333333333, 72.33333333333333, 73.66666666666667, 73.66666666666667, 74.33333333333333, 73.33333333333333, 73.33333333333333, 72.33333333333333], ('rolling', 73.5, 28))",
    "avg_seven_samples_per_day": "([65.0, 63.57142857142857, 65.28571428571429, 67.0, 64.0, 64.14285714285714, 65.85714285714286, 66.0, 63.0, 64.71428571428571, 66.42857142857143, 65.0, 63.57142857142857, 65.28571428571429, 67.0, 64.0, 64.14285714285714, 65.85714285714286, 66.0, 63.0, 64.71428571428571, 66.42857142857143, 65.0, 63.57142857142857, 65.28571428571429, 67.0, 64.0, 64.14285714285714, 65.85714285714286, 66.0], ('rolling', 65.14285714285714, 28))",
    "empty": "([], ('empty', None, 0))",
    "forty_days_falling": "([130.0, 128.0, 126.0, 124.0, 122.0, 120.0, 118.0, 116.0, 114.0, 112.0, 110.0, 108.0, 106.0, 104.0, 102.0, 100.0, 98.0, 96.0, 94.0, 92.0, 90.0, 88.0, 86.0, 84.0, 82.0, 80.0, 78.0, 76.0, 74.0, 72.0, 70.0, 68.0, 66.0, 64.0, 62.0, 60.0, 58.0, 56.0, 54.0, 52.0], ('rolling', 79.0, 28))",
    "forty_days_rising": "([50.0, 52.0, 54.0, 56.0, 58.0, 60.0, 62.0, 64.0, 66.0, 68.0, 70.0, 72.0, 74.0, 76.0, 78.0, 80.0, 82.0, 84.0, 86.0, 88.0, 90.0, 92.0, 94.0, 96.0, 98.0, 100.0, 102.0, 104.0, 106.0, 108.0, 110.0, 112.0, 114.0, 116.0, 118.0, 120.0, 122.0, 124.0, 126.0, 128.0], ('rolling', 101.0, 28))",
    "forty_days_with_gaps": "([73.0, 73.5, 72.5, 72.0, 73.5, 72.5, 72.0, 71.0, 74.0, 72.0, 72.5, 71.5, 73.5, 72.5, 71.5, 73.5, 72.5, 73.0, 71.0, 74.0, 73.0, 72.5, 71.5, 73.0, 72.5, 71.5, 72.0, 72.5, 73.0, 72.0], ('rolling', 72.5, 28))",
    "many_samples_after_now": "([71.5], ('bootstrap', 71.5, 1))",
    "single_sample_after_now": "([70.0], ('bootstrap', 70.0, 1))",
    "seven_days_rolling_edge": "([81.5, 78.5, 75.5, 72.5, 69.5, 66.5, 63.5], ('rolling', 72.5, 7))",
    "six_days_bootstrap_edge": "([78.5, 75.5, 72.5, 69.5, 66.5, 63.5], ('bootstrap', 71.0, 6))",
    "steps_all_zero": "([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], ('rolling', 0.0, 20))",
    "steps_constant": "([8000.0, 8000.0, 8000.0, 8000.0, 8000.0, 8000.0, 8000.0, 8000.0, 8000.0, 8000.0, 8000.0, 8000.0, 8000.0, 8000.0, 8000.0, 8000.0, 8000.0, 8000.0, 8000.0, 8000.0, 8000.0, 8000.0, 8000.0, 8000.0, 8000.0, 8000.0, 8000.0, 8000.0, 8000.0, 8000.0], ('rolling', 8000.0, 28))",
    "steps_then_five_zero_days": "([9000.0, 9000.0, 9000.0, 9000.0, 9000.0, 9000.0, 9000.0, 9000.0, 9000.0, 9000.0, 9000.0, 9000.0, 9000.0, 9000.0, 9000.0, 9000.0, 9000.0, 9000.0, 9000.0, 9000.0, 9000.0, 9000.0, 9000.0, 9000.0, 9000.0, 0.0, 0.0, 0.0, 0.0, 0.0], ('rolling', 9000.0, 28))",
    "three_days_last_in_future": "([61.0, 70.0, 82.0], ('bootstrap', 70.0, 3))",
    "zero_values_null_baseline": "([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], ('rolling', 0.0, 20))",
}


# =============================================================================
# The net
# =============================================================================


def _service_with(samples: list[HealthSample]) -> HealthMetricsService:
    service = HealthMetricsService(MagicMock())
    service.sample_repo = _FakeSampleRepo(samples)  # type: ignore[assignment]
    return service


@pytest.mark.parametrize(
    "case_name,kind,day_values",
    CASES,
    ids=[case[0] for case in CASES],
)
@pytest.mark.parametrize("window_days", WINDOW_DAYS)
async def test_baseline_and_variations_are_pinned(
    case_name: str,
    kind: str,
    day_values: list[tuple[int, list[int]]],
    window_days: int,
) -> None:
    """Service output must be byte-identical to the pre-conversion golden."""
    service = _service_with(_make_samples(kind, day_values))

    delta = await service.compute_kind_baseline_delta(USER_ID, kind, window_days=window_days)
    variations = await service.detect_all_variations(USER_ID, window_days=window_days)

    assert repr((delta, variations)) == EXPECTED[f"{case_name}|{window_days}"]


def test_golden_table_covers_every_case_and_window() -> None:
    """Guard the net against silent shrinkage (a dropped case still passes)."""
    assert set(EXPECTED) == {f"{name}|{w}" for name, _, _ in CASES for w in WINDOW_DAYS}
    assert len(EXPECTED) == len(CASES) * len(WINDOW_DAYS)


def test_golden_table_is_not_vacuous() -> None:
    """A net that only pins empty results would survive any regression.

    Asserts the table actually exercises the branches its docstring claims:
    every baseline mode, both trend directions, and the notable-event path.
    """
    blob = "".join(EXPECTED.values())
    for mode in ("'mode': 'empty'", "'mode': 'bootstrap'", "'mode': 'rolling'"):
        assert mode in blob, f"golden table never exercises {mode}"
    assert "'trend': 'rising'" in blob
    assert "'trend': 'falling'" in blob
    assert "'event': 'inactivity_streak'" in blob


@pytest.mark.parametrize("case_name,kind,day_values", CASES, ids=[case[0] for case in CASES])
def test_unrounded_daily_aggregates_are_pinned(
    case_name: str,
    kind: str,
    day_values: list[tuple[int, list[int]]],
) -> None:
    """Pin the aggregation contract BELOW the service payload's rounding.

    ``compute_kind_baseline_delta`` rounds every number to one decimal, so a
    sub-0.05 drift is invisible in the main net (verified by mutation testing:
    rounding the daily average to 1 decimal leaves all 182 entries green).
    The rollup's correctness claim is *bit-exactness*, so it is pinned here,
    on the raw values: per-day aggregates and the unrounded baseline median.
    """
    spec = HEALTH_KINDS[kind]
    samples = _make_samples(kind, day_values)

    daily = _daily_aggregate(samples, spec.baseline_kind)
    baseline = compute_baseline(samples, spec)

    assert (
        repr((daily, (baseline.mode, baseline.median_value, baseline.days_available)))
        == EXPECTED_DAILY[case_name]
    )


@pytest.mark.parametrize("case_name,kind,day_values", CASES, ids=[case[0] for case in CASES])
def test_rollup_matches_in_python_grouping(
    case_name: str,
    kind: str,
    day_values: list[tuple[int, list[int]]],
) -> None:
    """``daily_stats_from_samples`` must reproduce ``_daily_aggregate`` exactly.

    This is the in-memory half of the rollup equivalence; the SQL half (that
    PostgreSQL's per-day ``sum``/``count``/``min`` equals this grouping) is
    pinned by the integration test against a real database.
    """
    spec = HEALTH_KINDS[kind]
    samples = _make_samples(kind, day_values)

    stats = daily_stats_from_samples(samples)
    derived = [_stat_value(stat, spec.baseline_kind) for stat in stats]

    assert derived == _daily_aggregate(samples, spec.baseline_kind)
    assert [stat.day for stat in stats] == sorted(_group_samples_by_day(samples))
    assert all(stat.count >= 1 for stat in stats)
    assert [stat.total for stat in stats] == [
        sum(_group_samples_by_day(samples)[stat.day]) for stat in stats
    ]


@pytest.mark.parametrize(
    "baseline_kind,expected",
    [
        (BaselineKind.DAILY_SUM, 300.0),
        (BaselineKind.DAILY_AVG, 100.0),
        (BaselineKind.RESTING, 60.0),
    ],
)
def test_stat_value_reduces_each_baseline_kind(
    baseline_kind: BaselineKind, expected: float
) -> None:
    """``RESTING`` is unreachable from the registry today, but the branch must
    stay correct for the future kinds its placeholder was written for."""
    stat = DailyStat(day=FROZEN_NOW.date(), total=300, count=3, minimum=60)

    assert _stat_value(stat, baseline_kind) == expected


def test_stat_value_handles_every_baseline_kind() -> None:
    """Completeness guard: a new ``BaselineKind`` without a ``match`` arm would
    fall through and return ``None`` silently, poisoning every downstream
    median. Enum-keyed reductions get an explicit exhaustiveness check (same
    doctrine as the boot-time registry asserts)."""
    stat = DailyStat(day=FROZEN_NOW.date(), total=300, count=3, minimum=60)

    for baseline_kind in BaselineKind:
        assert isinstance(_stat_value(stat, baseline_kind), float), baseline_kind


# =============================================================================
# Explicit coverage the golden table cannot carry (see the fixture-clock note)
# =============================================================================


async def test_single_visible_day_yields_empty_baseline_and_no_variation() -> None:
    """A one-day series: the window swallows it, leaving no baseline.

    ``compute_kind_delta_from_stats`` splits off ``min(window_days, len)`` days
    as the window, so a single day leaves an empty baseline prefix (``mode``
    ``empty``) while still reporting the window value. ``detect_recent_variations``
    then compares the day against itself — a zero delta, never a streak.
    """
    service = _service_with(_make_samples("heart_rate", [(3, [70, 80])]))

    delta = await service.compute_kind_baseline_delta(USER_ID, "heart_rate", window_days=7)
    variations = await service.detect_all_variations(USER_ID, window_days=7)

    assert delta["mode"] == "empty"
    assert delta["window_value"] == 75.0
    assert delta["baseline_value"] is None
    assert delta["delta_pct"] is None
    assert delta["days_available"] == 0
    assert variations == []


async def test_single_visible_day_steps_zero_is_not_an_inactivity_streak() -> None:
    """One zero-step day must not trip the streak (threshold is 3 days)."""
    service = _service_with(_make_samples("steps", [(3, [0])]))

    variations = await service.detect_all_variations(USER_ID, window_days=7)

    assert variations == []


async def test_samples_dated_after_now_are_excluded() -> None:
    """The ``date_start < to_ts`` bound is a contract, not an accident.

    A device clock ahead of the server (or a batch import stamped in the
    future) must not leak into any window — otherwise a single bad sample
    could anchor the baseline.
    """
    service = _service_with(_make_samples("heart_rate", [(0, [200])]))

    delta = await service.compute_kind_baseline_delta(USER_ID, "heart_rate", window_days=7)

    assert delta["mode"] == "empty"
    assert delta["window_value"] is None
