"""Golden net + read-path guard for ``build_heartbeat_health_signals``.

The builder had **no test at all** before v1.25.18 — which is precisely how it
grew to issue six queries and ship ~30 000 raw sample rows per heartbeat tick
for a payload of a few dozen numbers. Two independent nets are pinned here:

1. **Payload golden** — the exact dict for eight datasets, generated by running
   the pre-extraction implementation (the builder still lived on
   ``HealthMetricsService`` and re-fetched through
   ``compute_kind_baseline_delta`` / ``detect_all_variations``). It must pass
   unchanged now that the builder is a module function fetching one per-day
   rollup per kind and reusing it.

2. **Read-path guard** — the exact number and shape of repository calls. A
   payload golden alone cannot see a regression that recomputes the same window
   twice: the output stays identical, only the cost explodes. That is the exact
   defect this work fixed, so it gets its own assertion rather than a comment.

Branch coverage of the case table (counted at generation time): the ``None``
return (no data at all), ``summary_today`` present/absent per kind, the 24-hour
freshness cutoff (``stale_only`` has a baseline but nothing fresh — proving
``any_data`` and ``baseline_deltas`` are independent gates), a fresh series with
no history (summary present, baseline ``empty``), single-kind and both-kind
payloads, a notable falling variation, and a steps inactivity streak.

Fixture clock: samples are placed at 09:00 UTC of their day, before the frozen
11:00 clock, so a ``days_ago=0`` entry IS visible — unlike the baseline
characterization net, where the same-day entries deliberately fall after
``now``.
"""

from __future__ import annotations

from dataclasses import replace
from datetime import UTC, datetime, timedelta
from typing import Any
from unittest.mock import MagicMock
from uuid import UUID

import pytest

from src.domains.health_metrics.baseline import DailyStat, daily_stats_from_samples
from src.domains.health_metrics.heartbeat_signals import (
    _summary_value,
    build_heartbeat_health_signals,
)
from src.domains.health_metrics.kinds import HEALTH_KINDS, AggregationMethod
from src.domains.health_metrics.models import HealthSample

pytestmark = pytest.mark.unit

USER_ID = UUID("00000000-0000-0000-0000-0000000000aa")
FROZEN_NOW = datetime(2026, 6, 15, 11, 0, tzinfo=UTC)


class _FrozenDatetime(datetime):
    """datetime subclass with a pinned now(); everything else inherited."""

    @classmethod
    def now(cls, tz=None):  # type: ignore[override]
        if tz is None:
            return FROZEN_NOW.replace(tzinfo=None)
        return FROZEN_NOW.astimezone(tz)


class _RecordingRepo:
    """In-memory repository that records every call it receives."""

    def __init__(self, samples: list[HealthSample]) -> None:
        self._samples = samples
        self.daily_calls: list[tuple[str, datetime, datetime]] = []
        self.sample_calls: list[tuple[str, datetime, datetime]] = []

    def _window(self, kind: str, from_ts: datetime, to_ts: datetime) -> list[HealthSample]:
        return [s for s in self._samples if s.kind == kind and from_ts <= s.date_start < to_ts]

    async def fetch_samples_kind(
        self, user_id: UUID, *, kind: str, from_ts: datetime, to_ts: datetime
    ) -> list[HealthSample]:
        self.sample_calls.append((kind, from_ts, to_ts))
        return self._window(kind, from_ts, to_ts)

    async def fetch_daily_stats(
        self, user_id: UUID, *, kind: str, from_ts: datetime, to_ts: datetime
    ) -> list[DailyStat]:
        self.daily_calls.append((kind, from_ts, to_ts))
        return daily_stats_from_samples(self._window(kind, from_ts, to_ts))


def _make_samples(entries: list[tuple[str, int, list[int], int]]) -> list[HealthSample]:
    """Build samples at ``FROZEN_NOW - days_ago``, 09:00 UTC, one per minute."""
    out: list[HealthSample] = []
    for kind, days_ago, values, offset in entries:
        base = (FROZEN_NOW - timedelta(days=days_ago)).replace(
            hour=9, minute=0, second=0, microsecond=0
        ) + timedelta(minutes=offset)
        for index, value in enumerate(values):
            ts = base + timedelta(minutes=index)
            out.append(
                HealthSample(
                    user_id=USER_ID,
                    kind=kind,
                    date_start=ts,
                    date_end=ts + timedelta(minutes=1),
                    value=value,
                    source="test",
                )
            )
    out.sort(key=lambda s: s.date_start)
    return out


def hr(days_ago: int, values: list[int], offset: int = 0) -> tuple[str, int, list[int], int]:
    return ("heart_rate", days_ago, values, offset)


def st(days_ago: int, values: list[int], offset: int = 0) -> tuple[str, int, list[int], int]:
    return ("steps", days_ago, values, offset)


# Mirrored EXACTLY by the generator that produced EXPECTED_PAYLOAD.
BUILDER_CASES: dict[str, list[tuple[str, int, list[int], int]]] = {
    "no_data": [],
    "only_heart_rate_rich": [hr(i, [70 + (i % 5), 72 + (i % 3)]) for i in range(40, -1, -1)],
    "only_steps_rich": [st(i, [4000, 5000]) for i in range(30, -1, -1)],
    "both_kinds_rich": (
        [hr(i, [70 + (i % 5), 72 + (i % 3)]) for i in range(40, -1, -1)]
        + [st(i, [4000, 5000]) for i in range(30, -1, -1)]
    ),
    # Everything older than the 24 h freshness cutoff: no summary_today, but a
    # baseline still exists -> any_data False AND baseline_deltas non-empty.
    "stale_only": [hr(i, [70, 72]) for i in range(40, 1, -1)],
    # Only today's samples: summary_today present, baseline empty.
    "fresh_only_no_history": [hr(0, [70, 71, 72])],
    "steps_inactivity_streak": (
        [st(i, [4000, 5000]) for i in range(30, 5, -1)] + [st(i, [0]) for i in range(5, -1, -1)]
    ),
    "both_kinds_falling": (
        [hr(i, [50 + i * 2]) for i in range(40, -1, -1)]
        + [st(i, [max(0, 9000 - (30 - i) * 400)]) for i in range(30, -1, -1)]
    ),
}


@pytest.fixture(autouse=True)
def _frozen_clock(monkeypatch: pytest.MonkeyPatch) -> None:
    """Pin the module clock of every module that branches on ``now()``."""
    monkeypatch.setattr("src.domains.health_metrics.heartbeat_signals.datetime", _FrozenDatetime)
    monkeypatch.setattr("src.domains.health_metrics.signals.datetime", _FrozenDatetime)


def _install_repo(monkeypatch: pytest.MonkeyPatch, samples: list[HealthSample]) -> _RecordingRepo:
    repo = _RecordingRepo(samples)
    monkeypatch.setattr(
        "src.domains.health_metrics.heartbeat_signals.HealthSampleRepository",
        lambda _db: repo,
    )
    return repo


# =============================================================================
# Golden table — GENERATED, never hand-written
# =============================================================================

EXPECTED_PAYLOAD: dict[str, str] = {
    "both_kinds_falling": "{'summary_today': {'heart_rate': {'value': 50.0, 'unit': 'bpm', 'last_update_minutes_ago': 120}, 'steps': {'value': 0, 'unit': 'steps', 'last_update_minutes_ago': 120}}, 'baseline_deltas_7d': {'heart_rate': {'pct': -38.5, 'mode': 'rolling', 'baseline_value': 91.0}, 'steps': {'pct': -100.0, 'mode': 'rolling', 'baseline_value': 4400.0}}, 'recent_variations': [{'kind': 'heart_rate', 'trend': 'falling', 'days': 7, 'delta_pct': -38.5, 'notable': True, 'baseline_mode': 'rolling', 'baseline_value': 91.0}, {'kind': 'steps', 'trend': 'falling', 'days': 7, 'delta_pct': -100.0, 'notable': True, 'baseline_mode': 'rolling', 'baseline_value': 4400.0}], 'notable_events': [{'event': 'inactivity_streak', 'kind': 'steps', 'days': 7}]}",
    "both_kinds_rich": "{'summary_today': {'heart_rate': {'value': 71.0, 'unit': 'bpm', 'last_update_minutes_ago': 119}, 'steps': {'value': 9000, 'unit': 'steps', 'last_update_minutes_ago': 119}}, 'baseline_deltas_7d': {'heart_rate': {'pct': -0.4, 'mode': 'rolling', 'baseline_value': 72.5}, 'steps': {'pct': 0.0, 'mode': 'rolling', 'baseline_value': 9000.0}}, 'recent_variations': [], 'notable_events': []}",
    "fresh_only_no_history": "{'summary_today': {'heart_rate': {'value': 71.0, 'unit': 'bpm', 'last_update_minutes_ago': 118}}, 'baseline_deltas_7d': {}, 'recent_variations': [], 'notable_events': []}",
    "no_data": "None",
    "only_heart_rate_rich": "{'summary_today': {'heart_rate': {'value': 71.0, 'unit': 'bpm', 'last_update_minutes_ago': 119}}, 'baseline_deltas_7d': {'heart_rate': {'pct': -0.4, 'mode': 'rolling', 'baseline_value': 72.5}}, 'recent_variations': [], 'notable_events': []}",
    "only_steps_rich": "{'summary_today': {'steps': {'value': 9000, 'unit': 'steps', 'last_update_minutes_ago': 119}}, 'baseline_deltas_7d': {'steps': {'pct': 0.0, 'mode': 'rolling', 'baseline_value': 9000.0}}, 'recent_variations': [], 'notable_events': []}",
    "stale_only": "{'summary_today': {}, 'baseline_deltas_7d': {'heart_rate': {'pct': 0.0, 'mode': 'rolling', 'baseline_value': 71.0}}, 'recent_variations': [], 'notable_events': []}",
    "steps_inactivity_streak": "{'summary_today': {'steps': {'value': 0, 'unit': 'steps', 'last_update_minutes_ago': 120}}, 'baseline_deltas_7d': {'steps': {'pct': -85.7, 'mode': 'rolling', 'baseline_value': 9000.0}}, 'recent_variations': [{'kind': 'steps', 'trend': 'falling', 'days': 6, 'delta_pct': -100.0, 'notable': True, 'baseline_mode': 'rolling', 'baseline_value': 9000.0}], 'notable_events': [{'event': 'inactivity_streak', 'kind': 'steps', 'days': 6}]}",
}


# =============================================================================
# Payload golden
# =============================================================================


@pytest.mark.parametrize("case_name", sorted(BUILDER_CASES), ids=sorted(BUILDER_CASES))
async def test_payload_is_pinned(case_name: str, monkeypatch: pytest.MonkeyPatch) -> None:
    """Payload must be byte-identical to the pre-extraction implementation."""
    _install_repo(monkeypatch, _make_samples(BUILDER_CASES[case_name]))

    payload = await build_heartbeat_health_signals(MagicMock(), USER_ID)

    assert repr(payload) == EXPECTED_PAYLOAD[case_name]


def test_golden_table_covers_every_case() -> None:
    """Guard against silent shrinkage of the case table."""
    assert set(EXPECTED_PAYLOAD) == set(BUILDER_CASES)


def test_golden_table_is_not_vacuous() -> None:
    """A table of empty payloads would survive any regression."""
    blob = "".join(EXPECTED_PAYLOAD.values())
    assert EXPECTED_PAYLOAD["no_data"] == "None"
    assert "'last_update_minutes_ago'" in blob
    assert "'baseline_deltas_7d': {'heart_rate'" in blob
    assert "'trend'" in blob
    assert "'event': 'inactivity_streak'" in blob


# =============================================================================
# Read-path guard — the defect the payload golden cannot see
# =============================================================================


async def test_reads_one_rollup_and_one_fresh_window_per_kind(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Exactly 2 queries per kind, and never the same window twice.

    The pre-fix builder issued 6 queries for 2 kinds because
    ``compute_kind_baseline_delta`` and ``detect_all_variations`` each re-fetched
    the identical 36-day window. The payload was correct throughout — only this
    assertion can catch the regression coming back.
    """
    repo = _install_repo(monkeypatch, _make_samples(BUILDER_CASES["both_kinds_rich"]))

    await build_heartbeat_health_signals(MagicMock(), USER_ID)

    kinds = list(HEALTH_KINDS)
    assert [call[0] for call in repo.daily_calls] == kinds
    assert [call[0] for call in repo.sample_calls] == kinds
    # No window is ever fetched twice — the duplication that caused the defect.
    assert len(set(repo.daily_calls)) == len(repo.daily_calls)
    assert len(repo.daily_calls) + len(repo.sample_calls) == 2 * len(kinds)


async def test_every_window_derives_from_a_single_clock_reading(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """All windows must share one ``now``.

    The pre-extraction shape let the builder, the delta and the variations each
    call ``datetime.now(UTC)``, so a single payload described three instants a
    few milliseconds apart. Harmless in practice, incoherent by design.
    """
    repo = _install_repo(monkeypatch, _make_samples(BUILDER_CASES["both_kinds_rich"]))

    await build_heartbeat_health_signals(MagicMock(), USER_ID)

    upper_bounds = {call[2] for call in repo.daily_calls + repo.sample_calls}
    assert upper_bounds == {FROZEN_NOW}
    # The rollup window is the wider one: baseline span + recent window.
    assert {call[1] for call in repo.daily_calls} < {call[1] for call in repo.sample_calls} or all(
        daily[1] < fresh[1] for daily in repo.daily_calls for fresh in repo.sample_calls
    )


async def test_freshness_window_is_the_configured_cutoff(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """``summary_today`` must read exactly the configured freshness window."""
    from src.core.constants import HEALTH_METRICS_HEARTBEAT_FRESHNESS_MINUTES

    repo = _install_repo(monkeypatch, _make_samples(BUILDER_CASES["both_kinds_rich"]))

    await build_heartbeat_health_signals(MagicMock(), USER_ID)

    expected_from = FROZEN_NOW - timedelta(minutes=HEALTH_METRICS_HEARTBEAT_FRESHNESS_MINUTES)
    assert {call[1] for call in repo.sample_calls} == {expected_from}


# =============================================================================
# _summary_value — including the branch no registered kind reaches
# =============================================================================


@pytest.mark.parametrize(
    "aggregation_method,expected",
    [
        (AggregationMethod.SUM, 60),
        (AggregationMethod.AVG_MIN_MAX, 20.0),
        (AggregationMethod.LAST_VALUE, 30),
    ],
)
def test_summary_value_covers_every_aggregation_method(
    aggregation_method: AggregationMethod, expected: float
) -> None:
    """``LAST_VALUE`` is unreachable from the registry but must stay correct."""
    spec = HEALTH_KINDS["steps"]
    spec_with_method = replace(spec, aggregation_method=aggregation_method)
    samples = _make_samples([st(1, [10, 20, 30])])

    assert _summary_value(spec_with_method, samples) == expected


def test_summary_value_handles_every_aggregation_method() -> None:
    """Completeness guard: a new method without a ``match`` arm returns None."""
    spec = HEALTH_KINDS["steps"]
    samples = _make_samples([st(1, [10, 20, 30])])

    for aggregation_method in AggregationMethod:
        spec_with_method = replace(spec, aggregation_method=aggregation_method)
        value: Any = _summary_value(spec_with_method, samples)
        assert isinstance(value, int | float), aggregation_method
