"""
Draft Modification Service - Regenerates draft content based on user instructions.

This service handles the EDIT action in draft_critique HITL flow.
When user asks to modify a draft (e.g., "make it more touching"), this service:
1. Takes the original draft content
2. Takes the user's modification instructions
3. Uses LLM to regenerate the content while preserving context (recipient, etc.)
4. Returns the modified draft

Architecture:
    OrchestrationService detects EDIT intent via HitlResponseClassifier
    → hitl_dispatch_node calls DraftModificationService.modify()
    → LLM regenerates content with instructions
    → Modified draft stored in state
    → Re-interrupt() for user validation

Generic Design:
    - Supports all draft types: email, event, contact, task
    - Each type has specific preserved fields (e.g., "to" for email)
    - LLM prompt adapts to draft type

Created: 2025-12-23
"""

from __future__ import annotations

import json
import re
from typing import Any

import structlog

from src.core.i18n_types import get_language_name
from src.domains.agents.constants import DEFAULT_CONTACT_NAME
from src.infrastructure.llm.factory import get_llm
from src.infrastructure.llm.instrumentation import create_instrumented_config
from src.infrastructure.llm.invoke_helpers import enrich_config_with_node_metadata

logger = structlog.get_logger(__name__)


# Fields to preserve per draft type (not modified unless explicitly requested)
# FIX 2026-01-11: Recipient fields removed from preserved - can be modified when user
# requests alternative email address (e.g., "use their @carven address")
PRESERVED_FIELDS: dict[str, list[str]] = {
    "email": [],  # "to", "cc", "bcc" can all be modified
    "email_reply": ["message_id", "thread_id"],  # reply threading context
    "email_forward": ["message_id"],  # forward source reference
    "event": ["calendar_id", "timezone"],
    "event_update": ["event_id", "calendar_id", "timezone"],
    "contact": [],  # All fields can be modified
    "contact_update": ["resource_name"],
    "task": ["task_list_id"],
    "task_update": ["task_id", "task_list_id"],
    # Delete types: homogenized with update types for draft type changes
    "event_delete": ["event_id", "calendar_id", "timezone", "send_updates"],
    "contact_delete": ["resource_name"],
    "task_delete": ["task_id", "task_list_id"],
}

# Content fields that can be regenerated by LLM
# FIX 2026-01-11: Added recipient fields to allow modification with contact_context
# FIX 2026-01-11: Added all modifiable fields for contacts and tasks
CONTENT_FIELDS: dict[str, list[str]] = {
    # Email types
    "email": ["to", "cc", "bcc", "subject", "body"],
    "email_reply": ["to", "body"],  # no cc/bcc/subject: reply protocol doesn't support them
    "email_forward": ["to", "cc", "body"],  # no bcc/subject: forward protocol doesn't support them
    # Event types
    "event": ["attendees", "summary", "description", "location", "start_datetime", "end_datetime"],
    "event_update": [
        "attendees",
        "summary",
        "description",
        "location",
        "start_datetime",
        "end_datetime",
    ],
    # Contact types - all user-facing fields
    "contact": ["name", "email", "phone", "organization", "notes"],
    "contact_update": ["name", "email", "phone", "organization", "notes", "address"],
    # Task types - all user-facing fields
    "task": ["title", "notes", "due"],
    "task_update": ["title", "notes", "due", "status"],
    # Delete types: same content fields as update types for draft type changes
    "event_delete": [
        "attendees",
        "summary",
        "description",
        "location",
        "start_datetime",
        "end_datetime",
    ],
    "contact_delete": ["name", "email", "phone", "organization", "notes", "address"],
    "task_delete": ["title", "notes", "due", "status"],
}


class DraftModificationService:
    """
    Service for modifying draft content based on user instructions.

    Uses LLM to regenerate content while preserving structural fields
    like recipients, IDs, and references.

    Example:
        >>> service = DraftModificationService()
        >>> modified = await service.modify(
        ...     original_draft={"to": "jean@example.com", "subject": "Hello", "body": "I love you."},
        ...     instructions="make it more touching and profound but short",
        ...     draft_type="email",
        ...     user_language="fr",
        ... )
        >>> print(modified["body"])
        "Chaque jour à tes côtés est un cadeau précieux. Je t'aime profondément."
    """

    def __init__(self) -> None:
        """Initialize the service with LLM."""
        # Use the same LLM as HITL question generator for consistency
        self.llm = get_llm(
            llm_type="hitl_question_generator",
            config_override={"temperature": 0.7},  # Slightly creative for content generation
        )

    async def modify(
        self,
        original_draft: dict[str, Any],
        instructions: str,
        draft_type: str,
        user_language: str = "fr",
        run_id: str | None = None,
        contact_context: list[dict[str, Any]] | None = None,
    ) -> dict[str, Any]:
        """
        Modify draft content based on user instructions.

        Args:
            original_draft: Original draft content dict
            instructions: User's modification instructions (e.g., "make it shorter")
            draft_type: Type of draft (email, event, contact, task, etc.)
            user_language: Language for content generation
            run_id: Optional run ID for logging
            contact_context: Optional list of related contacts with their emails.
                FIX 2026-01-11: Enables resolution of references like "@carven"
                to alternative email addresses of the contact.
                Format: [{"name": "jean dupond", "emails": ["jean@gmail.com", "jean@carven.com"]}]

        Returns:
            Modified draft content dict with regenerated content fields

        Raises:
            Exception: If LLM invocation fails
        """
        logger.info(
            "draft_modification_started",
            run_id=run_id,
            draft_type=draft_type,
            instructions=instructions[:100] if instructions else None,
            original_keys=list(original_draft.keys()),
            has_contact_context=contact_context is not None,
        )

        # Get fields configuration for this draft type
        content_fields = CONTENT_FIELDS.get(draft_type, [])

        # Build the prompt
        prompt = self._build_modification_prompt(
            original_draft=original_draft,
            instructions=instructions,
            draft_type=draft_type,
            content_fields=content_fields,
            user_language=user_language,
            contact_context=contact_context,
        )

        # Log the system prompt for debugging
        system_content = prompt[0]["content"] if prompt else ""
        logger.debug(
            "draft_modification_prompt_built",
            run_id=run_id,
            system_prompt_preview=system_content[:800],
            instructions=instructions[:200],
        )

        # Create instrumented config
        config = create_instrumented_config(
            llm_type="draft_modifier",
            tags=["hitl", "draft_modification", draft_type],
            metadata={
                "draft_type": draft_type,
                "instructions_length": len(instructions),
                "run_id": run_id,
            },
        )
        config = enrich_config_with_node_metadata(config, "draft_modifier")

        try:
            # Call LLM
            result = await self.llm.ainvoke(prompt, config=config)
            content = result.content if isinstance(result.content, str) else str(result.content)

            logger.debug(
                "draft_modification_llm_raw_response",
                run_id=run_id,
                response_preview=content[:500],
            )

            # Parse the response
            modified_content = self._parse_modification_response(
                content, content_fields, original_draft
            )

            # Post-processing: if the LLM didn't change recipient fields but the
            # instructions contain explicit email addresses, apply them directly.
            # This handles cases where the LLM ignores recipient change instructions.
            if draft_type in ("email", "email_reply", "email_forward"):
                modified_content = self._apply_explicit_recipient_override(
                    modified_content, instructions, original_draft, contact_context, run_id
                )

            # Merge with preserved fields from original
            modified_draft = original_draft.copy()
            modified_draft.update(modified_content)

            # Log actual changes for debugging
            actual_changes = {
                k: {"old": original_draft.get(k), "new": v}
                for k, v in modified_content.items()
                if original_draft.get(k) != v
            }
            logger.info(
                "draft_modification_completed",
                run_id=run_id,
                draft_type=draft_type,
                modified_fields=list(modified_content.keys()),
                actual_changes=list(actual_changes.keys()),
            )

            return modified_draft

        except Exception as e:
            logger.error(
                "draft_modification_failed",
                run_id=run_id,
                draft_type=draft_type,
                error=str(e),
            )
            raise

    def _build_modification_prompt(
        self,
        original_draft: dict[str, Any],
        instructions: str,
        draft_type: str,
        content_fields: list[str],
        user_language: str,
        contact_context: list[dict[str, Any]] | None = None,
    ) -> list[dict[str, str]]:
        """
        Build the LLM prompt for draft modification.

        Args:
            original_draft: Original draft content
            instructions: User's modification instructions
            draft_type: Type of draft
            content_fields: Fields that can be modified
            user_language: Target language
            contact_context: Optional related contacts with their emails

        Returns:
            List of message dicts for LLM
        """
        # Extract current content for the modifiable fields
        current_content = {
            field: original_draft.get(field, "")
            for field in content_fields
            if field in original_draft
        }

        # Build context about what is preserved (not to be changed)
        context_info = self._build_context_info(original_draft, draft_type)

        # FIX 2026-01-11: Build contact context for email address resolution
        contact_info = self._build_contact_context_info(contact_context)

        # Load externalized prompt and replace placeholders
        from src.domains.agents.prompts import load_prompt

        system_prompt = (
            load_prompt("draft_modifier_prompt")
            .replace("{user_language}", get_language_name(user_language))
            .replace("{draft_type}", draft_type)
            .replace("{context_info}", context_info)
            .replace("{contact_info}", contact_info)
            .replace("{current_content}", json.dumps(current_content, ensure_ascii=False, indent=2))
            .replace("{instructions}", instructions)
            .replace("{expected_fields}", self._format_expected_fields(content_fields))
        )

        user_message = f"Modifie le brouillon selon les instructions: {instructions}"

        return [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_message},
        ]

    def _build_contact_context_info(self, contact_context: list[dict[str, Any]] | None) -> str:
        """
        Build contact context information for email address resolution.

        FIX 2026-01-11: Enables the LLM to resolve references like "@carven"
        to the correct email address from the contact's email list.

        Args:
            contact_context: List of contacts with their emails

        Returns:
            Formatted string with contact email information, or empty string
        """
        if not contact_context:
            return ""

        lines = ["\n## Adresses email disponibles du contact"]
        for contact in contact_context:
            name = contact.get("name", DEFAULT_CONTACT_NAME)
            emails = contact.get("emails", [])
            if emails:
                emails_str = ", ".join(emails)
                lines.append(f"- {name}: {emails_str}")

        if len(lines) == 1:
            return ""  # No emails found

        return "\n".join(lines)

    def _build_context_info(self, draft: dict[str, Any], draft_type: str) -> str:
        """Build context information about preserved fields."""
        if draft_type in ("email", "email_reply", "email_forward"):
            to_addr = draft.get("to", "non spécifié")
            cc = draft.get("cc", "")
            subject = draft.get("subject", "")
            parts = [f"Destinataire actuel (modifiable): {to_addr}"]
            if cc:
                parts.append(f"CC actuel (modifiable): {cc}")
            if subject and draft_type == "email":
                parts.append(f"Sujet actuel: {subject}")
            return "\n".join(parts)

        elif draft_type in ("event", "event_update"):
            summary = draft.get("summary", "")
            start = draft.get("start_datetime", "")
            return f"Événement: {summary}\nDate: {start}"

        elif draft_type in ("contact", "contact_update"):
            name = draft.get("name", "")
            return f"Contact: {name}"

        elif draft_type in ("task", "task_update"):
            title = draft.get("title", "")
            return f"Tâche: {title}"

        else:
            return "Brouillon générique"

    def _format_expected_fields(self, fields: list[str]) -> str:
        """Format expected JSON fields for the prompt."""
        return ",\n".join([f'  "{field}": "contenu modifié"' for field in fields])

    # Regex for extracting email addresses from free-text instructions
    _EMAIL_RE = re.compile(r"[a-zA-Z0-9._%+\-]+@[a-zA-Z0-9.\-]+\.[a-zA-Z]{2,}")

    def _apply_explicit_recipient_override(
        self,
        modified_content: dict[str, Any],
        instructions: str,
        original_draft: dict[str, Any],
        contact_context: list[dict[str, Any]] | None,
        run_id: str | None,
    ) -> dict[str, Any]:
        """Apply explicit recipient changes from instructions when the LLM failed to do so.

        Detects email addresses or contact names in the instructions and overrides
        the to/cc fields if the LLM returned unchanged values.

        Args:
            modified_content: Content returned by the LLM (parsed)
            instructions: User's modification instructions
            original_draft: Original draft before modification
            contact_context: Available contacts with their emails
            run_id: Run ID for logging

        Returns:
            modified_content with recipient fields corrected if needed
        """
        original_to = original_draft.get("to", "")
        llm_to = modified_content.get("to", original_to)

        # Only intervene if the LLM didn't change the 'to' field
        if llm_to == original_to:
            # Strategy 1: Extract explicit email addresses from instructions
            emails_in_instructions = self._EMAIL_RE.findall(instructions)
            if emails_in_instructions:
                new_to = ",".join(emails_in_instructions)
                modified_content["to"] = new_to
                logger.info(
                    "draft_modification_recipient_override_email",
                    run_id=run_id,
                    extracted_emails=emails_in_instructions,
                    original_to=original_to,
                    new_to=new_to,
                )
                return modified_content

            # Strategy 2: Resolve contact names from instructions via contact_context
            if contact_context:
                resolved_email = self._resolve_contact_from_instructions(
                    instructions, contact_context
                )
                if resolved_email:
                    modified_content["to"] = resolved_email
                    logger.info(
                        "draft_modification_recipient_override_contact",
                        run_id=run_id,
                        original_to=original_to,
                        new_to=resolved_email,
                    )
                    return modified_content

        return modified_content

    def _resolve_contact_from_instructions(
        self,
        instructions: str,
        contact_context: list[dict[str, Any]],
    ) -> str | None:
        """Try to resolve a contact name mentioned in instructions to an email.

        Args:
            instructions: User's modification instructions
            contact_context: Available contacts with their emails

        Returns:
            Email address if a contact name match is found, None otherwise
        """
        instructions_lower = instructions.lower()
        for contact in contact_context:
            name = contact.get("name", "")
            emails = contact.get("emails", [])
            if not name or not emails:
                continue
            # Match full name or individual name parts (first/last)
            name_parts = name.lower().split()
            if name.lower() in instructions_lower or any(
                part in instructions_lower for part in name_parts if len(part) > 2
            ):
                return emails[0]
        return None

    def _parse_modification_response(
        self,
        response: str,
        content_fields: list[str],
        original_draft: dict[str, Any],
    ) -> dict[str, Any]:
        """
        Parse LLM response to extract modified content.

        Args:
            response: Raw LLM response
            content_fields: Expected fields
            original_draft: Original draft for fallback

        Returns:
            Dict with modified content fields
        """
        # Try to extract JSON from response
        response = response.strip()

        # Handle markdown code blocks
        if "```json" in response:
            start = response.find("```json") + 7
            end = response.find("```", start)
            if end > start:
                response = response[start:end].strip()
        elif "```" in response:
            start = response.find("```") + 3
            end = response.find("```", start)
            if end > start:
                response = response[start:end].strip()

        try:
            parsed = json.loads(response)

            # Validate and extract only expected fields
            result = {}
            # Fields where empty string means "remove" (not "keep original")
            clearable_fields = {"cc", "bcc"}
            for field in content_fields:
                if field in parsed:
                    if parsed[field]:
                        result[field] = parsed[field]
                    elif field in clearable_fields:
                        # Allow explicit clearing of optional fields (cc, bcc)
                        result[field] = ""

            # If no fields were extracted, log warning and return empty
            if not result:
                logger.warning(
                    "draft_modification_no_fields_extracted",
                    response_preview=response[:200],
                    expected_fields=content_fields,
                )
                return {}

            return result

        except json.JSONDecodeError as e:
            logger.warning(
                "draft_modification_json_parse_error",
                error=str(e),
                response_preview=response[:200],
            )

            # Fallback: try to extract content heuristically
            # For email, the response might just be the new body text
            if "body" in content_fields and len(response) > 10:
                return {"body": response}

            return {}


# Singleton instance for convenience
_service_instance: DraftModificationService | None = None


def get_draft_modification_service() -> DraftModificationService:
    """Get the singleton DraftModificationService instance."""
    global _service_instance
    if _service_instance is None:
        _service_instance = DraftModificationService()
    return _service_instance
