// @vitest-environment node
/**
 * The browser engine against the toolbox's reference (ADR-329): the REAL models
 * the app ships, on the REAL ONNX Runtime Web (single-threaded WASM, as in the
 * worker), fed the golden audio the toolbox scored with openWakeWord's own
 * streaming arithmetic. Same scores (within float noise between two runtimes),
 * same detections.
 *
 * The fixture is regenerated by `task wake:golden -- fr` from the exported
 * model; it names the classifier's SHA-256, so a model retrained without a new
 * fixture fails here by name.
 */
import { readFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

import { describe, expect, it } from 'vitest';

import { WakeWordEngine } from '../engine';
import { parseManifest } from '../manifest';
import { createOrtRuntime } from '../ort-runtime';
import { DetectionPolicy } from '../policy';

const HERE = dirname(fileURLToPath(import.meta.url));
const PUBLIC = join(HERE, '..', '..', '..', '..', '..', 'public');
const FIXTURES = join(HERE, 'fixtures');
/** Two runtimes (ONNX Runtime native and Web) differ by float noise, never more. */
const SCORE_TOLERANCE = 2e-4;

interface Golden {
  language: 'fr';
  classifier_sha256: string;
  scores: number[];
  detections: number[];
}

/** The int16 samples of a mono 16-bit PCM WAV. */
function wavSamples(bytes: Buffer): Int16Array {
  let offset = 12;
  while (offset + 8 <= bytes.length) {
    const id = bytes.toString('ascii', offset, offset + 4);
    const size = bytes.readUInt32LE(offset + 4);
    if (id === 'data') {
      const data = bytes.subarray(offset + 8, offset + 8 + size);
      return new Int16Array(data.buffer.slice(data.byteOffset, data.byteOffset + data.byteLength));
    }
    offset += 8 + size + (size % 2);
  }
  throw new Error('no data chunk');
}

describe('wake-word engine parity with the toolbox (fr)', () => {
  it('scores the golden audio as the reference did, and detects where it did', async () => {
    const golden = JSON.parse(readFileSync(join(FIXTURES, 'golden-fr.json'), 'utf-8')) as Golden;
    const manifest = parseManifest(
      JSON.parse(
        readFileSync(join(PUBLIC, 'models', 'wake', 'v1', 'fr', 'manifest.json'), 'utf-8')
      ),
      'fr'
    );
    expect(
      manifest.files.classifier.sha256,
      'golden fixture is stale: run task wake:golden -- fr'
    ).toBe(golden.classifier_sha256);
    const ortDist = dirname(
      createRequire(import.meta.url).resolve('onnxruntime-web/ort-wasm-simd-threaded.wasm')
    );
    const runtime = await createOrtRuntime(manifest, {
      fetchBytes: async url => {
        const file = readFileSync(join(PUBLIC, url));
        return file.buffer.slice(file.byteOffset, file.byteOffset + file.byteLength);
      },
      wasmPaths: `${pathToFileURL(ortDist).href}/`,
    });
    const engine = new WakeWordEngine(runtime, new DetectionPolicy(manifest.policy));
    const results = await engine.push(wavSamples(readFileSync(join(FIXTURES, 'golden-fr.wav'))));

    expect(results).toHaveLength(golden.scores.length);
    const worst = Math.max(...results.map((r, i) => Math.abs(r.score - golden.scores[i])));
    expect(worst).toBeLessThan(SCORE_TOLERANCE);
    const detections = results.flatMap((r, i) => (r.detected ? [i + 1] : []));
    expect(detections).toEqual(golden.detections);
    expect(detections.length).toBeGreaterThan(0);
  }, 60_000);
});
